redwoodjs/graphql

- README.md
> Add hammer emoji to README

- README.md
> Update: adding some branding

- packages/web/src/graphql/withCell.js
> Sets default beforeQuery to wrap props in { variables }

- packages/web/src/RedwoodForm.js
- packages/web/src/graphql/withCell.js
> Render <Empty> component in Cell if data is null or empty array

- packages/cli/package.json
closes https://github.com/redwoodjs/redwood/issues/75
> Alias `redwood` CLI command to `rw`

- docs/contributing.md
@peterp Spent a bit of time fiddling with `yarn link` workflow today and found the process to be less straightforward than expected. Hoping this doc can help clarify for me and future contributors.
Could you take a look and correct and/or add where needed? Pro Tips grately appreciated in advance. Thanks!
> add contributing.md for local dev setup

- packages/cli/src/commands/generate/README.md
- packages/cli/src/commands/generate/commands/scaffold.js
- packages/cli/src/commands/generate/commands/sdl.js
- packages/cli/src/commands/generate/commands/service.js
- packages/cli/src/commands/generate/helpers.js
- packages/cli/src/commands/generate/templates/page/page.js.template
- packages/cli/src/commands/generate/templates/service/readme.mdx.template
- packages/cli/src/commands/generate/templates/service/service.js.template
- packages/cli/src/commands/generate/templates/service/test.js.template
By @cannikin and @peterp 
Fixes #124
> Fix generators

- packages/api/package.json
- packages/api/src/graphQLServer.ts
- yarn.lock
> Disconnect db on uncaught exception.

- packages/cli/src/commands/generate/commands/scaffold.js
> Check id datatype before setting route param type

- packages/create-redwood-app/src/create-redwood-app.js
Closes redwoodjs/tutorial/issues/34
> remove git init task from CRA bootstrap

- docs/builds.md
- docs/releases.md
- packages/api/src/makeMergedSchema/makeMergedSchema.js
- packages/api/src/makeMergedSchema/makeMergedSchema.test.js
> Add support for Type resolvers

- packages/create-redwood-app/package.json
- packages/create-redwood-app/src/create-redwood-app.js
- yarn.lock
Per Slack conversation today and yarn issues experienced by both Tom and Rob.
Added tasks to confirm whether or not the installation environment meets package.json engine requirements. If requirements are not met, I added a lot of messaging to specify:
1) what happened
2) what needs to be fixed
3) the next steps (e.g. yarn install didn't run so you'll need to do that)
> Check Node and Yarn Engine Requirements during CRA Bootstrap

- packages/create-redwood-app/src/create-redwood-app.js
Fix spelling of 'compatibility'.
> Fix spelling.

- docs/redwood.toml.md
Adds documentation for the redwood.toml configuration
> Update documentation for added app configuration

- packages/cli/src/commands/build.js
- packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js
- packages/cli/src/commands/dbCommands/down.js
- packages/cli/src/commands/dbCommands/generate.js
- packages/cli/src/commands/dbCommands/save.js
- packages/cli/src/commands/dbCommands/up.js
I'm doing this to remove ambiguity about where the command is run, and to make sure that we run the local version in node_modules rather than a global.
> Run commands via yarn

- packages/cli/src/lib/index.js
> Checks for the existence of a route in Routes.js

- .github/workflows/build-eslint-jest.yaml
- package.json
- packages/cli/package.json
- packages/eslint-config/index.js
set up for matrix, only running against node 12 at this time
> Add GH Action to build, lint, test

- packages/api/src/makeMergedSchema/rootSchema.js
> Return Redwood version in Redwood GraphQL query

- yarn.lock
Security issue fix:
https://github.com/redwoodjs/redwood/network/alert/yarn.lock/minimist/open
> update minimist per security warning

- packages/core/config/webpack.common.js
> Fix cell regex for windows.

- packages/cli/src/commands/generate/templates/scaffold/components/EditNameCell.js.template
- packages/cli/src/commands/generate/templates/scaffold/components/NamesCell.js.template
- packages/cli/src/commands/generate/templates/scaffold/components/NewName.js.template
> Set fetchPolicy to `cache-and-network` for scaffolded list page

- README.md
Few questions:
I don't see a supported db list anywhere in docs. I imagine it's this? https://github.com/prisma/prisma2/blob/master/docs/supported-databases.md
> Your business logic is
organized into "services" that represent their own internal API and can be
called both from external GraphQL requests and other internal services. Redwood
can automatically connect your internal services with Apollo, reducing the
amount of boilerplate you have to write.
This is unclear to me and I imagine others. Are the services separate lambda functions? And are they Apollo federation services? "external GraphQL requests" meaning the client sending requests?
> Databases are a little trickier, especially the traditional relational ones
like PostgreSQL and MySQL. Right now, you still need to set these up …
> Copyedit README.md

- packages/cli/README.md
> Update CLI documentation

- packages/api/package.json
- packages/cli/package.json
- packages/core/package.json
- yarn.lock
https://github.com/prisma/prisma2/releases/tag/2.0.0-preview024
> upgrade prisma preview24

- packages/core/config/babel-preset.js
> Use relative paths instead of absolute for alias

- docs/webpack.md
Adds documentatino on how to use the webpack configuration (Thanks for implementing @Idered )
closes https://github.com/redwoodjs/redwood/issues/325
> Add webpack docs

- packages/api/package.json
- packages/cli/package.json
- packages/core/package.json
- yarn.lock
For Prisma release notes, see https://github.com/prisma/prisma/releases/tag/2.0.0-beta.2
⚠️ I have **not** yet tested deploy. To do before a new release.
> Upgrade to Prisma v2-beta.2

- packages/eslint-config/index.js
> Only use redwood-eslint-plugin when in a redwood project.

- packages/core/config/webpack.common.js
- packages/core/package.json
> Build core packages and reference them correctly.

- packages/cli/package.json
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/edit.js
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js
- packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/NameCell.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
- packages/cli/src/lib/__tests__/index.test.js
- packages/cli/src/lib/index.js
- yarn.lock
> Fixes mutation constant names in generated code

- packages/cli/package.json
- yarn.lock
> fix Windows issue: `yarn rw info` not displaying redwoodjs packages

- .github/workflows/build-eslint-jest.yaml
The current workflow was running on Ubuntu in both instances, instead of Ubuntu and Windows.
> Use matrix os instead of ubuntu latest

- .github/workflows/build-eslint-jest.yaml
'cause broken and needs fixing!
> CI runner: remove Windows OS, add Node 14

- packages/web/src/form/form.js
> Allow override of input props

- packages/auth/README.md
This PR just fixes a few stray misnamed functions in the auth readme. Thanks to @cannikin for catching them!
> Change login to logIn, etc

- packages/router/README.md
> Add Private and Redirect to Router README

- packages/api/package.json
- yarn.lock
https://github.com/redwoodjs/redwood/network/alert/packages/api/package.json/apollo-server-lambda/closed
Needs deployment testing
> upgrade apollo-server-lambda per security alert

- packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js
- packages/cli/src/commands/generate/page/__tests__/page.test.js
- packages/cli/src/commands/generate/page/templates/page.js.template
The test may be overkill, but I figured it couldn't hurt anything.
> Fix pluralization in gen page name

- packages/api/package.json
- packages/auth/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/create-redwood-app/package.json
- packages/dev-server/package.json
- packages/eslint-plugin-redwood/package.json
- packages/internal/package.json
- packages/router/package.json
- packages/testing/package.json
- packages/web/package.json
> nodemon double quotes to fix windows issue

- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/editCell.js
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/edit.js
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/new.js
- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js
- packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
- packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
- packages/web/src/flash/Flash.js
- packages/web/src/flash/__tests__/flash.test.js
fixes #714 
@thedavidprice @cannikin 
This also takes care of the lint warnings referenced [here](https://github.com/redwoodjs/redwood/pull/654#issuecomment-645724017).
> FIX!! addMessage errors and disable lint errors

- packages/auth/package.json
- packages/cli/src/commands/generate/auth/templates/firebase.auth.js.template
> Fixes auth firebase

- packages/cli/src/commands/dev.js
- packages/internal/ambient.d.ts
- packages/internal/package.json
- packages/internal/src/dev.ts
- packages/internal/src/main.ts
- packages/internal/tsconfig.json
- yarn.lock
This allows us to shutdown the process running on the ports that we require (8910, 8911) to run the dev-servers.
Closes #494
> commandeer ports when they are in use

- packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js
- packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.ts
- packages/cli/src/commands/generate/sdl/sdl.js
> Properly append array syntax

- packages/router/README.md
Add the useLocation hook docs to router Readme. Closes #727 
@jtoar - please feel free to request additions or changes and, of course, feel free to take the reins.
> Add useLocation hook to router readme

- packages/cli/src/commands/generate/page/__tests__/page.test.js
- packages/cli/src/commands/generate/page/page.js
> Generators: Workaround for POSIX-to-Windows path conversion

- packages/cli/README.md
Let's give thedavid his own line
> Fix list formatting in cli README.md (minor fix)

- packages/api/README.md
Long overdue, pull-request version of #526. This PR updates the api readme, mainly the purpose/vision and contributing sections, leaving the roadmap untouched.
> Edit api readme

- packages/api/README.md
Corresponding docs update to #788 which removed `importAll` in favor of a babel-plugin. This PR just exchanges importAll docs for babel-plugin docs, mainly changing the `importAll` section, but also the table of contents and such.
> Replace importAll docs with babel-plugin import docs

- packages/structure/README.md
- packages/structure/src/index.ts
This pull request:
* Improves the documentation README
* Adds a few non-breaking changes to the exported API (to keep it in sync with the improved usage instructions in the README)
> Improve @redwoodjs/structure

- packages/dev-server/src/http.ts
> dev-server: wildcard match lambda functions

- packages/dev-server/src/http.ts
> Lambda function list with no comma

- packages/router/src/__tests__/router.test.js
Just some basic integration tests for the Router component.
> Add Router tests

- packages/internal/package.json
- yarn.lock
> Bump kill-port

- packages/create-redwood-app/src/create-redwood-app.js
needed for the in-process work on #875
> remove all-contributors file from new CRA installation

- packages/structure/README.md
- packages/structure/src/language_server/README.md
* This PR improves the README for the structure package
* It clarifies some confusion related to its usage (see this [forum thread](https://community.redwoodjs.com/t/getting-started-with-redwood-structure/976))
> Improve README for the structure package

- packages/cli/README.md
- packages/cli/src/commands/dbCommands/studio.js
- Update db studio link to CLI docs
- Remove Prisma Studio from Coming Soon section of CLI README
> Minor changes re: db studio command

- packages/web/src/components/RedwoodProvider.js
See https://github.com/redwoodjs/redwood/issues/926 for details.
> Fix graphQLClientConfig bug in GraphQLWithAuth provider

- README.md
- packages/router/README.md
[Prisma 2.0 was released on June 9th](https://www.prisma.io/blog/announcing-prisma-2-n0v98rzc8br1) so I don't think there is a need for this messaging anymore.
> Adjust the production usage warning

- packages/cli/src/commands/generate/deploy/__tests__/deploy.test.js
- packages/cli/src/commands/generate/deploy/deploy.js
- packages/cli/src/commands/generate/deploy/providers/netlify.js
- packages/cli/src/commands/generate/deploy/providers/vercel.js
> Adds deploy generator, netlify and vercel targets

- packages/create-redwood-app/src/create-redwood-app.js
@quantuminformation @peterp 
Closes #794 
I saw that this issue might still be open, so I drafted a PR in case it could be helpful.
> Add option to skip yarn install to create-redwood-app

- packages/api/package.json
- packages/cli/package.json
- packages/cli/src/commands/generate/page/__tests__/page.test.js
- packages/core/package.json
- packages/structure/package.json
- yarn.lock
Prisma Release Notes:
- https://github.com/prisma/prisma/releases/tag/2.5.0
- Middlewares
- removing duplicates with `distinct`
- aggregations
- many more preview features; see release notes
- https://github.com/prisma/prisma/releases/tag/2.5.1
- Client bug fixes
Basic local tests == ✅
> Upgrade to Prisma 2.5.1

- packages/api/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/structure/package.json
- yarn.lock
tested all the things = ✅
https://github.com/prisma/prisma/releases/tag/2.6.0
> Upgrade Prisma v2.6.0

- packages/cli/src/commands/generate/util/tailwind/tailwind.js
- packages/core/config/webpack.common.js
> Fix tailwind webpack configuration

- packages/cli/src/commands/check.js
> rename diagnostics to check

- README.md
Now that it is possible to use FaunaDB and Redwood together, let's link to it.
> Mention and link to FaunaDB

- packages/cli/package.json
- yarn.lock
Working on resolving #1204 
Merging in order to create a canary for testing.
> upgrade envinfo v7.7.3

- packages/core/src/configs/node/jest.setup.js
> Fix usage of private variable

- packages/cli/src/commands/setup/tailwind/tailwind.js
Adds info about opt-in to future changes enabled. Updated link.
> update "setup tailwind" confirmation output

- packages/structure/src/language_server/RWLanguageServer.ts
- packages/structure/src/model/RWProject.ts
- packages/structure/src/outline/outline.ts
- packages/structure/src/x/vscode-languageserver.ts
This is a maintenance patch containing all changes in this PR (https://github.com/redwoodjs/redwood/pull/1267)
> Make language server more robust

- packages/cli/src/commands/deploy.js
- packages/cli/src/commands/destroy.js
- packages/cli/src/commands/setup.js
- packages/cli/src/commands/setup/i18n/i18n.js
Attempts to resolve https://github.com/redwoodjs/redwood/issues/1223
Adjusted the Yargs structure of `setup.js`. Working well on local test.
Various misc formatting fixes.
> restructure Setup to fix windows error

- packages/structure/src/model/RWEnvHelper.ts
* This PR fixes #1280
* Origin of bug was a small omission (4 characters!)
Note: 
* We need to refactor many parts of structure into easily (unit) testable utils
> Fix #1280 (env visibility bug)

- packages/core/config/storybook/main.js
Fixes #954
I've verified that it works on Windows GitBash, Windows PowerShell and Windows Cmd
Can someone else please check that I didn't break it for MacOS/Linux? I'm especially worried about path with spaces on *nix
> Fix storybook on Windows

- packages/structure/CONTRIBUTING.md
* This PR adds one file: `structure/CONTRIBUTING.md`
* As discussed with @thedavidprice in [this PR comment](https://github.com/redwoodjs/redwood/pull/1331#issuecomment-708084430)
> add structure/CONTRIBUTING.md

- README.md
Added a more descriptive link to node/yarn requirements.
> Redwoodjs.com docs Introduction link to node/yarn requirements

- README.md
- tasks/all-contributors/.all-contributorsrc
- tasks/all-contributors/.crwa.all-contributorsrc
- tasks/all-contributors/.rwjs.com.all-contributorsrc
added 10 new contributors in the past week'ish 🚀
added Tobbe as Community Lead
> Update contributors 10/16

- package.json
- packages/auth/src/AuthProvider.tsx
- packages/create-redwood-app/package.json
- packages/structure/src/model/RWProject.ts
- packages/testing/src/MockProviders.tsx
- packages/testing/src/MockRouter.tsx
- packages/testing/src/customRender.tsx
- packages/testing/src/global.ts
- packages/testing/tsconfig.json
- packages/web/package.json
- packages/web/scripts/postBuild.js
- packages/web/src/components/RedwoodProvider.tsx
- packages/web/src/config.js
- packages/web/src/config.ts
- packages/web/src/global.web-auto-imports.ts
- packages/web/src/graphql/index.tsx
- packages/web/src/graphql/withCell.tsx
- packages/web/src/index.ts
- packages/web/tsconfig.json
& Clean up a bunch of functionality.
Closes #1336
> Fix auto-mocking

- CONTRIBUTING.md
A very qualitative contribution™️
> Fix typo in contribution guide

- packages/router/README.md
> Fixed typo in User route param types section

- packages/cli/src/commands/__tests__/build.test.js
- packages/cli/src/commands/build.js
- packages/internal/src/__tests__/config.test.ts
- packages/internal/src/config.ts
I should write some tests for these that we missed.
> Fix schema paths

- packages/cli/src/commands/setup/tailwind/tailwind.js
> Tailwind setup: use fs.renameSync instead of mv

- packages/auth/package.json
- packages/auth/src/authClients/supabase.ts
- yarn.lock
See https://github.com/redwoodjs/redwood/pull/1536#issuecomment-742339089 for context
> supabase@1.1.1 with cleaner imports

- packages/core/src/babelPlugins/babel-plugin-redwood-import-dir.ts
> Make glob import dir ignore *.scenarios.* files.

- .github/workflows/publish_pr_packages.yaml
If all goes well, the Action Workflow formatting will now look like this:
> update PR Package Action formatting

- packages/api/src/auth/decoders/netlify.ts
- packages/api/src/auth/decoders/supabase.ts
- packages/cli/src/commands/dev.js
> Verify supabase, netlify and goTrue auth tokens in prod

- packages/core/config/storybook/main.js
> [core] Small Storybook webpack fix

- packages/create-redwood-app/package.json
> Add build:js script for CRWA.

- packages/auth/src/authClients/azureActiveDirectory.ts
- tasks/test-tutorial
The auth library does not include the client side code, we can only import types.
> Make test-tutorial use template directory & fix azure imports

- packages/testing/package.json
- packages/testing/tsconfig.json
> Add auth package to deps.

- packages/create-redwood-app/template/web/package.json
- packages/testing/package.json
> Fix dependencies

- packages/create-redwood-app/template/.env
- packages/create-redwood-app/template/.env.defaults
- packages/create-redwood-app/template/.env.example
This reconciles updates to CRWA repo that were not included during the migration to packages/create-redwood-app
> Add missing env changes to template

- README.md
- tasks/all-contributors/.all-contributorsrc
- tasks/all-contributors/.learn.all-contributorsrc
- tasks/all-contributors/.rwjs.com.all-contributorsrc
Core: 12
Contribs: 159
Total: 171
> update all contributors v0.24.0

- packages/cli/src/commands/setup/webpack/templates/webpack.config.js.template
At some point env was renamed to mode 🤷🏽‍♂️.
> Fix env loading in users webpack config

- packages/internal/src/paths.ts
.ts Pages can be used as kind of proxy pages, see https://discord.com/channels/679514959968993311/747258086569541703/806556064849854505 for more context
> Router: Automatically import .ts Page files

- packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
- packages/structure/src/model/RWProject.ts
> Fix import in RWProject in rw/structure

- README.md
Updated Status of Storybook in Technologies
> Updated Status of Storybook in Technologies

- packages/router/package.json
> Fix router typescript problem

- packages/router/package.json
Specify types for the router package
> Specify types for the router package

- packages/create-redwood-app/template/api/db/schema.prisma
> update CRWA template remove dynamic provider and related copy

- packages/cli/src/commands/test.js
related to Prisma v2.16 upgrade
> Update Test command to use new Prisma command

- packages/api/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/structure/package.json
- yarn.lock
v2.16.1 Release Notes:
- https://github.com/prisma/prisma/releases/tag/2.16.1
> upgrade Prisma v2.16.1

- packages/cli/src/commands/prisma.ts
Shows errors coming through from Prisma
> Show errors coming from Prisma cli

- .github/workflows/e2e.yaml
- tasks/e2e/cypress.json
- tasks/e2e/package.json
- tasks/test-tutorial
We'll now run our Cypress e2e tests for each pull-request! 🥇
> Add Cypress workflow

- packages/api/src/globalContext.ts
> Lazily create AsyncLocalStorage when needed

- packages/api-server/src/watch.ts
- packages/cli/src/commands/dev.js
- packages/core/config/webpack.common.js
- packages/core/esbuild/apiBuild.js
- packages/core/package.json
- tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
- tasks/run-e2e
This adds the esbuild-loader for the web side. I've noticed a 50% reduction in compile time when using babel-loader + esbuild-loader, but the general compile time has not decreased.
> Use esbuild-loader for web side.

- packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js
- packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template
> Fixes formatDateTime helper when field is optional and value is empty

- packages/core/esbuild/apiBuild.js
> Fix glob matching to support subdirectories.

- packages/router/src/RouteNameContext.tsx
- packages/router/src/__tests__/router.test.tsx
- packages/router/src/__tests__/set.test.tsx
- packages/router/src/router.tsx
> Router: only render one page

- packages/router/README.md
Documents the new `Set` component introduced in https://github.com/redwoodjs/redwood/pull/1898.
> Add the new Set component to the Router docs

- LICENSE
- packages/create-redwood-app/template/LICENSE
> Update year in LICENSE

- packages/create-redwood-app/README.md
> update CRWA quick-start Node requirement

- packages/router/src/__tests__/router.test.tsx
- packages/router/src/page-loader.tsx
- packages/router/src/params.tsx
This will populate the useParams for the `Set` component and nested routes.
@peterp  do you mind taking a look at this I had been working on a fix to this before it was brought up. But it was slightly different and saw that there was a couple of changes that were made. So I tacked on my changes to your test.
related #2149
> Recalculate param on location change

- packages/create-redwood-app/template/yarn.lock
> update template/yarn.lock v0.28.4

- packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
- packages/cli/src/commands/generate/service/templates/service.ts.template
As title - the types for generated service function in TS wasn't correct
---
Fixes #2325
> fix(generator): Fix type for update service function

- packages/api/src/webhooks/index.ts
- packages/api/src/webhooks/webhooks.test.ts
- packages/cli/src/commands/deploy/render.js
- packages/cli/src/commands/serve.js
- packages/cli/src/commands/setup/deploy/deploy.js
- packages/cli/src/commands/setup/deploy/providers/render.js
Merging v0.31 release candidate, to create canary build.
> Create v0.31 canary release

- packages/eslint-config/package.json
- yarn.lock
- https://github.com/redwoodjs/redwood/pull/2263/
- https://github.com/redwoodjs/redwood/pull/2284
> Upgrade @typescript-eslint to v4.22 (dependabot)

- README.md
The Readme which is also the redwoodjs.com introduction docs was missing some feature worthy of highlight:
* logging
* webhooks
* prerender
* more deployment targets
While this readme could use an update ahead of the v1.0 launch as well, this adds in those items ahead of that effort.
> chore(readme): Added logging, webhook, prerender, deploy features

- yarn.lock
preparing CRWA template for next release
> update CRWA/template/yarn.lock to v0.31.2

- README.md
- tasks/all-contributors/.all-contributorsrc
- tasks/all-contributors/.learn.all-contributorsrc
- tasks/all-contributors/.rwjs.com.all-contributorsrc
- tasks/all-contributors/package.json
- tasks/all-contributors/yarn.lock
Total 196 + 14 (core team) = **210 contributors** 🤩 
Updates from framework, www, and tutorial (learn.rwjs.com) repos.
https://user-images.githubusercontent.com/2951/118574047-84dc1700-b738-11eb-8a3a-36215c3b0332.mp4
> Update Contributors corresponding with release v0.32

- CONTRIBUTING.md
subject says it all. 
Hey all!
A great weekd too for you all!
António
> CONTRIBUTING.md: add missing char

- CHANGELOG.md
- testing with tag v1.1.1
- testing `merge` PR
> lerna test case: merge

- CHANGELOG.md
> lerna test case: squash

- CONTRIBUTING.md
Proposed changes as per issue #2789  to provide guidance regarding running `yarn rwt cp` on Windows.
> Update CONTRIBUTING.md (Windows dev mode)

- packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
- packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
Just a small typo fix "newPos" -> "newPost"
> scaffold tests: Fix newPos typo

- packages/api/src/types.ts
- packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
- packages/cli/src/commands/generate/service/templates/service.ts.template
> Create ResolverArgs type.

- .github/workflows/e2e.yaml
- tasks/e2e/cypress.json
- tasks/e2e/cypress/integration/02-cli/02-cli-commands.spec.js
- tasks/e2e/cypress/integration/03-storybook/storybook.spec.js
Increase timeouts in an attempt to improve Cypress flakyness.﻿
> Attempt to remove Cypress flakyness.

- tasks/build-and-copy
> Log the errors if build and copy fails in rwt link

- packages/cli/src/commands/generate/sdl/sdl.js
- packages/cli/src/commands/generate/service/__tests__/scenario.test.js
- packages/cli/src/commands/generate/service/service.js
> Create test values for Decimal and Boolean types

- CONTRIBUTING.md
2 line update to Contributing.md
> update contributing.md table of contents

- packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template
- packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
- packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
> Fix missing styles in dbAuth scaffold

- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
- packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template
- packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
- packages/router/src/__tests__/route-announcer.test.tsx
close #3058 
No visual differences after the fix :)
> Fixed the ESLint error for generated template

- packages/cli/src/commands/setup/tailwind/tailwind.js
I was using require in #3087 when I really should've just read the file with fs.
> Fix setup tailwind

- __fixtures__/example-todo-main/web/src/Routes.js
- __fixtures__/example-todo-main/web/src/pages/PrivatePage/PrivatePage.tsx
- packages/internal/src/__tests__/files.test.ts
- packages/internal/src/__tests__/paths.test.ts
- packages/internal/src/__tests__/typeDefinitions.test.ts
- packages/structure/src/model/RWRouter.ts
- packages/structure/src/model/__tests__/model.test.ts
> Prerender `Private` routes

- .vscode/settings.json
Accidentally commited my personal vscode settings.
This PR restores it back :)
> Undo vscode settings change

- .gitpod.yml
Enables generating gitpods on PRs from forked repos.
> Enable generating gitpods for forks

- packages/api/package.json
- packages/cli/package.json
- packages/graphql-server/package.json
- packages/structure/package.json
- yarn.lock
Release Notes:
- [2.30.3](https://github.com/prisma/prisma/releases/tag/2.30.3)
- [2.30.2](https://github.com/prisma/prisma/releases/tag/2.30.2)
> upgrade Prisma v2.30.3

- packages/core/config/babel-preset.js
@jtoar  just getting it started here. This is the chagne that fixed it for me :) 
I think it might be a good idea to add an svg or something to the e2e tests too
> Remove invalid config from babel-inline-react-svg plugin

- packages/cli/src/commands/generate/__tests__/helpers.test.js
- packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
- packages/cli/src/lib/__tests__/index.test.js
- packages/cli/src/lib/index.js
> Make sure import filename case matches actual filename

- packages/internal/package.json
Reverts redwoodjs/redwood#3441
> Revert "Add some missing @redwoodjs/internal dependencies"

- packages/graphql-server/package.json
Another missing dev from the netlify bundle
brute force FTW
> netlify fix: add node fetch to graphql package

- packages/codemods/src/codemods/v0.37.x/addDirectives/addDirectives.ts
As title. Double dots on the extension :)
> Fix ts extension when adding directives

- packages/api-server/package.json
- packages/api/package.json
- packages/auth/package.json
- packages/cli/package.json
- packages/codemods/package.json
- packages/core/package.json
- packages/create-redwood-app/package.json
- packages/eslint-config/package.json
- packages/forms/package.json
- packages/graphql-server/package.json
- packages/internal/package.json
- packages/prerender/package.json
- packages/router/package.json
- packages/structure/package.json
- packages/testing/package.json
- packages/web/package.json
This simply fix linting errors introduced in the PR #3687
> Fix lint of all package.json

- packages/web/src/components/createCell.test.tsx
- packages/web/src/components/createCell.tsx
We were missing tests for `createCell`. This PR adds a bunch. If anyone sees a glaring hole in the test coverage please let me know. Otherwise I think this is ready to get merged now.
> createCell tests

- packages/router/src/__tests__/util.test.ts
Testing the prefix/suffix behavior.
> More router tests

- packages/router/src/__tests__/util.test.ts
- tasks/framework-tools/yarn.lock
Regenerates lock file, after deleting all node_modules and reinstalling again 
Also fixes formatting/linting on router util test
> Regenerate lock file(s)

- packages/testing/config/jest/api/jest.setup.js
> Scenario teardown needs to catch different error codes from Postgres and MySQL

- packages/cli/src/lib/__tests__/schemaHelpers.test.js
- packages/cli/src/lib/schemaHelpers.js
- packages/cli/src/lib/test.js
- packages/testing/config/jest/api/jest.setup.js
Defaults to double quotes `"` for every provider except MySQL, which likes backticks `` ` ``.
Closes #3655
> On scenario teardown, change table quote style based on provider

- packages/cli/src/commands/setup/ui/tailwindcss.js
> Upgrade setup tailwind to v3

- .github/renovate.json
Moving a few settings over from https://github.com/redwoodjs/redwood/pull/3803.
> Tweak renovate settings

- .github/renovate.json
`chalk` v5 is now pure ESM
cc @jtoar
> add chalk to renovate blocklist

- packages/create-redwood-app/template/scripts/seed.ts
The default seed file types were quite right accurate, without `["data"]` it refers to the object with `{ select: {..}, data: {..} }` etc. This narrows that down.
> Update seed.ts in template

- packages/create-redwood-app/template/scripts/tsconfig.json
- packages/internal/src/ts2js.ts
> Add scripts/{j,t}sconfig.json to CRWA template

- packages/cli/src/commands/dataMigrate/up.js
> exit(1) in dataMigrate on caught errors

- packages/api-server/src/app.ts
- packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
See #3884
2-step workaround denied GitHub branch permissions.
> (chore) merge #3884 into main

- .github/workflows/require-PR-label.yaml
Fixes a typo in the require-label workflow.
> Remove extra colon

- packages/testing/config/storybook/main.js
cc @jtoar
see also: https://github.com/redwoodjs/redwood/pull/3515#issuecomment-1000355169
> fix: Storybook e2e

- packages/testing/config/storybook/main.js
cc @virtuoushub 
- Adds polyfill path handling (webpack v5)
- applies staticDirs config per context
> Update Storybook Config per PR #3515

- package.json
- tasks/release/__tests__/__snapshots__/generateReleaseNotes.test.mjs.snap
- tasks/release/__tests__/generateReleaseNotes.test.mjs
- tasks/release/__tests__/updateNextReleasePullRequestsMilestone.test.mjs
- tasks/release/cli.mjs
- tasks/release/generateReleaseNotes.mjs
- tasks/release/jest.config.mjs
- tasks/release/jest.setup.mjs
- tasks/release/octokit.mjs
- tasks/release/prompts.mjs
- tasks/release/release.mjs
- tasks/release/updateNextReleasePullRequestsMilestone.mjs
- yarn.lock
This PR improves the release script, adding a terminal notifier to notify when long-running processes are done (`git clean` and `yarn install`, local QA, etc), PR-milestone validation, validating that there aren't any PRs without a milestone or with an inappropriate one, and moves the option to close the newly-created milestone at the end.
> Update release tooling

- packages/cli/src/commands/generate/scaffold/scaffold.js
- packages/cli/src/commands/generate/scaffold/templates/components/NameForm.tsx.template
This bugged me when I was going to fix another issue 🙂
> Scaffold: Fix deserialize spelling

- tasks/release/prompts.mjs
- tasks/release/release.mjs
Just a small refactor of the last step to `confirmRuns`.
> Tweak release script

- packages/telemetry/src/sendTelemetry.ts
> Fix telemetry showing Node version for Yarn and npm

- packages/cli/src/commands/deploy/render.js
continues #4278 by reducing mem used by `prisma migrate deploy` when called via RW Yargs command
> (render deploy) use bin for prisma migrate command

- .github/workflows/e2e.yaml
Adds a few extra checks to e2e workflow, making sure there aren't obvious dependecy issues in `rw setup`, `rw setup ui` and `rw setup deploy` commands
> Add extra checks for setup commands on the cli

- packages/cli/src/commands/setup/auth/providers/dbAuth.js
> Changed delimiter to a correct one.

- .github/renovate.json
Closes https://github.com/redwoodjs/redwood/pull/4415.
> Ignore lru-cache

- yarn.lock
This resolves security vulnerabilities for the following packages:
- [node-forge](https://github.com/advisories/GHSA-8fr3-hfg3-gpgp)
- [node-fetch](https://github.com/advisories/GHSA-r683-j2x4-v87g)
- [follow-redirects](https://github.com/advisories/GHSA-74fj-2j2h-c42q)
> Feb security vulnerabilities

- packages/cli/src/commands/dataMigrate/up.js
> fix: link anchor to dataMigrate up docs

- README.md
Streamlined the Readme and made it more relevant to today's Redwood and the imminent 1.0 release.
> Revamp Readme for 1.0

- packages/web/src/components/DevFatalErrorPage.tsx
Probably don't need these logs.
> Clear up dev log in error page

- packages/core/package.json
- packages/core/src/bins/rw-log-formatter.ts
- yarn.lock
Closes https://github.com/redwoodjs/redwood/issues/4670.
> [Yarn 3] Add bin proxy for rw-log-formatter

- packages/forms/src/index.tsx
Fixes #4748
Update link to Tutorial section in forms help
> (docs) update link to Tutorial forms section

- docs/docs/tutorial/saving-data.md
After merging #4756 we can now use Service Validations in the tutorial! This updates the text to make it so. It also includes a few trademark quips and fun "here's what else you can do" sections!
> Updates Saving Data section with Service Validations

- docs/docs/cells.md
- docs/docs/cli-commands.md
- docs/docs/router.md
Redo of https://github.com/redwoodjs/redwood/pull/4815.
Actually this may not be as simple as I thought. It looks like the checks don't run, but they're still required. GitHub has a few suggestions here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks.
> Copy content and fixes from redwoodjs.com

- docs/docs/tutorial/side-quest-how-redwood-works-with-data.md
See https://github.com/redwoodjs/learn.redwoodjs.com/pull/198.
> Copy fix from learn PR #198

- docs/docs/tutorial2/our-first-test.md
Closes: 
- https://github.com/redwoodjs/redwood/issues/4837
- https://github.com/redwoodjs/redwood/issues/4836
> Fix import in tutorial

- docs/docs/cli-commands.md
Minor tweaks to the changes introduced in #4787
> Minor tweaks to the "regenerate" docs

- packages/cli/src/commands/setup/tailwind.js
Closes Issue #4818 with a wrong reference link to the docs.
> Change reference link to the docs

- docs/docusaurus.config.js
This PR updates the algolia config for the docs. The one before was incorrect.
> Update algolia config

- packages/graphql-server/src/functions/graphql.ts
> Fix linting warnings on new gql function

- docs/docusaurus.config.js
> Add toml syntax highlighting

- docs/docs/builds.md
- docs/docs/cli-commands.md
- packages/cli/src/commands/setup/deploy/providers/baremetal.js
- packages/cli/src/commands/setup/deploy/templates/baremetal.js
The deploy docs are broken out into their own pages now, so I had to update this link!
> Updates baremetal setup post-install doc link

- packages/cli/src/commands/setup/auth/providers/clerk.js
Found more places that needed updating with the new env var for clerk
> More clerk doc comment updates

- docs/docs/cookbook/background-worker.md
- docs/docs/cookbook/custom-function.md
- docs/docs/cookbook/file-uploads.md
- docs/docs/cookbook/gotrue-auth.md
- docs/docs/cookbook/mocking-graphql-in-storybook.md
- docs/docs/cookbook/pagination.md
- docs/docs/cookbook/role-based-access-control.md
- docs/docs/cookbook/self-hosting-redwood.md
- docs/docs/cookbook/sending-emails.md
- docs/docs/cookbook/supabase-auth.md
- docs/docs/cookbook/using-a-third-party-api.md
- docs/docs/tutorial/chapter2/getting-dynamic.md
- docs/docs/tutorial/chapter2/side-quest.md
- docs/docs/tutorial/chapter3/saving-data.md
- docs/docs/tutorial/chapter4/authentication.md
- docs/docs/tutorial/chapter4/deployment.md
- docs/docs/tutorial/chapter5/first-test.md
- docs/docs/tutorial/chapter6/comment-form.md
- docs/docs/tutorial/chapter6/comments-schema.md
- docs/docs/tutorial/chapter6/multiple-comments.md
- docs/docs/tutorial/chapter7/rbac.md
Follow up to https://github.com/redwoodjs/redwood/pull/4941; fixes some of the languages and line highlights.
> Code blocks: fix language and highlighted lines

- docs/docusaurus.config.js
- docs/src/css/custom.css
Addresses a few of the concerns in https://github.com/redwoodjs/redwood/pull/4993#issuecomment-1086752657.
> Fix logo link, mobile button

- docs/docs/webpack-configuration.md
Not many changes, mainly just the template and being a little more to-the-point/concise.
> Update the webpack configuration doc

- docs/docs/app-configuration-redwood-toml.md
- docs/docs/assets-and-files.md
- docs/docs/custom-web-index.md
Minor language changes to custom web index, more involved updates to assets and redwood.toml.
> Update docs: assets, redwood.toml, custom web index

- docs/docs/a11y.md
Cherrypicking a change from https://github.com/redwoodjs/redwood/pull/5003 that's ready to go.
> Update a11y documentation

- docs/docs/contributing-walkthrough.md
This PR adjusts the spelling of Gitpod.
> Rename GitPod to Gitpod

- docs/sidebars.js
> Add Layer0 to deploy menu

- docs/docs/tutorial/chapter6/the-redwood-way.md
> [Tutorial] Fix wrong property

- docs/docs/tutorial/chapter4/deployment.md
Closes https://github.com/redwoodjs/redwood/issues/5041.
> Update connection pooling link

- packages/core/package.json
- yarn.lock
Fixes #5054
Don't ask me how I figured this out....
> Bump webpack version to match storybook

- packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
Just formatting some code to get rid of warnings in chakra-ui.js
Introduced in https://github.com/redwoodjs/redwood/pull/5031
> chakra-ui setup: Format code

- docs/docs/how-to/mocking-graphql-in-storybook.md
Fix typo: _with with_ on l. 15
> Typo fix in mocking-graphql-in-storybook.md

- docs/docs/deploy/baremetal.md
- docs/docs/deploy/serverless.md
- docs/docs/introduction.md
- docs/docs/tutorial/chapter3/saving-data.md
- docs/docs/tutorial/chapter6/comment-form.md
- docs/docs/tutorial/chapter6/multiple-comments.md
Hi all, 
All the best, 
António
> yet another batch of typo squashing

- CONTRIBUTING.md
Hello,
I noticed that this typo is still present on main branch, so i fixed it.
> Foreward -> Foreword

- docs/docs/tutorial/afterword.md
- docs/docs/tutorial/chapter1/file-structure.md
- docs/docs/tutorial/chapter1/first-page.md
- docs/docs/tutorial/chapter1/installation.md
- docs/docs/tutorial/chapter1/layouts.md
- docs/docs/tutorial/chapter1/prerequisites.md
- docs/docs/tutorial/chapter1/second-page.md
- docs/docs/tutorial/chapter2/cells.md
- docs/docs/tutorial/chapter2/getting-dynamic.md
- docs/docs/tutorial/chapter2/routing-params.md
- docs/docs/tutorial/chapter2/side-quest.md
- docs/docs/tutorial/chapter3/forms.md
- docs/docs/tutorial/chapter3/saving-data.md
- docs/docs/tutorial/chapter4/authentication.md
- docs/docs/tutorial/chapter4/deployment.md
- docs/docs/tutorial/chapter5/first-test.md
- docs/docs/tutorial/chapter5/storybook.md
- docs/docs/tutorial/chapter6/comment-form.md
- docs/docs/tutorial/chapter6/comments-schema.md
- docs/docs/tutorial/chapter6/multiple-comments.md
- docs/docs/tutorial/chapter6/the-redwood-way.md
- docs/docs/tutorial/chapter7/rbac.md
- docs/docs/tutorial/foreword.md
- docs/src/css/custom.css
> Adds admonitions to Tutorial

- docs/docs/schema-relations.md
I forgot to include a commit in the final edits to https://github.com/redwoodjs/redwood/pull/4849. Including it here.
> Update schema relations doc

- docs/docs/tutorial/chapter3/forms.md
I think it was copied from the last code block :)
> Remove unnecessary highlight from docs

- docs/docs/tutorial/chapter3/saving-data.md
> Fix: api side file extension in "Saving Data" docs

- docs/docs/cli-commands.md
- docs/docs/schema-relations.md
Some tweaks to the documentation introduced with #4849
I think "issue" too strongly implies there's something wrong with our code, which I don't believe there is.
> Tweak documentation for generator troubleshooting

- docs/docs/forms.md
- docs/docs/tutorial/chapter4/authentication.md
- docs/docs/tutorial/chapter6/comment-form.md
- docs/docs/tutorial/intermission.md
Hi again!
&& a great weekend too!
> docs/: yet another batch of single-bit typo squashing

- .github/actions/message_slack_publishing/action.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
> (chore) minor changes to package publishing Slack notifications

- docs/docs/how-to/file-uploads.md
I found these two bugs after going through the How-to.
> Minor changes to get code working

- docs/docs/tutorial/chapter5/first-story.md
There are some types incorrect
> modify typescript example

- docs/docs/authentication.md
Fixes https://github.com/redwoodjs/redwood/issues/5351.
> Fix broken link in authentication.md

- .github/workflows/publish-release-candidate.yml
Removed it in the canary but not the RC https://github.com/redwoodjs/redwood/commit/682acb493a60028042008924f3e69b94187bcd6f.
> Remove extra checkout in RC workflow

- packages/create-redwood-app/template/web/tsconfig.json
The include part should includes the ./types folder instead of ../types
> fix tsconfig.json in web template

- __fixtures__/test-project/package.json
Trying Isaac's suggestion here: https://github.com/redwoodjs/redwood/pull/5543#issuecomment-1126992784.
> Fix: try bumping glob resolution in test project

- docs/README.md
- docs/docs/tutorial/chapter2/routing-params.md
- Readme
- added small section to clarify where to make changes to the docs and where to find them
- Chapter Two > Routing Params
- fixed wrong type in ArticleCell.tsx
- added missing update of ArticleCell.tsx in the end
> Fix minor issues with the docs/tutorial

- docs/docs/how-to/role-based-access-control.md
Hello Team Redwood 👋  My first PR
I think in the role matrix example a homeowner should be able to access their own bedroom
> Fix typo in RBAC docs

- docs/docs/deploy/baremetal.md
- docs/docs/testing.md
- docs/versioned_docs/version-1.0/deploy.md
- docs/versioned_docs/version-1.0/deploy/serverless.md
- docs/versioned_docs/version-1.0/tutorial/chapter3/saving-data.md
- docs/versioned_docs/version-1.0/tutorial/chapter5/first-test.md
- docs/versioned_docs/version-1.0/tutorial/chapter6/comment-form.md
- docs/versioned_docs/version-1.0/tutorial/chapter6/multiple-comments.md
- docs/versioned_docs/version-1.0/tutorial/intermission.md
- docs/versioned_docs/version-1.1/deploy/serverless.md
- docs/versioned_docs/version-1.1/tutorial/chapter3/saving-data.md
- docs/versioned_docs/version-1.1/tutorial/chapter6/comment-form.md
- docs/versioned_docs/version-1.1/tutorial/chapter6/multiple-comments.md
- docs/versioned_docs/version-1.1/tutorial/intermission.md
- docs/versioned_docs/version-1.2/forms.md
- docs/versioned_docs/version-1.2/tutorial/chapter4/authentication.md
- docs/versioned_docs/version-1.2/tutorial/intermission.md
- docs/versioned_docs/version-1.5/deploy/baremetal.md
- packages/cli/README.md
- packages/cli/src/commands/setup.js
- packages/codemods/src/codemods/v0.37.x/updateGraphQLFunction/README.md
- packages/record/README.md
> Fix typos in docs

- docs/docs/project-configuration-dev-test-build.mdx
Hi again, 
&& All the best
António
> docs: yet another single byte typo squash

- docs/docs/tutorial/chapter3/saving-data.md
Small typo in Chapter 3 of tutorial
> docs: Removes unnecessary word in Chapter 3: saving-data.md

- docs/docs/tutorial/chapter6/multiple-comments.md
- docs/versioned_docs/version-1.5/tutorial/chapter6/multiple-comments.md
> Adds note about errors when generating cells without a SDL file

- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
- packages/cli/src/commands/generate/scaffold/scaffold.js
- packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/Name.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/NameCell.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/Names.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/NewName.tsx.template
- packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
- packages/cli/src/commands/generate/service/templates/service.ts.template
- packages/create-redwood-app/template/api/src/functions/graphql.ts
Closes https://github.com/redwoodjs/redwood/issues/5738.
> Lint fix some template files

- docs/docs/tutorial/chapter6/comment-form.md
> Docs -> Tutorial - Update comment-form.md - Minor Typo

- packages/testing/src/api/directive.ts
> fix(directive): Pass directiveArgs to mockExecution for transformers

- docs/docs/deploy/vercel.md
> Fix link to Prisma & Database

- docs/docs/tutorial/intermission.md
Was a missing word in a paragraph that I now have added
> Tutorial: intermission.md - add missing word

- docs/docs/tutorial/chapter2/side-quest.md
"for which that [file] acts as the entry-point to" contains too many prepositions: either remove `for` or remove `to`. I opted to remove `to` for no particular reason
> Tutorial chapter 2: Fix grammar in side-quest.md

- docs/docs/tutorial/intermission.md
Remove `prisma db seed` command
Closes #6075
> Remove prisma db seed from intermission.md

- docs/docs/auth/azure.md
I just tried setting up Azure auth, and did some tweaks to the docs to hopefully make them a bit clearer
Closes https://github.com/redwoodjs/redwood/issues/6041
> Update Azure auth docs

- packages/codemods/package.json
- yarn.lock
… for `tsconfig-for-route-hooks` codemod added in #6098
> fix(codemods): Add typescript as a dependency of codemods package 

- packages/cli/src/commands/lint.js
> Include ./scripts and ./web/config folders when linting

- docs/docs/testing.md
The title/path pointed to the wrong file
> testing.md: Update file path in code snippet

- packages/testing/config/jest/web/jest-preset.js
> Fix jest-preset formatting

- docs/docs/app-configuration-redwood-toml.md
- docs/docs/auth/dbauth.md
- docs/docs/graphql.md
- docs/docs/how-to/sending-emails.md
- docs/docs/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-1.0/how-to/sending-emails.md
- docs/versioned_docs/version-1.0/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-1.0/tutorial/chapter6/comment-form.md
- docs/versioned_docs/version-1.0/tutorial/chapter7/rbac.md
- docs/versioned_docs/version-1.1/how-to/sending-emails.md
- docs/versioned_docs/version-1.1/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-1.1/tutorial/chapter7/rbac.md
- docs/versioned_docs/version-1.2/how-to/sending-emails.md
- docs/versioned_docs/version-1.2/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-1.2/tutorial/chapter7/rbac.md
- docs/versioned_docs/version-1.3/how-to/sending-emails.md
- docs/versioned_docs/version-1.3/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-1.4/how-to/sending-emails.md
- docs/versioned_docs/version-1.4/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-1.5/how-to/sending-emails.md
- docs/versioned_docs/version-1.5/project-configuration-dev-test-build.mdx
- docs/versioned_docs/version-2.0/how-to/sending-emails.md
- docs/versioned_docs/version-2.1/auth/azure.md
- docs/versioned_docs/version-2.1/how-to/sending-emails.md
- docs/versioned_docs/version-2.2/auth/azure.md
- docs/versioned_docs/version-2.2/how-to/sending-emails.md
This PR fixes some minor typos in docs.
> docs: fix typos

- babel.config.js
We recently switched to node 14 as our lowest supported version. Forgot to update this comment
> Align comment with code

- packages/router/src/__tests__/router.test.tsx
Increased some delays to try and see if that makes it easier for Windows to keep up with what's going on
> Try fixing flaky test on Windows

- docs/versioned_docs/version-1.0/graphql.md
This is fixed in the latest docs but thought why not fix here as well 🙃
> chore(Spelling): Fix tiny spelling issue

- packages/cli/src/commands/generate/sdl/sdl.js
Broken out of my big decouple auth PR
> sdl.js: Format comment

- packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
- packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
The actual template files were updated, so lets update the test fixture files too
> Make cli-helpers fixtures reflect actual files

- packages/router/src/__tests__/router.test.tsx
- packages/router/src/__tests__/set.test.tsx
Set/Reset mockDelay for each test
> Router test tweaks

- tasks/smoke-test/tests/rbacChecks.spec.ts
This makes the test less flaky when running locally against the same test project multiple times
> Make rbac spec less flaky

- packages/graphql-server/src/plugins/__tests__/useRedwoodAuthContext.test.ts
- packages/web/src/components/FetchConfigProvider.test.tsx
A couple of type errors I discovered after merging the decouple auth PR
> Fix decouple auth related type errors

- docs/docs/tutorial/chapter6/comment-form.md
Found this while going through the tutorial :)
> chore: Remove redundant space " "

- packages/auth-providers-setup/src/firebase/setup.ts
Update firebase auth setup script to install RW packages and configure the auth decoder to use on the API side
> Auth: Update firebase setup script

- packages/auth-providers-setup/src/clerk/setup.ts
Clerk was missing a decoder for the API side
> Add auth decoder to clerk auth setup

- packages/auth-providers-web/src/clerk/clerk.tsx
Might be a bit of code golf, but couldn't help myself ⛳ 
Does bring it more inline with other auth implementations (Netlify)
> Clerk: Simplify web implementation

- docs/docs/auth/firebase.md
Updates firebase auth docs with a new code sample
> Update firebase auth docs

- docs/docs/auth/clerk.md
Update Clerk docs to reflect how things work now with RW's new auth implementation
> Update Clerk docs

- packages/auth-providers-setup/src/ethereum/setup.ts
Add missing packages to Ethereum auth setup
> Missing packages for Ethereum auth setup

- packages/auth-providers-setup/src/auth0/setup.ts
> Auth0 setup: Install correct packages

- packages/auth-providers-setup/src/goTrue/setup.ts
Update packages and docs for goTrue setup cli
> Setup auth: Update goTrue

- packages/auth-providers-setup/src/azureActiveDirectory/setup.ts
Add needed packages for azure active directory
> Azure setup auth: Install and import all needed packages

- tasks/release/release.mjs
This tweaks the release script for publishing from the next branch.
> [Chore]: tweak release script for publishing from the next branch

- packages/cli/src/commands/setup/auth/auth.js
Include instructions on switching to @next in auth setup warning message
> Update auth setup warning message

- docs/docs/auth/netlify.md
> Update Netlify auth docs

- packages/auth-providers-setup/src/auth0/setup.ts
> Fix auth0 decoder import

- packages/api-server/src/requestHandlers/awsLambdaFastify.ts
Closes #6765.
Thanks for the suggestion for the fix @dthyresson 
I've validated that it works
> fix(api-server): Fixes issue using fastify compress plugin

- .github/workflows/ci.yml
Disabling replay to fix broken CI!
> chore(smoke-test): Temporarily disable replay

- packages/auth-providers/custom/api/.babelrc.js
- packages/auth-providers/custom/api/README.md
- packages/auth-providers/custom/api/jest.config.js
- packages/auth-providers/custom/api/package.json
- packages/auth-providers/custom/api/src/__tests__/custom.test.ts
- packages/auth-providers/custom/api/src/decoder.ts
- packages/auth-providers/custom/api/src/index.ts
- packages/auth-providers/custom/api/tsconfig.json
- packages/auth-providers/custom/setup/.babelrc.js
- packages/auth-providers/custom/setup/README.md
- packages/auth-providers/custom/setup/jest.config.js
- packages/auth-providers/custom/setup/package.json
- packages/auth-providers/custom/setup/src/__tests__/setup.test.ts
- packages/auth-providers/custom/setup/src/index.ts
- packages/auth-providers/custom/setup/src/setup.ts
- packages/auth-providers/custom/setup/src/templates/api/lib/auth.ts.template
- packages/auth-providers/custom/setup/src/templates/web/auth.ts.template
- packages/auth-providers/custom/setup/tsconfig.json
- yarn.lock
Separate package for custom auth
> Custom auth package

- packages/auth-providers/dbAuth/setup/src/templates/web/auth.webAuthn.ts.template
There was a mistake in the import path for webAuthn in the dbAuth setup web template
> Fix webAuthn import path in setup template

- .github/actions/setup_job/action.yml
- .github/workflows/ci.yml
Try fixing https://github.com/redwoodjs/redwood/issues/7133.
> chore(CI): try passing action's github token

- __fixtures__/test-project/package.json
The fix for this was merged recently https://github.com/babel/babel/pull/15303
> chore: try reverting babel resolution for storybook in test project fixture

- __fixtures__/test-project/api/package.json
- __fixtures__/test-project/package.json
- __fixtures__/test-project/web/package.json
- packages/auth-providers/azureActiveDirectory/setup/src/templates/api/lib/auth.ts.template
- packages/auth-providers/azureActiveDirectory/setup/src/templates/web/auth.ts.template
- packages/auth-providers/clerk/setup/src/templates/api/lib/auth.ts.template
- packages/auth-providers/clerk/setup/src/templates/web/auth.tsx.template
- packages/auth-providers/dbAuth/setup/src/templates/web/auth.webAuthn.ts.template
- packages/auth-providers/firebase/setup/src/templates/web/auth.ts.template
- packages/auth-providers/supertokens/setup/src/templates/web/auth.ts.template
- packages/cli/src/commands/setup/auth/auth.js
- tasks/test-project/tasks.js
I ran the setup command for each auth provider and found miscellaneous things to fix with about half of them. Most were just linting fixes, but there were a few things that were broken about azure, clerk, and dbAuth.
> Decoupling auth polishes

- packages/cli-helpers/src/auth/__tests__/__snapshots__/addAuthConfig.test.ts.snap
- packages/cli-helpers/src/auth/__tests__/addAuthConfig.test.ts
- packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/functions/graphql.ts
- packages/cli-helpers/src/auth/__tests__/fixtures/app/api/src/functions/graphqlNonStandardAuthDecoder.ts
- packages/cli-helpers/src/auth/authTasks.ts
Simple refactoring inspired by my review of #6956
Took the opportunity to add some `addApiConfig` tests too
> authTasks.ts: Extract addAuthDecoderToCreateGraphQLHandler

- packages/cli-helpers/src/auth/__tests__/__snapshots__/addAuthConfig.test.ts.snap
- packages/cli-helpers/src/auth/authTasks.ts
Refactor/simplify `addApiConfig` in authTasks.ts
> authTasks: Refactor auth decoder arg handling

- packages/cli-helpers/src/auth/__tests__/addAuthConfig.test.ts
- packages/cli-helpers/src/auth/authTasks.ts
Another PR inspired by my review of #6956. This one is a simple search-replace
> authTasks: Rename to addConfigToWebApp

- packages/cli-helpers/src/auth/__tests__/addAuthConfig.test.ts
- packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
- packages/cli-helpers/src/auth/authTasks.ts
- packages/cli-helpers/src/auth/setupHelpers.ts
Yet another PR inspired by #6956 
Split `addAuthConfigToWeb` into three different tasks for better progress reporting
> More setup tasks for better progress reporting

- tasks/smoke-test/playwright.config.ts
Single quotes instead of double quotes
> Format playwright config file

- packages/cli-helpers/src/auth/authTasks.ts
- packages/cli-helpers/src/lib/index.ts
> Setup auth: Handle skipping api lib auth.ts

- docs/docs/auth/custom.md
- docs/docs/graphql.md
Reading through the new docs found a couple of readability corrections that could be made. Solid docs, as to be expected!
> Minor corrections to v4 GQL Armor and Auth docs

- __fixtures__/test-project/api/package.json
- __fixtures__/test-project/web/package.json
- packages/cli-helpers/src/auth/authTasks.ts
Supersedes https://github.com/redwoodjs/redwood/pull/6911.
> fix: setup web/src/auth.js file in JS projects

- packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
- packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
- packages/cli-helpers/src/auth/__tests__/mockFsFiles.ts
> authTasks: Improve tests to also cover tsx template

- packages/internal/src/generate/watch.ts
- packages/vite/bins/rw-vite-dev.mjs
I forgot to push this up as part of https://github.com/redwoodjs/redwood/pull/7384
> feat(dev): Enable restarting vite and typgen by typing "rs"

- packages/cli/src/commands/setup/auth/auth.js
I think the final `return false` really should have been `return true`. But instead of just making that change I moved the logic around a little bit to hopefully make it easier to reason about
> Set up auth: Fix isInstalled logic

- __fixtures__/test-project/scripts/seed.ts
- packages/create-redwood-app/template/scripts/seed.ts
Closes https://github.com/redwoodjs/redwood/issues/7128.
> fix(CRWA): import `hashPassword` from `@redwoodjs/auth-dbauth-api`

- docs/docs/auth/custom.md
Fixes part of https://github.com/redwoodjs/redwood/issues/7558; let's leave that issue open though, there's more to it.
> fix(docs): finish custom auth docs on authDecoder

- packages/api/src/validations/__tests__/validations.test.js
- packages/api/src/validations/validations.ts
Including those mentioned in #7481
> Fix validation types and tests

- packages/router/src/Set.tsx
Improve comments in Set.tsx. Mostly formatting.
> Set.tsx: Improve code comments

- docs/docs/typescript/utility-types.md
- docs/versioned_docs/version-3.x/typescript/utility-types.md
- docs/versioned_docs/version-4.0/typescript/utility-types.md
As pointed out in https://community.redwoodjs.com/t/typescript-performance-strict-mode/4636/13
> Fix wrong cell file names in docs

- packages/api-server/src/__tests__/logFormatter.test.ts
> Format source

- docs/versioned_docs/version-5.0/tutorial/chapter1/file-structure.md
- docs/versioned_docs/version-5.0/tutorial/chapter1/installation.md
- docs/versioned_docs/version-5.0/tutorial/chapter1/layouts.md
- docs/versioned_docs/version-5.0/tutorial/chapter1/prerequisites.md
- docs/versioned_docs/version-5.0/tutorial/chapter1/second-page.md
- docs/versioned_docs/version-5.0/tutorial/chapter2/getting-dynamic.md
- docs/versioned_docs/version-5.0/tutorial/chapter2/side-quest.md
- docs/versioned_docs/version-5.0/tutorial/chapter5/first-test.md
- docs/versioned_docs/version-5.0/tutorial/chapter6/comment-form.md
- docs/versioned_docs/version-5.0/tutorial/chapter6/comments-schema.md
- docs/versioned_docs/version-5.0/tutorial/chapter6/multiple-comments.md
- docs/versioned_docs/version-5.0/tutorial/foreword.md
Backports the changes in https://github.com/redwoodjs/redwood/pull/8154 to v5.
> chore(docs): backport v5 tutorial changes

- packages/project-config/package.json
Just updating the repository.directory value to match what it should be.
> chore(project-config): Fix repo directory value in project.json

- packages/auth-providers/azureActiveDirectory/web/package.json
> chore(auth-azure-active-directory-web): Fix typo in repo directory

- packages/create-redwood-app/src/create-redwood-app.js
Fixes https://github.com/redwoodjs/redwood/issues/8224
> fix(crwa): correctly filter on booleans for compat checks

- docs/docs/how-to/build-dashboards-fast-with-tremor.md
Fixes typo of "Tremor" in description front matter.
> docs: Update build-dashboards-fast-with-tremor.md typo in frontmatter

- packages/studio/frontend/src/Components/SearchFilterBar.tsx
> Fix studio lint warning

- docs/docs/how-to/dbauth-passwordless.md
This just makes the how-to easier to read.
After this is closed we can probably close #6204
> Fix passwordless doc typos

- docs/docs/forms.md
"There's some functions" is a little bit tough to read,  "There are some functions" is easier and more grammatically correct.
> Update forms.md to fix small grammatical error

- packages/cli/src/commands/setup/auth/auth.js
This is most likely a regression from https://github.com/redwoodjs/redwood/pull/8456
> Fix await import in auth setup

- .github/actions/check_test_project_fixture/check_test_project_fixture.mjs
Follow-up on https://github.com/redwoodjs/redwood/pull/8516
> Update command to rebuild test project fixture

- packages/cli/src/plugin.js
Rename to be more consistent with our naming convention.
> chore(cli): Rename command cache file

- __fixtures__/test-project/web/package.json
- __fixtures__/test-project/web/public/README.md
README changes after we updated all docs from Webpack to Vite
And updated Storybook version
> Update test-project after Vite doc changes

- packages/cli/src/commands/testHandler.js
The jest test output does not need to be caught and handled by the top level error handler. 
I must have either missed the output when testing or had a bad sync between framework and test project.
> fix(cli): Revert change to error display for `rw test`

- packages/cli/src/commands/experimental/setupStreamingSsrHandler.js
- packages/cli/src/commands/experimental/templates/streamingSsr/Document.tsx.template
- packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
- packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
entry.client needs to be updated 
entry.server and Document both needs to be added for streaming to work
This PR adds those two things to the setup command for streamingSsr
> Add files needed for React Streaming SSR

- docs/docs/how-to/oauth.md
- docs/versioned_docs/version-3.x/how-to/oauth.md
- docs/versioned_docs/version-4.x/how-to/oauth.md
- docs/versioned_docs/version-5.0/how-to/oauth.md
Thanks @dthyresson for the suggestion!
> Oauth How-to: Adds note about not exposing accessToken via SDL

- .github/workflows/publish-canary.yml
Update rw package versions in the CRWA templates package.jsons. Then git commit and push the changes
> push CRWA package version changes

- .github/workflows/publish-canary.yml
Set git username and email to be allowed to commit
Also specifies what branch to push to.
Using [GITHUB_REF_NAME](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables:~:text=branch%2D1.-,GITHUB_REF_NAME,-The%20short%20ref)
> GH Action: Set git config

- packages/create-redwood-app/templates/js/api/package.json
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/js/web/package.json
- packages/create-redwood-app/templates/ts/api/package.json
- packages/create-redwood-app/templates/ts/package.json
- packages/create-redwood-app/templates/ts/web/package.json
Until we've decided how we want to handle the pushed version of CRWA RW versions, let's keep it at latest stable
Related: https://github.com/redwoodjs/redwood/pull/8863
> CRWA use RW v5.4.3

- packages/cli/src/commands/serve.js
Use `yarn rw serve` for serving also when the RSC experiment is enabled
> RSC: Use rw serve

- docs/docs/create-redwood-app.md
Was reading through the docs because I needed to add a new flag, and found some thing we might want to change.
> Proofreading updates to the CRWA docs

- packages/vite/package.json
- yarn.lock
I was getting `yarn constraints` errors on this
> @rwjs/vite: Pin acorn-loose version

- docs/docs/tutorial/chapter1/file-structure.md
RW v6 (our implementation of Vite support really) introduces a new file, `entry.client.{jsx,tsx}`. 
This PR adds a short description of this file to the tutorial
This is a follow-up to the changes made here https://github.com/redwoodjs/redwood/pull/8959
> Docs: Explain the entry.client.{jsx,tsx} file

- __fixtures__/test-project/README.md
- __fixtures__/test-project/web/package.json
- __fixtures__/test-project/web/src/components/AuthorCell/AuthorCell.stories.tsx
- __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.stories.tsx
- __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.stories.tsx
- __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.stories.tsx
- __fixtures__/test-project/web/src/index.css
- __fixtures__/test-project/web/src/pages/AboutPage/AboutPage.stories.tsx
- docs/docs/quick-start.md
- packages/create-redwood-app/templates/js/README.md
- packages/create-redwood-app/templates/ts/README.md
- tasks/test-project/rebuild-test-project-fixture.js
Fixes https://community.redwoodjs.com/t/quick-start-tutorial-storybook-section-throws-error/5175.
> fix(docs): update quick start to fix Storybook start up

- docs/docs/cells.md
Fixed the link to CreateCells.tsx
> Fixed broken link (404) in the cell tutorial

- packages/create-redwood-app/templates/ts/web/src/App.tsx
Corrects lint warning in the create redwood app package
> chore(lint): crwa linting

- packages/cli/src/commands/generate/dbAuth/dbAuth.js
> generate dbAuth: one more thing formatting

- packages/auth-providers/dbAuth/setup/src/setupHandler.ts
- packages/auth-providers/supertokens/setup/src/__tests__/setupHandler.test.ts
- packages/auth-providers/supertokens/setup/src/setupHandler.ts
- packages/cli-helpers/src/auth/setupHelpers.ts
Refactor `standardAuthHandler` to take an array of extra tasks instead of just one
> auth setup: Array of extra tasks

- packages/auth-providers/dbAuth/api/src/index.ts
- packages/auth-providers/dbAuth/setup/src/templates/api/lib/auth.ts.template
- packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/lib/auth.ts.template
I messed up two exports in #9248. This PR fixes that.
> dbAuth: Fix cookie related exports

- packages/router/src/util.ts
I'm going to make some actual logic updates to this file and didn't want these minor changes to muddle that PR, so doing this one first.
> Router utils: Fix some spelling mistakes and other minor changes

- packages/api-server/src/plugins/withWebServer.ts
This PR copies the fix in https://github.com/redwoodjs/redwood/pull/9272 into `@redwoodjs/api-server`. The `@redwoodjs/api-server` can be accessed via `npx @redwooodjs/api-server rw-server api`. We won't have to do this once the code between the two entry points is deduplicated but till then, yeah.
> fix(api-server): copy fallback fix from #9272

- .github/actions/issue_metrics/monthly_issue_metrics.yml
- .github/actions/issue_metrics/monthly_issue_metrics_json.yml
- .github/actions/issue_metrics/weekly_issue_metrics.yml
This PR adds some GH actions that all uses https://github.com/github/issue-metrics/tree/main to generate issue metrics
> Issue Metrics GitHub action

- .github/workflows/weekly_issue_metrics_json.yml
> Issue Metrics: Weekly JSON report

- README.md
Add a Leadership Team section to the README
> README: Add Leadership Team

- __fixtures__/test-project-rsa/web/src/Routes.tsx
- __fixtures__/test-project-rsa/web/src/entry.client.tsx
- __fixtures__/test-project-rsc-external-packages/web/src/Routes.tsx
- __fixtures__/test-project-rsc-external-packages/web/src/entry.client.tsx
- packages/cli/src/commands/experimental/templates/rsc/Routes.tsx.template
- packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
Using the standard Routes.tsx file for routing definitions
> RSC: Use Routes.tsx for (client-side) routing

- __fixtures__/test-project/.vscode/tasks.json
- __fixtures__/test-project/web/package.json
A couple of PRs have been merged that affected the test project. Updating it to incorporate those changes, to make it less confusing to contribute to the framework ("Why are those files updated? I didn't touch anything related to those"
> Update test project fixture

- docs/docs/environment-variables.md
- docs/versioned_docs/version-6.0/environment-variables.md
This is a continuation of https://github.com/redwoodjs/redwood/pull/9289
For some reason I wasn't able to push changes to that PR directly, so I had to create a new PR
> Add a note about build and runtime environments

- packages/studio/api/index.ts
- packages/studio/api/mail/index.ts
Wow, I did a real shoddy job with the #9709 PR 🙁 
This fixes two obvious errors. Hopefully I didn't introduce even more 🙁
> Fix Studio paths

- tasks/nmHoisting/nmHoisting.mjs
- tasks/nmHoisting/nmHoistingData.js
- tasks/nmHoisting/nmHoistingVisualize.html
- tasks/nmHoisting/nmHoistingVisualize.js
This PR adds a comparison view to the nmHoisting visualisation. It also makes the actual generation script a little more robust.
The code added here is a little messier and not in the same style as the existing. We should refactor this in the future.
> chore(tasks): Add comparison view to nmHoisting visualisation

- docs/docs/auth/supertokens.md
Fixes a typo that slipped through in https://github.com/redwoodjs/redwood/pull/9757/files/d9c3c6b4ca1cdb50a06b7c3088efea47e2bc166c#r1436602477
> docs: Supertokens.md: Fix typo

- packages/router/src/router-context.tsx
With the (semi-) recent changes to the router code this context implementation can be simplified to just use a single context instead of two as it did before.
The context values are never updated except for when rerendering and new values are passed in as props.
> Router: Use a single RouterContext

- packages/cli-helpers/src/lib/__tests__/project.addTomlSetting.test.ts
Forgot to add the new test file for #9832 🙈
> Add missing cli-helpers test file

- packages/auth-providers/netlify/api/src/__tests__/netlify.test.ts
- packages/cli-helpers/src/auth/__tests__/authFiles.test.ts
- packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
- packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
- packages/cli-helpers/src/lib/__tests__/index.test.ts
- packages/cli-helpers/src/lib/__tests__/project.addTomlSetting.test.ts
- packages/cli-helpers/src/lib/__tests__/project.test.ts
- packages/cli-helpers/src/lib/__tests__/version.test.ts
- packages/cli-helpers/tsconfig.json
- packages/cli/src/commands/setup/graphql/features/trustedDocuments/__tests__/trustedDocuments.test.ts
- packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
Ran into some TS errors that I decided to fix
Plus one spelling mistake and a `@ts-expect-error` comment that was pretty easy to get rid of
> chore(tests): Fix some TS errors

- packages/api-server/src/__tests__/createServer.test.ts
When I see this, I find it hard to know if all that output means the test failed or not
This PR mocks logging, to make the tests run cleanly.
> chore(tests): api-server: Suppress logs

- packages/api-server/package.json
- packages/api-server/src/__tests__/createServer.test.ts
- packages/api-server/src/__tests__/fastify.test.ts
- packages/api-server/src/__tests__/lambdaLoader.test.ts
- packages/api-server/src/__tests__/lambdaLoaderNumberFunctions.test.ts
- packages/api-server/src/__tests__/requestHandlers/awsLambdaFastify.test.ts
- packages/api-server/src/__tests__/withFunctions.test.ts
- packages/api-server/tsconfig.build.json
- packages/api-server/tsconfig.json
Wanted to get rid of some red squiggles in the api-server tests.
> chore(tests): api-server: Improve types

- __fixtures__/test-project-rsc-external-packages-and-cells/.vscode/settings.json
- __fixtures__/test-project-rsc-external-packages-and-cells/README.md
- __fixtures__/test-project-rsc-external-packages-and-cells/api/package.json
- __fixtures__/test-project-rsc-external-packages-and-cells/package.json
- __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/NewUserExample/NewUserExample.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExamplesCell/UserExamplesCell.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entries.ts
Various updates to the RSC test project fixture to bring it up to date with the latest RW code. And to make it look closer to a real/regular RW project
> RSC: chore(test): Update RSC test fixture project

- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/Routes.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExample/UserExample.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExampleServerCell/UserExampleServerCell.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entries.ts
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/pages/UserExample/UserExamplePage/UserExamplePage.tsx
- tasks/smoke-tests/rsc-external-packages-and-cells/tests/rsc-external-packages-and-cells.spec.ts
RSC smoke tests for server rendered cells
> RSC: Server cell smoke tests

- .github/renovate.json
Disable renovate for our special Apollo package
See https://github.com/redwoodjs/redwood/pull/9992 for context
> chore(renovate): Disable for experimental apollo package

- CHANGELOG.md
Updates the Changelog with v7 information.
> chore(changelog): add v7

- packages/vite/src/rsc/rscWorker.ts
Because we always know where the `entries.ts` file is located we can simplify the code a bunch. This is one of the benefits of being an opinionated framework 😁
> RSC: Simplify entriesFile loading

- packages/vite/src/react-server-dom-webpack/node-loader.ts
"serverbut" -> "server but"
and source code formatting
> RSC: Fix node-loader message typo

- packages/vite/src/buildFeServer.ts
- packages/vite/src/streaming/buildForStreamingServer.ts
Mostly a refactor. There's a tiny change re `emptyOutDir`, but nothing any user should have to care about.
I marked this RSC even though it's StreamingSSR code because it also has/uses code that's only RSC related
> SSR: Extract buildForStreamingServer function

- packages/project-config/src/paths.ts
- packages/vite/src/rsc/rscBuildAnalyze.ts
- packages/vite/src/rsc/rscBuildClient.ts
- packages/vite/src/rsc/rscBuildClientEntriesFile.ts
- packages/vite/src/rsc/rscBuildForServer.ts
- packages/vite/src/rsc/rscBuildRwEnvVars.ts
- packages/vite/src/rsc/rscVitePlugins.ts
- packages/vite/src/rsc/rscWorker.ts
- packages/vite/src/rsc/rscWorkerCommunication.ts
- packages/vite/src/runFeServer.ts
When other people read the code you've written it becomes much more obvious where the parts that are difficult to understand are, and where more comments are needed, and where the naming doesn't make sense, etc.
This PR addresses some of those areas
> RSC: Update comments, naming etc based on Danny's input

- packages/vite/src/runFeServer.ts
Don't do a try/catch if we know it'll fail
> RSC: runFeServer: wrap RSC code with `if (rscEnabled)`

- packages/vite/src/rsc/rscVitePlugins.ts
- packages/vite/src/rsc/rscWebpackShims.ts
Just a small refactor where I extract the Webpack shims out into their own file
> RSC: Extract webpack shims into their own file

- packages/vite/src/plugins/vite-plugin-rsc-transform.ts
Make the vite rsc transform plugin self-contained by doing the transform inside the plugin itself
> RSC: transform inside plugin

- .github/workflows/ci.yml
- tasks/smoke-tests/rsc-dev/playwright.config.ts
- tasks/smoke-tests/rsc-dev/tests/rsc.spec.ts
Adds a basic smoke test for RSC dev that's basically the RSC serve one to make sure we don't regress.
> chore(rsc): add smoke test for rsc dev

- packages/vite/src/lib/getMergedConfig.ts
- packages/vite/src/rsc/rscBuildAnalyze.ts
- packages/vite/src/rsc/rscBuildClient.ts
- packages/vite/src/rsc/rscBuildForServer.ts
- packages/vite/src/streaming/buildForStreamingServer.ts
For RSCs, while we're debugging and figuring things out, it'd be more helpful for me at least to unminify dist for now.
> chore(rsc): unminify dist

- packages/vite/src/client.ts
- packages/vite/src/rsc/rscRequestHandler.ts
Seemed like this was supposed to be a question mark to make a query string url and @Tobbe confirmed
> fix(rsc): use query string in rsc url

- README.md
- __fixtures__/fragment-test-project/web/src/entry.client.tsx
- __fixtures__/test-project-rsa/web/src/entry.client.tsx
- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/entry.client.tsx
- __fixtures__/test-project/web/src/entry.client.tsx
- docs/docs/custom-web-index.md
- docs/docs/introduction.md
- docs/versioned_docs/version-1.x/custom-web-index.md
- docs/versioned_docs/version-2.x/custom-web-index.md
- docs/versioned_docs/version-3.x/custom-web-index.md
- docs/versioned_docs/version-4.x/custom-web-index.md
- docs/versioned_docs/version-5.x/custom-web-index.md
- docs/versioned_docs/version-6.x/custom-web-index.md
- docs/versioned_docs/version-7.0/custom-web-index.md
- packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
- packages/create-redwood-app/templates/js/web/src/entry.client.jsx
- packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
- packages/web/src/entry/index.js
> [#10273] Fix react docs links

- __fixtures__/test-project/web/package.json
Just needed to update the package.json file to not block other PRs getting stuck on the fixture CI check
> chore(test-project): Update autoprefixer and postcss versions

- README.md
This adds a section to explain what we intend to do with Bighorn and info on how to follow along. Also removes Features and How it Works sections, to simplify things.
> Update Readme for Bighorn epoch.

- __fixtures__/test-project/web/package.json
Updating the test-project fixture to make CI pass for all other PRs
> chore(test-project): Update tailwindcss version

- __fixtures__/example-todo-main/web/src/graphql/fragment-masking.ts
I kept seeing this diff after running tests locally. Given the contents of the other files in this fixture it looks like this comment should be here so I'm adding it.
> chore(fixtures): linting comment

- .github/actions/detect-changes/cases/docs_changes.mjs
- .github/actions/detect-changes/detectChanges.mjs
Refactoring the `docs_only` detection in preparation for future feature additions to the `detectChanges` code
> chore(ci): Refactor docs_only detection

- .github/actions/detect-changes/README.md
- .github/actions/detect-changes/detectChanges.mjs
Wanted to make this code easier to work with and expand on. So I added a README describing how to run/test it locally, and refactored out a method to get a json reply from a given URL, with retry handling on failure
> chore(ci): Refactor detectChanges and add README

- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
I accidentally changed two files too many when I did #10384. This PR undos those changes. Thankfully it was only comment changes, so didn't affect any behavior.
> chore(ci): Undo unrelated docs-only change

- .github/actions/detect-changes/detectChanges.mjs
Had two bugs related to setting the `code` output.
When not on a branch the old `code_only` and `changesets_only` outputs were still used
When all tests were supposed to be run, the `code` output was set to `false`, but should have been `true`
> chore(ci): Fix bug related to when setting the detectChanges `code` output

- .github/actions/detect-changes/detectChanges.mjs
PR https://github.com/redwoodjs/redwood/pull/10393 did two things (which is never a good idea...). It fixed some logic related to setting the `code` output (yay 🎉 ). But it also subtly changed how we handle changed files (nay 🙁). That last part wasn't fully thought through... So this PR reverts some of those changes and implements the logic in a (hopefully) more correct way.
> chore(ci): detectChanges: Iterate on merge commit handling

- packages/router/src/server-router.tsx
- packages/vite/src/plugins/vite-plugin-rsc-css-preinit.ts
- packages/vite/src/rsc/rscBuildForServer.ts
Remove some noisy console.logs and minor fixes to a few code comments
> RSC: Clean up some comments and logs

- packages/cli/src/commands/upgrade.js
Re-applies PR #10491
The labeling and milestone here is a bit weird/difficult.
This is a new feature, but not user-facing. This allows us to ship with patches for packages we depend on. But users need to have this feature first, already installed, before we can actually start using it. Can't ship this together with packages that need patching.
> fix(upgrade): Download yarn patches

- packages/router/src/__tests__/analyzeRoutes.test.tsx
Note: Made this a PR and added the RSC milestone simply to make release triage easier - committing to main will mean I have to explicitly add the commit as ignored.
> chore(linting): fix minor lint warnings

- packages/vite/src/middleware/invokeMiddleware.ts
I was reading through this code when trying to understand https://github.com/redwoodjs/redwood/pull/10537 and noticed a couple of minor things I wanted to change
> chore(middleware): Format code and comments and fix comment grammar

- packages/auth-providers/dbAuth/middleware/README.md
- packages/auth-providers/supabase/middleware/README.md
Some formatting, grammar and a comment I don't think should be there
> chore(docs): Update dbAuth and Supabase middleware READMEs

- packages/vite/src/client.ts
We now have a separate `clientSsr.ts` file that we use during SSR, so the TODO comment here isn't relevant anymore.
> RSC: Fix TODO regarding SSR in client.ts

- packages/vite/src/rsc/rscWorker.ts
Just refactoring a bit to make it easier to see what's going on for just RSC (and not having to mentally filter out the RSA stuff). Plus make it easier to modify just the RSC (or just the RSA) bits and knowing you're not interfering with the other one (rsc or rsa)
> Split RSC and RSA handling in rscWorker

- package.json
- yarn.lock
It does not look like we use this package at all now so we should remove it from our dependency list.
> chore(deps): Remove unused octokit package

- .github/actions/set-up-rsc-project/README.md
The README file wasn't true to what was actually happening, so updated it to match. Also fixed a typo.
> chore(ci): Update rsc readme

- __fixtures__/fragment-test-project/web/src/App.tsx
- __fixtures__/fragment-test-project/web/src/entry.client.tsx
- __fixtures__/test-project-rsa/web/src/App.tsx
- __fixtures__/test-project-rsa/web/src/entry.client.tsx
- __fixtures__/test-project-rsc-kitchen-sink/web/src/App.tsx
- __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.client.tsx
- packages/create-redwood-app/templates/ts/web/src/App.tsx
The CRWA template was updated as part of #10441. This PR updates some of our test projects to match the new template
> chore(__fixtures__): Make test projects match newer CRWA template

- __fixtures__/test-project-rsa/web/src/entry.client.tsx
- __fixtures__/test-project-rsc-kitchen-sink/web/src/entry.client.tsx
This is a silly little PR. Should have been part of #10655
> chore(__fixtures__): Follow-up: Make test projects match newer CRWA template

- __fixtures__/test-project-rsc-kitchen-sink/web/src/components/EmptyUser/EmptyUsersCell/EmptyUsersCell.tsx
Just tidying up the source a bit of this file in a separate PR so that I don't have to include it as part of #10557
> RSC: Source format of EmptyUsersCell in kitchen-sink

- packages/vite/src/clientSsr.ts
- packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.mts
Update some comments and change a variable name to make clientSsr usage a little bit more clear. Still room for improvements for sure!
> RSC: clientSsr changes to make usage more clear

- docs/docs/how-to/supabase-auth.md
Update import { useAuth } from '@redwoodjs/auth' to 'src/auth' in the Supabase authentication how-to
> docs: update useAuth import in Supabase how-to

- packages/vite/src/plugins/vite-plugin-rsc-transform-client.ts
Cleaning up after #10682
Didn't realize I had auto-merge turned on 🙈 A couple of extra console.logs ended up being merged
> RSC: Support CJS 'use client' modules

- packages/vite/src/ClientRouter.tsx
Fetch new page from RSC server when navigating
> RSC: client side navigation

- .changesets/10690.md
- __fixtures__/fragment-test-project/package.json
- __fixtures__/test-project-rsa/package.json
- __fixtures__/test-project-rsc-kitchen-sink/package.json
- __fixtures__/test-project/package.json
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/ts/package.json
See https://github.com/swc-project/swc/issues/8988
and https://github.com/storybookjs/storybook/issues/27385
> fix(deps) Temporary fix for broken @swc/types package publishing

- packages/router/src/location.tsx
Nobody knows how class components work anymore (at least I can't remember). So I added some comments to make it easier to understand the code here.
Eventually we should just convert this to a function component. But now now.
> chore(comments): Explain how class components work >.<

- packages/auth-providers/auth0/web/tsconfig.json
- packages/auth-providers/azureActiveDirectory/web/tsconfig.json
- packages/auth-providers/clerk/web/tsconfig.json
- packages/auth-providers/dbAuth/api/tsconfig.json
- packages/auth-providers/dbAuth/middleware/tsconfig.json
- packages/auth-providers/dbAuth/web/tsconfig.json
- packages/auth-providers/firebase/web/tsconfig.json
- packages/auth-providers/netlify/web/tsconfig.json
- packages/auth-providers/supabase/api/tsconfig.json
- packages/auth-providers/supabase/middleware/tsconfig.json
- packages/auth-providers/supabase/web/tsconfig.json
- packages/auth-providers/supertokens/web/tsconfig.json
Started this work in https://github.com/redwoodjs/redwood/pull/10706 but found some more tsconfig files that needed updating
> chore(build) reference auth.tsconfig.build

- packages/auth-providers/supabase/api/package.json
- packages/auth-providers/supabase/api/tsconfig.json
The dependences and devDependencies listed in package.json didn't reflect actual usage. So updated those.
Also, the `references` section of tsconfig was wrong.
> chore(auth): auth-supabase-api dependency fixes

- packages/vite/src/lib/getMergedConfig.ts
Fixes this warning I was getting on an unrelated PR
> RSC: Remove forbidden non-null assertion

- packages/vite/src/middleware/MiddlewareRequest.ts
- packages/vite/src/middleware/MiddlewareResponse.ts
Typos, spelling mistakes and comment format fixes
> chore(spelling): Fix some spelling mistakes in vite/middleware

- .changesets/10788.md
- __fixtures__/test-project/web/src/pages/LoginPage/LoginPage.tsx
- __fixtures__/test-project/web/src/pages/SignupPage/SignupPage.tsx
- packages/auth-providers/dbAuth/middleware/src/index.ts
- packages/cli/src/commands/generate/dbAuth/__tests__/__snapshots__/dbAuth.test.js.snap
- packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template
- packages/cli/src/commands/generate/dbAuth/templates/login.webAuthn.tsx.template
- packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template
- packages/vite/src/middleware/invokeMiddleware.ts
Shouldn't be importing react twice. Looks really weird and is surprising, which is usually not a good thing.
> fix(dbauth): Combine react imports

- packages/cli/src/commands/generate/dbAuth/__tests__/__snapshots__/dbAuth.test.js.snap
- packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.test.js
Update test case for `rw g dbAuth` that tests the WebAuthn prompt to actually answer "yes" as it's supposed to. Also had to update the snapshots that were previously expecting the wrong output
> chore(dbAuth): Fix test for webauthn prompt in `g dbAuth`

- packages/auth-providers/dbAuth/setup/package.json
- yarn.lock
Just fixes the yarn check issue.
> chore: fix deps

- __fixtures__/fragment-test-project/web/package.json
- __fixtures__/test-project-rsa/web/package.json
- __fixtures__/test-project-rsc-kitchen-sink/web/package.json
- __fixtures__/test-project/package.json
- __fixtures__/test-project/web/package.json
- packages/auth-providers/auth0/web/package.json
- packages/auth-providers/azureActiveDirectory/web/package.json
- packages/auth-providers/clerk/web/package.json
- packages/auth-providers/dbAuth/web/package.json
- packages/auth-providers/firebase/web/package.json
- packages/auth-providers/netlify/web/package.json
- packages/auth-providers/supabase/web/package.json
- packages/auth-providers/supertokens/web/package.json
- packages/auth/package.json
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/js/web/package.json
- packages/create-redwood-app/templates/ts/package.json
- packages/create-redwood-app/templates/ts/web/package.json
- packages/forms/package.json
- packages/ogimage-gen/package.json
- packages/prerender/package.json
- packages/router/package.json
- packages/storybook/package.json
- packages/vite/package.json
- packages/web/package.json
- yarn.lock
RW v8.0.0 should still release with React 18
> deps(react): 18.3.1

- README.md
Move Dom from Maintainers to Alumni
> chore(readme): Update contributors section: Dom to Alumni

- __fixtures__/test-project-rsc-kitchen-sink/web/src/pages/LoginPage/LoginForm.tsx
- tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
- tasks/smoke-tests/shared/common.ts
Add CI tests for accessing the profile page and then clicking the logout button on there
> RSC: Test logging out

- packages/router/src/server-router.tsx
Throw with a 401 or 403 message if the user isn't authorized to access the requested route
> RSC: Add auth support to ServerRouter

- packages/cli-helpers/package.json
- packages/cli-helpers/src/lib/loadEnvFiles.ts
Just a couple of minor clean things that I missed when bringing loadEnvFiles in over from the cli package
> chore(cli-helpers): loadEnvFiles cleanup

- packages/cli/src/commands/generate/directive/directive.js
Before:
After:
Notes for release:
I didn't include a changeset in this PR because I don't think it's anything we need to include in any release notes
> fix(g directive): Notes formatting

- packages/cli/src/commands/experimental/templates/rsc/Counter.tsx.template
- packages/cli/src/commands/experimental/templates/rsc/HomePage.tsx.template
Improve initial impression of RSCs by removing red squiggles
> RSC: Fix red squiggles in default template

- docs/versioned_docs/version-7.1/tutorial/foreword.md
- docs/versioned_docs/version-7.3/tutorial/foreword.md
- docs/versioned_docs/version-7.4/tutorial/foreword.md
- docs/versioned_docs/version-7.5/tutorial/foreword.md
- docs/versioned_docs/version-7.6/tutorial/foreword.md
- docs/versioned_docs/version-7.7/tutorial/foreword.md
Follow up to #10959 for the minor versions which are stored in the next branch.
> chore(docs): remove MailChimp from minor versions

- packages/core/package.json
- yarn.lock
I think we don't need these packages anymore since we removed webpack.
> chore(deps): Remove webpack related packages

- .gitignore
- package.json
- tasks/test-project/rebuild-test-project-fixture.ts
- yarn.lock
See: #10805. 
A discussion on what should be checked in to git or not with regards to `.nx`: https://github.com/nrwl/nx/discussions/20813
I have also included removing it from the fixture generation which seems logical.
> chore(deps): update chore

- packages/router/attw.ts
Removing comments and fixing formatting that were left-over from copying this script from the vite package
> chore(router): attw: removed invalid copy/pasted comment

- packages/cli/src/commands/generate/page/templates/page.tsx.template
- packages/web/package.json
As title, also adds Metadata to the web package exports field
> chore(rsc): Update page generate templates to use exports fields

- packages/graphql-server/package.json
- packages/graphql-server/src/plugins/useArmor.ts
- yarn.lock
https://github.com/Escape-Technologies/graphql-armor/releases/tag/%40escape.tech%2Fgraphql-armor%402.3.2
https://github.com/Escape-Technologies/graphql-armor/releases/tag/%40escape.tech%2Fgraphql-armor%402.4.0
> fix(deps): update dependency @escape.tech/graphql-armor to v2.4.0

- packages/create-redwood-rsc-app/src/prerequisites.ts
Improves the messaging around yarn detection
Improves the output by tweaking whitespace
Fixes an issue where it would fail to detect corepack when running through tsx
Fixes an issue with paths when there are multiple yarns in $PATH
> fix(crwrsca): Fix yarn detection when running using tsx

- .changesets/10266.md
- .changesets/10412.md
- .changesets/10464.md
- .changesets/10538.md
- .changesets/10677.md
- .changesets/10859.md
- .changesets/10867.md
- .changesets/10871.md
- .changesets/10873.md
- .changesets/10874.md
- .changesets/10910.md
- .changesets/10922.md
- .changesets/11068.md
This simply tidies up some of the existing changelog entries.
> chore(changelog): tweaks to existing entries

- packages/create-redwood-rsc-app/package.json
- packages/create-redwood-rsc-app/yarn.lock
npm was complaining about a couple of fields in the crwrsca package.json file. This PR fixes that.
Also has to please yarn. So this is the best middle-way I could find
There's a related issue on yarn here: https://github.com/yarnpkg/berry/issues/6184
> chore(crwrsca): npm pkg fix

- packages/router/src/rsc/RscCache.ts
Add support for reading current RSC cache entries
> feat(rsc): rsc-cache-read

- __fixtures__/rsc-caching/web/src/components/ServerDelayForm/ServerDelayForm.css
- __fixtures__/rsc-caching/web/src/components/ServerDelayForm/ServerDelayForm.tsx
- __fixtures__/rsc-caching/web/src/components/ServerDelayForm/actions.ts
Forgot to `git add` some new files when I did #11128 🙁
> chore(rsc): Add ServerDelayForm to rsc-caching fixture (missing files)

- packages/create-redwood-rsc-app/knip.json
> chore(crwrsca): Update knip config to include publish.ts

- packages/create-redwood-rsc-app/src/prerequisites.ts
> fix(crwrsca): Spell please correctly

- packages/create-redwood-rsc-app/src/latest.ts
Don't use the `@tobbe.dev` version
> fix(crwrsca): Use the correct version of crwrsca when spawning

- packages/create-redwood-rsc-app/src/config.ts
- packages/create-redwood-rsc-app/src/index.ts
- packages/create-redwood-rsc-app/src/version.ts
> feat(crwrsca): Add support for --version/-V

- packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
See https://github.com/redwoodjs/redwood/pull/11158 for why I'm adding this 😅
> RSC: RSA: Add more comments to the basic 'use server' check

- packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Making code I've copy/pasted better match our RW coding style
> RSC: RSA: Better match error handling with how we generally do it in RW

- packages/vite/tsconfig.json
Apply autoformat on the vite tsconfig in preparation for some changes I'm going to make
> chore(tsconfig): Format vite tsconfig

- __fixtures__/test-project/web/package.json
As title. Just needed to commit the version update for the CI check to go green on other PRs.
> chore(fixture): Rebuild test project fixture

- .github/actions/check_changesets/package.json
- .github/actions/check_create_redwood_app/package.json
- .github/actions/detect-changes/package.json
- __fixtures__/test-project/package.json
- docs/package.json
- package.json
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/ts/package.json
- tasks/check/package.json
> chore(deps): update yarn to v4.4.0

- packages/vite/src/plugins/__tests__/vite-plugin-rsc-transform-server.test.ts
This should have been part of #11169
> chore(rsc): Switch last remaining transform-server test to inline snapshot

- .eslintrc.js
- package.json
- yarn.lock
Changes:
1. Refactors the usage of react and react-hooks plugins
2. Consolidates the ts-eslint plugin usage
> chore(lint): refactor react, react-hooks and ts-eslint usage

- .eslintrc.js
- packages/api/src/auth/index.ts
- packages/api/src/cors.ts
- packages/auth-providers/auth0/web/src/auth0.ts
- packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
- packages/auth-providers/dbAuth/setup/src/__tests__/setupDataMockDMMF.test.ts
- packages/codemods/src/codemods/v2.3.x/tsconfigForRouteHooks/tsconfigForRouteHooks.ts
- packages/forms/src/FormError.tsx
- packages/graphql-server/src/__tests__/makeMergedSchema.test.ts
- packages/internal/src/generate/trustedDocuments.ts
- packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
- packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
- packages/router/src/a11yUtils.ts
- packages/vite/src/devFeServer.ts
- packages/vite/src/lib/registerFwGlobalsAndShims.ts
- packages/vite/src/middleware/register.test.ts
- packages/vite/src/react-server-dom-webpack/node-loader.ts
- packages/web/src/components/DevFatalErrorPage.tsx
Enables `typescript-eslint/prefer-optional-chain` and addressed issues raised.
> chore(lint): enable 'typescript-eslint/prefer-optional-chain'

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/rfc.yml
- .github/actions/actionsLib.mjs
- .github/actions/check_changesets/check_changesets.mjs
- .github/actions/check_create_redwood_app/check_create_redwood_app.mjs
- .github/actions/detect-changes/README.md
- .github/actions/detect-changes/cases/rsc.mjs
- .github/actions/detect-changes/cases/ssr.mjs
- .github/actions/require-milestone/requireMilestone.mjs
- .github/actions/set-up-rsa-project/jsconfig.json
- .github/actions/set-up-rsa-project/setUpRsaProjectGitHub.mjs
- .github/actions/set-up-rsa-project/setUpRsaProjectLocally.mjs
- .github/actions/set-up-rsc-kitchen-sink-project/jsconfig.json
- .github/actions/set-up-rsc-kitchen-sink-project/setUpRscKitchenSinkProjectGitHub.mjs
- .github/actions/set-up-rsc-kitchen-sink-project/setUpRscKitchenSinkProjectLocally.mjs
- .github/actions/set-up-rsc-project/jsconfig.json
- .github/actions/set-up-rsc-project/setUpRscProject.mjs
- .github/actions/set-up-rsc-project/setUpRscProjectLocally.mjs
- .github/actions/set-up-test-project/action.yaml
- .github/actions/set-up-test-project/setUpTestProject.mjs
- .github/actions/telemetry_check/check.mjs
- .github/scripts/publish_canary.sh
- .github/workflows/check-changelog.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
- .github/workflows/require-release-label.yml
- .prettierignore
> chore(formatting): include .github dir in prettier

- crowdin.yml
I don't really have any context around this file. I wasn't with the project when it was last touched. It hasn't been updated in years and the content inside it looks outdated. 
I would suggest we just delete file and if we need to look into our translation setup again then we can do so. No point in an old file laying around if it's not providing value.
> chore: delete crowdin config file

- .prettierignore
> chore(lint): tidy up the prettier ignore

- packages/core/package.json
- yarn.lock
Looks like these are some webpack specific dependencies we don't need anymore.
> chore(deps): Remove webpack related dependencies

- README.md
Kris is no longer an active Maintainer
> chore(README): Move Kris from Maintainer to Alumni

- README.md
Put all maintainers on one row now that there are only five of us
> chore(README): Fix formatting. One row

- README.md
> chore(readme): Add my middle initials

- docs/docs/tutorial/chapter7/api-side-currentuser.md
Changed '@requireAdmin' to '@requireAuth' as I believe this was a mistake, and also added a title/fixed some highlighting in the code containers related to adminPost services as it was missing/broken.
> Docs: Updated api-side-currentuser.md

- docs/docs/tutorial/chapter7/api-side-currentuser.md
CI was failing for other PRs, so wanted to get this fix in
> chore(docs): fix docs formatting

- tasks/smoke-tests/rsc-kitchen-sink/tests/rsc-kitchen-sink.spec.ts
A broken test seems to have passed CI somehow 🙁 🤷 
This PR fixes the test
> chore(test): Fix RSC server cell smoke test

- packages/api-server/tsconfig.json
- packages/cli/tsconfig.json
Properly link to api-server's tsconfig.build.json file
> chore(tsconfig): Properly link to api-server's tsconfig

- packages/cli/vitest.workspaces.ts
I had this locally, but had forgotten to save the file when I did https://github.com/redwoodjs/redwood/pull/11350
> chore(cli tests): Fix include glob

- docs/docs/background-jobs.md
Also moves instructions for running a job immediately from a :::note to a full section.
Closes #11360
> Adds docs for how to do recurring jobs

- packages/router/src/rsc/rscFetchForClientRouter.tsx
- packages/vite/src/buildRscClientAndServer.ts
- packages/vite/src/client.ts
- packages/vite/src/rsc/rscBuildAnalyze.ts
- packages/vite/src/rsc/rscRequestHandler.ts
- packages/vite/src/rsc/rscStudioHandlers.ts
- packages/vite/src/rsc/rscWorker.ts
- packages/vite/src/rsc/rscWorkerCommunication.ts
It's React Server Actions (not react server functions)
> chore(rsc): Rename rsf -> rsa

- .github/workflows/check-changelog.yml
- .github/workflows/check-create-redwood-app.yml
- .github/workflows/check-test-project-fixture.yml
- .github/workflows/codeql-analysis.yml
Working towards have the minimum permissions in our CI workflows.
> chore(ci): More workflow permission changes

- docs/yarn.lock
> chore(deps): Bump 'loader-utils' within docs

- __fixtures__/test-project-rsc-kitchen-sink/web/src/layouts/AuthLayout/AuthLayout.tsx
The internal name used for the component was wrong
> chore(fixtures): Use proper name for AuthLayout component

- packages/vite/src/rsc/rscRequestHandler.ts
Consistent naming of internal variables
> rscRequestHandler.ts: Make BASE_PATH naming match client.ts

- __fixtures__/test-project/web/package.json
dependabot has updated postcss, so we need to update the test-project too
> chore(test-project): Update postcss to 8.4.42

- __fixtures__/test-project/web/package.json
Updates fixture after rebuild.
> chore: Rebuild fixture

- packages/vite/src/plugins/vite-plugin-rsc-transform-server.ts
Mostly moving things around and formatting code.
The biggest change is the extraction of the `registerServerRef` function
> chore(rsc): Refactor: Clean up RSA babel transform

- __fixtures__/test-project-rsc-kitchen-sink/web/src/Routes.tsx
Add two missing routes to the RSA blog example in the kitchen sink test project
> chore(rsa): Add missing routes to test project blog

- __fixtures__/test-project/web/package.json
Updating the test project to use the new postcss version
I wish we could automate this!
> chore(test-project): Update to postcss 8.4.45

- packages/vite/src/rsc/rscWorker.ts
- packages/vite/src/rsc/rscWorkerCommunication.ts
Not all messages were ever sent from rscWorkerCommunication to the worker. So I'm removing a bunch of unused code here
> chore(rsc): Remove unused methods in the worker

- packages/router/src/rsc/ServerRouter.tsx
- packages/vite/modules.d.ts
- packages/vite/src/rsc/rscRequestHandler.ts
- packages/vite/src/rsc/rscWorker.ts
- packages/vite/src/utils.ts
PR with random minor changes. Mostly comments, console logs etc. To limit churn in the PR that removes the worker. So it's easier to see what's *actually* going on in that PR
> chore(rsc): Random changes, mostly to comments etc, in prep for removing the worker

- docs/docs/uploads.md
This fix should work. Right now the ::: doesn't close correctly and the note is open for several sections incorrectly.
> Correct Note Admonition

- tasks/server-tests/bothServer.test.mts
For whatever reason auto merge just rammed #11461 right in even though the server tests failed.
> chore(ci): Fix snapshots after CLI update

- docs/docs/how-to/dbauth-passwordless.md
* Remove incorrect line highlight (21) in two places
* Fix comment to now mention two imports
* Remove duplicated comment
* Use `const` instead of `let` for variables that aren't updated
CC @antonmoiseev
> docs(how-to): Fix example in dbauth-passwordless docs

- packages/router/src/rsc/RscRoutes.tsx
I figured out how I could do things without the need for the external promise I had before. This simplifies the code a lot
> chore(rsc): Simplify RscRoutes by removing external promise

- __fixtures__/test-project/web/package.json
TW was updated. Updating test-project fixture to use latest version
> chore(test-project): Update TailwindCSS

- docs/docs/uploads.md
- docs/versioned_docs/version-8.1/uploads.md
We want to have this labelled as experimental.
> fix(docs): warn that uploads/storage is experimental

- yarn.lock
Addresses a dependency security alert.
> chore(deps): Bump rollup

- docs/versioned_docs/version-8.3/tutorial/chapter4/deployment.md
Some of the previous docs changes weren't pulled over into next and then didn't get applied to the versioned docs. I checked and it looks like it was just the grove related deployment docs.
> docs: fix versioned docs

- packages/router/src/rsc/clientSsr.ts
Fix misleading console log output and add TODO for future investigation
> chore(rsc): Fix console log and add todo

- docs/docs/tutorial/chapter4/deployment.md
- docs/versioned_docs/version-8.3/tutorial/chapter4/deployment.md
> docs(deploy): fix grove command

- packages/vite/src/rsc/rscRequestHandler.ts
Just extracting out RSA handling into its own method instead of a giant if-statment in the main rsc handler method
> chore(rsc): Extract RSA handling in rscRequestHandler.ts

- packages/vite/src/rsc/rscStudioHandlers.ts
- packages/vite/src/runFeServer.ts
Getting rid of some redundant if-statements and adds early returns to make code easier to read
> chore(rsc): Refactor/format code that sends Flight to Studio

- __fixtures__/test-project/web/package.json
TailwindCSS was updated by dependabot
> chore(test-project): Update TailwindCSS to 3.4.14

- docs/docs/tutorial/chapter4/deployment.md
This fixes a small typo in the documentation. Thanks for your hard work!
> Fix typo in deployment.md

- __fixtures__/test-project/web/package.json
Updating the test project to unblock other PRs
> chore(test-project): Update TailwindCSS to 3.4.15 and PostCSS to 8.4.49

- packages/auth-providers/dbAuth/api/src/shared.ts
> chore(dbAuth): Early return to make code easier to read

- packages/vite/src/devFeServer.ts
Extracting this change from a bigger PR to not distract from the important changes in that other PR
> chore(vite): Refactor vite plugin - early return

- docs/docs/serverless-functions.md
Serverless functions do not refer to the custom functions how-to which explains CORS considerations.
Furthermore I added a hint on lambda functions ecosystem. Being new to it, it would have been helpful for me, to know about the possibilities to hook into it with custom functions.
> chore(docs):  Add additional hints to serverless functions

- packages/cli/src/commands/generate/__tests__/helpers.test.js
- packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
- packages/cli/src/commands/generate/function/function.js
- packages/cli/src/commands/generate/function/templates/function.ts.template
Update custom function generator template to fix blue squiggles
> fix(cli): Fix TS warnings in custom function template

- __fixtures__/test-project/web/package.json
Update the test project to unlock other PRs
> chore(deps): Update test project to use TW 3.4.17

- package.json
- packages/cli-helpers/package.json
- packages/cli/package.json
- packages/codemods/package.json
- packages/eslint-config/package.json
- packages/internal/package.json
- yarn.lock
Upgrading to latest version of Prettier
I was hoping this would solve the formatting issues reported on the docs. But unfortunately it didn't help.
But upgrading is good nonetheless
> chore(deps): Upgrade Prettier from 3.3.3 to 3.4.2

- packages/cli/src/commands/generate/page/__tests__/page.test.js
Caused a lot of noise when running tests
> chore(cli): Remove debug console.log

- packages/cli/src/commands/setup/deploy/providers/render.js
Fixes #11826
Fixes #11703
The setup script for Render was accidentally overwritten with the deploy script for Render in #10869
This PR simply restores the setup script to what it looked like before that PR was merged
> fix(deploy): Restore Render deploy setup script

- package.json
- yarn.lock
Updating nx to 19.8.14 didn't help fix the build issue. (See https://github.com/redwoodjs/redwood/pull/11852 for details).
Trying v20
> chore(deps): nx v20.3.0

- .github/actions/check_changesets/package.json
- .github/actions/check_create_redwood_app/package.json
- .github/actions/detect-changes/package.json
- .yarnrc.yml
- __fixtures__/fragment-test-project/package.json
- __fixtures__/rsc-caching/package.json
- __fixtures__/test-project-rsa/package.json
- __fixtures__/test-project-rsc-kitchen-sink/package.json
- __fixtures__/test-project/package.json
- docs/package.json
- package.json
- packages/cli/src/commands/upgrade.js
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/ts/package.json
- packages/create-redwood-rsc-app/yarn.lock
- yarn.lock
This updates the whole stack (incl. create-redwood-app) to the latest version of Yarn.
> [Chore] Update yarn to v4.6.0

- docs/package.json
- docs/yarn.lock
Upgrading to the latest version of Docusaurus
> chore(deps): docusaurus 3.7.0

- docs/docs/tutorial/chapter0/what-is-redwood.md
two distinct words with different meanings
> fix a spelling error (principal -> principle)

- __fixtures__/test-project/web/package.json
Updating the test project to use the latest PostCSS version.
Needed to unblock other PRs
> chore(test-project): Update PostCSS to 8.5.3

- .changesets/11966.md
- __fixtures__/test-project/web/package.json
- packages/cli/src/commands/deploy/__tests__/flightcontrol.test.ts
- packages/cli/src/commands/deploy/flightcontrol.ts
To fix this issue: https://github.com/redwoodjs/redwood/issues/11965
> fix(cli): flightcontrol:deploy handle command errors

- packages/adapters/fastify/web/src/resolveOptions.test.ts
- packages/adapters/fastify/web/src/web.test.ts
- packages/adapters/fastify/web/src/webFallback.test.ts
- packages/adapters/fastify/web/vitest.config.mts
- packages/adapters/fastify/web/vitest.setup.mts
- Add vitest config and setup to be consistent with other packages
- Fix some TS warnings
> chore(fastify): TS: Improve web adapter tests

- packages/babel-config/src/common.ts
Format existing comment, and add a new one with even more info.
I did this as part of another PR, but it really didn't belong there, so I extracted it out as a separate PR instead
> chore(babel-config): @babel/register comment

- .changesets/11981.md
- package.json
- packages/auth-providers/dbAuth/setup/package.json
- packages/auth-providers/dbAuth/web/package.json
- packages/babel-config/package.json
- packages/cli-helpers/package.json
- packages/cli/package.json
- packages/codemods/package.json
- packages/create-redwood-app/package.json
- packages/eslint-config/package.json
- packages/graphql-server/package.json
- packages/internal/package.json
- packages/router/package.json
- packages/structure/package.json
- packages/web/package.json
- yarn.lock
Changes since the last version:
https://github.com/babel/babel/pull/17142
https://github.com/babel/babel/pull/17127
https://github.com/babel/babel/pull/17052
> deps(@babel/core): Bump to 7.26.10

- package.json
- packages/vite/package.json
- yarn.lock
Changes since the last version:
https://github.com/babel/babel/pull/17153
https://github.com/babel/babel/pull/17062
https://github.com/babel/babel/pull/17028
https://github.com/babel/babel/pull/17019
https://github.com/babel/babel/pull/16958
https://github.com/babel/babel/pull/16959
https://github.com/babel/babel/pull/16948
https://github.com/babel/babel/pull/16850
https://github.com/babel/babel/pull/16841
https://github.com/babel/babel/pull/16708
https://github.com/babel/babel/pull/16732
> deps(@babel/generator): Bump to 7.26.10

- docs/docs/how-to/dbauth-passwordless.md
I was working through the passwordless how-to and noticed that it hadn't been updated in a while to match newer RW templates/conventions. So I updated it as I followed along. It still needs more work. Most pressing issue is converting it to TypeScript. But I don't have time for that now, and this is still a big improvement over what we currently have, so putting this up as a PR.
> docs(dbauth): Update the passwordless/OTP how-to

- packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap
- packages/cli/src/commands/generate/service/templates/scenarios.ts.template
Generating code with errors just isn't a good look 👀 💅
> fix(testing): Don't generate scenarios with red squiggles

- packages/codemods/README.md
Pusing a simple PR to GitHub just to see if that passes CI. I've been seeing a lot of weird issues.
> chore(codemods): Format README

- packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__testfixtures__/default.input.ts
- packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/__testfixtures__/default.output.ts
- packages/codemods/src/codemods/v4.2.x/updateClerkGetCurrentUser/updateClerkGetCurrentUser.ts
- packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.ts
- packages/codemods/src/codemods/v5.x.x/updateAuth0ToV2/updateAuth0ToV2.ts
- packages/codemods/src/codemods/v5.x.x/upgradeToReact18/upgradeToReact18.ts
- packages/codemods/src/lib/cells.ts
- packages/codemods/tsconfig.json
We're having CI errors on the codemod package. Trying to limit the scope of what I need to look into I'm fixing all TS issues first. They're distracting.
> chore(codemods): Fix TS errors

- __fixtures__/test-project/package.json
- package.json
- packages/cli-packages/storybook-vite/package.json
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/ts/package.json
- packages/storybook/package.json
- yarn.lock
7.6.18: Core: Fix addon bundling script https://github.com/storybookjs/storybook/pull/26145, thanks @ndelangen!
7.6.19: Fix bad release of 7.6.18 containing wrong dependency identifiers, thanks @JReinhold!
7.6.20: Couldn't find any release notes
> chore(deps): storybook 7.6.20

- packages/ogimage-gen/package.json
- packages/storybook/package.json
- packages/vite/package.json
- yarn.lock
> chore(deps): Bump vite to 5.4.15

- packages/ogimage-gen/package.json
- packages/storybook/package.json
- packages/vite/package.json
- yarn.lock
Bump Vite to get their latest security patch
> chore(deps): Bump Vite to 5.4.16

- docs/docs/graphql/realtime.md
> Typo Fix: Update realtime.md

- .vscode/settings.json
- docs/docusaurus.config.ts
Added Announcement Bar to the Docs
> ✨ Added Announcement Bar to Docs

- docs/package.json
- docs/yarn.lock
Originally this was a part of https://github.com/redwoodjs/graphql/pull/12047, I just wanted smaller, more focused, PRs
> chore(deps): Bump docusaurus to v3.8.1
