- packages/graphql-server/src/functions/graphql.ts
Seeing 
```
invalid json response body at https://undefined/api/graphql?query=%7Bpost%28id%3A1%29%7Btitle%7D%7D&query=%7Bpost%28id%3A1%29%7Btitle%7D%7D&query=%7B&query=p&query=o&query=s&query=t&query=%28&query=i&query=d&query=%3A&query=1&query=%29&query=%7B&query=t&query=i&query=t&query=l&query=e&query=%7D&query=%7D reason: Unexpected token e in JSON at position 0
```
Notice the many `query` per character.
This PR reworks the way the `multiValueQueryStringParameters` and gives that precedence of the queryString to avoid duplicates.
> GraphQL Yoga / Rework multi and non-multi query string param handling when building request

- packages/core/src/bins/rw-server.ts
We were missing `rw-server` from the bins in core required for Yarn 3.
Does this look correct @jtoar?
> add rw-server bin to core bins

- docs/docs/contributing-overview.md
The splash page links to this URL. Reported by @virtuoushub 🚀
> Fix link to docs/contributing

- docs/docusaurus.config.js
Search on the redwoodjs.com/docs page is broken; the redirects don't work because this is a single page app (at least, I think that's why), so we have to change the paths in the algolia index. I did that in another algolia app, just so we can switch back to the docs search app if/when we hear back
> Change algolia config

- docs/docusaurus.config.js
Seeing as https://github.com/redwoodjs/redwood/pull/4908 didn't work, a quick follow-up using a different strategy. Maybe we can force redirects with [externalUrlRegex](https://docusaurus.io/docs/search#connecting-algolia). Apologies for the PRs. Deploy previews don't seem to be working too well for the site either.
> [Search] Try external url regex

- docs/docusaurus.config.js
After swizzling the docs search bar and trying things out locally, this seems to be redirecting the tutorial search results from the learn URLs to the new ones consistently.
> Use learn instead of redwoodjs.com for external url regex

- packages/graphql-server/src/functions/graphql.ts
Fixes issue: https://github.com/redwoodjs/redwood/issues/4913
> Fix regression where GraphQL Yoga would rename all errors to the default value before other plugins could consume them

- packages/testing/config/storybook/main.js
- packages/testing/package.json
- yarn.lock
> Storybook Essentials is a curated collection of addons to bring out the best of Storybook.
I think Storybook Essentials should be by default on every project. 
This give all these tools : 
[Actions](https://github.com/storybookjs/storybook/tree/next/addons/actions)
[Backgrounds](https://github.com/storybookjs/storybook/tree/next/addons/backgrounds)
[Controls](https://github.com/storybookjs/storybook/tree/next/addons/controls)
[Docs](https://github.com/storybookjs/storybook/tree/next/addons/docs)
[Viewport](https://github.com/storybookjs/storybook/tree/next/addons/viewport)
[Toolbars](https://github.com/storybookjs/storybook/tree/next/addons/toolbars) (Need for #4764)
> Add @storybook/addon-essentials by default 

- docs/docs/tutorial/chapter2/cells.md
Found a small error where `posts` didn't get updated to `articles`
> small copy paste error s/posts/articles

- packages/internal/src/__tests__/graphqlCodeGen.test.ts
- packages/internal/src/generate/graphqlCodeGen.ts
- packages/internal/src/generate/graphqlSchema.ts
**What is currently happening?**
Demo without changes: https://s.tape.sh/gcgUm5Kw
1. If we have some issue in GraphQL files (web - query/mutations | api - sdls), that error is swallowed. Without a pointer where the error is it's extremely difficult to debug the issue. This unfairly impacts more on the web side because before the codegen step, we generate the schema from api source and probably that same error would be caught and printed in this earlier step.
2. Error is printed twice if there's something wrong with sdl, for example - invalid type.
**What this PR does?**
Demo with changes: https://s.tape.sh/a64iFBIq
1. console the errors for both api and web typegen. @Tobbe I tried to gather context from earlier PR but I didn't understand why we only log the error in test files but not in …
> Fix: Don't swallow typegen errors

- docs/docs/tutorial/chapter7/rbac.md
1. `role` => `roles`. `role` was replaced by `roles` in https://github.com/redwoodjs/redwood/pull/4681
2. Fixed update user role example.
> Fix issues in rbac.md

- docs/src/css/custom.css
The styling for the HTML details element was Docusaurus's default, a light blue. This updates it to at least look a little more consistent.
> Update details CSS (docs)

- docs/docs/toast-notifications.md
Removed an old deprecation warning and a lot of content as the react-hot-toast docs are very good.
> Update toast notifications doc

- docs/docs/typescript.md
Not many changes here; removed a section on CI because it seemed outside the scope and we plan on adding a redwood CI action soon. I'd like for this doc to be longer, especially the section on generated types, but adding content isn't a priority at the moment.
> Update the TS doc

- docs/docs/tutorial/chapter1/prerequisites.md
Wasn't sure whether to keep `<= 16.x` format from current docs, or switch to `< 17.0.0` from current redwood CLI error message, but opted for the latter
> Update docs node version requirement to reflect current redwood reqs

- docs/docs/authentication.md
- docs/docs/deploy/introduction.md
Tweaking the intros for Auth and Deploy docs in attempt to clarify that the links are to external URLs and _not_ sections within the doc itself.
> (docs) update intro section links for Auth and Deploy Docs

- docs/docs/tutorial/chapter3/saving-data.md
Closes https://github.com/redwoodjs/redwood/issues/5016. I've still got one more to replace.
> Update GraphQL Explorer in the Tutorial

- docs/netlify.toml
We've implemented this page in https://github.com/redwoodjs/redwood/pull/4993.
> Remove docs/introduction redirect

- docs/docs/tutorial/chapter5/first-test.md
I think @virtuoushub has just overlooked these relics from the old tutorial in the last fix #4983
> [Tutorial] Fix inconsistent naming in "Our First Test"

- docs/docs/environment-variables.md
Explains use of REDWOOD_ENV_EDITOR in dev error page.
Can use this envier to change the default of `vscode` when generating links to the code file in the error page.
Also introduces the concept of the dev fatal error page so people can search and find.
> Docs: Explains use of REDWOOD_ENV_EDITOR in dev error page

- docs/docs/tutorial/chapter4/deployment.md
- docs/docs/tutorial/intermission.md
Updates the provider value to match the [local postgres setup doc](https://redwoodjs.com/docs/local-postgres-setup) and [prisma docs.](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference)
> [Tutorial] Update postgresql provider string in schema.prisma

- docs/docs/tutorial/chapter2/cells.md
- docs/docs/tutorial/chapter2/routing-params.md
This avoids warning `'ArticlesCell' cannot be used as a JSX component.
Its return type 'Element[]' is not a valid JSX element.`.
Closes #5008
> [Tutorial] Chapter 2: Wrap rendered `<article>` in React fragments

- packages/cli/src/commands/setup/i18n/templates/storybook.preview.js.template
When running `yarn rw setup i18n` it gives you a `web/config/storybook.preview.js` file. There was a minor issue with how a comment was formatted in that file. See screenshot below
This PR just removes one of the extra forward slashes that shouldn't be there
> i18n setup: Fix storybook preview config template

- docs/docs/tutorial/chapter3/saving-data.md
Present in Tutorial -> chapter3
> Fix typo (`valiation` -> `validation`) in Docs

- .github/workflows/build-eslint-jest.yaml
- .github/workflows/e2e.yaml
- .github/workflows/smoke-test.yaml
While we think about https://github.com/redwoodjs/redwood/pull/4848, we should just let CI run (and pass) on docs in the meantime instead of not running at all
> Let CI run for docs

- docs/docs/tutorial/chapter6/comments-schema.md
The section is discussing creating Comment sdl but references the previous example of creating Post but mistakenly calls it Comment.
> Incorrect Copy, changed "Comment" to "Post"

- .github/workflows/publish-npm-canary.yaml
For docs-only changes, we definitely want to skip this workflow at least. I think we've already published quite a few 1.0.1 canaries as it is 😅
> Don't publish canaries on docs-only changes

- package.json
- packages/auth/package.json
- packages/core/package.json
- packages/forms/package.json
- packages/testing/package.json
- packages/web/package.json
- yarn.lock
Fixes #5189
`@types/react-dom` .15 fixed the semver
This upgrades `@types/react` and removes previous resolutions.
going to release as patch 1.0.2
> Fix for @types/react using new versions

- docs/docs/cells.md
Closes https://github.com/redwoodjs/redwood/issues/5111. I've just commented it out for now in case we want to add it back in if the site goes up again, since it's a piece of Redwood history!
> Comment out link to predictcovid

- packages/core/package.json
Follow up to https://github.com/redwoodjs/redwood/pull/5192. In that PR, we removed resolutions in `@redwoodjs/forms`, `@redwoodjs/testing` and `@redwoodjs/web`, but left it in `@redwoodjs/core`. @thedavidprice was there a reason the one in `@redwoodjs/core` was left in? Yarn seems to totally ignore it (this output is from `yarn install`):
```
➤ YN0000: ┌ Project validation
➤ YN0057: │ @redwoodjs/core: Resolutions field will be ignored
➤ YN0000: └ Completed
```
> Remove stray @types/react resolution from @redwoodjs/core

- .github/workflows/publish-npm-canary.yaml
- .github/workflows/publish-npm-rc.yaml
- tasks/publish-rc
Closes https://github.com/redwoodjs/redwood/issues/2439.
This PR makes it so that the `publish-npm-rc.yaml` workflow publishes premajors, minors, and patches when a `release/${semver}/v${version}` branch is pushed to. It also has built-in tag-checking mechanism for exiting early if the tag that's in main equals or exceeds the tag that it would publish.
> Update RC-publishing workflow

- packages/cli/src/commands/generate/directive/directive.js
Was in the process of reviewing https://github.com/redwoodjs/redwood/pull/5205 and realized that `yarn rw g directive` breaks at generating types:
```
$ yarn rw g directive uppercase
✔ What type of directive would you like to generate? › Validator
✔ Generating directive file ...
✔ Successfully wrote file `./api/src/directives/uppercase/uppercase.test.js`
✔ Successfully wrote file `./api/src/directives/uppercase/uppercase.js`
✖ Generating TypeScript definitions and GraphQL schemas ...
→ $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
Next steps...
Command failed with exit code 1: yarn rw-gen
Usage Error: Couldn't find a script named "rw-gen".
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```
The …
> Fix type gen on `yarn rw g directive`

- packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
- packages/cli/src/lib/__tests__/index.test.js
- packages/cli/src/lib/index.js
This should solve https://github.com/redwoodjs/redwood/issues/5089
> Add recommended VS Code extensions when setting up tailwindcss

- packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js
- packages/cli/src/lib/__tests__/index.test.js
- packages/codemods/src/testUtils/index.ts
- packages/internal/package.json
- yarn.lock
cc @jtoar 
- reverts https://github.com/redwoodjs/redwood/pull/5181
- updated codemods test parser syntax to pass. See:
https://github.com/redwoodjs/redwood/pull/5287/commits/5cdbf8e4166c11f46a541f4d80fcf6bdfcf3fc4a#diff-1df4cc7b04164297e24519ab93a462620384a3de38e1867c824a409353394c36
- cleanup fixture in CLI test
> fix prettier codemods and CLI failing test; revert glob v8 PR

- .github/actions/message_slack/action.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
Apparently you can't use GitHub secrets in actions (makes sense retrospectively). This PR changes it so that the secret is passed to the action.
> Pass secret to slack message action

- .github/actions/message_slack/action.yml
- .github/workflows/publish-canary.yml
Got the slack message working in https://github.com/redwoodjs/redwood/commit/6f0093393f53b064d94ab930605ca3ec6d401e53 but the actual publish step is failing. I removed a seemingly innocuous line, `git describe`, that I'm adding back now to see if it makes a difference.
> [Canary publishing] add back git describe

- .github/actions/message_slack/action.yml
I forgot that GitHub actions have no real way of doing if else statements, breaking the slack message job here https://github.com/redwoodjs/redwood/runs/6147235092?check_suite_focus=true. So this PR uses [jq](https://stedolan.github.io/jq/), a JSON CLI tool, to get the emoji via the `status` (success, failure). This should hopefully be the last one for now.
> Use `jq` to get status emoji for publish action

- docs/docs/tutorial/chapter6/comment-form.md
The interface is shown later in the tutorial, but is missing when it is implemented and used in the `onSubmit` function.
> Added missing interface.

- docs/ignore_build.js
- docs/netlify.toml
Right now Netlify builds Redwood's docs site on every PR, whether it includes docs changes or not. This PR adds an ignore script that Netlify runs to check if it should build the docs site: https://docs.netlify.com/configure-builds/ignore-builds/.
The script is basically the inverse of the [only_doc_changes](https://github.com/redwoodjs/redwood/blob/main/.github/actions/only_doc_changes/only_doc_changes.mjs) action, except that this one excepts to run on Node.js 12 while the other expects to be able to use the GitHub actions toolkit. It may be worth trying to merge both into one in the future, but right now I just want to see if this works at all.
> Netlify: ignore PRs without changes in the docs directory

- tasks/release/__tests__/generateReleaseNotes.test.mjs
- tasks/release/cli.mjs
- tasks/release/generateReleaseNotes.mjs
Closes the last item in https://github.com/redwoodjs/redwood/issues/5229. This PR adds a `--release-candidate` (alias, `--rc`) flag to `yarn release generate-release-notes` (alias, `notes`). When using this flag, the command logs the two links necessary for the RC's release notes. Example output
```bash
yarn release notes --rc
No milestone was provided; using the latest: v1.2.0
$ yarn npm info @redwoodjs/core@latest --fields version --json
{"name":"@redwoodjs/core","version":"1.1.1"}
{
compare: 'https://github.com/redwoodjs/redwood/compare/v1.1.1...release/minor/v1.2.0',
mergedPrs: 'https://github.com/redwoodjs/redwood/pulls?q=is%3Apr+is%3Amerged+milestone%3Av1.2.0'
}
```
> Generate RC release notes

- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
- package.json
This PR adds the [`--no-git-reset` lerna flag](https://github.com/lerna/lerna/tree/main/commands/publish#--no-git-reset) to the `publish:canary` command. This is so that we can use the version later in another job. This PR also moves the `publish:canary` command to the workflow, removing it from the package.json. @thedavidprice let me know if you'd like to undo this last change.
Using this PR as a summary of some of the changes I've made to the canary and release candidate workflows:
- https://github.com/redwoodjs/redwood/commit/e00d42146fd3fda8f918ca6ac151d34b3da90700 - the "main" PR, refactors the workflows
- https://github.com/redwoodjs/redwood/commit/15751daa3f12668965e55ac6ce74950b710f8733 - debugging (forgot to checkout the repo)
- …
> Remove `git reset` in canary workflow

- docs/docs/tutorial/chapter5/testing.md
When working through the tutorial I spotted the failing test and thought I was doing something wrong. I worked through fixing the failure on my own in a slightly different way than outlined in the next section, but if I had seen the tutorial presented this way I would have felt more confident and less confused with what I was doing. This appeared to be a simple fix to the docs, so I thought I would present it.
> Updated testing.md to reflect tutorial flow

- docs/docs/tutorial/chapter4/authentication.md
Add ‘s’ to make in the sentence “The shell `auth.{js,ts}` that's created in a new app make sure things like…”
> Grammar change

- docs/docs/tutorial/chapter3/saving-data.md
Hello 👋 
The `SubmitHandler` is not used in the [Creating a Contact](https://redwoodjs.com/docs/tutorial/chapter3/saving-data#creating-a-contact) section for JavaScript, but is included as an import in the code example (it looks like it belongs in the TypeScript code example instead).
This PR removes that import from the JavaScript example and adds it to the TypeScript example.
> Remove unused `SubmitHandler` in example JavaScript code

- docs/docs/cli-commands.md
This pull request fixes the docs by adding [WindiCSS](https://windicss.org/) to the list of all ``setup ui`` available. The setup command for Windi has been added some days ago, but the updated documentation is missing. Here is the fix.
> fix(docs): add WindiCSS in setup ui list

- packages/testing/config/storybook/preview.js
- packages/testing/src/web/StorybookProvider.tsx
the loaders are async and execute before the story is rendered.
- https://storybook.js.org/docs/react/writing-stories/loaders
- https://mswjs.io/
---
Why this matters:
**_interaction testing_**
- https://storybook.js.org/blog/interaction-testing-with-storybook/
- https://storybook.js.org/docs/react/writing-tests/interaction-testing
Because using a loader happens before a story is rendered, we do not have to worry about the mock data being unavailable to a component. With the previous approach, we possibly had to wait for a couple render cycles in order to guarantee the mock data was available to the component.
> chore(story📗): extract MSW logic into a loader

- packages/graphql-server/package.json
- yarn.lock
Update: turns out I removed it in the merge commit, so entirely self inflicted: [https://github.com/redwoodjs/redwood/commit/5c891294188b95cc5beaceb32930a14ea61cdcca](https://github.com/redwoodjs/redwood/commit/5c891294188b95cc5beaceb32930a14ea61cdcca).
***
After releasing v1.2.1, [redwoodjs](https://www.github.com/redwoodjs)/graphql-server can't find graphql-scalars: [https://github.com/redwoodjs/redwood/runs/6261468443?check_suite_focus=true#step:6:86](https://github.com/redwoodjs/redwood/runs/6261468443?check_suite_focus=true#step:6:86).
It was never listed in its package.json so I'm not sure how it found it before; probably a dependency of a dependency. This lists it explicitly since resolvers are imported from it in `rootSchema.ts`: …
> Add graphql-scalars to graphql-server

- tasks/release/generateReleaseNotes.mjs
Minor fix to the release process; yargs handles this when invoked directly, but it's failing when invoked by the release script.
> Set default value for RC release notes

- constraints.pro
- packages/api-server/package.json
- packages/api/package.json
- packages/auth/package.json
- packages/cli/package.json
- packages/create-redwood-app/package.json
- packages/forms/package.json
- packages/graphql-server/package.json
- packages/prerender/package.json
- packages/record/package.json
- packages/router/package.json
- packages/structure/package.json
- packages/telemetry/package.json
- packages/testing/package.json
- packages/web/package.json
- yarn.lock
**What's the problem this PR addresses?**
Not all workspaces that build using the Babel config declares `@babel/runtime-corejs3` and `core-js` as dependencies even though they all might end up importing from them.
Follow-up to https://github.com/redwoodjs/redwood/pull/5457
**How did you fix it?**
Wrote a constraint to enforce that all workspaces with a `build:js` script depends on `@babel/runtime-corejs3` and `core-js`.
> fix: declare `@babel/runtime-corejs3` and `core-js` as dependencies

- packages/prerender/src/browserUtils/index.ts
Changed children type to ReactElement<any, any> in BrowserOnly from BrowserUtils.
During implementation of prerender in my app, i tried to use BrowserOnly to test prerender, unfortunatly children type was set to React.Node and it doesn't worked for me.
I changed it by ReactElement<any, any>.
- Build ok
- tests ok for my modification
- lint ok
> Fixing type for BrowserOnly children

- docs/ignore_build.js
Once PRs with doc-related changes are merged to main, they should deploy no matter what.
The diff makes it look like there's a lot of changes, but I really just added an if else statement that checks if `process.env.BRANCH` is main.
I'm not sure what the value of `process.env.BRANCH` will actually be if the branch is main (I assume just `'main'`), so I'll have to merge to find out. I'll follow up with a fix if necessary.
> Fix netlify ignore build script

- package.json
- tasks/release/__tests__/__snapshots__/generateReleaseNotes.test.mjs.snap
- tasks/release/__tests__/release.test.mjs
- tasks/release/cli.mjs
- tasks/release/generateReleaseNotes.mjs
- tasks/release/octokit.mjs
- tasks/release/prompts.mjs
- tasks/release/release.mjs
- tasks/release/updatePRsMilestone.mjs
Follow up to https://github.com/redwoodjs/redwood/pull/5438; this PR adds an updating docs step for majors and minors, and adds an all contributors step. It also just gives the release script some TLC since I had to go through most of it again.
> Update release script to handle all contributors, versioning

- __fixtures__/test-project/package.json
Opening this PR to see if it fixes CI. Using the workaround here: https://github.com/isaacs/node-glob/issues/471#issuecomment-1126739067.
Update: it looks like this works. I'm going to merge this for now so that we can keep our velocity. I'll make a note to remove it when the Storybook patch comes in.
Note that this resolution is for the test project fixture, not create redwood app.
> Try adding glob resolution to test project

- packages/core/config/webpack.perf.js
This fix #5425 by updating the regex to find babel rule. 
Before #3719, JS and TS had two different rules. Now that is merged together, the regex for babel rules on webpack.perf.js is not valid anymore.
> Fix yarn rw build web --perf option

- packages/structure/src/model/RWCell.ts
Fixes #5529
When debugging 5529 we traced the error down to this code
https://github.com/redwoodjs/redwood/blob/bc79162f36057c0b6b59d75a29a87cc43a008dae/packages/cli/src/commands/generate/cell/cell.js#L23-L28
Further tracing led me into the structure package and its `queryAst` getter. It tries to parse the gql query in the cell, but that fails because of the syntax error described in #5529. This exception wasn't caught, and caused the cell generator to crash.
I've wrapped the call to `parse` with a try/catch and print out any error that it throws, together with the filename of the cell where the error occurs. I also return `undefined` from the getter, which will propagate all the way up to the cell generator where it'll just be filtered out. So what'll happen in the end is that the cell …
> RWCell: Print error on gql syntax error

- packages/internal/package.json
- yarn.lock
`@redwoodjs/internal` imports from `terminal-link` but doesn't require it in its package.json. Should fix https://github.com/redwoodjs/redwood/issues/5584.
> Fix: add missing dep terminal link to internal

- __fixtures__/test-project/package.json
Now that glob has been patched this shouldn't be necessary.
- https://github.com/redwoodjs/redwood/pull/5543
- https://github.com/redwoodjs/redwood/pull/5561
> Chore: remove glob resolution in test project fixture

- packages/testing/package.json
Tries to close https://github.com/redwoodjs/redwood/issues/5612. Will only consider this a legit fix if users don't have to do anything downstream.
> Fix: try pinning @mswjs/interceptors internally

- packages/testing/package.json
This reverts commit 4a7e6fa800560c3d60322ff889cfdeabead35d57. Still not sure how to set resolutions that take effect downstream. We had the same problem with react types.
> Revert "Fix: try pinning @mswjs/interceptors internally (#5613)"

- packages/internal/package.json
- yarn.lock
On v1.5.0, the dev server takes a long time to start up and after it does, outputs the following errors to the console (that do resolve themselves promptly afterwards):
```
Error whilst shutting down "api" port: No process running on port
Error whilst shutting down "web" port: No process running on port
```
It looks like it's because we upgraded kill-port to v2 (see https://github.com/redwoodjs/redwood/pull/5569). This issue here matches what we're seeing: https://github.com/tiaanduplessis/kill-port/issues/61. The solution for now seems to be to just revert the upgrade. Note that this isn't user-facing so we should be able to release this in a patch.
> Fix: revert kill-port upgrade

- docs/docs/deploy/baremetal.md
Hey all, 
only note is that you may want to keep last edit as technically isn't a typo - albeit i'm not sure if we want to use [it](https://www.dictionary.com/e/slang/normie/) as 'normies' perhaps a bit too _undergroundish_ slang.... (and OTOH makes translations harder, IMHO) 
All the best, 
António
> yet another batch of typo squashing

- docs/docs/tutorial/chapter2/routing-params.md
- docs/versioned_docs/version-1.5/tutorial/chapter2/routing-params.md
The error was caused by not declaring the variable $id.
======== Actual Error Notation ========
Error: Response not successful: Received status code 400
> fix: The error was caused by not declaring the variable $id.

- docs/docs/tutorial/chapter1/file-structure.md
I found some typo on diagram of "files and directories".
"`├`" should be replaced by "`└`".
> Fix typo in tutorial

- docs/docs/tutorial/chapter2/routing-params.md
[Tutorial 2 ](https://redwoodjs.com/docs/tutorial/chapter2/routing-params)of the official Redwood docs has a typo in the last example code snippet that forces the tutorial website to fail.
I ran into this issue this afternoon and it looks like @mdkess ran into this yesterday.
#5693 
I don't have much experience contributing  to open source projects. I've already read the [official contributing docs,](https://redwoodjs.com/docs/contributing) but didn't have the time to watch the official contributing  [Youtube video.](https://www.youtube.com/watch?v=aZs_9g-5Ms8)  If there are any subtle PR/contributing etiquette things I'm missing, feel free to point them out.
> Fix typo in ArticleCell code snippet of Tutorial 2 docs

- docs/docs/forms.md
Update documentation on the "Input Fields" section of [Forms](https://redwoodjs.com/docs/forms)
I needed to build a more complicated custom input field for my application. I ended up finding that `useRegister` and `useErrorStyles` was recently added to things I could use. This is to document their availability and possible usage to build a custom input.
I added a section under "Input Fields" called "Custom Input Fields". There I describe use of `useRegister` and `useErrorStyles` along with a simple example.
Open to any critiques or changes needed/desired. I don't love the example, but wanted to keep it short & simple.
> 📝 Add documentation for custom input fields

- docs/docs/contributing-walkthrough.md
- Fixed "ew" into "we" on the GitHub Desktop paragraph
- Suggested new phrasing on the MacOS - iTerm + Oh My ZSH paragraph,
since MacOS now comes with zsh by default.
- Added Missing dot at the end of that same paragraph
> docs: adding precisions and fixes to contributing

- docs/docs/tutorial/chapter3/saving-data.md
Couldn't find an equivalent relevant link, so removed the link to Apollo Server Playground docs completely.
> docs: GraphQL Yoga's playground, not Apollo Server's

- packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
- packages/internal/src/__tests__/graphqlCodeGen.test.ts
- packages/internal/src/generate/graphqlCodeGen.ts
- packages/internal/src/generate/graphqlSchema.ts
Fixes https://github.com/redwoodjs/redwood/issues/5667
For an example of how the JSON scalar used in the SDL causes a type incompatibility with Prisma, see https://github.com/redwoodjs/redwood/issues/5667
In Prisma, the Json field supports a few additional types, such as string and boolean. These additional types exist to match the types supported by [JSON.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse).
```ts
export declare type JsonValue =
| string
| number
| boolean
| null
| JsonObject
| JsonArray
```
This PR imports `Prisma` and maps 
```
JSON: 'Prisma.JsonValue',
JSONObject: 'Prisma.JsonObject',
```
> Maps JSON GraphQL Scalars to Prisma Json field types for compatibility

- docs/docs/authentication.md
I haven't tried, but as the whole example doesn't show a single route of `name='forbidden'` i believe the two private sets at the bottom cannot redirect anywhere.
Also, route `name`s are supposed to be unique, correct?
> Fix misnamed forbidden page route

- packages/testing/config/storybook/main.js
- tasks/smoke-test/tests/storybook.spec.ts
Order for [`stories`](https://storybook.js.org/docs/react/configure/overview#configure-your-storybook-project) matters [in order to let you define which story is default](https://stackoverflow.com/a/68097205).
Our current implementation has the RW defaults take precedence.
> fix: have user config for `addons` and `stories` take precedence

- packages/cli/src/commands/setup/auth/templates/auth.ts.template
- packages/cli/src/commands/setup/auth/templates/auth0.auth.ts.template
- packages/cli/src/commands/setup/auth/templates/azureActiveDirectory.auth.ts.template
- packages/cli/src/commands/setup/auth/templates/clerk.auth.ts.template
- packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
- packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
- packages/cli/src/commands/setup/auth/templates/magicLink.auth.js.template
- packages/graphql-server/src/functions/__tests__/fixtures/auth.ts
This one came to me while i was contemplating over #5856. It's just a nice thing that you can to with JSDoc – it makes the types clickable, so users may navigate to complex return types faster.
Of course these types are so simple that one would hardly ever need to look up their implementations, but if you want to, now you can do it with a single click :grinning: 
Guess there are many areas where this may be very helpful. So maybe something to take up into the coding standards / linting rules / what-have-you going forward.
> Link non-primitive types in JSDoc

- docs/docs/tutorial/chapter2/cells.md
Aligns this link with the one in [Our First Page](https://redwoodjs.com/docs/tutorial/chapter1/first-page)
> Tutorial chapter 2: Update text for link to chapter 5

- packages/internal/src/generate/templates/all-currentUser.d.ts.template
Closes #5038
No breaking change, no codemods or other updates needed to existing projects.
---
This fixes a typescript error that has been bugging me for some time. Whenever generating the `dbAuth` setup, but not implementing any role-based access control (RBAC), vscode goes full on red on `auth.ts`:
I know one may debate whether this is actually a problem or not (imho generated code should always pass 100 % of all rules in order maximize trust in the framework, i know e.g. @dac09 has a different stance on this), but this one is that severe that it comes up when running `yarn rw type-check`
Don't know if this is the perfect solution and am open to better ones. But i feel it's just good enough, in my test the `rules`-type got properly overwritten (becoming mandatory) as soon as one changes …
> Fix type errors in `lib/auth.ts` when using a non-RBAC `dbAuth` setup

- packages/router/src/__tests__/util.test.ts
- packages/router/src/util.ts
I missed the cause of this error each time (and was figuring my routes were incorrect) until I dug through the error stack, this should raise the key bit of info into the top line
> [minor] Makes the error message a bit clearer when a navigation url is crashing your app

- packages/telemetry/src/telemetry.ts
Because of this error here https://github.com/redwoodjs/redwood/pull/5899#issuecomment-1182509983
> Fix: Remove "node:os" import from telemetry

- docs/docs/tutorial/chapter2/getting-dynamic.md
```
... otherwise they are identical **to** the name of the page you generated.
```
> Fix type in docs.

- packages/testing/src/web/MockProviders.tsx
- add `forgotPassword`, `resetPassword`, and `validateResetToken`.
- also add better typings and comment to improve this mock provider.
_note:_ not sure if the `async` keyword is a 💯 % necessary here (outside of the typings...), and if it will cause issues for downstream users. 
---
For context, I found this over at:
- https://deploy-preview-104--redwoodjs-example-storybook.netlify.app/storybook/?path=/story/generated-dbauth-resetpasswordpage--generated
```
main.ed7cf5c7.iframe.bundle.js:2 Uncaught (in promise) Error: Auth client custom does not implement this function
at validateResetToken (main.ed7cf5c7.iframe.bundle.js:2:57990)
at main.ed7cf5c7.iframe.bundle.js:2:110416
at l (main.ed7cf5c7.iframe.bundle.js:2:2024969)
at Generator._invoke (main.ed7cf5c7.iframe.bundle.js:2:2024757)
at …
```
> chore: clean up mock auth client

- packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
- packages/cli/src/commands/generate/cell/templates/stories.js.template
- packages/cli/src/commands/generate/component/__tests__/__snapshots__/component.test.ts.snap
- packages/cli/src/commands/generate/component/templates/stories.tsx.template
- packages/cli/src/commands/generate/layout/__tests__/__snapshots__/layout.test.ts.snap
- packages/cli/src/commands/generate/layout/templates/stories.tsx.template
- packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap
- packages/cli/src/commands/generate/page/templates/stories.tsx.template
Without this, we don't get the Doc Block / "Show code" feature Storybook provides without having the framework user modify their stories files.
see:
- https://github.com/storybookjs/storybook/issues/8104#issuecomment-932279083
- https://storybook.js.org/docs/react/writing-docs/doc-block-source
> fix(storybook): add `args` to auto generate docs

- packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
Line 108 indicates that this method can be used without supplying roles at all:
https://github.com/redwoodjs/redwood/blob/4707b988f0d5ff58da057afee9a13bf1f6f08710/packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template#L108
However, this would trigger a typescript warning:
```bash
Argument of type '{}' is not assignable to parameter of type '{ roles: AllowedRoles; }'.
Property 'roles' is missing in type '{}' but required in type '{ roles: AllowedRoles; }'.ts(2345)
auth.ts(101, 42): 'roles' is declared here.
```
This fixes it.
> Avoid typescript warning when no roles key is supplied

- packages/cli/src/commands/testHandler.js
> fix(cli): Modify existence check of jest.config to check for both .js and .ts extensions in rw test

- docs/docs/cli-commands.md
The generate commands are listed alphabetically except script. It is currently out of order behind generate types. See the generated list on the side at: https://redwoodjs.com/docs/cli-commands#generate-alias-g and notice that script is at the end.
With this change, I cut and pasted the generate script section into the correct alphabetical position.
> Doc: Move generate script up in list

- docs/docs/tutorial/chapter2/cells.md
- docs/docs/tutorial/chapter2/routing-params.md
- docs/docs/tutorial/chapter3/saving-data.md
- docs/docs/typescript/generated-types.md
- docs/versioned_docs/version-2.2/tutorial/chapter2/routing-params.md
1. Updates the links for generated and utlity types. 
2. Adds a tip in the tutorial where we'd get a TypeScript error (see here #5878)
> docs(ts): Update some TS links, and add a tip to the tutorial

- packages/api/package.json
- packages/cli/package.json
- packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
- packages/cli/src/commands/setup/deploy/providers/render.js
- packages/cli/src/lib/schemaHelpers.js
- packages/graphql-server/package.json
- packages/record/package.json
- packages/record/src/tasks/parse.js
- packages/structure/package.json
- packages/structure/src/model/RWProject.ts
- packages/testing/config/jest/api/jest.setup.js
- yarn.lock
Prisma 4 renames the `@prisma/sdk` package to `@prisma/internals` to dissaude using it since it won't be subject to SemVer: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4#prisma-no-longer-exports-prismadmmfschema-into-the-generated-prisma-client.
Besides the rename, the only other change that's important for us on the framework side is that Prisma is dropping Node.js 12 support.
While this upgrade looks like it'll be simple, more work may need to be done in the future if `getDMMF` or any of the other functions we import from `@prisma/internals` change, which could now happen in any Prisma version.
> [Chore]: Upgrade prisma dependencies and specifiers to v4

- docs/docs/tutorial/chapter4/authentication.md
Looks like this hasn't been updated a while :)
Actually, on second look that code is even dysfunctional b/c `hasRole(roles)` call in `requiredAuth` would have failed.
Also took the liberty of degrading `:::caution` to `:::info`, as there really is no need to be "alarmed" about anything, we're merely providing some context.
> Tutorial 4.1: Update lib/auth code & remove warning about non-existent TS error (fixed via #5856, shipped in v2.1)

- __fixtures__/test-project/web/src/components/BlogPostCell/BlogPostCell.test.tsx
- __fixtures__/test-project/web/src/components/BlogPostsCell/BlogPostsCell.test.tsx
- __fixtures__/test-project/web/src/components/WaterfallBlogPostCell/WaterfallBlogPostCell.test.tsx
- packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
- packages/cli/src/commands/generate/cell/templates/test.js.template
> Fix unused import in generator cell test template

- __fixtures__/test-project/api/src/lib/auth.ts
- docs/docs/tutorial/chapter4/authentication.md
- docs/docs/tutorial/chapter7/rbac.md
- docs/docs/typescript/strict-mode.md
- packages/cli/src/commands/setup/auth/templates/auth.ts.template
- packages/cli/src/commands/setup/auth/templates/dbAuth.auth.ts.template
- packages/cli/src/commands/setup/auth/templates/dbAuth.auth.webAuthn.ts.template
- packages/cli/src/commands/setup/auth/templates/okta.auth.ts.template
I noticed two things (fixed via d481ca52ab11079a2b9d37ba07f27703bc872904):
* some inconsistencies in the optional javascript chaining, e.g. in dbAuth there was an empty check on context in dbAuth (but only on one execution path), on the majority it was `context.currentUser?.roles`, but on some execution paths (okta, webauthn) there was no chaining at all 
* default auth, dbAuth, webauthn and okta all had execution paths that did not consistently use the `currentUserRoles` constant yet, without any obvious reason
I've now changed `currentUserRoles` to also optionally chain `context` (see a7e85cbb2), so no errors can be thrown from that function anymore should context be undefined – which is exactly what at least one execution path of dbAuth already did :wink:
---
When approved, kindly keep …
> Harmonize optional chaining across all `hasRole` flavors & reduce duplication, avoiding errors on empty currentUser

- packages/api/src/bins/redwood.ts
- packages/api/src/bins/rwfw.ts
- packages/cli/src/index.js
- packages/core/src/bins/cross-env.ts
- packages/core/src/bins/redwood.ts
- packages/core/src/bins/rwfw.ts
- packages/web/src/bins/msw.ts
- packages/web/src/bins/redwood.ts
- packages/web/src/bins/rwfw.ts
To upgrade RW projects to yarn 3, we had to make bin "proxy" files so that we could still access the bins of our dependencies. See https://github.com/redwoodjs/redwood/pull/4444 for the full break down.
When you run a bin, yarn 3 sets the cwd to the workspace calling it. This revealed a hidden dependency in many of our CLI commands that expect the cwd to be the root, so we imported `getPaths` from `@redwoodjs/cli` (an export of the one in `@redwoodjs/internal`) in many of the bin proxy files to find the root and change to it.
This works and has worked for a long time, but turns out to be a not-so-great idea because it means pulling in a massive amount of `@redwoodjs/internal` for any CLI command, and possibly introducing some indeterminacy around the way env vars are loaded.
Instead of …
> Leverage PROJECT_CWD to set cwd in yarn 3 bin "proxies"

- docs/docs/tutorial/chapter6/comments-schema.md
Using `postId` in the input for the createComment-test in `api/src/services/comments/comments.test.ts` gives the following red squiggle:
```bash
Type '{ name: string; body: string; postId: number; }' is not assignable to type 'CommentCreateInput'.
Object literal may only specify known properties, but 'postId' does not exist in type 'CommentCreateInput'. Did you mean to write 'post'?ts(2322)
comments.ts(22, 3): The expected type comes from property 'input' which is declared here on type 'CreateCommentArgs'
```
1. use `Prisma.CommentUncheckedCreateInput` instead of `Prisma.CommentCreateInput`, thus being able to reuse the current JS test code on the TS tab solution without getting a type warning. This is what 53dfb680f9e6bf71363c05ae1cc2364e495cecff does
2. Don't use `postId`, but rather …
> Tutorial 6.3: Fix prisma type error on comment creation

- docs/docs/graphql.md
Just stumbled over this 404 on https://redwoodjs.com/docs/graphql#the-root-schema
> Fix redwood root schema definition link on GraphQL docs page

- docs/docs/tutorial/chapter4/deployment.md
- docs/versioned_docs/version-2.2/tutorial/chapter4/deployment.md
Removed `'` from 'Connections' - `open it's own connection`
Instead should be `open its own connection` as `its` is possessive, not `it's` which is a contraction of `it is`.
> Tutorial Chapter 4: Miniscule typo fixup

- docs/docs/typescript/generated-types.md
- docs/docs/typescript/introduction.md
Reorganises the typescript intro docs to add a new "core concepts" section. 
This should hopefully make it a little clearer on how TS works with Redwood - but I find it difficult to communicate.
Feel free to edit @jtoar!
> docs(ts): Add section on core concepts and reorg introduction

- docs/docs/project-configuration-dev-test-build.mdx
Make VSCode ignore the `.yarn`-folder and thus exclude it from parsing.
Some more zen for the DX – and i guess some cpu cycles saved as VSCode won't try to ~~discover and parse~~ watch and search a 2.1MB javascript executable.
In the least it doesn't hurt to exclude this from the IDE – unless someone knows and actual need to do something in the `.yarn`-folder via VSCode.
> Add section on VSCode folder-/watcher-ignore settings to "Project Configuration" docs (using `.yarn`-folder as an example)

- docs/docs/typescript/strict-mode.md
- packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
- packages/internal/src/__tests__/resolverFn.test.ts
- packages/internal/src/generate/graphqlCodeGen.ts
This reverts the change I tried to make to allow resolvers to return partial Prisma models.
My change however would:
a) Make all the resolvers partial - which is definitely not desired behaviour
b) Cause issues in service tests
This returns the behaviour back to how it was - which unfortunately is to require complete prisma models to be returned from resolvers.
> fix(ts): Avoid using partial resolver return types in codegen

- __fixtures__/example-todo-main/api/src/lib/polyfill.js
- packages/internal/src/__tests__/build_api.test.ts
- packages/internal/src/build/babel/api.ts
This PR adds more api-side polyfill tests so that I can better gauge the changes in (formerly https://github.com/redwoodjs/redwood/pull/5405, new branch in the works), which upgrades babel, bumps the Node.js target, and changes the polyfill strategy. I only added more api-side tests because 1) I was just trying to do one thing at a time and 2) the web side doesn't pin polyfills the way the api side does. 
More on the second point: the web side uses Babel's preset-env polyfill strategy which takes the target into account. The api side 1) uses the plugin-transform-runtime polyfill strategy which doesn't take the target into account and 2) pins the version of core-js it uses to 3. So the changes I'm making to Redwood's Babel config in (formerly https://github.com/redwoodjs/redwood/pull/5405, …
> [Build] Add more api-side polyfill tests

- docs/docs/tutorial/chapter2/routing-params.md
Fixes #6205 #6214 
The scaffold generator produces cell components that use curly braces and a return statement. This PR updates the code snippet in the tutorial to match.
> Tutorial: Use curly braces and `return` in ArticleCell Success

- babel.config.js
- packages/internal/src/__tests__/build_api.test.ts
- packages/internal/src/build/api.ts
- packages/internal/src/build/babel/api.ts
Getting the bump-the-node-target part of https://github.com/redwoodjs/redwood/pull/6209 in because we're leaning towards taking our time with the polyfills.
> [Build] Bump Node.js target from 12 to 14

- packages/graphql-server/src/__tests__/cors.test.ts
Tests were failing when trying to upgrade @graphql-yoga/common because of this test case. Specifying content-type also for multi-value headers is the correct thing to do.
> Specify content-type in Yoga CORS test

- packages/testing/config/jest/web/jest-preset.js
Follow up to the [v2.2.2](https://github.com/redwoodjs/redwood/releases/tag/v2.2.2) patch; jest 28 changes this option to `testEnvironmentOptions.url`. See https://jestjs.io/docs/upgrading-to-jest28#testurl.
> [Fix] Swap `testURL` for `testEnvironmentOptions.url` in Jest web preset

- packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.yargs.ts
When running
```npx @redwoodjs/codemods@canary configure-fastify```
```Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
⠸ Configure Fastify
ERR /Users/xxx/redwood.toml Transformation error (Topic reference is used, but the pipelineOperator plugin was not passed a "proposal": "hack" or "smart" option. (1:0))
SyntaxError: Topic reference is used, but the pipelineOperator plugin was not passed a "proposal": "hack" or "smart" option. (1:0)
at instantiate (/Users/xxx/.npm/_npx/6af5e84efc8d7cdf/node_modules/@babel/parser/lib/index.js:72:32)
at constructor (/Users/xxx/.npm/_npx/6af5e84efc8d7cdf/node_modules/@babel/parser/lib/index.js:366:12)
at TypeScriptParserMixin.raise (/Users/xxx/.npm/_npx/6af5e84efc8d7cdf/node_modules/@babel/parser/lib/index.js:3453:19)
at …
```
> Fix: Fixes an error seen with the Configure Fastify codemod for v3-rc

- packages/router/src/__tests__/router.test.tsx
- packages/router/src/__tests__/util.test.ts
- packages/router/src/active-route-loader.tsx
- packages/router/src/router.tsx
- packages/router/src/util.ts
Closes https://github.com/redwoodjs/redwood/issues/5497. When it comes to the router, it's react components all the way down. The router is a react component; routes are react components; pages are react components. We pass path and search parameters to pages as props, so that you can do things like...
```jsx
const PostPage = ({ id }) => {
return <PostCell id={id} />
}
```
(You can also get `id` from the params context via `useParams`, but destructuring it from props is more convenient.) When a path or search param is `ref` or `key`, there's an issue. If it's `ref`, the component throws since you can only pass the return of `React.createRef` or `useRef` to `ref`. With `key`, nothing happens, but the component consumes the prop and you don't get access to it. It's still accessible via …
> Handle special props `ref` and `key` in path and search params

- packages/router/src/Set.tsx
Fix the bug mentioned in #6357 about a non-descriptive message when using a non-defined route for the unauthenticated prop of Private
> Use try/catch to access unauthenticated

- docs/docs/deploy/baremetal.md
- packages/cli/src/commands/deploy/baremetal.js
- packages/cli/src/commands/setup/deploy/templates/baremetal.js
Closes https://github.com/redwoodjs/redwood/issues/6363
If you're using Baremetal deploy, we've got an easier way to specify your private key. Previously, if you wanted to connect the [private key option](https://redwoodjs.com/docs/intro-to-servers#private-key), you needed to include the actual content of the private key itself as a `Buffer` in the `privateKey` config option. That option still remains, but we now also include a `privateKeyPath` option if you just want to include the path to the key:
```diff
[[production.servers]]
host = "server.com"
username = "user"
+ privateKeyPath = "/Users/rob/.ssh/private.pem"
sides = ["api","web"]
path = "/var/www/app"
processNames = ["serve"]
repo = "git@github.com:myorg/myapp.git"
branch = "main"
keepReleases = 5
```
> Adds `privateKeyPath` option to Baremetal deploy

- .github/actions/only_doc_changes/only_doc_changes.mjs
- .github/workflows/cherry-pick-into-release-pr.yml
- .github/workflows/enable-auto-merge.yml
This PR adds two new workflows that 1) create PRs against the release branch when a PR is merged to the main branch (as long as the PR isn't breaking) and 2) enables auto-merge on said PRs. I've tested these workflows on my fork of Redwood, but they may still need some work.
We're trying out a new branch strategy so that we can merge breaking changes into main while still releasing minors and patches. I won't go into all the details right now, but this is one of the first things we need.
> [Chore] Add cherry pick CI

- .eslintrc.js
- packages/create-redwood-app/README.md
- packages/internal/package.json
- packages/structure/src/hosts.ts
- packages/structure/src/index.ts
- packages/structure/src/model/RWProject.ts
- packages/structure/src/model/RWRouter.ts
- packages/structure/src/model/__tests__/model.test.ts
- packages/structure/src/outline/outline.ts
- packages/telemetry/README.md
- packages/telemetry/src/sendTelemetry.ts
The telmetry script was failing, because it couldn't find the module typescript. 
You can see this by running with the verbose flag: `REDWOOD_VERBOSE_TELEMETRY=true yarn create-redwood-app bazinga`
1. `typescript` is an explicit dependency of `rwjs/internal` . This is because we use it for detecting strict mode. 
What was happening was this import sequence:
crwa -> rwjs/structure -> rwjs/internal -> ts
Why is TS even imported here? Because of the import statement in rwjs/structure project.ts and host.ts: 
```
import { getPaths, processPagesDir } from '@redwoodjs/internal'
```
2. Makes sure structure also imports from specific files in internal i.e.
```diff
-import { getPaths, processPagesDir } from '@redwoodjs/internal'
+import { getPaths, processPagesDir } from …
```
> fix(crwa): Fixes telemetry issues on CRWA

- packages/auth/src/AuthProvider.tsx
- packages/router/src/__tests__/router.test.tsx
callback takes the previous state as the first argument.
> setState() does not always immediately update the component. It may batch or defer the update until later. This makes reading this.state right after calling setState() a potential pitfall. Instead, use componentDidUpdate or a setState callback (setState(updater, callback)), either of which are guaranteed to fire after the update has been applied. If you need to set the state based on the previous state, read about the updater argument below.
see:
- https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md
- https://reactjs.org/docs/react-component.html#setstate
Closes #5627
> chore(react): use `updater` callback function

- docs/docs/deploy/baremetal.md
- packages/cli/src/commands/deploy/__tests__/baremetal.test.js
- packages/cli/src/commands/deploy/baremetal.js
Related to #6426.
I have added in the default port option to the default server config `DEFAULT_SERVER_CONFIG` and have ensured the configured port setting is passed through to the node-ssh connection.
This is my first open-source contribution so thanks for your patience with me.
> fix: Added default port ssh port 22 and forwarding of config port setting

- packages/testing/config/jest/api/jest-preset.js
- packages/testing/config/jest/api/jest.setup.js
...by loading scenarios in the same context as jest.
This unfortunately is a compromise, because the work I did to improve the memory usage of our scenario tests gets a little nullified now. 
One of the memory optimisations I did was to make sure scenarios are loaded and seeded _outside_ the context/VM that the tests run in. This seemed to really help with memory usage, but unfortunately breaks tests in watch mode, with a cryptic DB/Prisma error (on Postgres):
```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(EXX000), message: "cache lookup failed for type 226432", detail: None, hint: None, position: None, where_: Some("unnamed portal parameter $3"), schema: …
```
> fix(jest): Fix watchmode on api tests 

- packages/cli/src/commands/generate/cell/__tests__/cell.test.js
Accidentally left linting errors in the tests that I added (I guess my Gitpod env isn't configured properly).
> chore(lint): Fix lint issues in cell test

- docs/docs/cli-commands.md
Documentation for the query flag added in #6442. Forgot to add it in the original PR 🤦‍♂️
> [Docs]: CLI Cell query flag added

- packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
We have a new nixpacks build option that automatically detects package manager versions, node versions, etc. So install command is no longer needed and no longer need to manually install yarn stable version.
> update flightcontrol deploy config

- package.json
- tasks/test-project/tasks.js
- tasks/test-project/test-project
- yarn.lock
Remove all our dependency on listr. This is a continuation on the work started in https://github.com/redwoodjs/redwood/pull/6444/
cc @Josh-Walker-GM
> Move to Listr2 for test-project

- docs/docs/local-postgres-setup.md
Running the brew install command on https://redwoodjs.com/docs/local-postgres-setup#install-postgres results in
```
No available formula with the name "postgres@14". Did you mean postgresql@14, postgrest, postgresql@12, postgresql@11, postgresql@10 or postgresql@13?
```
I believe this was a typo for postgresql as seen here: https://formulae.brew.sh/formula/postgresql@14
> Fix homebrew formula name for postgresql

- .github/renovate.json
It's ESM-only now. See https://github.com/redwoodjs/redwood/pull/6591.
> chore: ignore sort-package-json

- packages/structure/src/interactive_cli/command_builder.ts
I had a TS error in `command_builder.ts`
This is the error:
This PR fixes the issue by converting all arguments to strings
> command_builder: Explicitly convert args to strings

- packages/telemetry/src/sendTelemetry.ts
Fixing a spelling mistake (sensative -> sensitive)
(pulling this out of the decouple auth pr)
> Telemetry: Fix sensitive spelling

- docs/docs/tutorial/chapter2/routing-params.md
Without this definition, we encounter the TS error: "Property 'id' does not exist on type 'Props'"
> docs: Defined `id` in the Props interface

- .github/actions/check_test_project_fixture/check_test_project_fixture.mjs
The test project uses dbAuth, and the dbAuth setup will soon use cli-helpers. So it's possible that the test project fixture will have to be updated when something has changed in cli-helpers.
> Check if test-project fixture needs updating when updating cli-helpers

- packages/graphql-server/src/functions/__tests__/fixtures/auth.ts
- packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts
- packages/graphql-server/src/functions/useRequireAuth.ts
- packages/graphql-server/src/plugins/__tests__/useRedwoodAuthContext.test.ts
Tighten up types mainly for the tests in graphql-server
I originally did this as part of my Decouple Auth PR to make it easier to spot any errors when I was rewriting auth
> graphql-server: Stricter types

- lerna.json
- nx.json
Follow up to upgrading to lerna v6 in https://github.com/redwoodjs/redwood/pull/6676, this PR has the results of running lerna's new repair command.
> chore: run lerna repair

- packages/auth-providers-setup/src/dbAuth/templates/api/functions/auth.ts.template
- packages/auth-providers-setup/src/dbAuth/templates/api/functions/auth.webAuthn.ts.template
- packages/web/src/apollo/index.tsx
Couple of minor fixes from the Decouple Auth PR #5985
> fixes: dbAuth template and Apollo comment

- packages/cli/src/commands/setup/auth/auth.js
One stylistic warning from `yarn lint` after merging https://github.com/redwoodjs/redwood/pull/5985.
> chore: run lint fix post merge #5985

- packages/auth-providers-api/package.json
- packages/auth-providers-setup/package.json
- packages/auth-providers-web/package.json
- packages/cli-helpers/package.json
These packages were marked as private to keep canary publishing going before https://github.com/redwoodjs/redwood/pull/5985 was merged, but now that it's in main, we want these packages to be published.
> chore: remove private field on new packages package.json

- packages/auth-providers-setup/src/netlify/setup.ts
Now that @redwoodjs/auth-providers-api and @redwoodjs/auth-providers-api are available on npm we can install them during setup
> Netlify: Enable auth-providers-api and auth-providers-web installation

- __fixtures__/test-project/api/package.json
- __fixtures__/test-project/web/package.json
- packages/auth-providers-setup/src/dbAuth/setup.ts
- packages/auth-providers-setup/src/dbAuth/webAuthn.setupData.ts
- packages/cli-helpers/src/auth/setupHelpers.ts
There's another change or two needed here to fix webAuthn setup.
> fix(dbAuth): add required packages to setup command

- .github/workflows/cherry-pick-into-next-branch.yml
Fixes what we saw happen in https://github.com/redwoodjs/redwood/actions/runs/3245650941. In this run, even though the fast-forward job couldn't cleanly cherry pick the commit in the squashed PR, the PR step could (somehow), and went ahead and made a PR. Let's just exit if the first step fails.
This PR also adds a `skip-cherry-pick` flag for PRs that will cleanly cherry pick but that we don't want in the next, like those in the last few commits.
> fix(CI): don't PR against "next" if we can't cleanly cherry pick

- packages/auth-providers-setup/src/clerk/setup.ts
- packages/auth-providers-setup/src/clerk/templates/web/auth.tsx.template
Some helpful comments got lost somewhere when moving to the new setup structure. Adding them back. 
Also add @redwoojs/auth-providers-web and -api to packages to be installed.
> Update the Clerk setup script and templates

- packages/auth-providers-setup/src/supabase/setup.ts
This change hardcodes the version supported for Supabase in the webPackages const for the Supabase provider
The latest Supabase version v2.0.4 is incompatible with the current Supabase auth setup.
For example using their Docs on using Supabase with Redwood: https://supabase.com/docs/guides/with-redwoodjs
The function `client.auth.signIn` does not exist anymore in v2.0.4
Fix: https://github.com/redwoodjs/redwood/issues/6729
> fix(Supabase): Set Supabase webPackage to 1.35.7 (from main)

- docs/docs/authentication.md
- docs/versioned_docs/version-3.2/authentication.md
`context` is a global and should not be imported. In fact, trying to import it from rw/api will give red squiggles
> Update auth docs to not import global context

- docs/versioned_docs/version-3.1/tutorial/chapter2/routing-params.md
- docs/versioned_docs/version-3.1/tutorial/chapter5/first-story.md
- docs/versioned_docs/version-3.1/tutorial/chapter5/first-test.md
- docs/versioned_docs/version-3.1/tutorial/chapter5/testing.md
- docs/versioned_docs/version-3.1/tutorial/chapter6/comment-form.md
- docs/versioned_docs/version-3.1/tutorial/chapter6/comments-schema.md
- docs/versioned_docs/version-3.1/tutorial/chapter6/multiple-comments.md
- docs/versioned_docs/version-3.1/tutorial/chapter6/the-redwood-way.md
- docs/versioned_docs/version-3.1/tutorial/chapter7/api-side-currentuser.md
- docs/versioned_docs/version-3.1/tutorial/chapter7/rbac.md
- docs/versioned_docs/version-3.2/tutorial/chapter5/first-story.md
- docs/versioned_docs/version-3.2/tutorial/chapter5/first-test.md
- docs/versioned_docs/version-3.2/tutorial/chapter5/testing.md
- docs/versioned_docs/version-3.2/tutorial/chapter6/comment-form.md
- docs/versioned_docs/version-3.2/tutorial/chapter6/comments-schema.md
- docs/versioned_docs/version-3.2/tutorial/chapter6/multiple-comments.md
- docs/versioned_docs/version-3.2/tutorial/chapter6/the-redwood-way.md
- docs/versioned_docs/version-3.2/tutorial/chapter7/api-side-currentuser.md
- docs/versioned_docs/version-3.2/tutorial/chapter7/rbac.md
@jtoar here it is! I didn't include 3.0 because we didn't introduce the new ScaffoldLayout until 3.1 and the tutorial makes mention of that. I didn't want to try and diff the NEW stuff against the old PostsLayout junk. Plus anyone that's coming to the tutorial is probably only viewing the latest release version anyway.
> Backports tutorial updates to versioned docs 3.1 and 3.2

- packages/auth-providers-setup/src/dbAuth/templates/api/functions/auth.webAuthn.ts.template
Type was imported twice, and the second time from the wrong package
> Fix dbAuth webAuthn template (redundant type import)

- tasks/run-e2e
The Prisma v4.5.0 upgrade (https://github.com/redwoodjs/redwood/pull/6485) revealed a bug in the tutorial e2e CI job since the `yarn rw g scaffold` command now has an install step.
The problem is that the tutorial e2e test project uses the current stable version of Redwood (v3.2.1), which has Prisma v4.3.1. When we use rwfw to link, it adds v4.5.0 to the root package.json. Since there's now two different versions of Prisma, after the install step happens in `yarn rw g scaffold`, yarn realizes it can't hoist Prisma anymore since there's two versions (or something like that), so it installs v4.3.1 into `node_modules/@redwoodjs/cli/node_modules`.
> [CI]: Add Prisma resolutions to tutorial-e2e test project

- __fixtures__/test-project/web/package.json
- tasks/test-project/tasks.js
@virtuoushub reported that rebuilding the test project fixture with `yarn build:test-project --rebuild-fixture` on https://github.com/redwoodjs/redwood/pull/4992 was broken. Turns out it was also broken on main, I think for reasons similar to https://github.com/redwoodjs/redwood/pull/6772. This PR adds a step to recopy the framework code after generating the scaffold, and rebuilds the text project fixture cause it works now.
> [CI]: Fix and rebuild test project fixture

- packages/auth-providers-api/src/dbAuth/DbAuthHandler.ts
- packages/auth-providers-api/src/dbAuth/__tests__/DbAuthHandler.test.js
If this could be a 3.2.2 that'd be awesome. Otherwise can wait for 3.3.0.
Closes #6756
> Fix WebAuthn when event body is base64 encoded (like when deploying to Vercel)

- packages/auth-providers-api/src/dbAuth/DbAuthHandler.ts
- packages/auth-providers-api/src/dbAuth/__tests__/DbAuthHandler.test.js
> Strip resetToken and resetTokenExpiresAt from dbAuth forgotPassword handler

- .github/workflows/publish-canary.yml
Right now, the canary we publish on every commit to main is actually the next major, but it's tagged as if it were the next patch from v3.2.0 (since we don't include merged tags in main at the moment). Let's make it so that the canary is versioned as if it were the next major.
> [CI]: Publish canary using premajor

- docs/docs/tutorial/chapter3/saving-data.md
Fix #5902
> The "Saving Data" section of Chapter 3 (v2.0) is inconsistant with what I observe.
Confirmed by retry the output of `yarn rw g sdl Contact`
> [Tutorial]: Fix Typescript code blocks inconsistency

- packages/cli/src/commands/generate/scaffold/scaffold.js
Implement a fix for this issue: https://github.com/redwoodjs/redwood/issues/6654
Gitpod snapshot: https://gitpod.io#snapshot/e0161d70-2435-435a-a229-0578ef51a48b
Steps to reproduce:
1. Open [starter repo](https://github.com/redwoodjs/gitpod-starter) in Gitpod
2. `yarn rw g scaffold admin/UserExample`
3. Navigate to `admin/user-examples`
4. See the following error:
**Solution description**:
Generate `titleTo` and `buttonTo` in the same way that scaffold route names are generated, with the function `getTemplateStrings()`
> fix: have scaffold set titleTo and buttonTo depend on getTemplateStrings

- docs/docs/testing.md
I think I screwed up in https://github.com/redwoodjs/redwood/pull/5381 and should've put the hooks section after the components section. right now it's in the middle of it.
> [Docs]: Move hooks section after components section in testing reference

- docs/docs/cli-commands.md
- packages/create-redwood-app/src/create-redwood-app.js
- tasks/run-e2e
Hi All,
Related to: https://github.com/redwoodjs/redwood/issues/3989
This PR does the following:
- Adds `--git`  and `--git-init` args to the cli installer, `--git` is just an alias for `--git-init`. By default this also enables `--no-git` and `--no-git-init`
- Adds prompt for whether the user wants to init a new git repo
- Adds ListR task for initializing a new git repo using the following command `git init && git add . && git commit -m "Initial commit" && git branch -M main`
- Adds `onCancel: () => process.exit(1)` to both the code language prompt and git init prompt so there is a cleaner cancel if the user exits the process during the prompts
- Adds an error for when the user selects JavaScript but disables yarn install which won't work
The biggest question I had was _which_ prompt …
> (crwa): Add git init option

- packages/codemods/package.json
- packages/codemods/src/lib/getRWPaths.ts
- packages/internal/package.json
- packages/internal/src/config.ts
- packages/structure/package.json
- packages/structure/src/model/RWTOML.ts
- yarn.lock
**Problem**
Multiple different TOML packages are used in the framework. Is it possible to move to use a consistent TOML package?
**Motivation**
~~My own interest is that in a separate PR I wish to go from JSON to TOML but that doesn't appear to be support by `toml` but is by `@iarna/toml`.~~ `@iarna/toml` is a reasonable choice because it's more recently updated, has more active users and was not overly complex to switch to.
**Changes**
1. Updates to `structure`, `internal` and `codemods` package.json's. 
2. Update to imports to use `@iarna/toml` instead of `toml`
3. Some type casting in RWTOML.ts
> Change to use @iarna/toml instead of toml

- package.json
- tasks/release/branchStrategy/branchStrategyCLI.mjs
- tasks/release/branchStrategy/branchStrategyLib.mjs
- tasks/release/branchStrategy/findPRCommand.mjs
- tasks/release/branchStrategy/triageMainCache.json
- tasks/release/branchStrategy/triageMainCommand.mjs
- tasks/release/branchStrategy/triageNextCache.json
- tasks/release/branchStrategy/triageNextCommand.mjs
- tasks/release/branchStrategy/validateMilestonesCommand.mjs
This adds framework-side tooling for managing commits between the main, next, and release branches:
```
yarn branch-strategy --help
```
Commands:
- `triage-main`
- `triage-next`
- `find-pr`
- `validate-milestones`
The main commands are `triage-main` and `triage-next`. They're extensions of:
```
git log --graph --oneline --boundary --cherry-pick --left-only main...next
````
([`--cherry-pick`](https://git-scm.com/docs/git-log#Documentation/git-log.txt---cherry-pick) is the critical flag here.)
This command basically shows the difference between main and next. But since there's a lot of output, it's not helpful without more tooling to show...
- which commits don't need to be cherry picked
- which commits were cherry picked but have a different diff because they needed to be changed slightly …
> [Chore]: Add branch strategy tooling

- tasks/test-project/test-project
Follow up to adding a git init feature to CRWA https://github.com/redwoodjs/redwood/pull/6805.
> [Fix]: Rebuild test-project fixture by passing `--no-git`

- tasks/release/branchStrategy/README.md
- tasks/release/branchStrategy/branchStrategyCLI.mjs
- tasks/release/branchStrategy/branchStrategyLib.mjs
- tasks/release/branchStrategy/triageNextCommand.mjs
- tasks/release/branchStrategy/validateMilestonesCommand.mjs
This updates the branch strategy tooling, mainly expanding the scope of the `validate-milestones` command to validate all "active" milestones ("next-release", "v4.0.0" and the release milestone (right now, "v3.5.0")). It also forces the user to be on the `branch-strategy-triage` branch (which I will push up to this repo) because doing triage requires committing changes to the `triage*Cache.json` files, which is unfeasible to do on main since it happens constantly.
I've added the beginnings of a readme I'll expand on later.
> [Feat(branch strategy)]: Add readme, expand milestone validation

- packages/internal/src/__tests__/config.test.ts
- packages/internal/src/__tests__/configPath.test.ts
- packages/internal/src/__tests__/paths.test.ts
Closes #613 
**Problem**
Additional tests for `getPaths` within the internal package is wanted. 
**Changes**
1. Adds tests for the `getPaths` function which ensures the paths match those expected for the 4 different project fixtures.
2. Adds a test which confirms `getConfig` throws an error when given a bad path
3. Adds tests for the `getConfigPath` function
4. Other changes within the `paths.test.ts` to ensure the tests are run for each fixture.
**Questions**
1. The `paths.test.ts` is quite long now. Perhaps this is not the testing solution that others had envisioned?
2. Is there an appetite to expand this to include additional test coverage or is it fine to just address the paths?
> chore: Additional tests for paths and config

- __fixtures__/test-project/.vscode/launch.json
- packages/create-redwood-app/template/.vscode/launch.json
There are several different files `launch.json` - PR addresses the likely most often used one at `https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/template/.vscode/launch.json`. 
I am proposing to remove two arguments
```
"protocol": "inspector",
"stopOnEntry": false,
```
The first one is illegal in the context it is being used and the second one's default value is false, so it is redundant. 
I presented this [issue](https://community.redwoodjs.com/t/protocol-inspector-inside-launch-json-is-not-allowed/4319) in Discourse hoping to elicit some comments, go nothing so far
> fix launch.json

- packages/auth-providers/azureActiveDirectory/setup/src/__tests__/setup.test.ts
- packages/auth-providers/azureActiveDirectory/setup/src/setup.ts
- packages/cli/src/commands/setup/auth/auth.js
- tasks/framework-tools/lib/framework.mjs
- tasks/framework-tools/lib/project.mjs
We're starting to move the auth providers out of the `auth-provider-*` packages. See...
- https://github.com/redwoodjs/redwood/pull/6922
- https://github.com/redwoodjs/redwood/pull/6982
- https://github.com/redwoodjs/redwood/pull/6987
This PR adds basic import handling to the setup auth command so that it doesn't break when the auth setup commands are fully removed as CLI dependencies. This could be a preliminary version of plugins where the set of plugins available is hardcoded. But this is mostly just to keep things from breaking for now.
> fix(cli): Handle importing optional setup auth commands

- docs/docs/tutorial/chapter4/deployment.md
Netlify has changed how Environment Variables are set. They are no longer nested inside Build & Deploy.
> Ch4: Deployment - Updating Environment variable section

- packages/cli/src/commands/setup/auth/auth.js
I forgot to update the auth provider names in the setup command in https://github.com/redwoodjs/redwood/pull/7019.
> fix: auth provider names in setup auth

- packages/cli/src/commands/setup/auth/auth.js
The code for adding installed auth setup commands to `yarn rw setup auth` had a typo in the dbauth setup package name
> Fix typo in dbauth setup package name

- packages/cli/src/commands/setup/auth/auth.js
Throw an error if the error code is anything but MODULE_NOT_FOUND
> Setup auth: No return on missing modules

- packages/auth-providers/dbAuth/setup/src/setupHandler.ts
- packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
If you setup dbAuth with webAuthn, you get the wrong versions of the corresponding web and api packages.
> fix: dedupe redwoodjs packages

- packages/cli/src/commands/generate/__tests__/helpers.test.js
This test would fail if you had the repo checked out to a folder named anything but "redwood". Just removing that part make the test pass and be more flexible with folder names. `toMatch` does a substring match, that's why this works
> Allow other repo names than just "redwood"

- packages/cli-helpers/package.json
- packages/cli-helpers/src/lib/paths.ts
- packages/cli-helpers/tsconfig.json
- yarn.lock
While reviewing https://github.com/redwoodjs/redwood/pull/6956, I noticed more dependencies from `@redwoodjs/cli-helpers` that were missing. This PR adds them. If it's merged before https://github.com/redwoodjs/redwood/pull/6956, I'll remove the duped packages there (just prompts right now).
The steps behind this are:
- build the package
- search through the package's dist for all require statement
- is the required package listed in package.json's dependencies?
> fix: add missing deps to cli helpers

- packages/cli/package.json
- yarn.lock
https://github.com/redwoodjs/redwood/pull/7138, which removed `@redwoodjs/cli`'s dependency on `@redwoodjs/auth-providers-setup`, revealed a hidden dependency on `@redwoodjs/cli-helpers` introduced in https://github.com/redwoodjs/redwood/pull/6082. This PR lists it explicitly. Otherwise you get this in Redwood projects when trying to run `yarn rw setup` anything:
```
Error: Cannot find module '@redwoodjs/cli-helpers'
Require stack:
- /Users/dom/prjcts/redwood/redwood-app/node_modules/@redwoodjs/cli/dist/commands/setup/cache/cache.js
- /Users/dom/prjcts/redwood/redwood-app/node_modules/yargs/build/index.cjs
- /Users/dom/prjcts/redwood/redwood-app/node_modules/yargs/helpers/index.js
- /Users/dom/prjcts/redwood/redwood-app/node_modules/@redwoodjs/cli/dist/index.js
- …
```
> fix(setup): list `@redwoodjs/cli-helpers` as dependency to `@redwoodjs/cli`

- packages/api/package.json
- packages/api/src/cache/clients/RedisClient.ts
- packages/auth-providers/dbAuth/api/package.json
- yarn.lock
After reviewing https://github.com/redwoodjs/redwood/pull/7122, I noticed that there's other unnecessary dependencies in `@redwoodjs/api`'s package.json. So this PR tries to sort it out. 
> I had to add `@simplewebauthn/server` to `@redwoodjs/auth-dbauth-api`'s devDependencies because it uses types from it, and it was piggbacking off it being listed in `@redwoodjs/api`.
> chore: remove unnecessary `@redwoodjs/api` dependencies

- packages/cli/src/commands/generate/__tests__/createYargsForComponentGeneration.test.js
- packages/cli/src/commands/generate/__tests__/helpers.test.js
- packages/cli/src/commands/generate/dataMigration/dataMigration.js
- packages/cli/src/commands/generate/directive/directive.js
- packages/cli/src/commands/generate/function/function.js
- packages/cli/src/commands/generate/helpers.js
- packages/cli/src/commands/generate/model/model.js
- packages/cli/src/commands/generate/page/page.js
- packages/cli/src/commands/generate/script/script.js
> Check that most generator <name> positional arguments don't start with non-word characters

- .github/workflows/publish-canary.yml
Redwood's deploy target CI was failing on a version of the `next` tag. Curiously, the version it was at in main also failed if you rebuilt the `yarn.lock`, so something weird was going on. The `yarn.lock` look botched—it was installing `v3.7.1` of some of the redwood packages, not the `v3.7.1-next.*`. And there were semver carets all over the place, which our CI is supposed to catch.
The new npm code browser makes the problem clear:
Why do all the `@redwoodjs` packages have semver carets? Lerna is putting them there because we're not passing the `--exact` flag.
> chore: forego semver carets in canary publishing

- packages/cli/src/commands/setup/deploy/templates/render.js
Fixes #7195
https://community.render.com/t/blueprint-error-services-0-plan-no-such-plan-free-for-service-type-web/7067
> Render deploy: Static sites are always free

- packages/cli/src/commands/setup/deploy/providers/netlify.js
This url is no longer correct
Switched to https://redwoodjs.com/docs/deploy/netlify instead
> Correct link to Netlify deploy docs

- packages/auth-providers/clerk/setup/src/setupHandler.ts
Noticed this while I was writing docs for clerk—just a missing end quote on the package.
> fix: typo in clerk auth decoder import

- packages/auth-providers/supabase/setup/src/setupHandler.ts
The `yarn rw setup auth supabase` command is still using the old `auth-providers-{api,web}` packages instead of the new ones exclusive to supabase.
> fix: update packages in supabase setup

- packages/cli/src/commands/generate/helpers.js
Getting rid of unrelated warnings on other PRs
> cli generate helpers.js: Fix formatting warnings

- packages/cli/src/commands/setup/auth/auth.js
To make a canary version, lerna adds the commit hash after the number of commits. The canary versions end up looking like `4.0.0-rc.428+dd79f1726`. When you run `yarn npm info @redwoodjs/core --fields versions`, npm doesn't divulge the `+` part, just everything before it. This leads to false positives when checking for the version.
> Fix how the setup auth command checks for published versions

- packages/cli-helpers/src/auth/__tests__/setupHelpers.test.ts
the `rwVersion` argument was removed a few days/weeks ago, but we forgot to remove it from the tests
> setupHelpers.test.ts: Remove unused arg

- packages/cli/src/commands/setup/vite/vite.js
- packages/cli/src/commands/setup/vite/viteHandler.js
Follow up to https://github.com/redwoodjs/redwood/pull/6967; this PR 1) separates the handler from the rest of the  `yarn rw setup vite` command module and 2) fixes the version of `@redwoodjs/vite` installed by `yarn rw setup vite`, using the strategy `yarn rw setup auth` commands use.
More on the latter: right now, when you upgrade to canary and run `yarn rw setup vite`, it'll install version `0.0.1` of `@redwoodjs/vite` because `addWebPackages` installs the latest version of a package if no version is provided. We had this problem with the auth provider packages. The way we solved it was just being specific about which version to install by reading from the package.json, so that you always get exactly what you think you're getting.
> Separate setup vite handler, install canary version of `@redwoodjs/vite`

- .github/workflows/publish-canary.yml
I'd like to try using this action a bit more in our CI workflows to decongest our GitHub Actions runners. 
Sometimes things happen too fast, and irrelevant workflows are left as `in_progress` or `queued`. The main case where this happens I'm thinking of is renovate, when I squash merge a bunch of PRs that all pass CI. It could queue up 5+ canaries to be published, when it makes more sense to just do one.
So let's try this for a bit and see if it's effective; if so we can add it to other workflows.
> fix(CI): cancel previous `in_progress` or `queued` canaries

- packages/forms/src/index.tsx
- packages/internal/src/routes.ts
Seeingn some lint warnings in GitHub's "Unchanged files with check annotations" in PRs like https://github.com/redwoodjs/redwood/pull/7321; this PR runs `yarn lint --fix`
> chore: fix lint warnings forms/internal

- .github/actions/get_publish_flags/action.yml
- .github/actions/get_publish_flags/get_publish_flags.mjs
- .github/actions/message_slack_publishing/action.yml
- .github/workflows/publish-canary.yml
- .yarn/patches/@lerna-publish-npm-6.4.1-27e0fee593.patch
- package.json
- packages/cli/src/commands/upgrade.js
- yarn.lock
When there's a major RC, `yarn rw upgrade -t canary` is silently broken. 
`yarn rw upgrade -t canary` does it's thing by 1) changing the versions in the package.jsons to something like `^4.0.0-canary.456`, then 2) installing. Since the verisons in the package.jsons have carets, they grab the RC instead of the canary since the RC's specifier is "higher" (4.0.0-r... > 4.0.0-c...):
```
4.0.0-canary...
4.0.0-rc...
```
I tried to solve this in a few ways, all using lerna's existing api (i.e. CLI commands like `yarn lerna version`, `yarn lerna publish`). None of them worked, and after poking around the source of lerna's publish command, I discovered that what I want to do isn't possible unless I `git tag`, which I definitely don't want to do. So I patched lerna, adding a custom flag …
> Fix premajor canary publishing when there's a major RC 

- packages/api/src/auth/__tests__/getAuthenticationContext.test.ts
- packages/api/src/auth/index.ts
- packages/graphql-server/src/functions/useRequireAuth.ts
- packages/graphql-server/src/plugins/useRedwoodAuthContext.ts
To make it easier for our users to have multiple auth providers it's now possible to send an array of `authDecoder`s to `createGraphQLHandler` and it'll try them one by one until it finds one that can decode the auth token
> Allow passing an array of auth decoders to createGraphQLHandler

- packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
- packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
- packages/cli-helpers/src/auth/__tests__/fixtures/AppWithLegacyAuth.tsx
- packages/cli-helpers/src/auth/authTasks.ts
When setup mode is FORCE or REPLACE we remove any legacy AuthProvider imports because that's in practice what we want when we replace a legacy auth provider setup
> Remove legacy auth import

- packages/cli-helpers/src/auth/__tests__/__snapshots__/authTasks.test.ts.snap
- packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
- packages/cli-helpers/src/auth/authTasks.ts
If the setup mode is FORCE or REPLACE we remove the old AuthProvider before adding the new one (effectively replacing the old one). This also handles legacy AuthProvider configs
> Remove old AuthProvider when FORCE or REPLACE

- packages/cli-helpers/src/auth/authTasks.ts
Since only one option was available I disabled the prompt for now and default to the one and only option that was available
> Setup auth: Disable prompt

- packages/auth/src/AuthContext.ts
- packages/internal/src/generate/templates/all-currentUser.d.ts.template
Fixes #7359 
By not declaring `roles` on the "base" `CurrentUser` we give full flexibility to `getCurrentUser` in the user's project to define `roles` however it wants.
> CurrentUser: Let declaration merging add `roles`

- .github/workflows/check-test-project-fixture.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
- .github/workflows/require-release-label.yml
- .github/workflows/update-all-contributors.yml
In https://github.com/redwoodjs/redwood/pull/7323 I added https://github.com/styfle/cancel-workflow-action to the publish canary workflow. It worked exactly as intended, and as I was looking into adding it to other workflows, it seems that in the last few days that action has been scheduled for deprecation in favor of GitHub Action's native [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow) feature, which does the same thing.
> feat(CI): cancel in-progress runs

- packages/auth-providers/azureActiveDirectory/web/src/azureActiveDirectory.ts
Following the guidelines and code samples in https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md we're now only redirecting in `getToken` if we get an `InteractionRequiredAuthError`
Fixes #7112
> Azure: Only redirect in getToken on InteractionRequiredAuthError

- docs/docs/auth/azure.md
This PR changes the argument for running `rw setup auth azure-active-directory`
> docs: use correct argument for azure auth setup

- docs/docs/deploy/baremetal.md
- docs/versioned_docs/version-1.x/deploy/baremetal.md
- docs/versioned_docs/version-2.0/deploy/baremetal.md
- docs/versioned_docs/version-2.1/deploy/baremetal.md
- docs/versioned_docs/version-2.2/deploy/baremetal.md
- docs/versioned_docs/version-3.0/deploy/baremetal.md
- docs/versioned_docs/version-3.1/deploy/baremetal.md
- docs/versioned_docs/version-3.2/deploy/baremetal.md
Doing a deploy from scratch and going through the docs. Realized that I didn't tell people how to view pm2 log output so that they can see any error messages from the web/api serve processes.
Also backported to all existing versioned docs.
> Adds note about how to view pm2 logs

- packages/router/src/router.tsx
- packages/router/src/util.ts
@jtoar pointed out in #3977 that React has `isValidElement` that we can use instead of our own implementation. #3977 got closed, but I didn't want to forget about `isValidElement`, so this PR introduces just that one change
> Switch to React's isValidElement

- packages/auth-providers/clerk/web/src/clerk.tsx
- packages/auth/src/AuthProvider/AuthProviderState.ts
- packages/auth/src/AuthProvider/useReauthenticate.ts
Clerk isn't defined on the window object till Clerk has loaded, so right now, destructuring `client` from `useAuth` always returns `undefined` because it tries to access it too early. This makes it so that `client` is defined when Clerk has loaded. 
Note that https://community.redwoodjs.com/t/with-clerk-logout-triggers-a-react-error/2853 is no longer an error since in the new auth implementation, the auth provider wraps the clerk provider, so it no longer unmounts.
> [Fix]: Ensure client is defined using Clerk auth

- packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
- packages/auth-providers/supertokens/setup/src/setupHandler.ts
- packages/cli/src/commands/setup/auth/auth.js
This PR:
- fixes setting up dbAuth with webAuthn (it was installing the latest versions of the `@simplewebauthn` packages, which are v7)
- comments out `yarn rw setup auth supertokens`, as it's not working. note that it wasn't a setup command in v3, so not shipping one in v4 isn't breaking. but we'd like to get it working soon, probably in a v4 minor
To discuss with @thedavidprice later.
> fix: pin webAuthn, SuperTokens, comment out latter

- packages/cli/src/commands/setup/auth/auth.js
There was a typo in the auth setup provider descriptions. This PR fixes that
> Fix setup help text typo

- docs/docs/services.md
Looks like 'excludes' is either a typo or an alternative spelling that has been removed from Redwood 3.8
> Fix 'excludes' validator to 'exclusion'

- packages/cli/src/commands/setup/auth/auth.js
When using `yarn rwfw project:copy` the latest versions of all the auth provider packages are already copied over into the target project's node_modules. So no need to try to install the setup package. In fact, if it does try to install it'll grab the latest canary version from npm, which isn't want we want if we're trying to test something new in the setup package
> Make it easier to test auth setup with rwfw project:copy

- packages/cli/src/commands/setup/auth/auth.js
@Tobbe we forgot one thing here—`require.resolve` throws if it can't find the module. I'm going to merge this one if it passes checks cause it's broken in main and the RC, but feel free to do a review or change anything you want in another PR.
For the catch block, I could've made it more specific to the `MODULE_NOT_FOUND` error code, but I don't think we want this command to blow up if it can't find the module.
> fix(CLI): try-catch `require.resolve` in setup auth

- packages/cli/src/commands/setup/auth/auth.js
Follow up to https://github.com/redwoodjs/redwood/pull/7494. There seems to be a bug or at least undocumented behavior where `require.resolve` caches even modules it can't find. 
So `require.resolve` and `require` in general cache modules. You can see them all at `require.cache`, and if you want to delete one of them, you just use `delete`:
```js
delete require.cache[require.resolve(module)]
```
The issue we're having is that `require.resolve` seems to cache even exceptions... Which isn't a problem in and of itself, except for that we can't seem to delete them from the cache because `require.resolve` throws...
```ts
try {
require.resolve("@redwoodjs/auth-auth0-setup/package.json")
// This throws, not installed
} catch (e) {
// Can't delete it from the cache because you need …
```
> fix(CLI): use `require.resolve.paths` to avoid `require.resolve` cache

- packages/auth-providers/supabase/setup/src/setupHandler.ts
- packages/cli/src/commands/setup/auth/auth.js
- The notes output by setup Supabase were missing an env var
- Azure used to be invoked as `yarn rw setup auth azureActiveDirectory`. Since we keep redirects around for the other setup commands, may as well keep this one around as an alias, though the official help will still show `azure-active-directory`
> fix(CLI): add env var to Supabase notes, Azure alias

- packages/cli/src/commands/setup/auth/auth.js
This PR enables setting up SuperTokens auth by running `yarn rw setup auth supertokens`
> Enable yarn rw setup auth supertokens

- docs/docs/tutorial/chapter3/saving-data.md
- docs/docs/tutorial/chapter6/comments-schema.md
- docs/versioned_docs/version-4.0/tutorial/chapter3/saving-data.md
- docs/versioned_docs/version-4.0/tutorial/chapter6/comments-schema.md
Add groupId to all `<Tabs>` to make language selection sync between tab groups.
> Docs: Add missing groupId to <Tabs>

- packages/cli-helpers/src/auth/__tests__/authTasks.test.ts
- packages/cli-helpers/src/auth/authTasks.ts
Fixes https://github.com/redwoodjs/redwood/issues/7537. I've confirmed this works locally, but not sure if this's the best way to do it. @Tobbe you know more about RegExps, what do you think? We could also move the logic to the line that's actually failing:
https://github.com/redwoodjs/redwood/blob/c6a31f1da3329538ad94cd5a1847bbb780162898/packages/cli-helpers/src/auth/authTasks.ts#L226-L228
> fix(auth): handle CRLFs in `yarn rw setup auth`

- packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
Following up from the [issue here ](https://github.com/redwoodjs/redwood/issues/7597#issuecomment-1424054130) where the default `flightcontrol.json` no longer works after upgrading to RedwoodJS 4. Seems like the `buildType: 'nixpacks'` option was removed in [this PR](https://github.com/redwoodjs/redwood/pull/6941) (unsure why it was - seems the [issue](https://github.com/redwoodjs/redwood/issues/6927) it was solving only needed the `postBuildCommand` be removed.
Regardless, after discussing with the Flightcontrol team, we needed to get that added back for builds to work such that the node version would be respected and not fail on the null coalescing operator that was only introduced in node 15.
tl;dr - Closes #7597
> Add back `buildType: nixpacks` per Flightcontrol request

- packages/auth-providers/clerk/setup/src/templates/web/auth.tsx.template
- packages/auth-providers/clerk/web/src/clerk.tsx
- packages/auth/src/AuthImplementation.ts
- packages/auth/src/AuthProvider/useReauthenticate.ts
Alternative solution to https://github.com/redwoodjs/redwood/pull/7602
> Check if client has loaded before saying that loading is finished

- packages/vite/src/index.ts
Based on user feedback. This PR does two things:
The vite plugin now respects the host specified in `redwood.toml`. Note that when we specify the host to be `0.0.0.0` vite will still _print_ that its running on localhost but actually listen on all hosts, as per this doc: https://vitejs.dev/config/server-options.html#server-host
If you want to generate sourcemaps for production, this is now respected. The key changes here were
a) Passing through the sourceMap option from `redwood.toml` through to Vite's build settings
b) Making sure any custom transforms, in this case the html transformer (bundle injection), preserves the original sourcemap. 
The information on this was a little hard to find, but is in the rollup documentation: https://rollupjs.org/plugin-development/#transform
> If the …
> fix(vite): Respect `host`, `sourceMap` settings in redwood.toml on vite dev server

- packages/telemetry/src/sendTelemetry.ts
**Problem**
1. Calling `getConfig` which is needed to test for the web bundler option breaks telemetry when it is run for create-redwood-app. 
2. The telemetry ID cache file was not being created when running create-redwood-app.
**Changes**
1. Default to `webpack` for crwa telemetry and call `getConfig` for any other case.
3. Create the `.redwood` directory if it does not exist when trying to write the telemetry cache file.
**Ping**
@jtoar, @thedavidprice - the fix.
@dac09 - I tested and this still sends the `vite` bundler option when I enabled it on a new project. If suddenly the data stops let me know in case I've broken it in a more subtle way.
> fix(telemetry): Avoid getConfig for CRWA

- docs/docs/cors.md
Follow up from #7624 
Docs haven't yet been updated to reflect the changes for Redwood 4. This PR updates the docs wrt to the fix.
> Update CORS docs to reflect Redwood 4 changes

- packages/create-redwood-app/template/api/tsconfig.json
- packages/create-redwood-app/template/web/tsconfig.json
See comment from Orta here: https://github.com/redwoodjs/redwood/pull/7499#issuecomment-1428634775
**For Release Notes:**
In v4.1 we shipped with `skipLibCheck: true` in the template. If you created a new project in the last week, we recommend that you change this setting back to false in your `web/tsconfig.json` and `api/tsconfig.json`.
```diff
{
"compilerOptions": {
"noEmit": true,
-    "skipLibCheck": true,
+    "skipLibCheck": false,	
```
Alternatively you can just run`yarn rw setup tsconfig --force`, which will replace your existing tsconfigs with the one from the latest template on our repo.
> fix(ts): Undo skipLibCheck change

- packages/internal/src/files.ts
If users want to use JSX in a custom function on the api side, provided they have the babel config, they should be able to. Addresses @chenkie's use case specifically
> feat(api): support building .jsx, .tsx files

- packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
- packages/auth-providers/dbAuth/web/src/webAuthn.ts
Closes https://github.com/redwoodjs/redwood/issues/7637.
There's probably some tests that need updating here.
> fix:(webAuthn) use `globalThis`, not `process.env`

- docs/docs/serverless-functions.md
The api for `useRequireAuth` changed a little bit for RWv4. Updated the docs to reflect that
> Update useRequireAuth docs to v4 auth

- packages/forms/src/index.tsx
When building custom components that you want to be compatible with existing form components it'd be nice to be able to use the same type for `emptyAs`. Right now you have to copy/paste `null | 'undefined' | 0 | ''` and hope it never changes
> Forms: Export EmptyAsValue

- packages/cli/src/commands/setup/ui/libraries/chakra-ui.js
> Version 2 of Chakra UI is only compatible with React 18. If you are still needing to use React 17 or earlier, please use version 1 of Chakra UI.
see also:
- https://chakra-ui.com/getting-started
- https://github.com/redwoodjs/redwood/pull/4992#issuecomment-1235718694
- #5614
> chore(deps): bump setup of Chakra UI to V2

- packages/auth-providers/clerk/setup/src/templates/api/lib/auth.ts.template
The [privateMetadata property](https://clerk.dev/docs/users/user-metadata) should not be accessible on the client side. This commit removes this property from the getCurrentUser function returned user object.
> fix(clerk): Remove privateMetadata property from getCurrentUser

- packages/codemods/package.json
- packages/codemods/src/codemods/list.yargs.ts
- packages/codemods/src/codemods/v5.x.x/cellQueryResult/cellQueryResult.yargs.ts
- packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.ts
- packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.yargs.ts
- packages/web/src/components/createCell.test.tsx
- packages/web/src/components/createCell.tsx
- yarn.lock
Fixes https://github.com/redwoodjs/redwood/issues/7538.
Please note that the codemod is just a work in progress and probably won't ship the way it is. It works when I've tired it locally on a project, but needs tests, and more importantly, to not just copy from `@redwoodjs/internal`.
I can't remember the exact details of why we don't import from `@redwoodjs/internal` in the codemods package. It probably had to do with the size of the package, and maybe something with circular dependencies. It's been a while since, so maybe it's ok now and just needs a revisiting.
> [Cells]: Show Success if there's any data in any of the fields

- packages/auth-providers/auth0/web/src/__tests__/auth0.test.tsx
- packages/auth-providers/auth0/web/src/auth0.ts
- packages/auth-providers/azureActiveDirectory/web/src/__tests__/azureActiveDirectory.test.tsx
- packages/auth-providers/azureActiveDirectory/web/src/azureActiveDirectory.ts
- packages/auth-providers/clerk/web/src/__tests__/clerk.test.tsx
- packages/auth-providers/clerk/web/src/clerk.tsx
- packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
- packages/auth-providers/dbAuth/web/src/dbAuth.ts
- packages/auth-providers/firebase/web/src/__tests__/firebase.test.tsx
- packages/auth-providers/firebase/web/src/firebase.ts
- packages/auth-providers/netlify/web/src/__tests__/netlify.test.tsx
- packages/auth-providers/netlify/web/src/netlify.ts
- packages/auth-providers/supabase/web/src/__tests__/supabase.test.tsx
- packages/auth-providers/supabase/web/src/supabase.ts
- packages/auth-providers/supertokens/web/src/__tests__/supertokens.test.tsx
- packages/auth-providers/supertokens/web/src/supertokens.ts
- packages/auth/src/AuthContext.ts
- packages/auth/src/AuthImplementation.ts
- packages/auth/src/AuthProvider/AuthProvider.tsx
- packages/auth/src/AuthProvider/useForgotPassword.ts
- packages/auth/src/AuthProvider/useLogIn.ts
- packages/auth/src/AuthProvider/useLogOut.ts
- packages/auth/src/AuthProvider/useResetPassword.ts
- packages/auth/src/AuthProvider/useSignUp.ts
- packages/auth/src/AuthProvider/useValidateResetToken.ts
- packages/auth/src/__tests__/fixtures/customTestAuth.ts
- packages/auth/src/authFactory.ts
- packages/auth/src/useAuth.ts
- packages/router/src/router-context.tsx
Provide types for the auth method options, like `options` in `logIn(options)` and `signUp(options)`
Users who were previously (probably unknowingly) passing unsupported parameters to `logIn`, `signUp` and a few more methods will now see TS type errors when trying to build their code base, requiring them to fix their code.
> Auth: Add TS types for auth method options

- tasks/smoke-test/tests/prerender.spec.ts
This PR fixes errors like these
Also does this change
Because Replay strips html tags from test names. So when showing a failed test the name won't match the name in our source code, making it difficult to find
> prerender.spec.ts: Fix TS errors

- docs/docs/router.md
Update docs in Router's `private` Set section to include more information and code examples on using roles.
closes https://github.com/redwoodjs/redwood/issues/5997
> docs(roles): Update using roles to limit a private route

- packages/internal/src/build/babelPlugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
Refactor tests
Wrap tests in a `describe`, and break the one test with multiple assertions up into separate tests.
> babel-plugin-redwood-routes-auto-loader.tests.ts: Break up into separate tests

- packages/internal/src/__tests__/nestedPages.test.ts
- packages/structure/src/model/__tests__/model.test.ts
Fixes a few unit test TS errors
> Fix unit test TS errors

- packages/auth-providers/dbAuth/api/package.json
- packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
- packages/auth-providers/dbAuth/setup/package.json
- packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
- packages/auth-providers/dbAuth/web/package.json
- yarn.lock
Combines:
- https://github.com/redwoodjs/redwood/pull/7419
- https://github.com/redwoodjs/redwood/pull/7410
- https://github.com/redwoodjs/redwood/pull/7409
> Upgrade simplewebauthn packages

- packages/auth-providers/clerk/setup/src/templates/web/auth.tsx.template
Our Clerk set up is broken right now. See this topic on the forums for details:
- https://community.redwoodjs.com/t/clerk-the-signup-and-signin-components-cannot-render-when-a-user-is-already-signed-in-unless-the-application-allows-multiple-sessions-since-a-user-is-signed-in-and-this-application-only-allows-a-single-session/4694
This is a fix suggested by the Clerk team. We may iterate on it still, but it's already been broken for some time and I don't want there to be more broken projects.
This doesn't help existing projects. I'm working on a codemod for that.
> fix(Clerk): call reauthenticate before navigating

- docs/docs/webhooks.md
Fixes #7929 and fixes #7930 
**Problem**
Please see the issues linked. There was an outdated third party linked and some of the links to framework code pointed to a fork rather than the main repository.
**Changes**
1. Removed link to `automate.io` - see [article](https://automate.io/blog/closing-down-automate-io/)
2. Switched links from @dthyresson's fork to the main repo
3. Removed a duplicate entry in the `SupportedVerifiers` type union
> fix(docs): Update webhook links

- packages/graphql-server/package.json
- yarn.lock
Fixes https://github.com/Escape-Technologies/graphql-armor/pull/361 which caused some projects to change the value of `costLimit` in their GraphQL handler if they had recursive fragments. thanks @simoncrypta and @c3b5aw!
> chore: bump @escape.tech/graphql-armor to 1.8.1

- packages/vite/bins/rw-vite-dev.mjs
Recent changes to split out internal into project-config broke the RW vite dev handler, with the error:
```
web | file:///Users/dac09/Projects/nodeconf-rw-recipe/node_modules/@redwoodjs/vite/bins/rw-vite-dev.mjs:3
web | import { getPaths } from '@redwoodjs/project-config'
web |          ^^^^^^^^
web | SyntaxError: Named export 'getPaths' not found. The requested module '@redwoodjs/project-config' is a CommonJS module, which may not support all module.exports as named exports.
web | CommonJS modules can always be imported via the default export, for example using:
web | import pkg from '@redwoodjs/project-config';
web | const { getPaths } = pkg;
```
This PR fixes it according to the suggestion in the error
> fix(rw-dev): with vite

- tasks/unpublishPackageVersions.mjs
cc @jtoar 
This is a working script that will unpublish specific, targeted ranges + tags of packages. SAFETY-first built-in ⚠️
We need it (or so we were told) to try and get Core and CLI packages publishing again.
This will only work if and only if:
1. no other packages in the npm Public Registry depend on
2. had less than 300 downloads over the last week
3. has a single owner/maintainer
At this time, I cannot approval to unpublish any packages < 1.0.0. Errors are:
- too many downloads
- dependencies
---
We have now been blocked for
**7.**
**Days.**
🤦‍♂️ 
Current Feels
> chore: unpublish packages script

- packages/cli/src/commands/upgrade.js
fixes #7910
--force is no longer a valid option for yarn install (as of yarn v3)
> fix upgrade.js error message

- .github/workflows/ci.yml
**Problem**
After updating the engine check requirements to a minimum of `16.20` the GitHub ci node version is too low for telemetry checks to run as intended.
**Changes**
Update from `16` to `16.20.0` in the node version.
> chore(ci): Update node version for telemetry check

- packages/prerender/src/runPrerender.tsx
It's "find", not "found" in this case
> Fix spelling mistake in prerender error message

- packages/internal/src/build/babel/web.ts
If you had a cell named like this `MyCell.jsx` the babel transform wouldn't pick it up, because we were only looking for `js` or `tsx` files. 
Just add `jsx` to the list of extensions to match against
> fix(babel-vite): Also transform jsx Cell files

- docs/docs/cli-commands.md
- packages/cli/src/commands/upgrade.js
**Problem**
We want to allow users to select the `next` and `experimental` tags when running `yarn rw upgrade --tag [tag]` but this is currently not allowed.
**Changes**
1. Add `next` and `experimental` to the allowed tags list.
2. Update the docs to reflect the updated tag options.
> chore(cli): Enable 'next' and 'experimental' tags for `rw upgrade`

- packages/cli/src/commands/experimental/studio.js
- packages/cli/src/lib/packages.js
**Problem**
The studio package is not included by default so the CLI command fails to import and start the studio.
**Changes**
1. Automatically install the `@redwoodjs/studio` package if it is not found.
> fix(cli): Install studio package if not found

- packages/create-redwood-app/jsconfig.json
- packages/create-redwood-app/package.json
- yarn.lock
Follow up to https://github.com/redwoodjs/redwood/pull/8043. I thought I moved `@babel/node` to a devDependency there, but must've made a mistake.
> [CRWA] Housekeeping follow up to #8043

- packages/create-redwood-app/src/create-redwood-app.js
Follow up to https://github.com/redwoodjs/redwood/pull/8106. Now we only set a lower limit for the Node.js version (18 LTS). This means that the compatibility checks in `yarn create redwood-app` should go back to failing instead of prompting. We'll warn users about using higher Node.js versions during setup deploy.
> fix(CRWA): make node and yarn compatibility checks fail

- __fixtures__/test-project/package.json
- packages/create-redwood-app/package.json
- packages/create-redwood-app/src/create-redwood-app.js
- packages/create-redwood-app/template/package.json
- packages/tui/src/index.ts
- yarn.lock
This makes handling the case where a node or yarn version is lower than the wanted version different than if it's higher.
> fix(CRWA): handle node version compat check failures

- packages/codemods/src/codemods/v5.x.x/checkReactRoot/checkReactRoot.ts
- packages/codemods/src/codemods/v5.x.x/checkReactRoot/checkReactRoot.yargs.ts
- packages/codemods/src/codemods/v5.x.x/updateNodeEngines/README.md
- packages/codemods/src/codemods/v5.x.x/updateNodeEngines/updateNodeEngines.ts
- packages/codemods/src/codemods/v5.x.x/updateNodeEngines/updateNodeEngines.yargs.ts
This PR updates the check-react-root codemod to also update the version of react dependnecies in web/package.json and run yarn install. It also adds an update-node-engines codemod that updates the value of engines.node in a package.json to the new v5 value.
> fix(codemods): make react do install, add update node engines

- packages/auth-providers/firebase/api/package.json
- yarn.lock
This PR reverts the firebase admin upgrades (from v10.x to v11.x) in https://github.com/redwoodjs/redwood/pull/7523 and https://github.com/redwoodjs/redwood/pull/8029. They were never working properly and I didn't have time to debug during this RC cycle. We'll open them again and queue them up for the next major cycle.
> fix(v5): revert firebase admin v11 upgrades

- packages/cli/src/commands/setup/deploy/providers/flightcontrol.js
See:
- https://github.com/redwoodjs/redwood/issues/7557
- https://community.redwoodjs.com/t/setup-deploy-flightcontrol-broke-web-api-communication/4825/4
There's no downside to this change with the likely outcome that local dev experience will improve.
> fix: Flightcontrol setup improve SameSite config

- packages/api-server/package.json
- packages/graphql-server/package.json
- packages/studio/package.json
- packages/vite/package.json
- yarn.lock
The latest deploys of deploy target CI caught some packages that were using project-config but not listing it as a dependency.
> fix: list project-config as a dependency in api-server, graphql-server, studio, vite

- packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
Deploy target CI is down for Netlify and Vercel with the error:
```
Error: Could not find a "redwood.toml" file, are you sure you're in a Redwood project?
at getConfigPath (/var/task/node_modules/@redwoodjs/project-config/dist/configPath.js:20:11)
at getConfig (/var/task/node_modules/@redwoodjs/project-config/dist/config.js:91:63)
at Object.posts (/var/task/node_modules/@redwoodjs/graphql-server/dist/makeMergedSchema/makeMergedSchema.js:69:44)
at useRedwoodDirectiveValidatorResolver (/var/task/node_modules/@redwoodjs/graphql-server/dist/plugins/useRedwoodDirective.js:108:22)
at field.resolve (/var/task/node_modules/@envelop/on-resolve/cjs/index.js:33:48)
at async field.resolve (/var/task/node_modules/@envelop/on-resolve/cjs/index.js:33:42)
at async field.resolve …
```
> fix(deploy): try-catch attempt to read `redwood.toml` in `makeMergedSchema`

- docs/docs/auth/supabase.md
- docs/versioned_docs/version-5.0/auth/supabase.md
At some point during the upgrade of the Supabase SDK to v2 (just released in v5) the `authenticationMethod` prop must've been renamed to `authMethod` but we just forgot to update the docs to go along with it.
> fix(docs): rename authenticationMethod to authMethod

- __fixtures__/test-project/README.md
- __fixtures__/test-project/package.json
- __fixtures__/test-project/web/package.json
- packages/web/src/__typetests__/cellProps.test.tsx
- packages/web/src/components/createCell.tsx
Fixes https://github.com/redwoodjs/redwood/pull/7024#issuecomment-1528877742. @Tobbe works in VS Code with `yarn rwfw` going, but do you think it's this simple?
> fix(v5): type `queryResult` in Cells

- packages/codemods/src/codemods/v5.x.x/detectEmptyCells/detectEmptyCells.ts
Users with Cells that have fragments in their query like:
```js
export const QUERY = gql`
${MY_FRAGMENT}
query MyQuery($id: Int!) {
post(id: $id) {
...MyFragment
}
}
`
```
Will get the following unhelpful output from the `detect-empty-cells` codemod:
```
$ npx @redwoodjs/codemods@canary detect-empty-cells
✖ Detecting Cells susceptible to the new Empty behavior
→ Failed to detect cells susceptible to the new Empty behavior in your project 
Syntax Error: Unexpected <EOF>.
```
Fixing the functions used to parse the Cell query is a bit non-trivial at the moment, so in the meantime we can handle the error and tell the user to manually audit the Cell so that other Cells are still processed:
> fix(v5 codemod): handle errors in cell query parsing

- packages/create-redwood-app/package.json
- packages/create-redwood-app/src/create-redwood-app.js
- packages/create-redwood-app/src/telemetry.js
- yarn.lock
Create the UID at install time and report it within CRWA telemetry.
Ping: @jtoar as discussed with @thedavidprice
> chore(cli): Create and report UID

- packages/project-config/src/__tests__/paths.test.ts
Looks like we forgot to increment the number of pages found in a test after adding a page in https://github.com/redwoodjs/redwood/pull/8178, but this test doesn't seem to fail in PRs, only in CI that runs against main—in actions like publish canary (see https://github.com/redwoodjs/redwood/actions/runs/4856408246/jobs/8655938165#step:8:66).
> chore(tests): increment pages found in path test

- packages/create-redwood-app/src/create-redwood-app.js
Fixes #8224 
**Problem**
When using some terminals the "zero width space" is included in the URL link and causes a 404 when trying to access the link.
**Solution**
As per https://github.com/sindresorhus/terminal-link/issues/18 the solution is to add a fallback with the text formatted as we'd like it to be presented.
Using Hyper the output looks like:
FYI: I did try `text (url)` but it picked up the `)` in the url.
> fix(crwa): Prevent links including "zero width space" in URL

- docs/docs/cells.md
- docs/docs/typescript/utility-types.md
This PR updates of some sections of the docs that should've been updated for v5 related to the Cell's new `queryResult` prop; thanks for flagging this @KrisCoulson!
> fix(v5 docs): update Cells, utility types

- docs/versioned_docs/version-5.0/cells.md
- docs/versioned_docs/version-5.0/how-to/build-dashboards-fast-with-tremor.md
- docs/versioned_docs/version-5.0/typescript/utility-types.md
This PR backports the docs fixes in https://github.com/redwoodjs/redwood/pull/8235 to v5 so that they go live now instead of in the next minor, and adds https://github.com/redwoodjs/redwood/pull/8206 because there's nothing v5.1 specific about it and it may as well go live sooner than later.
> chore(docs): reversion docs for cell, type fixes

- docs/docs/tutorial/chapter4/authentication.md
Hi,
I am sending a fix for a _dbauth_ `signup.handler()` link in chapter 4 of the tutorial.
> Docs: Fix link to the dbauth signup.handler()

- packages/cli/src/commands/setup/deploy/templates/serverless/api.js
- packages/cli/src/commands/setup/deploy/templates/serverless/web.js
The Serverless deploy setup yaml files contained 2 deprecations and were using Node.js v14. This removes deprecations and updates Node.js to v18.
Note: this does not fully resolve issues with Serverless deploy. See https://github.com/redwoodjs/deploy-target-ci/issues/826
> fix: serverless deploy template node version and deprecations

- packages/create-redwood-app/src/create-redwood-app.js
Closes https://github.com/redwoodjs/redwood/issues/8164. For whatever reason, esbuild's postinstall script seems to complete when yarn's `nodeLinker` is `'node-modules'`. I didn't realize till just now that you could use env vars to configure yarn. I tried it locally and it actually works! Going to merge this in and test in canary.
> fix: set node linker to node_modules

- docs/versioned_docs/version-5.0/how-to/build-dashboards-fast-with-tremor.md
- docs/versioned_docs/version-5.0/tutorial/chapter4/authentication.md
Backports changes in https://github.com/redwoodjs/redwood/pull/8252 and https://github.com/redwoodjs/redwood/pull/8243 to v5 docs.
> chore(docs): backport recent fixes to v5

- packages/tui/src/index.ts
**Problem**
In non-tty environments like CI the TUI reactive components don't overwrite themselves and instead produce a bazillion lines.
**Changes**
1. For non-tty only draw the reactive component once at the start and once at the end.
> chore(tui): Avoid reactive drawing for non-tty

- __fixtures__/test-project/api/tsconfig.json
- __fixtures__/test-project/scripts/tsconfig.json
- __fixtures__/test-project/web/tsconfig.json
- tasks/test-project/tasks.js
- tasks/test-project/test-project
These changes are needed to make `yarn build:test-project --rebuildFixture` work after https://github.com/redwoodjs/redwood/pull/8191 was merged.
`yarn build:test-project --no-ts ~/tmp/rw-js-test-project` still doesn't work. It'll give you a TS project
> Fix --rebuildFixture

- packages/vite/package.json
- packages/vite/src/index.ts
- yarn.lock
Fixes https://community.redwoodjs.com/t/redwood-v5-0-0-upgrade-guide/4715/23.
> fix(vite): import default from `vite-plugin-commonjs`

- tasks/test-project/tasks.js
- tasks/test-project/test-project
Reverts most of the changes in #8273. When only supporting TS test project generation a lot of the complexity isn't needed anymore. 
So the main points of interest here are now:
* Always pass `--typescript` to CRWA (never `--typescript false`)
* Keep updated path to templates/ts/package.json from #8273
> Only support TS test projects

- packages/cli/src/commands/experimental/setupOpentelemetry.js
- packages/cli/src/commands/experimental/studio.js
In #8268 I forgot to add the epilogues to the builders, this corrects that.
> chore(cli): Add builder epilogue to experimental commands

- packages/core/config/webpack.development.js
Fixes https://community.redwoodjs.com/t/tutorial-email-server-validation-shows-a-runtime-error-coming-from-apollo/4883.
The issue has nothing to do with `@apollo/client`; it's `webpack-dev-server` v4.15.0 which added and enabled the `runtimeErrors` overlay which interferes with our form error handling.
See:
- https://github.com/redwoodjs/redwood/pull/8245
- https://github.com/webpack/webpack-dev-server/pull/4849
- https://github.com/webpack/webpack.js.org/commit/5873fcc08126bc60e83b3d0fb0d02e62d891f8e7
> fix(forms): disable webpack-dev-server overlay

- packages/cli/src/commands/upgrade.js
Late follow-up to https://github.com/redwoodjs/redwood/pull/7529, this PR removes the heads-up message about upgrading React to 18 in a project's web-side package.json.
> fix(cli): remove react 17/18 warning from canary upgrade

- packages/cli/package.json
- yarn.lock
> **Note**
>
> This is only in canary and doesn't require releasing a patch.
If you upgrade to `6.0.0-canary.168` canary and run `yarn rw dev` you'll get:
```
api | node:internal/modules/cjs/loader:1078
api |   throw err;
api |   ^
api | 
api | Error: Cannot find module '@redwoodjs/api-server/package.json'
api | Require stack:
api | - /Users/dom/prjcts/redwood/redwood-app/node_modules/@redwoodjs/core/dist/bins/rw-log-formatter.js
api |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
api |     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
api |     at Object.<anonymous> (/Users/dom/prjcts/redwood/redwood-app/node_modules/@redwoodjs/core/dist/bins/rw-log-formatter.js:5:65)
api |     at Module._compile (node:internal/modules/cjs/loader:1254:14)
api …
```
> fix(canary): add back api server for yarn rw dev

- docs/docs/deploy/coherence.md
- packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
A few small fixes for Coherence in v5.2.0. The doc change is the more important one and can be fixed without a patch. Made the links placeholders; waiting to hear back for the right ones.
> fix(coherence): correct doc links, add commas to template

- packages/cli/src/commands/setup/deploy/providers/coherenceHandler.js
cc @zach-withcoherence. We didn't catch this before since GCP health checks work different from AWS
> fix(coherence): fix health check path

- packages/cli/src/commands/setup/tsconfig/tsconfigHandler.js
This modifies the template path of tsconfig used during `yarn rw setup tsconfig` from:
- `https://raw.githubusercontent.com/redwoodjs/redwood/v5.2.2/packages/create-redwood-app/template/web|api/tsconfig.json`
to
- `https://raw.githubusercontent.com/redwoodjs/redwood/v5.2.2/packages/create-redwood-app/templates/ts/web|api/tsconfig.json`
This change is necessary after the CRAW template was split into separate directories.
> fix(cli) setup tsconfig update template path

- docs/docs/cli-commands.md
- packages/api-server/src/cliHandlers.ts
- packages/api-server/src/watch.ts
- packages/cli/src/commands/serve.js
#8385 introduced the `--host` option, with a `-h` alias. `-h` is probably best reserved for `--help`, so I'm removing it after discussing with @jtoar. 
Also updated the formatting of the docs for `--host` so that the table cells line up in the markdown source.
> Reserve h for help, and format docs

- packages/cli/src/commands/experimental/templates/server.ts.template
With the last PR merged for realtime, I forgot to clean up the server file template so a few bits that are not needed unfortunately snuck in.
This removes:
* Operation node types not needed
* some live query comments
* whitespacing
> chore: Cleans up server template for realtime

- packages/cli/src/plugin.js
- packages/create-redwood-app/templates/js/.redwood/command-cache.json
- packages/create-redwood-app/templates/ts/.redwood/command-cache.json
Alternative to #8491. The loading logic had not considered built-in commands. This also address the `MODULE_NOT_FOUND` issue.
[Screencast from 2023-06-02 13-47-49.webm](https://github.com/redwoodjs/redwood/assets/56300765/c007228f-89de-4dbf-9481-315a4b2baf66)
**Changes**:
* Provide a list of built in commands which require no plugin loading.
* Rework plugin module loading/install so that we check first if it's installed then load. Rather than attempt to load and catch the module not found exception.
> fix(cli): Fix plugin loading logic for built-in commands

- docs/docs/tutorial/chapter2/routing-params.md
The Success Component now returns a JSX Element instead of a string, which leads to an Error in the ArticlePage. Instead of return JSON.stringify(article) it is now return <div>{JSON.stringify(article)}</div> . With this change we don't get any error in the ArticlePage, where we use the ArticleCell
> Fix: return a jsx elemnet instead of string

- .github/actions/actionsLib.mjs
- .github/workflows/ci.yml
- __fixtures__/test-project/web/package.json
https://github.com/redwoodjs/redwood/pull/8471 added a new binary to a redwoodjs package. Our current tooling (`yarn rwfw project:deps, copy sync`) alone doesn't handle this use case. Instead we need the package with the binary to be installed, so I'm bumping `@redwoodjs/vite` to canary to see if it fixes it. If it does, I'll have to add a step to rebuilding the test project to persist this fix till we release the next major.
> chore(ci): use canary version of rwjs vite

- packages/cli-packages/storybook/build.mjs
- packages/cli-packages/storybook/package.json
- packages/cli-packages/storybook/src/commands/storybook.ts
- packages/cli-packages/storybook/src/commands/storybookHandler.ts
- yarn.lock
@Josh-Walker-GM here's a small set of changes to the cli-storybook package after our discussion earlier. I think the types could still be better, or at least I could be more confident in them, but what's in this PR is probably better than before. Most of this PR is just style changes though, and I thought I'd get those out of the way before we start moving other commands over.
I took a small crack at adding dependency cruiser, and adding it to every package.json seems like overkill, so I'm going to try making that into a script in `tasks/`.
Style changes:
- spaces between related config options in build.mjs
- functions over arrow functions in command module
- sorted the package.json
> chore(cli-storybook): improve types, style changes

- docs/docs/services.md
Extra whitespace breaks info admonition:
> fix(docs): Remove whitespace in `services.md`

- packages/internal/src/__tests__/__snapshots__/graphqlCodeGen.test.ts.snap
- packages/internal/src/generate/graphqlCodeGen.ts
There isn't a file at `@redwoodjs/graphql-server/dist/functions/types` as the type got merged  into the dist dir at some point
> Fix the codegen path for the GraphQL context object

- packages/internal/package.json
- yarn.lock
Switch my app to run entirely from this lib via Redwood proper now
https://github.com/sdl-codegen/sdl-codegen/blob/main/CHANGELOG.md#0010
- Uses user-app prettier settings to format .d.ts files
- Doesn't ship with any eslint warnings in my codebase at least
- Includes SDL version of #8585
> feat: Update the SDL types lib

- __fixtures__/test-project/api/server.config.js
- docs/docs/app-configuration-redwood-toml.md
- packages/api-server/src/fastify.ts
- packages/api-server/src/server.ts
- packages/cli/src/commands/serveHandler.js
- packages/create-redwood-app/templates/js/api/server.config.js
- packages/create-redwood-app/templates/ts/api/server.config.js
- packages/fastify/src/config.ts
The default experience of `yarn dev` lets you know a bunch of stuff you don't really care about WRT fastify (e.g. I've never once cared about what plugins are installed, but it fills my terminal) 
This moves them all (and the templated files) to use trace so that they are opt-in when you want to know about those sort of internal details - pairs with #8588
> Move fastify.logger.infos to fastify.logger.traces

- tasks/framework-tools/frameworkDepsToProject.mjs
- tasks/framework-tools/frameworkFilesToProject.mjs
- tasks/framework-tools/frameworkSyncToProject.mjs
- tasks/framework-tools/lib/framework.mjs
- tasks/framework-tools/lib/project.mjs
When I clean the framework (`git clean -fxd -e .env`) so that build has to happen from scratch instead of pulling from the Nx cache, I can reproduce `yarn rwfw project:sync` failing with:
```
rwfw  /<path>/redwood/packages/cli-packages/storybook/meta.json
node:fs:601
handleErrorFromBinding(ctx);
^
Error: ENOENT: no such file or directory, open '/<path>/redwood/packages/cli-packages/package.json'
at Object.openSync (node:fs:601:3)
at Object.readFileSync (node:fs:469:35)
at packageJsonName (file:///<path>/redwood/tasks/framework-tools/lib/framework.mjs:146:24)
at FSWatcher.<anonymous> (file:///<path>/redwood/tasks/framework-tools/frameworkSyncToProject.mjs:100:25)
at FSWatcher.emit (node:events:513:28)
at FSWatcher.emitWithAll (/<path>/redwood/node_modules/chokidar/index.js:541:32)
at …
```
> chore(rwfw): working refactor, make `project:sync` ignore more files

- .github/workflows/ci.yml
- package.json
- tasks/smoke-tests/basePlaywright.config.ts
- yarn.lock
After my change to split up the smoke tests into their own steps, which required using Playwright's built-in way of starting dev servers (I detailed all of it here: https://github.com/redwoodjs/redwood/pull/8449), I forgot to follow up with a change to its reporter so that we could see each dev servers' output. Here it is.
-- snip --
> chore(ci): use the line reporter for now

- packages/cli/src/commands/setup/vite/viteHandler.js
Fixes bug in setup handler, as per comment here: https://github.com/redwoodjs/redwood/pull/8592#discussion_r1228986793
> fix(vite): Do not use getPaths in vite setup handler

- tasks/release/releaseCommand.mjs
I was looking at the contents of `@redwoodjs/tui`'s dist, and most of the files are only a few kilobytes. But one, `tsconfig.tsbuildinfo`, is ~75 kilobytes—several times larger than the rest of the files combined. It's still not that big in the scheme of things (i.e. compared to most dependencies), but it struck as me being completely unnecessary since this file is for speeding up TypeScript's build's step (source: https://www.typescriptlang.org/tsconfig#tsBuildInfoFile).
Source: https://www.npmjs.com/package/@redwoodjs/tui?activeTab=code
Since this file is to make incremental builds with TS faster, we can't just delete it after we build packages. But we can delete it before we publish, so that's what this PR does.
> fix(publishing): remove tsconfig.tsbuildinfo

- packages/eslint-plugin/src/__tests__/process-env-computed.test.ts
- packages/eslint-plugin/src/process-env-computed.ts
As title, just changes the error message.
> chore(lint): Humanise eslint error for accessing process.env

- packages/core/config/webpack.common.js
- packages/prerender/ambient.d.ts
- packages/prerender/src/internal.ts
- packages/vite/src/index.ts
- packages/web/ambient.d.ts
- packages/web/src/global.web-auto-imports.ts
Leftovers from migrating to Vite. We ended up not using/needing this
> Remove unused global var RWJS_WEB_BUNDLER

- tasks/test-project/rebuild-test-project-fixture.js
Start by printing the tmp dir so it's easy to find if rebuilding fails and you want to resume.
Also does a few other minor tweaks to the output
> rebuild-test-project-fixture: Print tmp dir and other output tweaks

- packages/internal/src/webpackPlugins/ChunkReferencesPlugin.ts
`name` is sometimes `undefined`, and that's correct and works as expected.
See https://github.com/redwoodjs/redwood/pull/8549 for more context
> ChunkReferencesPlugin: Update types in webpack plugin

- packages/codemods/src/codemods/v0.50.x/updateDevFatalErrorPage/updateDevFatalErrorPage.ts
Codemod for upgrading to v5 should use v5 version of the DevFatalErrorPage file
> Fix failing v5 codemod for DevFatalErrorPage

- packages/auth-providers/clerk/api/src/decoder.ts
Just wanted to get rid of this warning on all PRs
> Clerk decoder: Fix code format

- __fixtures__/test-project/scripts/seed.ts
- packages/create-redwood-app/templates/js/scripts/seed.js
- packages/create-redwood-app/templates/ts/scripts/seed.ts
I uncommented those lines (41-58 in `seed.ts`) as I wanted to create some users in my seeder and it didn't work as expected. After inserting that `const` before `user`, everything worked according to plan. It's also according to the `for...of` [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#try_it) as far as I know.
Perhaps it would have been fine in old school javascript or in coffeescript, but I don't think y'all are aiming for that 😊
> fix: Insert const in for...of loop

- packages/internal/src/build/web.ts
To me it looks like this comment is not true anymore. The `buildWeb` function is used from `rw-vite-build` which is invoked when you run `yarn rw build`
It's silly how minor this PR is. But I wanted to get @dac09's eyes on it, to make sure I'm not misunderstanding something
> chore(vite) Remove invalid comment

- packages/cli/src/commands/__tests__/dev.test.js
- packages/cli/src/commands/buildHandler.js
- packages/cli/src/commands/devHandler.js
- packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts
- packages/prerender/src/runPrerender.tsx
Vite should be the default. So the only way to use webpack should be to have `bundler === 'webpack'`. As soon as `bundler !== 'webpack'` we use vite
> Use vite unless bundler === webpack

- packages/cli/src/commands/setup/vite/viteHandler.js
Because Vite is now the default this message wasn't exactly right in that Vite is also set as the bundler if no flag exists in redwood.toml. So I updated the messaging a bit
The above was the main thing. But then I also noticed this
I changed that to be in line with how we do it in the tutorial 
Here's the final output
> Tweak vite setup output

- __fixtures__/test-project/redwood.toml
- packages/create-redwood-app/templates/js/redwood.toml
- packages/create-redwood-app/templates/ts/redwood.toml
I always get insecure about the array syntax in the toml for listing env vars. Like, am I allowed to have newlines?
Hopefully adding the comments on new lines inside the array makes it clear that you're allowed to do that.
Ideally I'd like the comment to say: 
> Add ENV_VARs each on their own line. Quote the variable name and end the line with a comma (,). Like this:
>  'EXAMPLE_VAR_ONE',
>  'EXAMPLE_VAR_TWO',
I figured that was too long, but happy to take suggestions on how to further improve the wording in the PR
> DX: Tweak comments in redwood.toml

- packages/cli/src/commands/setup/vite/vite.js
Vite support is no longer (as of v6) experimental, so removing notice in help text
> Setup vite: No longer experimental

- packages/cli/src/commands/experimental/templates/server.ts.template
When testing out the server file setup on an existing RedwoodJS project with auth, we forgot to setup the same auth used in the graphql handler function in the server file graphql options.
And of course -- authentication didn't work.
This PR simply adds some comment for the moment to remind the user and call out that if they use auth to import their decoder and getCurrentUser function and include in the options.
> chore: Remind to setup auth in server file GraphQL configuration

- packages/vite/package.json
- packages/vite/tsconfig.json
- packages/vite/vite-plugin-commonjs.d.ts
- yarn.lock
Removes vite-plugin-commonjs which is now unused since https://github.com/redwoodjs/redwood/pull/8648
> chore(vite): Remove unused vite-plugin-commonjs

- packages/create-redwood-app/src/create-redwood-app.js
**Problem**
On creation the UID was not set and was being returned as "" for the next 24 hours.
**Changes**
1. Corrects incorrect file io. 
**Notes**
@thedavidprice Corrects the issue you have detected.
> chore(crwa): Fix blank UID on project creation

- packages/cli/src/lib/background.js
- packages/cli/src/lib/updateCheck.js
**Description**
I recently added a helper for when we need to run background tasks. The aim was to ensure consistent use of spawn options (as they are quite cryptic) and to introduce consistency of the logging for the background processes.
**Changes**
1. The background task used to check for redwood updates now uses the background process helper.
* Output is now found in logs within `.redwood/logs`
* The process now has relatively verbose output to aid in debugging if it breaks in the future. 
2. The background process helper now writes some metadata at the head of the log files it creates for the process. This is introduced to ensure relevant data is available should we need to debug the background processes. It looks like so:
```
Starting log:
- Time: 2023-06-28T15:23:03.386Z
- Name: …
```
> chore(cli): Update checker background process logging improvement

- packages/web/src/apollo/index.tsx
This is a follow up to https://github.com/redwoodjs/redwood/pull/8500.
When I was trying to release that PR, I had a discussion with @thedavidprice about the name of the prop, `linkFactory`. After coming up with a few names, we decided to just break `link` instead. The reasons were...
- the major is coming up
- if the major was very far away, we probably wouldn't break it, but the RC is more-or-less imminent 
- the users of link aren't many (just my guess), and of those who use it, they'd probably prefer this API to the previous one, which was cumbersome
This PR also includes several stylistic changes to the `web/src/apollo/index.tsx` file, mainly around comments (changing some `/** ... */` comments to `//`), and around the name of types, preferring longer but more descriptive types.
> chore(apollo): make previous Apollo Link change breaking

- docs/docs/cli-commands.md
- packages/api-server/src/cliHandlers.ts
- packages/api-server/src/server.ts
- packages/api-server/src/watch.ts
- packages/cli/src/commands/__tests__/dev.test.js
- packages/cli/src/commands/__tests__/serve.test.js
- packages/cli/src/commands/devHandler.js
- packages/cli/src/commands/serve.js
- packages/cli/src/commands/serveHandler.js
- packages/core/config/webpack.development.js
This PR reverts the following three PRs that we've decided to save for the next next major (v7):
- https://github.com/redwoodjs/redwood/pull/8019
- https://github.com/redwoodjs/redwood/pull/8385
- https://github.com/redwoodjs/redwood/pull/8407
After the v6 RC branch is cut, we can revert this PR.
> chore(v6): temporarily revert host-related changes

- docs/docs/cli-commands.md
- docs/docs/custom-web-index.md
- packages/cli/src/commands/setup/custom-web-index/custom-web-index-handler.js
- packages/cli/src/commands/setup/custom-web-index/custom-web-index.js
In v6, the docs and command for the custom web index only apply to webpack projects.
> fix(v6): specify that the custom web index webpack only

- packages/eslint-config/index.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/__tests__/unsupported-route-components.test.ts
- packages/eslint-plugin/src/index.ts
- packages/eslint-plugin/src/unsupported-route-components.ts
- yarn.lock
Our router file officially really only supports `<Router>`, `<Route>`, `<Set>` and `<Private>` elements.
Unofficially you've been able to use other things, like `<div>` and stuff in certain places. But with the new Suspense enabled router we're introducing that's not going to be possible anymore.
So this is an eslint rule that for now only warns on unsupported elements. But when the new router is released we can change that to show an error instead of a warning
> eslint rule: unsupported-route-components

- packages/eslint-plugin/src/unsupported-route-components.ts
Follow up to https://github.com/redwoodjs/redwood/pull/8774. For v6, we want this rule to error.
> Make unsupported route components rule error for v6

- packages/eslint-config/index.js
Our new `unsupported-route-components` rule only really needs to be enabled for the Routes file
Fixes https://github.com/redwoodjs/redwood/issues/8792
> Only enable new eslint rule for the Routes file

- packages/vite/src/utils.ts
Fixes this warning that shows up in all PRs
> vite utils.ts: fix source format

- docs/docs/storybook.md
Follow up to https://github.com/redwoodjs/redwood/pull/8342. Storybook removed the ability to configure the manager (see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-configuration-for-manager). Let's remove this section from the docs as it's no longer true: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-more-configuration-for-manager
> fix(docs): remove the section on configuring Storybook's manager

- packages/structure/package.json
- packages/structure/src/x/ts-morph.ts
- yarn.lock
The lru-cache package version seems to be upgraded when running `project:copy`, causing issues for `@redwoodjs/structure`. This PR upgrades to v7 which lets us update the syntax we use when calling the `LRU()` constructor to be compatible with the version of lru we get by running `project:copy`
Fixes https://github.com/redwoodjs/redwood/issues/8734
> structure: Update lru-cache to v7 to minimize project:copy issues

- packages/cli/src/commands/buildHandler.js
In v6 having no bundler configured means you're using Vite, and should not need to clean web before building. Only when the bundler is explicitly set to 'webpack' should this task be executed.
This change also makes it easier to find this code later, when we need to remove all Webpack related code.
> "Cleaning web" is only needed for Webpack

- packages/cli/src/commands/buildHandler.js
- packages/vite/bins/rw-vite-build.mjs
- packages/vite/src/index.ts
Both existing vite build process and the new one for streaming/ssr needs `process.chdir` to be set for postcss/tw etc. So reusing the existing one here for new Streaming/SSR function call as well
> Use existing rw-vite-build bin for SSR as well

- packages/project-config/src/__tests__/paths.test.ts
- packages/project-config/src/paths.ts
- packages/vite/src/buildFeServer.ts
- packages/vite/src/devFeServer.ts
- packages/vite/src/runFeServer.ts
Update error messages to use "entry.server" and "entry.client" (dot (.) instead of dash (-))
Include the entry.server dist location in web paths, like all other paths we use in the dist folder
> entry.server and entry.client

- packages/cli/src/lib/__tests__/locking.test.js
- packages/cli/src/lib/__tests__/updateCheck.test.js
- packages/cli/src/lib/locking.js
- packages/cli/src/lib/updateCheck.js
**Problem**
@Tobbe highlighted a case where the update available message would trigger more than once and would result in output like so:
This was happening because some commands were spawning child commands which would show the message too. Adding a lock to make all processes aware an update message is pending fixes this.
**How to reproduce**
1. Delete `./redwood/updateCheck/data.json` to ensure an update check will be triggered.
2. Run some simple command like `yarn rw info` to trigger an update check.
3. Wait a few seconds to ensure the background update check has completed.
4. Run a command which spawns child commands like `yarn rw build web` which will spawn a prerender command. 
5. Observe the duplicate messages.
**Changes**
1. A lock is used to make any spawned process aware that …
> fix(cli): Prevent multiple update available messages

- packages/cli/src/commands/serve.js
- packages/vite/src/devFeServer.ts
- packages/vite/src/runFeServer.ts
Make it possible to run the new Streaming SSR FE server by running `yarn rw build && yarn rw serve` or `yarn rw dev`
> Streaming SSR: Fix build, serve and dev

- tasks/smoke-tests/common.ts
Made our dev and serve smoke tests verify the computed css values for the blue header and the blue header text
When moving to vite and a new frontend server getting CSS right is surprisingly difficult. So just adding a couple of checks here to make sure things don't break in the transition, and that no one accidentally breaks things in the future
> Rudimentary CSS check in our smoke tests

- packages/cli/src/commands/experimental/templates/liveQueries/auctions/auctions.sdl.ts.template
- packages/cli/src/commands/experimental/templates/liveQueries/auctions/auctions.ts.template
- packages/cli/src/commands/experimental/templates/liveQueries/blank/blank.sdl.ts.template
- packages/cli/src/commands/experimental/templates/liveQueries/blank/blank.service.ts.template
- packages/cli/src/commands/experimental/templates/subscriptions/blank/blank.ts.template
- packages/cli/src/commands/experimental/templates/subscriptions/countdown/countdown.ts.template
- packages/cli/src/commands/experimental/templates/subscriptions/newMessage/newMessage.ts.template
- packages/graphql-server/src/index.ts
- packages/graphql-server/src/plugins/useRedwoodDirective.ts
- packages/internal/src/validateSchema.ts
This PR implements validator directives on subscriptions like `@requireAuth` so one may enabled authentication on a Subscription just like one does for Queries and Mutation in RedwoodJS's GraphQL.
It also:
* enables any validator directive on Subscriptions (but not transformer ones)
* checks that subscriptions have the `@skipAuth` or `@requireAuth` directive (as do queries and mutations)
* updates the subscription templates to include `@requireAuth`
For authorization (that it is I can Subscribe to newMessage -- authn -- but not listen to changes to room 227 -- authz -- one can do something like where you check for a user and the room and raise if no access rights:
```ts
const newMessage = {
newMessage: {
subscribe: (
_,
{ roomId },
{
pubSub,
currentUser,
}: { pubSub: …
```
> feat: Support Authentication in Realtime Subscriptions

- packages/vite/src/buildFeServer.ts
- packages/vite/src/runFeServer.ts
Danny initially used dynamic imports with import assertions for a couple of json files.
When I got his code merged for the Streaming SSR feature I rewrote it to regular `fs.readFile` + `JSON.parse` because I couldn't get Jest to understand the import assertions.
For some reason I also renamed `ViteBuildManifest` to just `ViteManifest`. But I now think I like his original name better, so I rename it back again. We have more than one manifest, so it's good to be extra clear about exactly what manifest this is.
> ViteBuildManifest and note about import-attributes

- packages/cli/src/commands/prismaHandler.js
**Problem**
Prisma handles it's own error messaging so we don't want to throw to the top level try catch in that case.
**Changes**
1. Restores the try catch in the handler.
@jtoar - Address the problem you raised. I'm not sure the milestone for this one.
> fix(cli): Revert change to prisma error message

- __fixtures__/test-project/web/package.json
- packages/auth-providers/auth0/web/package.json
- packages/auth-providers/azureActiveDirectory/web/package.json
- packages/auth-providers/clerk/web/package.json
- packages/auth-providers/dbAuth/web/package.json
- packages/auth-providers/firebase/web/package.json
- packages/auth-providers/netlify/web/package.json
- packages/auth-providers/supabase/web/package.json
- packages/auth-providers/supertokens/web/package.json
- packages/auth/package.json
- packages/create-redwood-app/templates/js/web/package.json
- packages/create-redwood-app/templates/ts/web/package.json
- packages/forms/package.json
- packages/prerender/package.json
- packages/router/package.json
- packages/studio/frontend/package.json
- packages/web/package.json
- yarn.lock
For RSC we need to use a canary version of React.
I set the Milestone to 7.0.0, but most likely it shouldn't go out until v8 at the earliest
> React 18.3.0-canary-035a41c4e-20230704

- packages/vite/src/triggerRouteHooks.ts
Just cleaning up some imports. We were already using `import type` for some types. Cleaner to use it for all types 🙂
> Use "import type" for all types

- packages/core/package.json
- packages/internal/package.json
- yarn.lock
We're also using `proposal-class-properties`, so I'm moving that one over from core to internal too
> Fix babel devDeps in internal

- packages/cli/src/commands/experimental/templates/subscriptions/countdown/countdown.ts.template
This PR fixes the issue where: 
* the countdown example actually uses the interval to count down by ... and
*  also has a reasonable count pause
> fix: Fixes and simplifies the Countdown subscription example for Realtime

- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
- packages/vite/src/index.ts
Disabling the legacy mode was the only change needed to be able to keep having this config available for vite when building.
So thanks to this config no changes are needed to `vite.config.ts` in a user's project when trying RSCs
> Update entry.client and disable vite legacy mode

- packages/cli/src/commands/upgrade.js
This is the current `yarn rw upgrade --help` output. Notice how it says we're "< v1.0.0". This isn't true anymore.
After these changes:
> yarn rw upgrade: Not < v1 anymore

- packages/cli/src/commands/upgrade.js
Currently when running `yarn rw upgrade -t canary` we're only upgrading RW package versions.
If other packages that are listed in our create-redwood-app template package.jsons are upgraded the `rw upgrade` command won't catch that. 
So running `yarn rw upgrade -t canary` might not give you the same versions of packages as if you used a canary version of `yarn create redwood-app`.
I remember this being a problem when we upgraded React from v17 to v18.
And now it's a problem again when we've upgraded to a canary version of React.
So now when running `yarn rw upgrade -t canary` the upgrade command will download the `package.json` files from our template and get the versions of packages from in there.
Currently this is only done for canary, but we can (probably/hopefully) enable it for other …
> rw upgrade: Update package versions from template package.json

- packages/cli/src/commands/deploy/__tests__/nftPack.test.js
- packages/cli/src/commands/deploy/packing/nft.js
- packages/cli/src/commands/deploy/serverless.js
The packing/nft helper kind of mixes named exports with default exports and it ends up confusing build tools. It looks like we want named exports, so I just refactored it to that. This was causing `yarn rw deploy serverless --pack-only` to fail in deploy target CI (see https://github.com/redwoodjs/deploy-target-ci/actions/runs/5482609165/jobs/9988107090). Bug was introduced in https://github.com/redwoodjs/redwood/pull/8456.
> fix(v6, serverless): use named exports instead of default

- .github/renovate.json
Follow up to https://github.com/redwoodjs/redwood/pull/8856. Renovate is invaluable but noisy in a few ways; this PR doesn't address all the ways it's noisy, but does address two major ones.
The tradeoff with these kinds of changes is that merging Renovate PRs will be more manual. But honestly it always is right now. I'm always looking at them. The idea that they just automerge isn't true, but I  think we can get there. I need to make changes like this first though.
Nearly always, the first ~ten GitHub notifications are from renovate. And as soon as you dismiss them, they come back because Renovate updates PRs when they're behind main. We should rely on GitHub notifications more for triage, but renovate constantly rebasing PRs makes this difficult. This PR adds the `rebaseWhen: …
> chore(renovate): improve config to reduce noise

- .github/workflows/publish-canary.yml
Trying this to see if I can reliably get the next canary version that will be released in our GH action for canary releases.
If this works, the next step is to update the package.json files in our CRWA templates to include this version of all RW packages.
> chore(gh-actions) Dry-run publish to get next canary version

- packages/create-redwood-app/templates/js/api/package.json
- packages/create-redwood-app/templates/js/package.json
- packages/create-redwood-app/templates/js/web/package.json
- packages/create-redwood-app/templates/ts/api/package.json
- packages/create-redwood-app/templates/ts/package.json
- packages/create-redwood-app/templates/ts/web/package.json
When using the canary version of create-redwood-app we want you to also get the canary version of RW itself.
This PR:
1. Lets me test the theory that you can use `npx create-redwood-app@canary` to get canary versions of RW installed as long as the template package.jsons have the canary version specified
2. Lets me test the GH action update in #8862 
If both those things work, we can move forward with automating this 🤖 
@jtoar I was unsure about what milestone to use. This isn't something that will ever show up in a released version (because we have proper RW release versions like 5.3.1 or 6.0.0 in the CRWA when we do releases). But it also didn't feel right to use the chore milestone, because this is in code that our users get.
As you can see I also went back and forth on the test project …
> CRWA: Manually update rw package versions to v6 canary

- .github/workflows/publish-canary.yml
Remove overly verbose output to make it easier to find the info we need when scanning gh action output
> gh actions: Explain the publish dryrun command

- .github/workflows/publish-canary.yml
The "publish canary" gh action creates a git commit. I wanted to push that commit to the PR, so that it's included in the merge to main. But it's too late to do that when this gh action runs, because the commit is already on main. Also can't just push to main, because main is protected. Also can't make these changes any earlier because it's only now we know what version this will be released as.
> Don't git push. Remove debug logs

- .github/workflows/publish-canary.yml
When running the canary publishing GH action we first do a dry-run to get the version the next canary will get.
We then update all rw package versions in the CRWA templates and commit those changes. That commit will change the version we got from the dry-run because the version is based on the number of commits, which we just changed.
So now we increase the version number from the dry-run in anticipation of the commit we'll create.
> GH Action: Increase commit count based version by one

- packages/vite/src/buildRscFeServer.ts
We want to stay as close to our regular vite setup as possible. With this change we use the same base vite config as RW projects using Vite already do
> Include standard vite config in RSC build

- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/project-config/src/__tests__/paths.test.ts
- packages/project-config/src/paths.ts
- packages/vite/src/buildRscFeServer.ts
- packages/vite/src/waku-lib/rsc-handler-worker.ts
`entries.ts` is a central file to RSC. Shouldn't treat the path to that file just like every other path and have it included in `getPaths()` in `@redwoodjs/project-config`.
> RSC: Include entries.ts in paths

- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/project-config/src/paths.ts
Can't use `rwPaths.web.entries` in the setup script, because it's not created yet
> RSC: Fix experimental setup

- packages/vite/src/buildRscFeServer.ts
- packages/vite/src/index.ts
Our default config clashes with the config needed for our client component build. Will have to figure out how to handle this later. For now having it unconfigurable is good enough.
> RSC build without user config

- docs/docs/tutorial/chapter2/routing-params.md
Closes https://github.com/redwoodjs/redwood/issues/8889
This PR replaces `ArticleQuery` type with `FindArticleQuery`, which is the generated code when running `yarn rw g cell Article` (any singular-form name).
To be fair, it does not matter whether `ArticleQuery` or `FindArticleQuery` is used (ie. will not cause error either way), _except_ when user copy-pastes from the following block and does not modify their auto-generated code accordingly.
Thus it may be better to update the tutorial code to reflect the auto-generated code.
> docs: update ArticleQuery type in routing-params.md

- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/cli/src/commands/experimental/templates/rsc/App.css.template
- packages/cli/src/commands/experimental/templates/rsc/App.module.css.template
- packages/cli/src/commands/experimental/templates/rsc/App.tsx.template
- packages/cli/src/commands/experimental/templates/rsc/Counter.css.template
- packages/cli/src/commands/experimental/templates/rsc/Counter.module.css.template
- packages/cli/src/commands/experimental/templates/rsc/Counter.tsx.template
Includes external css and module.css files in the example
> RSC: Add css files to the example

- packages/cli/src/commands/experimental/setupRscHandler.js
Was previously reusing the description from the streaming ssr setup command. Now correctly uses its own description.
> RSC fix: setup description

- docs/docs/tutorial/chapter2/getting-dynamic.md
Update old layout name reference in the Docs.
The information with "PostLayout" is outdated. The scaffold is using the shared "ScaffoldLayout".
Chapter 2 > Getting Dynamic
There is no Issue Nr. for this PR.
> Update name reference in Redwood Docs

- packages/cli/src/commands/__tests__/dev.test.js
- packages/cli/src/commands/devHandler.js
- packages/cli/src/commands/experimental/templates/streamingSsr/entry.client.tsx.template
- packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
- packages/vite/src/devFeServer.ts
- packages/web/src/components/DevFatalErrorPage.tsx
- packages/web/src/serverContext.tsx
As title, addresses the following issues:
- fixes: no css styles
- fixes: DevFatalErrorPage breaks with “window” not defined during ssr
- fixes: ReferenceError: RWJS_DEBUG_ENV is not defined
- sets up `yarn rw dev` to use fe server when streaming experimen enabled
- Also removes server context, no longer needed.
Note: Not needed for v6!
> fix(ssr): Get experimental ssr setup working properly

- packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/README.md
- packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__testfixtures__/default.input.js
- packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__testfixtures__/default.output.js
- packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/__tests__/changeGlobalToGlobalThis.test.ts
- packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/changeGlobalToGlobalThis.ts
- packages/codemods/src/codemods/v6.x.x/changeGlobalToGlobalThis/changeGlobalToGlobalThis.yargs.ts
The legacy Node.js `global` object is still supported in Webpack for compatiblity reasons (src: https://webpack.js.org/api/module-variables/#global-nodejs), and there's a good chance that some projects are still using it because an old project of @Tobbe's was.
Since this isn't supported in Vite, we should codemod it, especially since it's as simple as a find and replace which jscodeshift already has support for.
> chore(v6): add codemod changing `global` to `globalThis`

- packages/vite/src/index.ts
Vite's built-in support for replacing environment variables in index.html has some issues. Especially with the way we handle environment variables. This works around those issues by implementing the replacement ourselves as a Vite plugin
See also #8928
> Vite plugin to replace env vars in index.html

- packages/cli/src/commands/devHandler.js
We decided to remove this warning, and instead remind people to run the codemod in our upgrade guides
> Remove warning message about jsx in js files

- babel.config.js
- packages/internal/src/__tests__/nestedPages.test.ts
- packages/internal/src/build/babel/web.ts
This change is a long time coming (~three years... https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) and is a change that our v6 Vite config already makes. 
The post I linked to above explains the change well and **I recommend reading it**. But here's an example of the difference in dist output:
Note that if a user has custom React preset config, this PR has no affect, making it less worrisome to add to a release.
@Tobbe I know we discussed earlier, but remind me what the motivation for this change was? That modern tools rely on it right?
Here's the Babel docs for completeness: https://babeljs.io/docs/babel-plugin-transform-react-jsx
> chore(v6): change to React automatic runtime

- packages/cli/src/commands/serveHandler.js
From Fastify's docs
> **listen**
> Starts the server and internally waits for the `.ready()` event. The signature is `.listen([options][, callback])`. Both the `options` object and the `callback` parameters extend the [Node.js core](https://nodejs.org/api/net.html#serverlistenoptions-callback) options object.
And looking at Node's docs we can read
> `path` `<string>` Will be ignored if port is specified. See [Identifying paths for IPC connections](https://nodejs.org/api/net.html#identifying-paths-for-ipc-connections).
Digging deeper into IPC (link above)
> The path is a file system pathname. It gets truncated to an OS-dependent length of sizeof(sockaddr_un.sun_path) - 1. Typical values are 107 bytes on Linux and 103 bytes on macOS. If a Node.js API abstraction creates the Unix domain …
> serve web: Fix socket support

- packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
> RSC fix typo in example code

- packages/vite/src/rscBuild.ts
- packages/vite/src/waku-lib/build-server.ts
- packages/vite/src/waku-lib/rsc-handler-worker.ts
Set the react-server condition to support poisoned imports and other multi-environment npm modules.
> RSC: react-server condition. Poisoned imports

- packages/cli/package.json
- packages/cli/src/commands/execHandler.js
- packages/cli/src/telemetry/exporter.js
- yarn.lock
**Problem**
We now use OpenTelemetry to instrument the CLI. This means that all telemetry generated during the CLI process is gathered and send off to our backend for storage and later analysis. This helps us understand usage and improve the CLI and overall framework.
We also allow users to instrument their project with OpenTelemetry for their own usage. This becomes a problem when we execute user code within the CLI process. This is what happens with `rw exec [script]` where we directly call their script code within the same CLI process. We must suppress telemetry gathering while executing their code or we risk gathering _their_ telemetry as our own. 
This does not apply when we spawn a new node process to run the user code, such as `rw dev` or `rw serve`.
**Changes**
1. We now depend on …
> fix(cli): Escape telemetry in exec command

- packages/fastify/src/graphql.ts
I missed this in https://github.com/redwoodjs/redwood/pull/8878 and it's causing `yarn rw serve` to break. `@redwoodjs/realtime` needs to be conditionally imported since it's an optional peer dependency.
> fix(rw serve): conditionally import `@redwoodjs/realtime`

- packages/web-server/src/server.ts
When I run `yarn rw serve web` I see this printed to the console
It's not wrong. But when clicking that link I get "page is not secure" warning icon
And I don't get the dev tools I get when using localhost instead
(which look like this)
The devtools thing might be more of a browser thing, but I also think people are just more used to seeing/using localhost.
So I suggest printing `http://localhost:8910` instead.
This issue was introduced with the new web-server package because I switched to just printing the `address` we get from Fastify.
> web-server: Print localhost instead of 0.0.0.0

- packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
I recently setup a new RW project with Tailwind and noticed a few improvements I thought could be made
First I wanted our setup to as closely as possible follow the latest instructions on https://tailwindcss.com/docs/installation/using-postcss
Mainly that meant to use `@tailwind base;` etc instead of `@import ...`
Unfortunately (?) I couldn't use their postcss config syntax, because they're using Next-specific syntax
https://github.com/tailwindlabs/tailwindcss.com/pull/870 TW PR that updated their docs
https://github.com/vercel/next.js/issues/10117 Next issue about the syntax with some good info in the comments, including motivation on why they use this non-standard syntax
Secondly I got syntax warnings in my css files after setting up Tailwind. After some googling I fixed that by …
> Update Tailwind setup. Show extensions to install

- packages/create-redwood-app/src/create-redwood-app.js
When creating a new Redwood app and selecting to initialize a git repo you always end up with an untracked yarn.lock file
This PR makes sure git initialization happens after the lock file has been created.
Screenshot from after my fix (notice that `git status` no longer lists yarn.lock as untracked)
@jtoar This one is probably good to get in as soon as possible
> CRWA: Move git init to include yarn.lock

- packages/vite/src/rscBuild.ts
- packages/vite/src/waku-lib/build-server.ts
- packages/vite/src/waku-lib/rsc-handler-worker.ts
Fixing some RSC settings that I broke in #8948
Thanks to @Josh-Walker-GM I now have a better understanding of how `noExternal` works.
If you want Vite to analyze/know about a file, you don't want it to be externalized. So you might want to put it in the `noExternal` list.
> RSC: Fix noExternal rule for server build

- packages/auth-providers/firebase/api/src/decoder.ts
- packages/auth-providers/firebase/setup/src/setupHandler.ts
Auditing firebase again for Redwood's v6 release, it was failing and I forgot why. Referring back to https://github.com/redwoodjs/redwood/pull/8305 reminded me that the versions of `firebase-admin` between the framework and a user's project need to be the same. One of the ways they get out of sync is with renovate. I don't want to read from the firebase api package during the firebase setup command—plus the versions can get out of sync in other ways—so for now, may as well save everyone some time by making the error more explicit:
This coupling really isn't ideal at all since any time we bump the version of `firebase-admin` in the framework and release a new versoin, users have to bump it in their projects too. I'm not sure what a better way is yet.
I've also upgraded the version of …
> fix(firebase): improve error handling

- packages/cli/src/commands/serveBothHandler.js
- packages/vite/package.json
- packages/vite/src/buildRscFeServer.ts
- packages/vite/src/waku-lib/node-loader.ts
Use experimental node loaders when launching the RSC FE Server
This is all done to try to make loading of 3rd party modules work. Specifically have been experimenting with the `server-only` package.
In the end it turned out that it's not working because there's a bug/missing feature in Vite
https://github.com/vitejs/vite/pull/13487
> RSC: Use experimental node loader

- packages/core/config/webpack.common.js
- packages/core/package.json
- yarn.lock
Using [resolve-url-loader](https://github.com/bholloway/resolve-url-loader) to set `root` for absolute imports. This makes it possible to use the same absolute-path style imports in css for both webpack and Vite RW projects.
So CSS like this should work for both Webpack and Vite now 
```css
@layer base {
@font-face {
font-family: 'My font';
src: url('/fonts/abeezee-v22-latin-regular.woff2') format('woff2');
font-weight: 300;
ascent-override: 97%;
}
* {
font-family: 'My font';
}
}
```
Notice `url('/fonts/...')`. The initial `/` is what's important.
> Webpack: Use resolve-url-loader to handle absolute paths in css url()

- packages/cli-packages/storybook/src/commands/storybook.ts
- packages/cli/src/telemetry/index.js
**Problem**
Storybook is showing an error message when you exit via a SIGINT. 
We have spent a few hours trying to understand why and work around this with no success.
*Changes**
1. Conditionally disable the additional default signal listeners based on the argv contents.
2. Emit a custom event on `process` to trigger the telemetry shutdown.
**Notes**
I'm not really proud of this PR. Disabling based on the contents of argv isn't all that robust against false positives. Emitting a custom event on `process` is not really supposed to be done - hence why TS is complaining about the name of the signal.
This work has also highlighted that on my windows 11 machine the background scripts are not firing... This was working when I updated the span values to match those found to work in this PR …
> fix(cli): Prevent unwanted SIGINT error message from storybook

- docs/docs/tutorial/chapter1/file-structure.md
Updated list of files in a newly created project.
Only really new thing for v6 is `entry.client.jsx` I think
> docs: Update file structure

- packages/create-redwood-app/templates/js/web/vite.config.js
- packages/create-redwood-app/tsToJS.mjs
First patch for v6. Missed this during release; the release script needs an update as well.
> fix(crwa): use JSDoc in JS template for vite config

- packages/vite/src/index.ts
Only env vars with names starting with `REDWOOD_ENV_` should be automatically available for substitution in html files
> Make sure env var name starts with REDWOOD_ENV_

- packages/router/src/AuthenticatedRoute.tsx
- packages/router/src/__tests__/router.test.tsx
- packages/router/src/router.tsx
- packages/router/src/util.ts
- Fixes rerender
- Fixes some types
We were mutating the wrappers array, when rendering an `AuthenticatedRoute`. This causes React to re-render the entire page.
WrappedPage now renders an array of wrappers, but doesn't mutate this array (instead creates a new one). React 🤷
> fix(router): Prevent rerendering authenticated routes on hash change

- docs/docs/tutorial/chapter3/saving-data.md
The paragraph above this code block says:
`We're not going to let anyone update or delete a message, so we can remove those fields completely. Here's what the SDL file looks like after the changes:`
Everything is removed from the code block except the `UpdateContactInput` that is not gonna be used by anything. This is just for the TS file, the JS file has the `UpdateContactInput` removed correctly.
> Docs: remove useless code in code snippet

- packages/graphql-server/src/plugins/useRedwoodDirective.ts
- packages/testing/src/api/directive.ts
**Problem**
Context isolation was not behaving as expect when using directive tests. See https://community.redwoodjs.com/t/redwood-v6-0-0-upgrade-guide/5044/46 for more details.
**Changes**
1. We set the global context to match the context passed in to the `mockRedwoodDirective` and then the mock directive gets the global context during execution.
**Notes**
It looks like in v5 we didn't pass through the context that was provided as a parameter to `mockRedwoodDirective`. It can be somewhat tricky to understand exactly what is happening due to a few layers and that in <v6 the context was not isolated between tests.
**Outstanding**
1. People may not fully expect the side effect that passing in the context to the mock directive sets the global context?
> Fix context in directive tests

- packages/web/src/components/createCell.test.tsx
While exploring the cell-related source, I noticed there was a `test.only` that seems to have inadvertently been left in.
Removing this restores 19 passing ✅ tests that would otherwise be skipped.
Context: In the `web` package...
```bash
% git rev-parse --show-prefix
packages/web/
```
Before:
```bash
% yarn test
...
Tests:       19 skipped, 15 passed, 34 total
```
After:
```bash
% yarn test
...
Tests:       34 passed, 34 total
```
> Remove `.only` from `createCell` test

- packages/graphql-server/src/functions/graphql.ts
**Problem**
v6 has seen some performance issues. These appear to have sneaked in on #8339. This just reverts the change by moving the creation of the yoga object so that it isn't created on every request.
**Changes**
1. Moves yoga creation.
**Outstanding**
1. We still have a tiny bit of work to do analysing a slight performance decline since 4.4.3
> fix(graphql-server): Move yoga creation to avoid creation on every request

- docs/docs/prerender.md
Tiny typo fix changing `your deploy your` to `you deploy your`
> Docs: Update prerender.md to fix typo

- __fixtures__/test-project/web/package.json
- packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
- tasks/test-project/tasks.js
- tasks/test-project/tui-tasks.js
fixes #9075
`prettier-plugin-tailwindcss` >= 0.5 requires Prettier v3. This PR pins the version to `0.4.1`, which is the most recent version prior to v0.5.
**NOTE:** This issue will still affect all previous versions of Redwood because the setup ui tailwindcss command defaults to adding the Tailwind deps at latest.
I'll open two PRs, one to revert this and one to upgrade Prettier to v3 (both for next major).
> fix: resolves Tailwind setup command failing due to unsupported prettier-plugin-tailwindcss v0.5

- docs/docs/deploy/baremetal.md
Add more description over putting public key on deploy server
> Update baremetal.md. Related to ssh connection

- packages/cli-packages/dataMigrate/e2eTest.mjs
- packages/cli-packages/dataMigrate/package.json
- packages/cli-packages/dataMigrate/src/bin.ts
- packages/cli-packages/dataMigrate/src/index.ts
- packages/cli/src/plugin.js
- yarn.lock
Follow up to https://github.com/redwoodjs/redwood/pull/8572. The latest suite of fixes to the new `@redwoodjs/cli-data-migrate` package. The previous were:
- https://github.com/redwoodjs/redwood/commit/c27f318e7a86c6bddea4fa3f5a8a68219ae8c114 fix(data-migrate): fix canary publishing
- https://github.com/redwoodjs/redwood/commit/2d6b93d2f7661025eb49ffe5321f9fef2d65d4eb fix(data-migrate): add missing dependency `@redwoodjs/cli-helpers`
@Josh-Walker-GM I'm going to take a shot at it, but I'll probably need your help making sure this is properly plugged into the CLI.
> fix(data-migrate): add `dotenv-defaults`, properly plug into CLI

- packages/graphql-server/ambient.d.ts
- packages/studio/backend/fastify/yoga.ts
- packages/studio/backend/graphql/yoga.ts
- packages/vite/src/waku-lib/rsc-handler.ts
Fixing a bunch of `yarn lint` warnings
> Fix yarn lint warnings regarding {}

- packages/web/src/components/cell/cellTypes.tsx
- packages/web/src/components/cell/createSuspendingCell.tsx
I'm using the presence of a the `Loading` component in a Cell to decide whether to wrap it in Suspense boundary or not.
**This allows the user to decide two things:**
a) If they want to wait for all the results to load before displaying to the user (by removing all the loading components in cells on a page)
b) If they want to display loaders differently for example:
- Cell 1 is a regular Cell with a loading component
- Cell 2 & 3 do _not_ have a loading component
```jsx
<Cell 1/> // 👈 Cell 1 has a loading component, so it will show loader
<Suspense fallback={'Wait for both 2 and 3 to load, and display this in the mean time'}>
<Cell2  />
<Cell3  />
</Suspense>
```
> feat(Cell Suspense): Allow Cells to not Suspend

- packages/vite/src/runFeServer.ts
Fixing this problem with fly deploys
But this isn't specific to Fly. Docker deploys in general usually require you to bind to 0.0.0.0. We already do this for regular non-streaming deploys. For example here 
https://github.com/redwoodjs/redwood/blob/8d0ab16aa1c39f1526e4213211608805735f6974/packages/cli/src/commands/serveBothHandler.js#L137
Also added some more details to the console output.
We want to print `http://localhost` etc so you get a nice link you can click in your console. But in reality we're not binding to `localhost` but rather `0.0.0.0` or `::` and knowing what address it's actually binding to is also good to know
> Streaming fe server: bind to 0.0.0.0 in prod

- packages/create-redwood-app/templates/js/api/server.config.js
- packages/create-redwood-app/templates/ts/api/server.config.js
The path for the Fastify configuration is not available at the current location when generating a new project.
> fix(types): wrong type path on server.config.js

- packages/babel-config/package.json
- packages/babel-config/src/__tests__/common.test.ts
- packages/babel-config/src/common.ts
It looks like I have to add the `typescript` package, which is ~40 MB, back to the `@redwoodjs/babel-config` package because TS config files aren't valid JSON. I'm not sure what they are; this issue here (https://github.com/microsoft/TypeScript/issues/44573) makes it sound like they're their own format, which means we need to use TypeScript's parser to be 100% sure we can read these files.
I had a look at how the `ts-morph` packages get around this problem. They bundle using rollup. That's probably the answer for the future, but we don't have experience bundling external dependencies like this, and I'm trying not to introduce breaking changes, so leaving that for a major and just taking the size hit for now.
> fix(babel-config): read TS config files using TS parser functions

- packages/cli/src/commands/setup/deploy/templates/render.js
@thedavidprice and I were seeing problems in deploy target CI related to CDNs using prerender. Netlify already has this 200.html file for prerender; using it render led to similar success. Original PR on 200.html for context: [https://github.com/redwoodjs/redwood/pull/4782](https://github.com/redwoodjs/redwood/pull/4782)
> fix(render): redirect to 200.html for prerender

- packages/studio/web/src/Pages/Explore/TraceList.tsx
Not designed to be permanent. Studio is being ported to a redwood project instead.
> fix(studio): Quick fix for trace rendering bug

- packages/vite/src/buildRscFeServer.ts
This unbreaks RSC after #8979 landed.
The `react-server` condition shouldn't be used when building the client-side bundle
> RSC: Don't set the react-server condition for client builds

- __fixtures__/test-project/api/server.config.js
- __fixtures__/test-project/api/tsconfig.json
- __fixtures__/test-project/web/package.json
- __fixtures__/test-project/web/src/components/Author/Author.stories.tsx
- __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.stories.tsx
- __fixtures__/test-project/web/src/pages/WaterfallPage/WaterfallPage.stories.tsx
- package.json
- packages/babel-config/package.json
- packages/babel-config/src/__tests__/api.test.ts
- packages/babel-config/src/api.ts
- packages/create-redwood-app/templates/js/api/jsconfig.json
- packages/create-redwood-app/templates/ts/api/tsconfig.json
- packages/internal/package.json
- yarn.lock
This is needed to support JSX email templates like
```jsx
import { Button } from '@react-email/button';
const Email = () => {
return (
<Button href="https://example.com" style={{ color: '#61dafb' }}>
Click me
</Button>
);
};
```
and also ai-jsx code like
```jsx
/** @jsxImportSource ai-jsx */
// ...
toStreamResponse(
<ChatCompletion temperature={1}>
<UserMessage>Write me a poem about {topic}</UserMessage>
</ChatCompletion>
).body
```
The `jsx` tsconfig setting needs to be `react-jsx` to support the `jsxImportSource` setting: https://www.typescriptlang.org/tsconfig#jsxImportSource
The babel jsx plugin setting needs to be `automatic` to support `jsxImportSource` comments: https://babeljs.io/docs/babel-plugin-transform-react-jsx#customizing-the-automatic-runtime-import
---
@jtoar This one …
> Support jsx/tsx on the api side (for mail templates, ai-jsx, etc)

- packages/vite/src/streaming/registerGlobals.ts
Prefer `RWJS_EXP_SSR_GRAPHQL_ENDPOINT` if it's set. Fallback to `proxiedApiUrl` if not.
> Streaming SSR: Fix RWJS_EXP_SSR_GRAPHQL_ENDPOINT logic

- packages/realtime/src/graphql/index.ts
- packages/realtime/src/graphql/plugins/useRedwoodRealtime.ts
- packages/realtime/src/index.ts
**Problem**
We want to be able to do things like invalidate the live query store from outside of a full graphql request - so without access to the context which these properties are typically attached to.
Eg: Watching a file for changes and then invalidating a query when that file updates.
**Changes**
1. Expose the pubsub and liveQueryStore from the realtime package
2. Minor renaming to make the exporting more convenient 
**Outstanding**
1. We may wish to do a future refactor to prevent inadvertent mutations of these but this does not need to be done right now.
> feat(realtime): Expose store and pubsub for easier access

- packages/cli/src/commands/experimental/templates/streamingSsr/Document.tsx.template
Without this html entities like `&times;` would render differently on the server vs the client and cause react rehydration errors
> Streaming: meta charSet=utf-8

- packages/vite/package.json
- packages/vite/src/lib/StatusError.ts
- packages/vite/src/runRscFeServer.ts
- yarn.lock
Add support for passing arguments to server actions
> RSC: Decode RSF args from request

- packages/cli/src/commands/generate/model/model.js
Fixes https://github.com/redwoodjs/redwood/issues/9069.
> fix(cli): import redwoodjs/record correctly in `yarn rw g model`

- packages/cli/src/plugin.js
**Problem**
#9150 highlights that there was a mistake in the cache loading logic.
**Changes**
1. We merge the current cache state with the defaults - this will ensure that the defaults which are hard coded cannot be missing when the user updates versions.
**Notes**
I'm updating some of this plugin loading logic so expect a little churn in this code.
> fix(cli): Prevent stale command cache defaults

- __fixtures__/test-project/web/src/components/Author/Author.stories.tsx
- __fixtures__/test-project/web/src/components/BlogPost/BlogPost.stories.tsx
- __fixtures__/test-project/web/src/pages/BlogPostPage/BlogPostPage.stories.tsx
- __fixtures__/test-project/web/src/pages/WaterfallPage/WaterfallPage.stories.tsx
- packages/cli/src/commands/generate/component/templates/stories.tsx.template
- tasks/test-project/codemods/updateBlogPostPageStories.js
- tasks/test-project/codemods/updateWaterfallPageStories.js
- tasks/test-project/rebuild-test-project-fixture.js
- tasks/test-project/tui-tasks.js
This updates the test-project rebuild script to be aligned with the changes introduced in https://github.com/redwoodjs/redwood/pull/8788
> Update test-project codemods for stories

- tasks/test-project/rebuild-test-project-fixture.js
- tasks/test-project/typing.js
- tasks/test-project/util.js
`yarn rebuild-test-project-fixture --resumeStep` used to only support a top level step number, like `7`.
Now you can specify a sub step to start on as well, like `7.3`
> Allow resuming rebuild-test-project-fixture at a specific sub step

- packages/vite/src/waku-lib/build-server.ts
- packages/vite/src/waku-lib/builder.ts
- packages/vite/src/waku-lib/rsc-handler-worker.ts
By configuring `noExternal` for the server side build correctly we now support using npm modules with client side only React components, i.e. components with `'use client'` at the top of the file.
Currently you have to patch vite for this to work. Still waiting for https://github.com/vitejs/vite/pull/13487 to be merged.
> RSC: Support 'use client' in 3pp packages

- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/cli/src/commands/experimental/templates/rsc/vite-npm-4.4.9-e845c1bbf8.patch.template
This is needed until https://github.com/vitejs/vite/pull/13487 is merged and released and RW uses that new version of Vite
> RSC: Patch vite when running setup command

- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/vite/ambient.d.ts
- packages/vite/src/fully-react/assets.tsx
Using these types both for RW the framework and RW apps https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/experimental.d.ts
This gives us proper types for `<form action...` in RW apps
> RSC: Use react/experimental types

- packages/cli/src/commands/experimental/setupRscHandler.js
With this check in place it's now safe to run the setup command multiple times, which is great when testing it.
> RSC: Check if index.html has already been updated during setup

- tasks/smoke-tests/auth/tests/rbacChecks.spec.ts
- tasks/smoke-tests/common.ts
- tasks/smoke-tests/prerender/tests/prerender.spec.ts
- tasks/smoke-tests/storybook/tests/storybook.spec.ts
Fixes errors like this:
And this:
> smoke-tests: Fix red squiggles (type import, * as)

- packages/cli/src/lib/packages.js
May fix https://github.com/redwoodjs/redwood/issues/9198.
> fix(cli): run dedupe after installing a redwood plugin

- packages/router/src/__tests__/analyzeRoutes.test.tsx
- packages/router/src/__tests__/router.test.tsx
- packages/router/src/router.tsx
- packages/router/src/util.ts
Fix for #9131
This handles use cases where there are multiple nested routes with different levels of authentication and redirect contexts
> Fix infinite loops on nested private routes with roles

- __fixtures__/test-project/web/package.json
- babel.config.js
- packages/babel-config/src/web.ts
- packages/core/config/webpack.common.js
- packages/create-redwood-app/templates/js/web/package.json
- packages/create-redwood-app/templates/ts/web/package.json
- packages/eslint-config/shared.js
- packages/web/package.json
- packages/web/src/global.web-auto-imports.ts
- yarn.lock
TypeScript has long been well established; React prop-types is a vestigial feature. The package hasn't been updated in ~2 years (https://www.npmjs.com/package/prop-types) and the legacy React docs recommend moving off it: https://legacy.reactjs.org/docs/typechecking-with-proptypes.html.
There are a few things about this PR that are technically breaking. `prop-types` isn't a huge package so I don't think it's important this goes into the next minor or anything; it can just be scheduled for the next major.
> chore(crwa): remove React `prop-types` package

- docs/docs/cli-commands.md
**Docs**
This is designed to cover the new `yarn rw setup package <npm-package>` command.
> docs(cli): Setup from npm package

- packages/vite/src/buildRscFeServer.ts
- packages/vite/src/waku-lib/rsc-handler-worker.ts
I saw this when running the RSC smoke tests on Windows
It's using double backslashes in the keys for `absoluteClientEntries`, but forward slashes later when trying to look up values in that map. And that's not going to work 🙂
> RSC: Handle Windows paths in clientEntries

- __fixtures__/test-project/web/package.json
- packages/create-redwood-app/templates/js/web/src/graphql/possibleTypes.js
- packages/create-redwood-app/templates/ts/web/src/graphql/possibleTypes.ts
Fixing GitHub "check annotations" warnings like these
> graphql possibleTypes: Fix formatting

- __fixtures__/test-project/package.json
Our CI is currently failing with this error
```
src/entry.client.tsx(13,34): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'ReactNode'.
Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
```
This is also affecting RW apps, not just our test-project
I've decided to only add the resolution to our test-project for now, to get CI passing. We should discuss in the team how we want to handle RW projects. We've historically been very careful about adding resolutions because they're difficult to get users to remove later once they're not needed anymore.
The issue is tracked upstream here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/66841
> test-project: yarn resolution for @types/react

- __fixtures__/empty-project/scripts/seed.ts
- __fixtures__/test-project/scripts/seed.ts
- packages/create-redwood-app/templates/js/scripts/seed.js
- packages/create-redwood-app/templates/ts/scripts/seed.ts
Currently this Promise is unhandled, meaning if it errors it won't get caught by the `try/catch`
> fix: `await` Promise when seeding

- packages/api-server/src/watch.ts
Fixes https://github.com/redwoodjs/redwood/issues/9237, using @shivghai's solution. At first I thought this solution was (borrowing his term) kludgy because we didn't know why it was happening. But after a few hours I was able to reproduce it on my machine in an app that wasn't his.
(I think) I was able to isolate the problem to the `transpileApi` step, which uses esbuild's `buildSync` method. This actually writes to disk, populating the `api/dist` directory. This must happen so slowly on his project that the "change" event from the original filesystem change becomes separate from the "addDir" event. (The more details I go into, the more I'm speculating, so I'll stop there for now.) All I can say is that at first we thought this problem was isolated tho Shiv's project and machine, and …
> fix(api-sever): stop infinite loop on large projects

- docs/docs/services.md
- docs/versioned_docs/version-5.x/services.md
- docs/versioned_docs/version-6.0/services.md
I've just started looking into redwood and have not gotten to the point of actually using services but I would expect this needs to be awaited and the docs further down for `validateWith` (in the v6 version) says you should `await` it.
(I then also realised the v5 docs actually use `validateWithSync` so I've fixed that)
> docs: add missing `await` in service validation example

- packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.ts.template
- packages/auth-providers/dbAuth/setup/src/templates/api/functions/auth.webAuthn.ts.template
- packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.ts.template
- packages/cli-helpers/src/auth/__tests__/fixtures/dbAuthSetup/templates/api/functions/auth.webAuthn.ts.template
Adds a missing comma in the dbAuth setup templates
*Really* wish there was an easier way to test the auth setup stuff 😆
> dbAuth template: Add missing comma

- packages/auth-providers/dbAuth/api/package.json
After cherry picking https://github.com/redwoodjs/redwood/pull/9248, Netlify and Vercel deploys were broken with the following error:
It took me a second to realize it, but `@redwoodjs/project-config` is listed as a dev dependency in `@redwoodjs/auth-dbauth-api` despite being used in a source file:
https://github.com/redwoodjs/redwood/blob/040589a4e600e298837e3f2b7373d1c2403eb784/packages/auth-providers/dbAuth/api/src/shared.ts#L4
@Tobbe this may not be the end of it—in those environments, there's no `redwood.toml` either, so I think `getConfig` will throw. But we can solve one bug at a time.
> fix(serverless): move project-config to auth-dbauth-api dependencies

- __fixtures__/test-project/web/src/entry.client.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/README.md
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/alreadyChecking.input.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/alreadyChecking.output.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/default.input.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/default.output.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/moreCode.input.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/moreCode.output.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/unintelligible.input.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__testfixtures__/unintelligible.output.tsx
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/__tests__/entryClientNullCheck.test.ts
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/entryClientNullCheck.ts
- packages/codemods/src/codemods/v6.x.x/entryClientNullCheck/entryClientNullCheck.yargs.ts
- packages/create-redwood-app/templates/js/web/src/entry.client.jsx
- packages/create-redwood-app/templates/ts/web/src/entry.client.tsx
**Problem**
Fixes #9059 which is a type error raised when you have strict type checking enabled. The `getElementById` call can return null as the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById#return_value) mention.
**Changes**
Adds a basic null check taken from the solution given in #9059. 
**Considerations**
This adds some boilerplate code to a user facing file but I think it's a reasonable addition. It's readable and clear what the code is doing without the need for further explanation or technical knowledge. In the case where this causes a runtime error then the message is clearer:
I haven't immediately been able to think of some hidden solution to this that isn't exposed to the user in some boilerplate code.
> fix(crwa): Explicit check for possible null value in `entry.client.tsx`

- docs/docs/testing.md
Improves the readability of the numbered lists in the "Testing forms" section https://redwoodjs.com/docs/testing#testing-the-form 
Right now it's a paragraph, not an ordered list. This PR fixes #9264
> fix (docs): use default markdown numbered list

- docs/docs/graphql.md
Not sure if that's an error, haven't tried, but for sure it looks wrong ;)
> Fix typo in RBAC @requireAuth example

- docs/docs/logger.md
Explains how to setup and configure the Prisma client to enable logging and also use a client extension since 
https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions#usage-of-on-and-use-with-extended-clients
handlePrismaLogging is a `$on`:
> $on and $use are not available in extended clients. If you would like to continue using these client-level methods with an extended client, you will need to hook them up before extending the client.
> docs: How to Use Prisma Client Extensions with DB Client and Logging

- packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap
- packages/cli/src/commands/generate/cell/templates/cell.tsx.template
- packages/cli/src/commands/generate/cell/templates/cellList.tsx.template
- packages/internal/src/__tests__/ast.test.ts
- packages/internal/src/__tests__/fixtures/web/src/cell.tsx
By default when generating a Cell you get a long red squiggly line at the top of the file. This simple fix gets rid of that by fixing the default formatting in the template.
This is what it used to look like
And if you hover it you get this error explanation
And this is what it looks like after the fix in this PR
> Cell generator: Fix formatting in template

- packages/vite/src/buildFeServer.ts
We need to generate Document in the `web/dist/server/Document` so that React can fallback correctly if there is an error in the shell. 
I mistakenly assumed that this file was being built in the build process!
> fix(ssr-build): Generate document in ssr build too!

- packages/eslint-plugin/src/unsupported-route-components.ts
- packages/router/src/AuthenticatedRoute.tsx
- packages/router/src/Set.tsx
- packages/router/src/__tests__/analyzeRoutes.test.tsx
- packages/router/src/__tests__/nestedSets.test.tsx
- packages/router/src/__tests__/router.test.tsx
- packages/router/src/router.tsx
- packages/router/src/util.ts
Deprecate the `<Private>` component and the `private` prop on `<Set>`. Instead we introduce a new `<PrivateSet>` component.
This PR should be fully backwards compatible. 
Fully removing `<Private>` and `private` will be done in RW v7 (or later major version)
See also: https://github.com/redwoodjs/redwood/pull/9271
Fixes https://github.com/redwoodjs/redwood/issues/2562
Fixes https://github.com/redwoodjs/redwood/issues/9304
Also fixes the issue addressed by https://github.com/redwoodjs/redwood/pull/9306
> `<PrivateSet>`

- packages/router/src/Set.tsx
- packages/router/src/__tests__/analyzeRoutes.test.tsx
- packages/router/src/__tests__/links.test.tsx
- packages/router/src/__tests__/nestedSets.test.tsx
- packages/router/src/__tests__/route-announcer.test.tsx
- packages/router/src/__tests__/route-focus.test.tsx
- packages/router/src/__tests__/router.test.tsx
- packages/router/src/__tests__/set.test.tsx
- packages/router/src/__tests__/setContextReuse.test.tsx
- packages/router/tsconfig.json
Fixes #9313
See the linked issue for details, but in short this PR lets you do this without type errors (notice the array of wrappers):
```tsx
const Routes = () => {
return (
<Router>
<Set wrap={[Wrapper]}>
<Route path="/" page={HomePage} name="home" />
</Set>
<Route notfound page={NotFoundPage} />
</Router>
)
}
```
> Fix Set wrapper type so you can have an array of wrappers

- .github/actions/set-up-rsc-project/setUpRscProject.mjs
- .github/actions/set-up-rsc-project/setUpRscProjectLocally.mjs
The console.log text was copy/pasted from an earlier step and not changed. Fixed it to reflect what's actually happening.
Updated the test project path we use to make it easier to find among all other folders in the tmp path. Now you can do `ls -la | grep redwood` and you'll find both the regular test project and the rsc test project.
> RSC e2e scripts: Fix console.log text. Change local test path

- packages/vite/src/rsc/rscRequestHandler.ts
- packages/vite/src/runRscFeServer.ts
Clean up the RSC server implementation by extracting out the request handler and removing unused code
> RSC: createRscRequestHandler

- packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/redwood.toml
- packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/Routes.tsx
- packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/pages/HomePage/HomePage.tsx
- packages/babel-config/src/plugins/__tests__/__fixtures__/route-auto-loader/failure/web/src/pages/HomePage/useHomePage.tsx
- packages/babel-config/src/plugins/__tests__/babel-plugin-redwood-routes-auto-loader.test.ts
- packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
**Problem**
The route auto import babel plugin currently generates duplicate import statements if you have multiple files which end in `Page.{js,jsx,ts,tsx}` within the same page directory. This causes an error later in the build/dev process. This currently imposes the restriction that only one file end in `Page.{js,jsx,ts,tsx}` inside the individual page directories. 
The error message which you get when this issue occurs is rather obscure and does not easily point users to the source of the problem. This was highlighted in #9165.
The error produced from `yarn rw dev` without this change:
In comparison to after this change:
**Changes**
1. Checks for duplicate pages as returned from the `processPagesDir` function and produces a more specific error message in the case where duplicates …
> fix(babel): Improved message for error relating to multiple files ending in `Page.{js,jsx,ts,tsx}` in page directories

- __fixtures__/test-project-rsa/web/src/chat.ts
The return type of `FormData.get()` is `FormDataEntryValue`, which resolves to `string | File`. This made the return type of `onSend` include `File` as a possible value. We only wanted it to be strings. So this PR adds a check that throws an error if it's not a string (which should never happen in this test project).
> RSC: test-project-rsa: Fix TS type error in onSend

- .github/actions/check_create_redwood_app/action.yml
- .github/actions/check_test_project_fixture/action.yml
- .github/actions/only_doc_changes/action.yml
- .github/actions/require-milestone/action.yml
- .github/actions/rsc_related_changes/action.yml
- .github/actions/set-up-test-project/action.yaml
- .github/actions/update_all_contributors/action.yml
- tasks/check/action.yml
Node 16 is almost End of Life and GitHub recommends that all actions should be updated to use Node 20
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update all GitHub actions to run on Node 20

- package.json
- tasks/clean.mjs
- tasks/server-tests/jest.config.js
- tasks/server-tests/server.test.ts
In https://github.com/redwoodjs/redwood/pull/9325, I added a few fixtures to the `@redwoodjs/api-server` package that include dist files. `yarn build:clean` deletes all dist directories in all packages (the glob is `packages/**/dist`), so `yarn rwfw project:sync` ended up deleting twenty or so files. This PR makes `yarn build:clean` a little smarter. I couldn't see a way to do it via the `rimraf` CLI, so I just made a script.
This PR also increases the timeout in the server tests which were a little flakey.
> chore: increase server test timeout, fix `yarn build:clean`

- tasks/k6-test/run-k6-tests.mts
- tasks/k6-test/setups/context_magic_number/templates/benchmarks.ts
- tasks/k6-test/setups/context_magic_number/templates/func.ts
- tasks/k6-test/tests/context_functions.js
**Problem**
Follow up to #9358 which didn't completely fix the broken tests.
**Changes**
1. Correct the function test.
2. Update to run the servers in the project not the framework. 
**Status**
You can now see the expected results which show function context is not isolated when running the `rw-server` but is isolated for `rw serve api`
> chore(k6): Fix function context test

- packages/internal/src/generate/graphqlSchema.ts
If you try to `await import` a module and it can't be found, it turns out Node throws a different error than if you try to `require` a module and it can't be found:
- `require(mod)` -> `MODULE_NOT_FOUND`
- `await import(mod)` -> `ERR_MODULE_NOT_FOUND`
We used to tranpsile `await import`s to `require`. When we stopped doing that, we forgot to change the error codes we were checking.
> fix(server-file): prefix `MODULE_NOT_FOUND` with `ERR_`

- packages/auth-providers/dbAuth/api/src/shared.ts
Follow up to https://github.com/redwoodjs/redwood/pull/9281. The functionality added in https://github.com/redwoodjs/redwood/pull/9248 depends on the `redwood.toml` file. This file doesn't exist in serverless environments.
A quick note on the implementation. I could've done this:
```js
let config
try {
config = getConfig()
} catch (e) {
if (e.message !== `Could not find a "redwood.toml" file, are you sure you're in a Redwood project?`) {
throw e
}
}
// ...
```
But that seemed more brittle because it depends on the error message.
Lastly, `getConfig` merges defaults with the raw config, so I don't think the `api?.port` is necessary.
> fix(serverless): try-catch `getConfigPath` for `cookieName`

- packages/cli/src/commands/experimental/templates/streamingSsr/entry.server.tsx.template
- packages/vite/src/streaming/streamHelpers.ts
Moves the LocationProvider out of the Entry server template, and into the framework.
We still pass the path to the ServerEntry (for now). 
During SSR, it tells the router what URL is being rendered (since you can't use browser apis on the server). 
Todo:
Works fine with old template, because we still pass the url/path to entry server.
> chore(ssr): Move LocationProvider inside framework for SSR

- .github/workflows/weekly_issue_metrics.yml
Fix date formatting for weekly report, and replace "monthly" with "weekly" in output and logging
> Issue Metrics: Fix weekly report

- packages/cli/src/commands/experimental/setupDockerHandler.js
Discovered this bug while trying out the setup command on the v6.40 RC with @KrisCoulson. We were seeing the following error:
Turns out I forgot to pass task through to `writeFile`.
> fix(docker): pass `task` to `writeFile`

- .github/actions/set-up-rsc-project/setUpRscProject.mjs
For RSC smoke tests:
Run `yarn install` and `rw build` after `project:copy` to build with latest changes to the framework
> RSC: smoke tests: install and build after project:copy

- packages/cli/src/commands/serveBothHandler.js
- packages/vite/src/rsc/rscWorkerCommunication.ts
Now that we use a worker thread to be able to run the main process without the react-server condition we should use our custom loaders on that worker thread only. It kind of worked before too because arguments from the main thread are inherited by worker threads. But we got a bunch of warnings. And this is the proper way to do it anyway!
> RSC: Move loaders to worker thread

- .github/actions/actionsLib.mjs
Copy framework changes over first, and then run build. Otherwise changes to the build command won't be used
> RSC GH action: Move build to after copy

- .github/actions/actionsLib.mjs
- .github/workflows/weekly_issue_metrics_json.yml
- packages/vite/src/client.ts
- packages/vite/src/rsc/rscRequestHandler.ts
- packages/vite/src/runRscFeServer.ts
To not "steal" the `/RSC` endpoint from rw app routes we also check that a special `rw-rsc` header is set. If it's not, we'll call `next()` to pass the request along to the next handler for that path. Also decided to switch from `/RSC` to `/rw-rsc` to make it even less likely it's a path someone else would use, plus it makes it consistent with the header name
> RSC: Check for rw-rsc header

- packages/core/config/webpack.common.js
- packages/project-config/src/__tests__/config.test.ts
- packages/project-config/src/config.ts
- packages/vite/src/index.ts
- packages/vite/src/plugins/vite-plugin-remove-from-bundle.ts
- packages/web/src/apollo/index.tsx
- tasks/smoke-tests/shared/common.ts
Follow up to #9009 and #9205.
#9009 increased the bundle size of Redwood apps:
<table>
<tr><th>stable (v6.3.3)</th><th>v6.4.0 RC</th><th>% increase</th></tr>
<tr><td>
- Rendered: 1.03MB (100.00%)
- Gzip: 338.99KB
- Brotli: 290.87KB
</td><td>
- Rendered: 1.46MB (100.00%)
- Gzip: 461.74KB
- Brotli: 394.16KB
</td><td>
- Rendered: 41.75%
- Gzip: 36.21%
- Brotli: 35.51%
</td></tr>
</table>
I'm using [rollup-plugin-visualizer](https://www.npmjs.com/package/rollup-plugin-visualizer) on a newly-created Redwood app to get these numbers and treemaps. Here's links to the full treemaps:
- [stable](https://github.com/redwoodjs/redwood/assets/32992335/41cf4204-10de-4b69-a07a-7d6b980ead31)
- [v6.4.0 RC](https://github.com/redwoodjs/redwood/assets/32992335/f1a6a5bf-a260-45cb-8c97-f68b4fe0730d)
We don't …
> fix(v6.4.0 RC): conditionally remove `SSELink` from the bundle

- tasks/clean.mjs
- tasks/framework-tools/frameworkSyncToProject.mjs
Follow up to https://github.com/redwoodjs/redwood/pull/9390. Previously, framework sync would remove all of a package's dist, then rebuild it. This meant the `tsconfig.tsbuildinfo` was removed too. 
#9390 moved the `tsconfig.tsbuildinfo`, saving megabytes of space for user's projects, but didn't update `yarn build:clean` or `yarn rwfw project:sync`. This PR restores their behavior. Paired with @Josh-Walker-GM on this one.
> fix: handle `tsconfig.tsbuildinfo` in clean, sync

- packages/cli-packages/storybook/src/commands/storybookHandler.ts
The default `yarn rw storybook --build` doesn't generate preview-stats.json which is required for TurboSnap feature of Chromatic.
https://www.chromatic.com/docs/turbosnap/
I made same change in my local environment and build my real project and confirmed successful build and generation of the preview-stats.json.
> preview stats when building storybook for Chromatic "TurboSnap"

- docs/docs/docker.md
- packages/cli/src/commands/experimental/templates/docker/Dockerfile
I'm working with @KrisCoulson on the experimental Dockerfile. His project needs Python, and I'm guessing others will too. I'm still torn on adding it to the Dockerfile since it's not a small addition, so till I have more clarity on that, the docs should at least highlight it because it's quite simple to fix.
> docs(docker): add troubleshooting section for python

- docs/docs/docker.md
Follow up to https://github.com/redwoodjs/redwood/pull/9548. Some of the links have changed on Docker's website since I wrote the docs, and https://yarnpkg.com now points to yarn 4. I updated the Docker links and changed https://yarnpkg.com links to https://v3.yarnpkg.com for now.
> fix(docker): correct links, fix typos

- docs/docs/docker.md
Reading through the docker file docs I found a few typos that I wanted to fix
> Docker docs: Typo fixes

- packages/cli/src/lib/exit.js
**Problem**
There are too many cases where using boxen for the default error output causes readability issues.
**Change**
1. Remove boxen and simply draw a few straight lines coloured with chalk. This should avoid the readability issues.
**Example**
**Context**
The reason this exists in the first place was to try and centralise the error output. There were so many places in the CLI code where errors are output in various different styles which is not necessarily the best experience.
> fix(cli): Remove boxen from default error output

- packages/router/src/__typetests__/routeParamsTypes.test.ts
This PR removes redundant nesting in a test of the `RouteParams` utility type.
> chore: clean up `RouteParams` type test structure

- packages/cli/src/commands/experimental/setupDockerHandler.js
Tried the dockerfile setup command yesterday and noticed a typo. This PR fixes that.
> Experimental Dockerfile: Fix typo in setup command

- packages/auth-providers/auth0/api/README.md
- packages/auth-providers/auth0/setup/README.md
- packages/auth-providers/auth0/web/README.md
- packages/auth-providers/azureActiveDirectory/api/README.md
- packages/auth-providers/azureActiveDirectory/setup/README.md
- packages/auth-providers/azureActiveDirectory/web/README.md
- packages/auth-providers/clerk/api/README.md
- packages/auth-providers/clerk/setup/README.md
- packages/auth-providers/clerk/web/README.md
- packages/auth-providers/custom/setup/README.md
- packages/auth-providers/dbAuth/api/README.md
- packages/auth-providers/dbAuth/setup/README.md
- packages/auth-providers/dbAuth/web/README.md
- packages/auth-providers/firebase/api/README.md
- packages/auth-providers/firebase/setup/README.md
- packages/auth-providers/firebase/web/README.md
- packages/auth-providers/netlify/api/README.md
- packages/auth-providers/netlify/setup/README.md
- packages/auth-providers/netlify/web/README.md
- packages/auth-providers/supabase/api/README.md
- packages/auth-providers/supabase/setup/README.md
- packages/auth-providers/supertokens/api/README.md
- packages/auth-providers/supertokens/setup/README.md
- packages/auth-providers/supertokens/web/README.md
- packages/auth/README.md
> fix: Remove "god code" typos from auth READMEs

- .editorconfig
- packages/cli/src/commands/setup/graphiql/supportedProviders.js
- packages/studio/api/lib/authProviderEncoders/dbAuthEncoder.ts
> fix: Prevent `rw graphiql setup` from breaking with encryptSession error

- docs/docs/tutorial/chapter1/prerequisites.md
Fix for https://github.com/redwoodjs/redwood/issues/9578 and https://community.redwoodjs.com/t/yarn-redwood-dev-throwing-internal-error/5557. @Tobbe and I paired on this one. Basically, there's a footgun in the yarn docs. If you read them too quickly, it seems like you can update your global version of yarn via `yarn set version stable`. But that command is actually only meant to be used in the context of a project (like a Redwood app).
> fix(crwa): clarify docs to avoid issues in yarn modern installs

- packages/vite/src/buildFeServer.ts
- packages/vite/src/buildRscFeServer.ts
- packages/vite/src/rsc/rscBuildAnalyze.ts
- packages/vite/src/rsc/rscBuildClient.ts
- packages/vite/src/rsc/rscBuildClientEntriesFile.ts
- packages/vite/src/rsc/rscBuildCopyCssAssets.ts
- packages/vite/src/rsc/rscBuildServer.ts
- packages/vite/src/rsc/rscRequestHandler.ts
Refactor the RSC build process into more uniform functions to make it easier to more tightly integrate this into the SSR build process later
> RSC: Refactor build process

- docs/docs/authentication.md
- docs/docs/how-to/role-based-access-control.md
- docs/docs/prerender.md
- docs/docs/router.md
- docs/docs/tutorial/chapter0/what-is-redwood.md
- docs/docs/tutorial/chapter4/authentication.md
- docs/versioned_docs/version-6.0/authentication.md
- docs/versioned_docs/version-6.0/how-to/role-based-access-control.md
- docs/versioned_docs/version-6.0/prerender.md
- docs/versioned_docs/version-6.0/router.md
- docs/versioned_docs/version-6.0/tutorial/chapter4/authentication.md
- docs/versioned_docs/version-6.0/tutorial/chapter7/rbac.md
- packages/internal/src/__tests__/fixtures/nestedPages/web/src/Routes.js
- packages/structure/src/model/RWRoute.ts
- packages/testing/src/web/__tests__/MockRouter.test.tsx
- packages/vite/src/__tests__/fixtures/nestedPages/web/src/Routes.js
`Private` and `Set private` was deprecated in v6.4.x - this PR changes the docs to use `<PrivateSet>` instead and updates some test fixtures.
> chore(private-set): Wrap profile page in <PrivateSet> instead of Private

- packages/cli/src/commands/buildHandler.js
- packages/vite/package.json
@Josh-Walker-GM and I have been working on the memory issue in v6 (see https://community.redwoodjs.com/t/memory-use-in-redwood-v6/5224/2). We started by making a script that profiles the number of processes started by `REDWOOD_DISABLE_TELEMETRY=1 yarn rw build --no-prerender` and the amount of memory each one uses. While it's hard to get a consistent number for memory (it differs between machines and OSes, among other things), the number of processes spawned is consistent and sheds some insight into what's going on.
In stable, `REDWOOD_DISABLE_TELEMETRY=1 yarn rw build --no-prerender` spawns nine processes. While there's two esbuild ones that seem like they could be deduplicated, there's three associated with `rw-vite-build` that seem to be redundant that take up a sizable amount of …
> fix(cli): avoid calling rw-vite-build via yarn

- __fixtures__/test-project-rsa/web/src/AboutCounter.tsx
- __fixtures__/test-project-rsa/web/src/AboutPage.tsx
- __fixtures__/test-project-rsa/web/src/entry.client.tsx
- __fixtures__/test-project-rsc-external-packages/web/src/AboutCounter.tsx
- __fixtures__/test-project-rsc-external-packages/web/src/AboutPage.tsx
- __fixtures__/test-project-rsc-external-packages/web/src/entry.client.tsx
- packages/cli/src/commands/experimental/setupRscHandler.js
- packages/cli/src/commands/experimental/templates/rsc/AboutCounter.tsx.template
- packages/cli/src/commands/experimental/templates/rsc/AboutPage.tsx.template
- packages/cli/src/commands/experimental/templates/rsc/entry.client.tsx.template
- packages/vite/src/buildFeServer.ts
- packages/vite/src/buildRscFeServer.ts
- packages/vite/src/react-server-dom-webpack/node-loader.ts
- packages/vite/src/rsc/rscBuildClient.ts
- packages/vite/src/rsc/rscBuildRwEnvVars.ts
- packages/vite/src/rsc/rscBuildServer.ts
- packages/vite/src/waku-lib/vite-plugin-rsc.ts
- packages/web/src/config.ts
- tasks/smoke-tests/rsc/tests/rsc.spec.ts
To be able to use the standard RW `<FatalErrorBoundary>` component with our `FatalErrorPage` we needed to also include our RWJS_* env vars in the RSC Vite config
> RSC: Add RW env var definitions to Vite config and include FatalErrorBoundary

- docs/docs/testing.md
The testing docs include info on how to test service, directives, cells, and more ... but did not link to the "how to test email" with the recent Redwood Mailer package.
This PR adds some short comy introducing the topic and a link to the main Mailer testing section.
> chore: Update Testing documentation to link to How to Test Email/Mailer

- packages/vite/src/rsc/rscBuildServer.ts
- packages/web/src/config.ts
#9622 added some logs which are useful for debugging during RSC development. They log on every project even those not using RSC so I'll comment them out here for just now. 
Also fixes a minor lint issue.
> chore: Linting and disable some console logs

- docs/docs/realtime.md
I was reading through the Realtime docs and found a few things I wanted to fix. This PR does that 🙂
> Proofreading fixes for realtime docs

- .eslintrc.js
enable `import/no-extraneous-dependencies` rule just for `project-config` (other projects can be added as needed).
- ~~adding explicit dependency definitions to `package.json`s that used to come from a transitive / implicit one can bring issues; usually these explicit definitions are benign, however it is a new risk (it also means more overhead in terms of  dependency management).~~
- ~~`@redwoodjs/studio` ( _synced w/ @Josh-Walker-GM about ignoring this package since that is an experimental one, this might be the approach we want to take; leaving changes to it in this PR for now._ )~~
> chore(eslint): enable `import/no-extraneous-dependencies` rule

- packages/auth-providers/clerk/setup/src/setupHandler.ts
Corrects the `packages/auth-providers/clerk/setup/src/setupHandler.ts` for errant comma in the post setup notes of the clerk setup command.
> fix(clerk auth): remove errant comma in post-setup notes

- docs/docs/auth/clerk.md
See issue https://github.com/redwoodjs/redwood/issues/9658
In the issue above, @swrichards found that if one places a Page.tsx in just the `pages` directory (ie, not /pages/PageName/PageName.tsx` and routes to it, one gets the following error building web / starting dev:
The found this while following the Clerk auth documentation -- and that said to make the HomePage in just the `pages` directory:
While this perhaps worked in the past, it doesn't seem to with the new site builds.
This PR updates the documentation to:
* say to use the page generator
* corrects filepath
* removes outdated screenshot of old Clerk widget
The issue of the error will be assigned and resolved in a future PR.
> docs: auth - Clerk - Corrects Home Page generation instructions

- .github/actions/detect-changes/cases/rsc.mjs
Currently the RSC smoke tests seem to be failing consistently on https://github.com/redwoodjs/redwood/pull/9649. In debugging, I noticed that the RSC smoke tests didn't actually run for https://github.com/redwoodjs/redwood/pull/9666 which changed the RSC fixtures. That's because those files weren't listed in the detect changes list. Adding them here.
> chore(CI): add RSC fixtures to detect changes list

- packages/forms/package.json
- packages/web/package.json
- yarn.lock
With the update to @testing-library/jest-dom v6 in #9673 types are built-in, and so https://www.npmjs.com/package/@types/testing-library__jest-dom should not be used anymore
Marking this as breaking since it requires #9673 which is breaking
> DT types for jest-dom should not be used

- package.json
- packages/auth/package.json
- packages/auth/src/__tests__/AuthProvider.test.tsx
- packages/forms/package.json
- packages/router/src/__tests__/location.test.tsx
- packages/router/src/__tests__/nestedSets.test.tsx
- packages/router/src/__tests__/route-announcer.test.tsx
- packages/router/src/__tests__/route-focus.test.tsx
- packages/router/src/__tests__/routeScrollReset.test.tsx
- packages/router/src/__tests__/router.test.tsx
- packages/router/src/__tests__/set.test.tsx
- packages/router/src/__tests__/setContextReuse.test.tsx
- packages/testing/jest.setup.ts
- packages/testing/package.json
- packages/web/package.json
- packages/web/src/components/FetchConfigProvider.test.tsx
- packages/web/src/components/GraphQLHooksProvider.test.tsx
- packages/web/src/components/cell/createCell.test.tsx
- packages/web/src/components/cell/createSuspendingCell.test.tsx
- packages/web/src/components/portalHead.test.tsx
- yarn.lock
This reverts https://github.com/redwoodjs/redwood/pull/9673 and https://github.com/redwoodjs/redwood/pull/9711.
With v6 of `@testing-library/jest-dom`, `yarn rw type-check` fails in Redwood projects because it can't locate the types for `@testing-libary/jest-dom`. They absorbed the definitely types package (`@types/testing-library__jest-dom`) in this PR: https://github.com/testing-library/jest-dom/pull/511. Here's an example of a failing run: https://github.com/redwoodjs/redwood/actions/runs/7213177056/job/19668365614?pr=9708.
The logical thing to do is remove `@testing-libary/jest-dom` from the `types` array in `web/tsconfig.json`, but when we do that we get a different failure from TS saying that it doesn't understand the extended matchers provided by `testing-library/jest-dom` like …
> Revert `@testing-library/jest-dom` v6 upgrade

- __fixtures__/test-project-rsa/api/package.json
- __fixtures__/test-project-rsa/package.json
- __fixtures__/test-project-rsa/web/package.json
- __fixtures__/test-project-rsc-external-packages/api/package.json
- __fixtures__/test-project-rsc-external-packages/package.json
- __fixtures__/test-project-rsc-external-packages/web/package.json
Follow up to https://github.com/redwoodjs/redwood/pull/9701. We needed to wait for a canary to be published.
> chore(RSC): update RSC test projects to latest canary

- packages/cli/src/commands/experimental/setupSentryHandler.js
Updated the cli url to point to the forum instead of the non-existent documentation based on the ticket open here. https://github.com/redwoodjs/redwood/issues/9006
> docs(#9006) - Update redwoodjs cli to include correct forum url

- docs/yarn.lock
We upgraded to yarn v4 (see https://github.com/redwoodjs/redwood/pull/9343) but forgot to generate a new `yarn.lock` file. This PR takes care of that.
> Update yarn.lock for docs/ following yarn v4 upgrade

- docs/docs/how-to/oauth.md
- docs/versioned_docs/version-6.0/how-to/oauth.md
There was a formatting issue within [the docs](https://redwoodjs.com/docs/how-to/oauth#prisma-schema-updates):
There was an extra space between `::: caution`
> 💬 Fixed formatting within the docs

- .vscode/settings.json
- __fixtures__/test-project/.vscode/settings.json
- packages/create-redwood-app/templates/js/.vscode/settings.json
- packages/create-redwood-app/templates/ts/.vscode/settings.json
The `source.fixAll.eslint` setting changed from `true` to `"explicit"`. It will actually correct this automatically on install
> Update `.vscode/settings.json` files for ESLint setting

- .vscode/settings.json
- __fixtures__/test-project-rsa/.vscode/settings.json
- docs/docs/project-configuration-dev-test-build.mdx
- packages/create-redwood-app/templates/js/.editorconfig
While trailing whitespace is just bit noise in code (well, 99 % of the time...), for markdown it has actual signifiance.
This used to drive me crazy for a while until i found this setting. This will save others the trouble.
---
There was some scope creep in the discussion below, so this PR now both introduces changes and also fixes intended behaviour, namely:
-  (Fix) Bring VSCode settings in line with `.editorconfig` in the RedwoodJS main project
- this is particularly nice b/c trailing whitespace is now preserved when editing the docs
- (change) Not only preserve whitespace for markdown, but also HTML & MJML files in the project template
> Preserve trailing whitespace for Markdown, HTML & MJML (RedwoodJS project + create-redwood-app template)

- tasks/run-e2e
I stumbled upon this code and thought I could revert it, because stable version of RW has upgraded Prisma since the code was written. But then I realized this is always going to be a potential issue, so I decided to write some comments explaining what the code does.
> e2e: Explain why we're setting package resolutions

- .gitpod.yml
this adds `corepack enable` in the gitpod init in order to properly set the node version.
visit https://gitpod.io/#https://github.com/redwoodjs/redwood
visit gitpod via my branch: https://gitpod.io/#https://github.com/colbywhite/redwood/tree/fix.node.version
Fixes #9731
> fix(gitpod): enable corepack to get proper node version

- .github/actions/detect-changes/cases/code_changes.mjs
- .github/actions/detect-changes/detectChanges.mjs
https://github.com/redwoodjs/redwood/pull/9544 was buggy in how it detected code/docs changes. This PR fixes that
> Fix isCodeFile logic

- docs/docs/graphql/trusted-documents.md
I was trying to set up Trusted Documents and noticed a few things that could be improved in the docs. This PR addresses those things
> Trusted Documents docs: Proofreading corrections

- docs/docs/seo-head.md
Fixes some typos and grammar misstakes in the Metadata docs
> Update Metadata docs

- packages/cli/src/commands/deploy/baremetal.js
sshExec errors were not printing to console when running `yarn rw deploy baremetal production`. I had errors both in update and install stages which both just exited without the console.error printing the error message. 
To reproduce the issue, in the deploy.toml change the name of "branch" to something incorrect as this will trigger an error. Then run `yarn rw deploy baremetal production` and the command will exit without displaying an error. You can also just put a console.log() in the async task: callbacks which also don't seem to fire.
To fix the issue I just replaced the console.errors() with a throw new Error() which gets caught by the handler and displays the message as it should.
My system environment while having the problem:
System:
OS: Windows 11 10.0.22621
Binaries:
Node: …
> Fix sshExec() errors not displaying

- docs/docs/auth/supertokens.md
- docs/docs/serverless-functions.md
Closes https://github.com/redwoodjs/redwood/issues/9741.
> docs: added some clarification on serverless functions getting executed in a non-serverless environment

- packages/studio/api/mail/index.ts
- packages/studio/api/services/mail.ts
**Problem**
#9545 Highlights some compatibility issues with studio on windows.
**Changes**
1. Removes some assumptions of `/` as the path separator.
**Fixes**
Fixes #9545 in combination with #9639
> fix(studio): Fix windows path issues

- packages/forms/jest.config.js
- packages/forms/jest.setup.ts
- packages/forms/src/__tests__/form.test.tsx
- packages/router/jest.config.js
- packages/router/jest.setup.js
- packages/router/jest.setup.ts
- packages/router/src/__tests__/links.test.tsx
We had a bunch of TypeScript errors like the one above. This PR fixes those by changing what import we use.
Trying to more closely follow https://github.com/testing-library/jest-dom#usage
Except we keep our config and setup files outside of TS `root`, so we can't include them. But it seems to work anyways.
> chore(unit tests): Use side-effect import to fix TS errors

- docs/docs/router.md
Adds a heading to the router docs for the `useMatch` hook to make it easier to find the docs for it (useParams and useLocation already had their own headings). Also fixes a grammatical mistake
> Make it easier to find useMatch docs

- .github/actions/detect-changes/cases/ssr.mjs
- tasks/test-project/codemods/delayedPage.js
Fixes this error in our CI
```
web | transporting incomingBackgroundQueries []
✓  1 [chromium] › progressiveRendering.spec.ts:25:5 › Check that homepage has content rendered from the server (progressively) (924ms)
[WebServer] web | 🔻 Caught error outside shell
[WebServer] web | ReferenceError: MetaTags is not defined
web |     at DelayedPage (/home/runner/work/redwood/test-project/web/src/pages/DelayedPage/DelayedPage.tsx:70:4)
web |     at renderWithHooks (/home/runner/work/redwood/test-project/node_modules/react-dom/cjs/react-dom-server.edge.development.js:8654:16)
```
https://github.com/redwoodjs/redwood/actions/runs/7337050830/job/19977328836?pr=9758
> SSR smoke-test: Use <Metadata />

- docs/docs/docker.md
The docker docs were updated in https://github.com/redwoodjs/redwood/pull/9764 but one broken path snuck in there. This PR fixes that
> docker.md: Fix web path

- .github/actions/detect-changes/detectChanges.mjs
I thought I already fixed this in [a previous PR (#9762)](https://github.com/redwoodjs/redwood/pull/9762), but I guess not... Trying again!
> chore(ci): retry detectChanges on error

- .github/actions/detect-changes/detectChanges.mjs
Fix for issue with #9769
Also saw this:
> chore(ci): retry detectChanges on error, and await result

- packages/router/src/__tests__/links.test.tsx
- packages/router/src/__tests__/useMatch.test.tsx
- packages/router/src/index.ts
- packages/router/src/links.tsx
- packages/router/src/useMatch.ts
- packages/router/src/util.ts
With the recent introduction `useRoutePaths` (#9755) and `useRouteName` (#9758) I wanted to also move `useMatch` to its separate file to make code organization more consistent.
> chore(router): Move useMatch to its own file

- packages/cli/src/commands/experimental/templates/opentelemetry.ts.template
Fixes PR https://github.com/redwoodjs/redwood/pull/9709/files where way `getConfig` is imported from `project-config` when setting up OpenTelemetry for use with RedwoodJS Studio.
Need to `require` and not import.
> fix: Fixes way OpenTelemetry setup template uses project-config for port setting

- packages/api-server/src/watch.ts
- packages/cli/src/commands/experimental/setupOpentelemetryHandler.js
- packages/cli/src/commands/experimental/templates/opentelemetry.ts.template
- packages/project-config/src/__tests__/config.test.ts
- packages/project-config/src/config.ts
**Problem**
The toml config value that was supported for the experimental OpenTelemetry support points to the source file. It was however being used as if it were pointing to the transpiled version of the file.
**Changes**
1. Switches the `opentelemetry.ts` file to use `import` over `require` syntax.
2. Removes the `apiSdk` toml option and now assumes the file exists at `api/src/opentelemetry.ts` such that it then also exists at `api/dist/opentelemetry.js`.
3. Adds a large `concurrencyLimit` option to the OTel trace exporter. This fixes a limitation of the current redwood studio. This config will be removed in an upcoming change to the redwood studio which will better support the `BatchSpanProcessor` instead. 
---
This is a breaking change for OTel, but since our OTel support is still …
> fix(otel): Fix OTel sdk loading

- __fixtures__/test-project/README.md
- __fixtures__/test-project/api/package.json
- __fixtures__/test-project/api/src/functions/auth.ts
- __fixtures__/test-project/api/src/functions/graphql.ts
- __fixtures__/test-project/api/src/lib/auth.ts
- __fixtures__/test-project/web/package.json
- __fixtures__/test-project/web/vite.config.ts
- tasks/test-project/codemods/models.js
- tasks/test-project/templates/api/context.test.ts.template
- tasks/test-project/tui-tasks.js
- tasks/test-project/util.js
The test-project fixture had drifted from what you actually get when you rebuild it. Both because all PRs haven’t included the needed updates. But also because the script that generates it needed some updates. This PR addresses both those things
> chore(test-project): Fix test-project generation script, and regenerate fixture

- __fixtures__/test-project/api/package.json
- __fixtures__/test-project/web/package.json
- tasks/test-project/tui-tasks.js
Now when the dbauth setup is updated (like changes to the template files) they'll be used when rebuilding the test project
> Use build:pack for dbauth when rebuilding the test project

- .gitignore
When running the new `yarn:pack` command (added in https://github.com/redwoodjs/redwood/pull/9766) you end up with a bunch of .tgz files. They should not be committed to git, so I'm adding them to our .gitignore
> chore(framework-tools): .gitignore

- tasks/release/releaseLib.mjs
`git fetch` was throwing errors about refusing to fetch
The reason is you can't `fetch` the current branch. So if you're currently on `main` you can't fetch main. In that case you should use `pull` instead
> chore(release-tooling): fetch -> pull

- .github/workflows/ci.yml
- packages/create-redwood-app/.babelrc.js
- packages/create-redwood-app/jest.config.js
- packages/create-redwood-app/package.json
- packages/create-redwood-app/scripts/setUpTestProject.mjs
- packages/create-redwood-app/scripts/tsToJS.mjs
- packages/create-redwood-app/templates/js/.editorconfig
- packages/create-redwood-app/templates/js/web/jsconfig.json
- packages/create-redwood-app/tests/e2e.test.mjs
- packages/create-redwood-app/tests/e2e_prompts.sh
- packages/create-redwood-app/tests/e2e_prompts_git.sh
- packages/create-redwood-app/tests/e2e_prompts_m.sh
- packages/create-redwood-app/tests/e2e_prompts_overwrite.sh
- packages/create-redwood-app/tests/e2e_prompts_ts.sh
- packages/create-redwood-app/tests/templates.test.mjs
Similar to https://github.com/redwoodjs/redwood/pull/9766, I was working on ESM and started with CRWA since it's the easiest package, and there really weren't any tests for it. (I think other tests, like the cypress e2e test, use it, so I think we'd catch if it totally broke, but it's not trivial to run that one locally for quick feedback.) This PR adds a couple of e2e tests.
To run them locally:
```bash
yarn build
cd ./packages/create-redwood-app
yarn build:pack
PROJECT_PATH=$(yarn set-up-test-project)
PROJECT_PATH=$PROJECT_PATH yarn test:e2e
PROJECT_PATH=$PROJECT_PATH ./tests/e2e_prompts.sh
```
Some of the CRWA e2e tests use [expect](https://core.tcl-lang.org/expect/index). I tried testing the prompts using `zx`, Node's `child_process`, etc and writing to `process.stdin`, but it never …
> chore(crwa): add e2e tests for create-redwood-app

- .github/workflows/ci.yml
- packages/create-redwood-app/src/create-redwood-app.js
I thought the prompt tests for CRWA introduced in https://github.com/redwoodjs/redwood/pull/9783 needed a little time between them to avoid flakiness so I added sleep statements, but @Tobbe showed me a failing run where the first test fails: https://github.com/redwoodjs/redwood/actions/runs/7370512212/job/20056962003?pr=9785.
@Josh-Walker-GM and I had a look at the code around the gitignore renaming step because that file starts as `gitignore.template` and gets renamed to `.gitignore` and we found an async `fs` method that wasn't being awaited. Changed it sync here.
We've had it this for quite a while now! Over two and a half years (see https://github.com/redwoodjs/redwood/pull/2752). I can't say I've ever seen it fail locally, but it's more likely in a resource constrained environment …
> fix(crwa): use `fs.renameSync` instead of `fs.rename`

- packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
**Problem**
Logging in with webauthn enabled was broken when you had customised your schema to use different column names than the default.
See #8743 for details. 
**Changes**
1. Alters the where clause to use the same column names as the create a few lines below. See: https://github.com/redwoodjs/redwood/blob/c7ae669e36c5e1b7edcd4ee5436558831bad94b8/packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts#L979-L983
**Fixes**
Fixes #8743
> fix(dbAuth): Correct hardcoded DB column

- packages/cli-packages/dataMigrate/src/__tests__/install.test.ts
I was seeing this test fail when running in VSCode
Even the editor part of VSCode gets confused about the control characters used in the string we're trying to match
(notice how you can't see the "https" part, and how the last control character is rendered after the end of the string (after `'`))
> Use regex to make test pass in VSCode

- docs/docs/router.md
- packages/router/src/__tests__/useRoutePaths.test.tsx
- packages/router/src/useRoutePaths.ts
Make `useRoutePath()` default to the path for the current route. This is probably the most common use case, so let's make that super easy to use.
> useRoutePath(): Get the path for the current route by default

- packages/api-server/src/plugins/withFunctions.ts
- packages/api-server/src/plugins/withWebServer.ts
- packages/fastify/src/api.ts
- packages/fastify/src/graphql.ts
- packages/fastify/src/web.ts
- packages/web-server/src/web.ts
**Problem**
A recent change in #9714 introduced a small issue where the `@fastify/url-data` plugin would register twice and on the second registration would throw an uncaught error. 
See: #9789 for more information.
**Changes**
1. I have introduced simple checks before registering the plugin to ensure it has not already been registered.
2. I have consistently awaited registration for the `@fastify/url-data` plugin.
**Fixes**
Fixes #9789
> fix(fastify): Prevent duplicate `@fastify/url-data` registration

- docs/docs/router.md
- packages/router/src/__tests__/useMatch.test.tsx
- packages/router/src/useMatch.ts
Make it possible to specify route param values that need to match.
If this is your route: `<Route path="/blog/{year}/{month}/{day}" page={BlogPostPage} name="blogPost" />`
And you want to only match posts from 2001 you can now do this:
`useMatch('/blog/{year}/{month}/{day}', { routeParams: { year: '2001' } })`
This is **finally** a solution to matching route paths. The work started in #7469, but we were never able to come up with an api/dx that we really liked. This PR and #9755 together however provides a solution that we're much more happy with, and that also supports the use case outlined in that original PR.
Here's the example from #7469 as it could be solved with the code in this PR
```jsx
const Navbar () => {
const { project } = useParams()
const routePaths = useRoutePaths()
const …
```
> Add routeParams to useMatch

- packages/cli-packages/dataMigrate/src/__tests__/upHandler.test.ts
**Problem**
Running `yarn test` would fail for the cli data migrate package. This is because the code itself sets the exit code to 1 when an error occurs. We deliberately test the case where an error occurs so the exit code is indeed set 1. Even though the jest expect cases pass the test suite thinks something when wrong due to the non-zero exit code. 
**Changes**
1. Resets the exit code to 0 for the test case we expect to set it to 1.
> chore(data-migration): Fix test exit code 

- packages/cli-packages/dataMigrate/src/__tests__/upHandler.test.ts
Running the upHandler tests you'd see this in your console
This PR cleans that up by mocking out console.log
It also fixes TS errors in the test code:
> data migrate: Clean up upHandler test

- docs/docs/graphql/fragments.md
Was trying to set up fragments and noticed a few things we could improve in the docs
> docs(fragments): Typo, grammar and formatting fixes

- package.json
- packages/router/package.json
- packages/web/package.json
- yarn.lock
This is very simple PR, but it makes your CIs faster.
@dac09 In the PR which introduced TSTyche for type testing, you mentioned that it would be the best to test using the installed version of TypeScript (reference: https://github.com/redwoodjs/redwood/pull/9394#discussion_r1390710725).
At that time it was not possible, because TSTyche could not load TypeScript from `node_modules`. It was installing another copy for itself in global cache directory, outside of the project.
That was redundant and also slow (for the first run). Latest release is introducing significant changes: `typescript` can be loaded from `node_modules` and it is used by default for type testing. In benchmarking I saw that current release needs on average 1/4 less time to run type tests than before. I was benchmarking …
> chore: bump TSTyche

- tasks/test-project/typing.ts
Don't just check that `then` exists, also make sure it's a function
Also fixes this TS error
> chore(cli): More robust isAwaitable

- packages/cli/src/commands/serveWebHandler.js
- packages/web-server/src/server.ts
I was working on Redwood's server config with @Josh-Walker-GM. One of the more unfortunate footguns is when you're serving the web side alone while the api side is somewhere else, on a completely different host. If you don't pass `apiHost`, and `apiUrl` isn't fully qualified, what happens is that the web side requests itself, resulting in network responses like this:
An easy fix that would go a long way is just erroring out if we detect the config is incompatible and not starting the server at all:
```
% yarn rw serve web        
Error: If you don't provide apiHost, apiUrl needs to be a fully-qualified URL. But apiUrl is /.redwood/functions.
```
We used a specific exit code because `yarn rw serve web` is a bin that's calling a bin `yarn rw-server-web`. We plan to fix that by deduping code …
> fix(server): error early on incompatible config (apiHost and apiUrl)

- packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
- packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
Remove extra newline that was sometimes inserted in redwood.toml
Also rename a variable to make it clearer what it is
> fragments setup: newline fix + refactor->rename

- packages/cli/tsconfig.json
Took the list of used packages from `package.json`
(marking this as "next-release", because tsconfig is introduced in a PR that's not going out until the next release)
> Update cli tsconfig to reference used packages

- packages/cli/src/commands/setup/graphql/features/fragments/fragments.ts
- packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
Fix for #8911 
Telemetry reporting should be done in the main handler, not the async imported one.
> graphql setup fragments: Move telemetry to main handler

- packages/cli/package.json
- yarn.lock
The setup commands for gql fragments and trusted documents use jscodeshift for more robust codemods than simple string regexes. So need to add jscodeshift as a package dependency
> cli: add missing dep jscodeshift

- .github/workflows/ci.yml
- tasks/test-project/set-up-trusted-documents.ts
Enable trusted-documents, then build (including prerender), and then run the prerender smoke tests.
> Add trusted-documents to fragments CI smoke-test

- packages/fastify/src/config.ts
We know the file extension, so we might as well use the exact file extension in the log message. Makes it nicer to read imho 🙂 
This is what it used to look like
And I'm sure you can imagine what it'll look like with this change 😉
> Fastify config: Use exact file extension in log message

- packages/cli/src/commands/experimental/setupSentryHandler.js
`isTypeScriptProject` was used as a constant, but is a function. This led to all projects being identified as TS project, which is wrong.
Also changed from tabs to spaces in generated `redwood.toml` content
> exp setup sentry: Fix file extension

- packages/cli/src/commands/setup/graphiql/__tests__/graphiqlHandler.test.js
- packages/cli/src/commands/setup/graphiql/graphiqlHandler.js
- packages/cli/src/commands/setup/graphiql/supportedProviders.js
Fix grammar in setup messages for graphiql. And print correct/exact filename
> Tweak graphiql setup messages

- packages/cli-helpers/src/lib/__tests__/project.test.ts
- packages/cli-helpers/src/lib/project.ts
- packages/cli/src/commands/setup/graphql/features/fragments/__tests__/fragmentsHandler.test.ts
- packages/cli/src/commands/setup/graphql/features/fragments/fragmentsHandler.ts
- packages/cli/src/commands/setup/graphql/features/trustedDocuments/trustedDocumentsHandler.ts
This PR adds a utility function to set/create/update a setting in `redwood.toml`. 
It's intended mainly to be used by our setup commands to enable features or change configurations. It's made to handle comments, indentation, duplicated setting names in different sections, etc. Writing and testing this code is something pretty much all setup commands have done before. That's just duplicated unnecessary work. Especially since we want community members to write their own plugins it'd be nice if there was a standardized way to do this, and now there is! 🙂 
Here's a snippet of a usage example:
```typescript
import { colors, prettierOptions, setTomlSetting } from '@redwoodjs/cli-helpers'
// ...
export async function handler({ force }: Args) {
const tasks = new Listr(
[
{
title:
'Update Redwood …
```
> Add cli-helpers util to update redwood.toml

- packages/internal/src/generate/watch.ts
I got this error when working on the new Studio
The problem is that we're watching for file changes inside `__fixtures__/test-project/`. There's no need to do that!
We solved a similar issue a couple of months ago in this PR: https://github.com/redwoodjs/redwood/pull/9079. So I just copied the solution from there.
> Only watch inside web/ and api/

- tasks/framework-tools/tarsync.mjs
Currently there's a `@graphql-codegen` package in canary that doesn't exist at the published version we have to set a resolution for (see https://github.com/dotansimha/graphql-code-generator/issues/9808). `yarn rwfw project:tarsync` overwrites the resolutions, so you have to add it back after running the command which is annoying. This just makes it add the tarball resolutions to the existing ones:
```json5
"resolutions": {
// This is now preserved
"@graphql-codegen/visitor-plugin-common": "4.0.1",
"@redwoodjs/fastify-plugin-streaming": "./tarballs/redwoodjs-fastify-plugin-streaming.tgz",
"@redwoodjs/api": "./tarballs/redwoodjs-api.tgz",
"@redwoodjs/api-server": "./tarballs/redwoodjs-api-server.tgz",
// ...
}
```
> chore(fwtools): handle existing resolutions in tarsync

- __fixtures__/test-project/web/package.json
- packages/router/src/__tests__/util.test.ts
- packages/router/src/util.ts
Encodes URL query params according to the rules here https://blog.lunatech.com/posts/2009-02-03-what-every-web-developer-must-know-about-url-encoding
Fixes https://github.com/redwoodjs/redwood/issues/9839
> Fix url query param encoding

- packages/cli/src/commands/generate/__tests__/helpers.test.js
We've been testing the wrong thing the whole time 😅 
Lucky us nothing broke without us noticing 😀 
Now actually testing `Decimal` and not `Float`!
> mapPrismaScalarToPagePropTsType: Fix Decimal test case

- packages/cli/src/commands/generate/service/service.js
- packages/cli/src/commands/generate/service/templates/test.ts.template
We were using `substr` in a few places. It's been deprecated, so I'm switching to `slice` instead.
> packages/cli: Switch from substr (deprecated) to slice

- docs/docs/realtime.md
i believe it's either _a subscription can yield_ or _a subscription yields_
> docs(typo): correct grammar in realtime docs

- .github/workflows/ci.yml
- packages/create-redwood-app/jest.config.js
- packages/create-redwood-app/package.json
- packages/create-redwood-app/tests/e2e.test.ts
- packages/create-redwood-app/tests/templates.test.ts
- packages/create-redwood-app/vitest.config.mts
- yarn.lock
Continuing the exploration of switching packages over to vitest.
Notes:
1. The `test:e2e` required a small change to the default vitest options. We have to add `--pool=forks` (see: https://vitest.dev/config/#pool-1-0-0 for the pool option). This is because we're using zx to do things like change directories. This is not possible with the default `threads` pool. See: https://github.com/vitest-dev/vitest/issues/566 for more information related to the specific error that I encountered.
> chore(crwa): switch to vitest

- packages/create-redwood-app/src/create-redwood-app.js
It successfully completed my command (quitting the install), so should exit with a successful exit code
> Fix(crwa): Exit 0 after Quit install

- .github/workflows/ci.yml
Forgot to set `REDWOOD_CI` and `REDWOOD_DISABLE_TELEMETRY` when I added e2e tests for CRWA in https://github.com/redwoodjs/redwood/pull/9783. It may be better to just set `REDWOOD_CI` at the very top of the workflow file but I wasn't sure if we're testing for its absence sometimes like we do for `REDWOOD_DISABLE_TELEMETRY` I think.
> chore(crwa): set `REDWOOD_CI` and `REDWOOD_DISABLE_TELEMETRY`

- packages/cli/src/commands/studioHandler.js
Need to call `serve()` with `enableWeb: true`, otherwise only the api side will start (this is for `yarn rw dev` inside the Studio project, which runs the web side separately)
> fix(studio): Upgrade to 11.0.1 and enable web-side

- packages/cli/src/commands/upgrade.js
Studio is versioned separately. It's a separate project with it's own versions. So it should not be included in the packages that `yarn rw upgrade` tries to upgrade.
> fix(cli): Skip Studio when running `rw upgrade`

- packages/create-redwood-app/src/create-redwood-app.js
- packages/create-redwood-app/tests/e2e.test.ts
By cd-ing into the new rw app directory we make sure `yarn install` is executed by yarn v4 (or whatever version is set in the root package.json)
> feat(crwa): Always install using yarn v4

- packages/create-redwood-app/package.json
- packages/create-redwood-app/scripts/buildPack.js
- packages/create-redwood-app/templates/js/web/package.json
- packages/create-redwood-app/templates/ts/web/package.json
- packages/create-redwood-app/tests/e2e.test.ts
- packages/create-redwood-app/tests/e2e_prompts.sh
- packages/create-redwood-app/tests/e2e_prompts_git.sh
- packages/create-redwood-app/tests/e2e_prompts_m.sh
- packages/create-redwood-app/tests/e2e_prompts_node_greater.sh
- packages/create-redwood-app/tests/e2e_prompts_node_less.sh
- packages/create-redwood-app/tests/e2e_prompts_overwrite.sh
- packages/create-redwood-app/tests/e2e_prompts_ts.sh
This PR fixes the CRWA e2e tests after the functionality introduced in https://github.com/redwoodjs/redwood/pull/9861.
For now I'm skipping `yarn install` since it's prone to timeouts in CI, and the subsequent step, generating types, is also flakey since `yarn pack` seems to skip the `.yarnrc.yml` which is necessary for configuring a proper install.
> chore(crwa): update e2e test to handle yarn install patch

- .github/actions/telemetry_check/check.mjs
The check is currently running indefinitely as it is waiting for the result of a prompt. This PR passes the `--no-yarn-install` flag to prevent this. That flag was introduced in #9861
> chore(ci): Fix CRWA telemetry check

- packages/project-config/.babelrc.js
- packages/project-config/jest.config.js
- packages/project-config/package.json
- packages/project-config/src/__tests__/config.test.ts
- packages/project-config/src/__tests__/paths.test.ts
- packages/project-config/vitest.config.mts
- yarn.lock
Switches our tests in `@redwoodjs/project-config` over to vitest.
> chore(project-config): switch to vitest

- packages/mailer/core/package.json
- packages/mailer/core/src/__tests__/mailer.test.ts
- packages/mailer/core/src/__tests__/utils.test.ts
- packages/record/package.json
- packages/record/src/redwoodrecord/__tests__/Core.test.js
- packages/record/src/redwoodrecord/__tests__/RedwoodRecord.test.js
- packages/record/src/redwoodrecord/__tests__/Reflection.test.js
- packages/record/src/redwoodrecord/__tests__/RelationProxy.test.js
- packages/record/src/redwoodrecord/__tests__/Validation.test.js
- packages/telemetry/package.json
- packages/telemetry/src/__tests__/sendTelemetry.test.js
- packages/tui/package.json
- packages/tui/src/__tests__/index.test.js
- yarn.lock
This PR:
1. Switches `@redwoodjs/mailer-core` to vitest
2. Removes the blank test and testing deps for `@redwoodjs/tui`
3. Switches `@redwoodjs/telemetry` to vitest
4. Switched `@redwoodjs/record` to vitest
These changes have been made because the were relatively easy to do. They're not any particular priority.
> chore: switch some more packages to vitest

- packages/vite/package.json
- packages/vite/src/__tests__/viteNestedPages.test.mts
- packages/vite/src/plugins/__tests__/remove-from-bundle.test.mts
- packages/vite/src/plugins/__tests__/swap-apollo-provider.test.mts
- packages/vite/vitest.config.mts
- yarn.lock
The vite package used the node test runner. This PR switches it over to vitest.
The transition was not difficult.
1. `before` and `after` for the node test runner have their vitest equivalents in `beforeAll` and `afterAll`. See: https://nodejs.org/api/test.html#afterfn-options where `after` is described as acting like `afterAll`.
2. Usage of `assert` was not too difficult to transition as they could be switched to `.toEqual` and `.not.toEqual`
3. Mocking of `fs` was achieved using spys and `mockImplementationOnce`. There was no clear need to use `Once` but it felt safer to assume that rather than continue to return the mock value for eternity.
@dac09 As requested I've switched this one out. One of the ts expect error comments is gone but one remains. From what I can see it seems to be a …
> chore(vite): switch to vitest

- packages/api-server/src/plugins/graphql.ts
Fixes the issue @Tobbe and I were seeing in studio:
```
~/redwood-project/node_modules/avvio/boot.js:244
throw new AVV_ERR_ROOT_PLG_BOOTED()
^
AvvioError [Error]: Root plugin has already booted
...
```
`fastify.ready` actually starts the server. All this is doing is logging. We want to use `addHook` instead. Follow up to https://github.com/redwoodjs/redwood/pull/9845.
> fix(createServer): use addHook instead of ready

- packages/cli/src/commands/__tests__/studioHandler.test.js
- packages/cli/src/commands/studioHandler.js
- packages/cli/src/lib/packages.js
* Only specify major version when installing Studio, so we always get the latest non-breaking features and bug fixes
* Make sure the user's RW version is compatible with the version of Studio we're installing.
Right now we're very specific with what version of RW we support, down to the canary version level. Reason is we need the new server-file stuff that was introduced in an earlier canary version
> fix(studio): Add version checks when first running Studio

- docs/docs/how-to/oauth.md
- docs/versioned_docs/version-6.3/how-to/oauth.md
- docs/versioned_docs/version-6.4/how-to/oauth.md
- docs/versioned_docs/version-6.5/how-to/oauth.md
- docs/versioned_docs/version-6.6/how-to/oauth.md
Went to add OAuth to one of my apps and realized that this had the old, manual method of encrypting the cookie. dbAuth now exports a shared function that you can use instead (which uses the new, more secure encryption algorithm).
Also realized I should have been following good Redwood practice and reuse the existing user creation service function rather than creating the user via Prisma directly.
The docs have been backported to 6.3 and up since the new algorithm was released in 6.3.3.
> Updates OAuth how-to to use new cookie encryption function, use user service for creation

- packages/create-redwood-app/src/create-redwood-app.js
- packages/create-redwood-app/tests/e2e.test.ts
Follow up to https://github.com/redwoodjs/redwood/pull/9861.
> fix(crwa): remove yarn-install option for yarn 1

- packages/cli/testUtils.d.ts
A few additional jest -> vitest changes for the cli package
Related: https://github.com/redwoodjs/redwood/pull/9863
> chore(cli tests): jest -> vitest

- packages/internal/src/generate/trustedDocuments.ts
- packages/web/src/global.web-auto-imports.ts
When Trusted Documents were introduced in https://github.com/redwoodjs/redwood/pull/9416 we accidentally lost the type for the global `gql` tagged template literal function.
This PR adds the global type back, and also improves the function we generate to handle matching `gql` for both regular RW projects and for TD-enabled RW projects.
New projects created with `yarn create redwood-app` currently gives you this for the `gql` tagged template literal function
Switching to canary, to get the code that enables support for TDs (with or without actually enabling them) makes it look like this
With this PR in place you'd instead see this, which is obviously better than red squiggles, but also better than what we've ever had before, imo
> fix(gql): Add back gql global type

- __fixtures__/example-todo-main/web/src/graphql/gql.ts
@Tobbe This looks to have failed publishing the canary/rc due to the uncommited changes that result after running `yarn test`. This was only file that changed for me but perhaps you have some more context on others that might also need updating.
> chore(fixtures): Update gql file content as a result of trusted documents fix

- packages/adapters/fastify/web/build.mjs
- packages/adapters/fastify/web/package.json
- packages/adapters/fastify/web/src/helpers.ts
- packages/adapters/fastify/web/src/web.ts
- packages/api-server/src/cliHandlers.ts
- packages/cli/package.json
- packages/cli/src/commands/serve.js
- packages/cli/src/commands/serveBothHandler.js
- packages/fastify/src/index.ts
- yarn.lock
Move `coerceRootPath()` to the new `@redwoodjs/fastify-web` package.
It was previously exported from `@redwoodjs/fastify`, but everyone who imported it from there uses it together with `redwoodFastifyWeb`, which is exported from `@redwoodjs/fastify-web`, so I thought it made sense this function also lives there.
Also managed to remove a duplicated implementation from another package.
> chore(cli): Move coerceRootPath()

- packages/cli/src/commands/studioHandler.js
Studio now imports from `@redwoodjs/fastify-web` which was introduced in a newer canary than what our min version was previously set to. So need to update it, or you'll get runtime errors when trying to start Studio if your canary version is too old
> fix(studio): Bump minimum RW canary version

- packages/web/src/components/Metadata.tsx
We can import this straight from node_modules instead of loading all the index which imports a bunch of other files and node_modules first.
> fix(web): import helmet from node_modules

- packages/adapters/fastify/web/src/web.ts
- packages/api-server/src/createServer.ts
- packages/api-server/src/plugins/graphql.ts
- packages/fastify/src/api.ts
Running `yarn rw serve` in the v7 RC emits two warnings:
```
$ yarn rw serve                                         
...
(node:69556) [FSTWRN002] FastifyWarning: The redwoodFastifyWeb plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
(Use `node --trace-warnings ...` to show where the warning was created)
(node:69556) [FSTWRN002] FastifyWarning: The redwoodFastifyAPI plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
```
These seem to be because the fastify plugins are async but use the `done` param, which is the callback style. This PR removes the callback style in favor of the async. 
I'm also removing this warn log which we've already handled on the frontend by registering a warning …
> fix(server): don't mix async and callback styles

- docs/docusaurus.config.ts
- docs/src/components/FileExtSwitcher.tsx
- docs/src/remark/file-ext-switcher.mjs
This should show the correct file extension depending on what language you have selected, not both of them
This PR fixes that
> fix(docusaurus): Make {jsx,tsx} file extensions switch properly

- __fixtures__/test-project/scripts/seed.ts
- packages/create-redwood-app/templates/js/scripts/seed.js
- packages/create-redwood-app/templates/ts/scripts/seed.ts
Makes it so that the default seed script we ship with our templates are safe to run multiple times. It'll now just skip updating the DB if it already has records in there.
This also makes the template more closely match what we have for our CI tests
> feat(crwa): Make the seed template idempotent

- packages/web/src/apollo/links.tsx
By using `RedwoodApolloLinks` to build `RedwoodApolloLinkName` we make sure they're never out of sync
> chore(apollo): Introduce TS type helper to reduce repetition

- __fixtures__/fragment-test-project/scripts/seed.ts
- __fixtures__/test-project/scripts/seed.ts
- packages/create-redwood-app/scripts/tsToJS.js
- packages/create-redwood-app/templates/js/scripts/seed.js
- packages/create-redwood-app/templates/ts/scripts/seed.ts
Tidy up the output when running the seed script. We know the exact name of the file – so let's use that 🙂 
Before
After
And running the ts-to-js script looks like this (see the new output at the end)
> fix(crwa): Use actual filename in seed file template

- packages/internal/src/__tests__/__snapshots__/typeDefinitions.test.ts.snap
- packages/internal/src/__tests__/typeDefinitions.test.ts
- packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
- packages/internal/src/generate/typeDefinitions.ts
We generate `.redwood/types/includes/web-routerRoutes.d.ts` to provide proper types for `routes` that users import from `@redwoodjs/router`. 
This file used to be a lot more complicated, but was greatly simplified in https://github.com/redwoodjs/redwood/pull/6364. However, we forgot to remove an import that's no longer used. This PR cleans that up
> fix(internal): Remove unused import

- .vscode/settings.json
- packages/cli/src/commands/__tests__/serve.test.js
- packages/cli/src/commands/deploy/flightcontrol.js
- packages/cli/src/commands/deploy/render.js
- packages/cli/src/commands/serve.js
- packages/cli/src/commands/serveBothHandler.js
Follow up to https://github.com/redwoodjs/redwood/pull/9948; missed a few things at the end there:
- misspelled "description" in a test mock
- the server file and both server handlers take the same options, so I deduped them
- related, I wasn't passing apiRootPath through to the server file handler
- I incorrectly accessed `.handler` on `apiServerHandler` in flightcontrol and render
> fix(server): spelling, fix deploy handler imports, dedupe server builder

- packages/api-server/src/createServerHelpers.ts
Both `--host` and `--port` can't use the `-p` alias (or "short").
Didn't want to use `-h` for `--host`, because `-h` should mean "help".
So I decided to just get rid for the alias. People will have to use the long-form arg
> fix(api-server): Remove duplicate command alias

- packages/mailer/handlers/resend/README.md
The docs said:
```
yarn rw workspace api ... 
```
Removed `rw` from the `yarn install` command.
```
yarn workspace api ... 
```
> docs(typo): Removed `rw` from `yarn install` command

- packages/project-config/src/__tests__/config.test.ts
- packages/project-config/src/__tests__/fixtures/redwood.studio.dbauth.toml
- packages/project-config/src/__tests__/fixtures/redwood.studio.supabase.toml
- packages/project-config/src/__tests__/fixtures/redwood.studio.toml
- packages/project-config/src/config.ts
Removes unused `inMemory` setting from Studio config
The database is now always written to disk
> fix(studio): Remove unused setting inMemory

- .vscode/settings.json
- docs/docs/studio.md
Be more explicit about available settings
Update section on availability to mention RW v7
> Update Studio docs

- packages/cli/src/testUtils/matchFolderTransform.ts
- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/README.md
- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__testfixtures__/input/graphql.config.js
- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__testfixtures__/output/graphql.config.js
- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/__tests__/updateGraphqlConfig.test.ts
- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/updateGraphqlConfig.ts
- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/updateGraphqlConfig.yargs.ts
- packages/codemods/src/testUtils/matchFolderTransform.ts
Replaces the root `graphql.config.js` file with one that includes types and gql
documents support.
Fetches the file from the create-redwood-app template files on GitHub
No jscodeshift is involved.
> feat(gql): Codemod existing projects to get newest gql config

- CONTRIBUTING.md
https://github.com/redwoodjs/redwood/pull/9579 also applies here, took like an hour to get a `yarn build` to succeed because a build was very close to working but didn't
> Mention the you need corepack enabled to run this repo

- packages/web/src/components/cell/cellTypes.ts
- packages/web/src/components/cell/createSuspendingCell.tsx
1. Cleans up some of the comments
2. Makes sure we pass variables passed to refetch, when we wrap it for the failure component
> fix(cell-suspense): pass through variables if passed to refetch

- packages/vite/src/rsc/rscBuildClient.ts
- packages/vite/src/rsc/rscBuildServer.ts
We load env files on our own, and set extra env variables etc. So don't want Vite to conflict with that.
We already have this setting configured in `rw-vite-dev.mjs`, `internal/src/build/web.ts` and out main vite plugin in `vite/src/index.ts`
> RSC: Take full control over the env vars

- packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
- packages/vite/src/rsc/rscBuildClient.ts
- packages/vite/src/rsc/rscBuildServer.ts
Slightly modified the logic for when RW inserts `export default createCell(...` at the end of cells to make it work with how RSC builds everything.
Enabled the web babel plugins when building for client and server
On the app side of things what you'll have to do is add `"use client"` to the top of your cell
> RSC: Enable babel plugins to get client Cell support

- docs/docs/docker.md
- packages/cli/src/commands/experimental/templates/docker/Dockerfile
- packages/cli/src/commands/experimental/templates/docker/docker-compose.prod.yml
PRing some fixes @Josh-Walker-GM tipped me off to:
- We need to add the `RUN mkdir -p /home/node/.cache` instruction after `RUN mkdir -p /home/node/.yarn/berry/index`. I still can't reliably reproduce this one, but have seen it fail reliably before too for sure and this seems to fix it
- I forgot to remove `--load-env-files` when I did the api-server work. It's a no-op now
- I forgot to change `API_HOST` to `API_PROXY_TARGET`
Adding a few style tweaks while I'm here:
- I guess I used `yarn redwood`? This isn't the tutorial
- Fixed a typo in the docs
> fix(docker): corepack permissions fix and style updates

- packages/api-server/src/__tests__/createServer.test.ts
- packages/api-server/src/__tests__/fixtures/redwood-app/redwood.toml
Just helps when you have another RW server running in the background :) 
I tried mocking with vitest, but it gets complicated because some of the test cases check against `getConfig` - this is good enough
> fix(test): Update createServer test to use a different port to normal

- packages/cli/src/commands/setup/auth/auth.js
- packages/cli/src/lib/packages.js
Some time ago I think I made the call to use `yarn npm info` to get information from NPM about a package's version because I didn't want to install yet another dependency. This was the wrong move in hindsight since it meant 1) spawning a child process and 2) while it seemed safe to assume that Redwood projects would have a version of yarn with the `npm` subcommand, this wasn't true in practice.
Now that fetch is in Node.js, we can just use that like @Josh-Walker-GM has elsewhere:
https://github.com/redwoodjs/redwood/blob/019361550736f5ed733c37d7f5241583f26d405b/packages/cli/src/commands/experimental/setupDockerHandler.js#L330-L339
I think this might fix the bug you saw when deploying yesterday.
> fix(cli): use fetch instead of `yarn npm info`

- packages/cli/src/commands/experimental/templates/docker/docker-compose.dev.yml
- packages/web-server/package.json
- yarn.lock
**Problem**
By default when once you have run the experimental setup command for docker, the compose setup for dev and prod doesn't quite work. 
**Changes**
1. We add missing `fs-extra` dependency for the `@redwoodjs/web-server`, it is a runtime dependency.
2. We add a `REDWOOD_API_HOST=0.0.0.0` env var for the dev setup. This is required for the vite dev server to proxy requests correctly. 
**Notes**
@jtoar I'm not overly sure how to test the compose with the updated dependency of the web-server package. Adding the dependency to the web side itself did work so I would imagine this works fine too.
> fix(docker): compose dev and prod

- packages/api-server/src/createServer.ts
- packages/api-server/src/plugins/graphql.ts
This PR fixes two things related to the server file and the GraphQL function.
- we have to specify file extensions with `await import` for relative paths; there was one missing for importing the graphql plugin
- out of the box the graphql function was registered with double slashes since `graphiQLEndpoint` defaults to `'/graphql'` and `apiRootPath` defaults to `'/'`, resulting in `'//graphql'`
> fix(server): use file extension in import, fix graphql route registering

- __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
I missed updating a few fixtures in https://github.com/redwoodjs/redwood/pull/9727 and this is the test that’s failing in https://github.com/redwoodjs/redwood/pull/9985.
> chore: update rsc fixture

- __fixtures__/test-project/web/src/layouts/BlogLayout/BlogLayout.tsx
- packages/router/src/ActivePageContext.tsx
- packages/router/src/AuthenticatedRoute.tsx
- packages/router/src/PageLoadingContext.tsx
- packages/router/src/__tests__/links.test.tsx
- packages/router/src/__tests__/useMatch.test.tsx
- packages/router/src/createNamedContext.ts
- packages/router/src/index.ts
- packages/router/src/link.tsx
- packages/router/src/location.tsx
- packages/router/src/navLink.tsx
- packages/router/src/params.tsx
- packages/router/src/redirect.ts
- packages/router/src/router.tsx
- packages/router/src/util.ts
- tasks/test-project/codemods/blogLayout.js
Splitting up some files in the router package into smaller pieces for finer granularity when importing things.
This gets more important with RSCs where you don't want a single client-only import in a file block the usage of all the functions/components in that file.
When putting `<Link />` and `<NavLink />` into separate files I also took the opportunity to use a composition pattern, so that `<NavLink />` internally uses `<Link />`. To make sure I didn't break anything when doing so I updated our test project fixture to use `<NavLink />`s for the main blog layout, and gave them all a nice little underline to show what page you're currently on
> chore(refactor): Router: Splitting things up into smaller files

- packages/web/package.json
- yarn.lock
Lenz on the Apollo team has created a special Redwood version of their NextJS SSR package. It's only available as a PR build right now, so we can't use the latest version of the package available from the npm registry.
> fix(dependencies): Use RW-specific version of apollo ssr package

- packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
When building for RSC we actually build it three times
1. Analyze the source code to find 'use client' and 'use server'
2. Build for the client
3. Build for the server
In the last step, where we build for the server, babel (for some unknown reason) parses over the files multiple times and keeps plugins in memory. And because it keeps plugins in memory plugin-scoped variables keep their values between different files. This caused a problem for us when transforming cells, so now I clear those variables as soon as we enter a new file.
> RSC: Fix babel-plugin-redwood-cell to work wiht more than one cell

- __fixtures__/test-project-rsc-external-packages-and-cells/.redwood/README.md
- __fixtures__/test-project-rsc-external-packages-and-cells/.vscode/launch.json
- __fixtures__/test-project-rsc-external-packages-and-cells/.vscode/tasks.json
- __fixtures__/test-project-rsc-external-packages-and-cells/api/db/schema.prisma
- __fixtures__/test-project-rsc-external-packages-and-cells/api/package.json
- __fixtures__/test-project-rsc-external-packages-and-cells/api/src/lib/auth.ts
- __fixtures__/test-project-rsc-external-packages-and-cells/api/tsconfig.json
- __fixtures__/test-project-rsc-external-packages-and-cells/graphql.config.js
- __fixtures__/test-project-rsc-external-packages-and-cells/package.json
- __fixtures__/test-project-rsc-external-packages-and-cells/scripts/tsconfig.json
- __fixtures__/test-project-rsc-external-packages-and-cells/web/package.json
- __fixtures__/test-project-rsc-external-packages-and-cells/web/tsconfig.json
- __fixtures__/test-project-rsc-external-packages-and-cells/web/vite.config.ts
This PR builds on top of what https://github.com/redwoodjs/redwood/pull/9990 started.
The goal is to make the test project fixture match what you'd get if you did this right now, with the latest canary
```
npx -y create-redwood-app@canary -y ~/tmp/rw-test-project
yarn rw experimental setup-streaming-ssr -f
yarn rw experimental setup-rsc
```
> RSC: Keep aligning test project with CRWA template

- packages/auth-providers/firebase/setup/src/setupHandler.ts
To match the same version on redwood's api, otherwise it will fail to work after auth setup.
> bug: Update setupHandler.ts firebase version

- packages/cli/src/lib/index.js
Before:
After:
With properly formatted jsdocs we get better hover help texts.
---
This is just a chore, because this is only code that's used internally
> chore(jsdocs): Fix jsdoc formatting for hover help

- packages/cli/src/commands/destroy/helpers.js
- packages/cli/src/commands/destroy/page/page.js
- packages/cli/src/commands/destroy/sdl/sdl.js
Fix "destroy" spelling when reporting command usage using telemetry
> fix(telemetry): Fix 'destroy' spelling

- packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
- packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
- packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldCustomIdName.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMulti.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiNoNest.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiwordNoNest.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNoNest.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/shouldUseEmptyAsUndefined.test.js
- packages/cli/src/commands/generate/scaffold/scaffold.js
- packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/NameCell.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.tsx.template
- packages/cli/src/commands/generate/scaffold/templates/components/NewName.tsx.template
When the RSC experimental feature is enabled the scaffold generator will now insert `'use client'` at the top of the client only components that it generates
> RSC: Insert 'use client' in scaffolded components

- packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
The resetting of `exportNames` and `hasDefaultExport` is now done in `enter()` instead, to also cover the cases of early returns in `exit()`. So no need to repeat at the end of `exit()`
> RSC: babel-plugin-redwood-cell remove redundant reset

- docs/docs/realtime.md
> Typos in realtime.md

- packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
- packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.fetch.test.js
- packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Fixes bug when User table had a primary key other than `id`. Shout out to @will-ks for finding this!
For apps which had a primary key other than `id`, all users will be logged out on their next request after this is deployed.
Not sure if we consider that breaking? But it is 7.0 so anything goes!
Closes #10005
> 7.0 RC: Remove hardcoded check for `session.id`

- packages/cli/src/commands/serveBothHandler.js
@dac09 pointed me to this bug; looks like we were still hardcoding the port passed to the api server for RSC/SSR serve.
Not sure if this should be milestoned RSC or SSR since it applies to both.
> fix(RSC/SSR): pass CLI options through to apiServerHandler

- __fixtures__/test-project-rsc-external-packages-and-cells/web/src/components/UserExample/UserExampleServerCell/UserExampleServerCell.tsx
- packages/babel-config/src/plugins/babel-plugin-redwood-cell.ts
- packages/web/src/components/cell/createServerCell.tsx
Make the `data` export lowercase instead of uppercase. It's a function, not a constant 🙂
> RSC: server cells lowercase data function

- tasks/update-package-versions
Adding back the `update-package-versions` task for @dac09 for publishing experimental releases. I resurrected this file from the commit just before https://github.com/redwoodjs/redwood/commit/05192858f5aeca715a5b4975e99094253c2d3825 which removed it.
> chore(release): add back `update-package-versions` task

- packages/testing/package.json
- yarn.lock
Have been thinking about this one on and off for a while now and I don't think any of our packages should have the react types packages as dependencies if the web workspace in apps is going to have them.
More generally, if a Redwood app is going to explicitly depend on a package that one of our framework packages also depends on, one of them should go or use the `'*'` specifier.
I ran into an issue related to this a day or two ago with the deploy target CI providers. It was easily fixed if you knew what to look for. Unpinning them was a step forward cause yarn can sometimes make it work if you run dedupe or at worst edit or regenerate the lock file. But most people don't know what to look for and we shouldn't expect them to.
The reason we didn't do this before (see the original comment in …
> fix(deps): remove react types packages from `@redwoodjs/testing` dependencies

- packages/api-server/src/__tests__/createServer.test.ts
- packages/api-server/src/createServer.ts
Running the server file via node means `RWJS_CWD` will never be set so we can't rely on it to load env files. I seemed to have gotten this right for the web server in https://github.com/redwoodjs/redwood/pull/9948 but missed it here in the api server.
> fix(server): fix env var loading in `createServer`
