redwoodjs/graphql

packages/hammer-cli/package.json, packages/hammer-cli/src/commands/New/New.js, yarn.lock
I created a new hammer app and was confused why `yarn dev` wasn't working right away—no packages were installed! 
This PR automatically installs packages using `yarn` or `npm` (whichever is installed on the user's system) after hammer.zip is unzipped in the target directory. The output is piped to the terminal as usual so the user can see what's going on.
One less thing for a newbie to worry about!
=> Automatically install packages after copying over hammer.zip

packages/eslint-config/index.js, packages/eslint-config/package.json, packages/eslint-plugin-redwood/index.js, packages/eslint-plugin-redwood/package.json, packages/eslint-plugin-redwood/src/no-unavailable-pages.js, packages/scripts/config/webpack.config.js, packages/scripts/loaders/routes-auto-loader.js, yarn.lock
This Webpack loader will add import statements for all pages from `web/src/pages` onto the top of the `web/src/Routes.js` file. This was the easiest approach I could find to make this work, and wanted to give it a try. It works for nested Pages too:
```
'src/pages/HomePage/HomePage.js'         -> HomePage
'src/pages/Admin/BooksPage/BooksPage.js' -> AdminBooksPage
```
=> First try at a Routes auto-loader

packages/scripts/config/webpack.config.js, packages/scripts/src/loaders/cell-loader.js
This PR shows a Webpack-loader approach to eliminating the need for the `index.js` file in cells. It looks in the cell file for the various possible exports and then default exports `withCell` with just the exports that exist. This should be identical in functionality to the `index.js` file that we currently use in the example apps.
Closes #30.
=> Automatic withCell for cells.

packages/cli/src/commands/Generate/Generate.js
(fix) typo "Appened" -> "Appended"
=> (fix) typo "Appened" -> "Appended"

packages/scripts/config/webpack.config.js
Requires the latest @redwoodjs/core on master.
=> Fix devtoolModuleFilenameTemplate for prod

packages/cli/package.json, packages/cli/src/commands/Self/Self.js, packages/cli/src/components/CommandList.js, packages/cli/src/index.js, packages/cli/src/lib/index.js
This adds commands that are useful for redwoodjs project developers:
`yarn rw self build ../path/to/redwood/library` will build and watch all the redwood packages.
`yarn rw self link` will create a symlink using `yarn link "@redwoodjs/*"` for all the redwood packages in your current project.
Closes #58
=> Add self commands

packages/cli/src/commands/Build/Build.js, packages/cli/src/commands/Db/Db.js, packages/cli/src/commands/Dev/Dev.js, packages/cli/src/commands/Tools/Tools.js, packages/cli/src/components/CommandList.js, packages/cli/src/components/Header.js, packages/cli/src/index.js, packages/cli/src/lib/index.js
This adds the following commands to the CLI
* `build`: `yarn rw build` / `yarn rw build api` / `yarn rw build api,web`
* `db`: `yarn rw db up` / `yarn rw db save` / `yarn rw db seed`
* `dev`: `yarn rw dev` / `yarn rw dev api` / `yarn rw dev api,db`
* `tools`:  `yarn rw tools lint` / `yarn rw tools link:fix`
Closes #65
=> Add commands to CLI

packages/api/__mocks__/@redwoodjs/core.js, packages/api/src/__tests__/__snapshots__/importAll.macro.test.js.snap, packages/api/src/importAll.macro.js, packages/cli/src/commands/Build/Build.js, packages/cli/src/commands/Dev/Dev.js, packages/scripts/config/babel-preset.js, packages/scripts/config/webpack.development.js, packages/scripts/config/webpack.production.js, packages/scripts/config/webpackConfig.js, packages/scripts/package.json
We exported config entry points in `web/config/webpack.<prod|dev>.js`, and whilst this allowed user's to modify their webpack configs easily it also makes it more difficult for us to upgrade redwood, and to be "zero config."
Closes #76
=> Make redwood's build and dev commands reference our internal webpack and babel configs.

packages/scripts/config/webpackConfig.js, packages/scripts/package.json, yarn.lock
- organizes css, js, and media directories within `web/dist`
- uses `copy-webpack-plugin` to handle static files in `web/public`, which are copied to root of `web/dist` (handles both files and directories and keeps structure as applicable
Will add PR in `create-redwood-app` with new `/public` directory including `favicon.png` and `robots.txt` by default. Also adding a `README.md` file to the app `web/public` directory with info about use of static files. And `README.md` will be ignored by webpack (potential edge case issue is that _any_ file within `/public` of same name+case will also be ignored).
More info about `copy-webpack-plugin` here:
https://github.com/webpack-contrib/copy-webpack-plugin
=> Handle app static files including favicon and robots.txt

docs/redwood.toml.md, packages/core/src/types.ts, packages/scripts/config/webpack.development.js
Fixes /redwoodjs/redwood/#55
The google said to do this: https://webpack.js.org/configuration/dev-server/#devserveropen
I agree this is the best setting for our getting started tutorial. But this will continually open new browser windows each time we go through a dev server stop/start cycle. In the future this may get annoying and we’ll possibly want to provide a config override on the app side. TBD
=> add browser open:true to webpack config

packages/router/README.md, packages/router/src/page-loader.js
A React class made this feel easier to reason about. 
This fixes the issue of clearing the`loadingTimeout`, removes the cache, and the "noop" branch whilst the component is "loading."
=> Convert PageLoader to React class.

packages/cli/package.json, packages/cli/src/commands/build.js, packages/core/config/webpack.development.js, packages/core/config/webpack.stats.js, packages/core/package.json, yarn.lock
This adds `yarn redwood build --stats` which launches the webpack bundle analyzer.
This also adds a `--verbose / -v` flag to the build steps.
=> Add bundle analyzer commands

packages/api/package.json, packages/api/src/__tests__/__snapshots__/importAll.macro.test.js.snap, packages/api/src/importAll.macro.js
We now place our services in subdirectories (`./api/services/todos/todos.js`). This modifies the glob search pattern to support that.
Closes #122
=> Make `importAll.macro` support subdirectories.

packages/cli/src/commands/dbCommands/generate.js, packages/cli/src/commands/dev.js
Not generating the client causes the dev-server to crash because of the missing package.
=> Run `db generate` before starting dev servers

packages/cli/src/commands/generate/helpers.js
Generator was forcing component file names to be singular. E.g.
`$ yarn rw generate cell blog-posts` generated the files:
-  `./web/src/components/BlogPostsCell/BlogPostCell.js`
This blocked the user from generating `…cell blog-post`.
Removed `pluralize.singular()` to allow user full control over file name plural/singular.
Fixes #125 required for tutorial to work as written.
=> Allow users to generate components with plural names

packages/create-redwood-app/src/create-redwood-app.js
Idea from create-react-app.
@peterp thoughts about this one? Please merge if the code checks out.
=> Git init, add, commit: create-redwood-app

packages/create-redwood-app/src/create-redwood-app.js
Provides a way to effectively have separate READMEs for 'create-redwood-app':
1. Repo: content is contributing developer focused, has instructions and link to tutorial for people who are really looking to install and build via `yarn create`
2. Local App: has setup instructions and helpful links to tutorial, website, etc.
Thoughts about this one @peterp ? 
Has a dependent PR in tutorial repo here: redwoodjs/create-redwood-app/pull/26
=> Set README within create-redwood-app based on context

packages/web/src/graphql/withCell.js
We create a bunch of components in `withCell` that just return null. This removes those so that the `Success` is called rather than`Empty`
=> Remove null components in withCell.

packages/create-redwood-app/src/create-redwood-app.js
Restores @thedavidprice copying of README_APP.md to README.md
Setting `.gitignore` in `create-redwood-app` is the actual one that git is using to figure out what to ignore in the codebase. But we want a different `.gitignore` for the app that's actually created by `create-redwood-app`. So we have a `.gitignore.app` that is the one that the app will use, and this PR updates the install scripts to replace `.gitignore` with `.gitignore.app`.
See https://github.com/redwoodjs/create-redwood-app/commit/699e6f56469698804ded142d1fb9f25acabb9f79
=> Copies .gitignore.app to .gitignore

packages/cli/src/commands/build.js, packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/down.js, packages/cli/src/commands/dbCommands/generate.js, packages/cli/src/commands/dbCommands/save.js, packages/cli/src/commands/dbCommands/up.js, packages/cli/src/commands/dev.js, packages/cli/src/index.js
- Generate the Prisma client during the build step.
- Conditionally generate the Prisma client for dev commands.
- Add option to not generate the Prisma client when running `yarn rw up`
Closes #189
=> Better Prisma client generation in build and dev commands

packages/cli/src/commands/generate/commands/service.js, packages/cli/src/commands/generate/helpers.js
All components we create are PascalCase for their filename (like `components/BlogPost/BlogPost.js`), but services should not be (like `services/posts/posts.js`). 
This code change adds an option to the generator to let you say what directory/name the created file should have.
=> Adds ability to override generated component filename/path

packages/core/config/babel-preset.js
@peterp Continuing the work from #152 which I thought was working when testing locally (I think my yarn lock was keeping packages I had removed).
Previously, I tried to move the auto-import from Webpack to Babel, which worked for Jest but did not work for running the development environment. When I read your recent doc about where/how we build, it seems that Webpack only is how we're building the web/ side, and **not** our file `core/config/babel-preset.js`. Researching a bit further about babel, I think I now understand this code:
```
overrides: [
// ** API **
{
test: './api/',
presets: [
[
'@babel/preset-env',
{
targets: {
node: TARGETS_NODE,
...
```
and this
```
// ** WEB **
{
test: './web',
...
```
is effectively a switch to use the included settings **only** to transpile in the case …
=> add babel auto import to jest test section of config

packages/core/config/webpack.common.js, packages/create-redwood-app/package.json, packages/create-redwood-app/src/create-redwood-app.js
@thedavidprice The task to check for node and yarn versions was not working properly. I decided to use the programmatic API instead.
Listr swallows a bunch of the output so I also decided to split out the functionality into individual functions which made it easier to test during development.
I also removed the bit of code that set the title in the html template and used the functionality that's included in html webpack plugin.
Closes #114
=> Fix check for nodejs and yarn versions

packages/cli/package.json, packages/cli/src/commands/generate/README.md, packages/cli/src/lib/index.js
the cli directory that contains templates is alternately named `Generate` and `generate` in the source.  This fails on case-sensitive file systems, but would not fail on case-preserving/case-insensitive file systems.
This fix updates the code and docs to use all lower-case `generate`.
=> [bug fix] fix case-sensitive generate directory

packages/core/config/webpack.development.js, packages/dev-server/src/main.ts, packages/internal/src/types.ts
Instead of hardcoding/assuming development host to be `localhost`,
make it configurable so that redwood servers being run inside a
container/VM can still be accessed setting host to "0.0.0.0"
The accompanying PR for create-redwood-app is at : https://github.com/redwoodjs/create-redwood-app/pull/32
=> Use host configuration provided in redwood configuration file (so that VM/container users can set it to "0.0.0.0")

packages/dev-server/src/main.ts
Resolution for issue  #220 
Files ending with '.db', '.sqlite', and '-journal' should no longer trigger dev-server refreshes when saved. This will speed up mutations when using SQLite dbs.
=> Prevent dev-server refreshes when mutating SQLite DB

packages/create-redwood-app/src/create-redwood-app.js
Hi there,
Here's a fix for a small typo in `create-redwood-app`.
Kind regards,
Hampus Kraft.
=> Fixing a typo

packages/cli/src/commands/generate/commands/sdl.js
Resolves the problem cited in [#210](https://github.com/redwoodjs/redwood/issues/210)
Per See https://graphql.org/graphql-js/mutations-and-input-types: "Input types can't have fields that are other objects, only basic scalar types, list types, and other input types".
In `generate scaffold`, identify custom types referenced by the model. Load model definitions for those types. Pass definitions to the `modelFieldToSDL` function. Identify the scalar data type used as the `@id` field in the referenced type and use that as the field type for the Input.
This changes the SDL for ___Input types only.  No change to base type, query or mutations.
=> update sdl.js to use scalar datatypes in input types

packages/cli/src/commands/generate/commands/scaffold.js, packages/cli/src/commands/generate/commands/sdl.js
Addresses issue #235 
Redwood currently doesn't support [composite ids](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#ids) and expects a single id
=> - Drop requirement for ID field to be labeled "id"

packages/cli/src/commands/dev.js, packages/create-redwood-app/src/create-redwood-app.js, packages/dev-server/src/main.ts
We use concurrently to run the web and api dev server commands. It does not allow us to specify the path where the command should be executed so we do something like this:
`cd /Users/my username/to/api && yarn dev-server`, which does not work if you have a space in your path because those need to be escaped with a backslash `\ `.
Fixes #222 
I've asked concurrently if it's possible to supply a cwd for commands: https://github.com/kimmobrunfeldt/concurrently/issues/216
=> Support spaces in directory names for yarn rw dev command.

packages/cli/src/commands/generate/commands/scaffold.js
I was following the [tutorial](https://redwoodjs.com/tutorial/getting-dynamic) and the order of routes was wrong. Here is a simple fix:
Make sure the `/new` route is above the `/{id}` route.
=> Fixed order of routes

packages/cli/README.md
While reading the documentation I noticed there was a typo. This PR fixes is and adds an hyperlink to the tool.
=> Fix typo and add an hyperlink

packages/internal/src/paths.ts
`path.join` caused the auto-imported statements to look like this:
```javascript
const FatalErrorPage = { name: 'FatalErrorPage', loader: () => import('src\\pages\\FatalErrorPage') }
```
They now look like this:
```javascript
importStatement: "const NotFoundPage = { name: 'NotFoundPage', loader: () => import('src/pages/NotFoundPage') }"
```
Fixes #219
=> path.join does not work for import statements on windows

babel.config.js, package.json, packages/api/__mocks__/@prisma/client.js, packages/cli/jest.config.js, packages/cli/src/commands/lint.js, packages/eslint-config/index.js, packages/eslint-config/package.json, yarn.lock
Our babel config ignored test files. The warnings where caused by trying to lint the test files. I no longer ignore test files, and I don't build them when NODE_ENV is production.
I tried `eslint-import-resolver-webpack` so that the directory named modules were resolved, but it didn't seem to do anything.
Closes #258
=> Fix ESLint warnings

README.md
The [oldest living redwood](https://en.wikipedia.org/wiki/President_(tree)) is 3,200 years old, not 2,500 years old.
=> Fix a factual error about redwoods

packages/core/config/babel-preset.js, packages/internal/src/paths.ts, packages/internal/src/types.ts
Added support in create-redwood-app: https://github.com/redwoodjs/create-redwood-app/pull/40
Building off the discussion in https://github.com/redwoodjs/redwood/issues/286 this looks for a local app `dbInstance` config file before resorting to the one in `@redwoodjs/api`. I like the idea of always including this file with a new app so that it's easy for people to change if needed (and we can include comments about how to use it).
Maybe this could be the beginning of a convention to allow configuration files to be put in their own home, `api/config`? And so we need a `web/config` as well? What do you think @mojombo?
* Will hot reloading work if changes are made to this file?
Closes #286
=> Check for local app's copy of dbInstance before resorting to @redwoodjs/api copy

packages/router/package.json, packages/router/src/__tests__/util.test.js, packages/router/src/router.js, packages/router/src/util.js
Regex named capture routes aren't supported in Firefox (and some other browsers), since we generate the regex during runtime we couldn't use the babel-tranform that adds support for them.
This pull requests changes the way that routes are matched:
1. It matches the URL to the route: `'/blog/{year}/{month}/{day}'` matches `'/blog/2019/12/07'`
2. It extracts the strings between `{}`: `'/blog/{year}/{month}/{day:Int}'` => `[['year'], ['month'], ['day', 'Int']]`
3. And applies the transformation if specified.
The data structure returned from `matchPath` remains unchanged: https://github.com/redwoodjs/redwood/blob/9b72f136f30cefaad58876b4aa6d4ced51934643/packages/router/src/util.js#L46
Fixes #205
=> Change the way a path is matched against a route

packages/cli/src/commands/generate/commands/scaffold.js
=> Skip scaffold.css duplication ignorance on Windows

packages/create-redwood-app/src/create-redwood-app.js
I tried `yarn create redwood-app .` in an empty directory where I wanted the files generated, and got an error saying the dir already exists.  
I think it should be OK to use an existing directory if it's empty 🙂 
I have also moved the error out of the Listr task itself, because it seems Listr is not actually stopping execution of the following tasks. At least, it continues outputting the next tasks' titles, which is confusing:
I'd say an early exit for this particular error is acceptable?
=> Allow creating app in existing empty dir

packages/cli/src/commands/generate/commands/service.js
@thedavidprice found that you couldn't run the `service` generator on its own as it expected a `crud` argument to exist that wasn't an option when called from the command line. The tutorial only uses the `scaffold` and `sdl` generators which call to the `service` generator behind the scenes and send in the `crud` argument themselves, so this wasn't exposed for the majority of early adopters.
=> Fix service generator

packages/cli/src/index.js
Addresses an issue for Windows users mentioned here:
https://github.com/redwoodjs/redwood/issues/322#issuecomment-602849062
I spend quite a bit of time looking for other ways to improve help text below. Unfortunately, I couldn't find more helpful options (e.g. provide an alias for main command, main command help text, etc.)
- This will "fix" the command display to be `rw`. Previously on Mac it would display whichever you used to output help (either `redwood` or `rw`). With this change it will _always_ be `rw`
- I added the example, which displays at the bottom. Is this useful to keep? Thoughts about how/if to improve? (Note: this example _only_ displays when help is called on the `rw` command.)
```shell
rw <command>
Commands:
rw build [app..]    Build for production.
rw db <command> …
```
=> Improves Yargs --help output on Windows

packages/cli/src/commands/generate/templates/service/service.js.template, packages/core/config/babel-preset.js
This removes some of the magic.
We feel that having the import visible in the services will help people understand that services are a layer where you can connect your schema to a database, but can also be a request to an API, to Redis, or anything else... the possibilities are endless.
=> Remove auto import of `db`

packages/cli/src/lib/index.js
The `addRoutesToRouterTask` function searches the routes file for `<Router>` and inserts a new route (1-by-1) directly below this line:
```jsx
<Router>
<NewRoute />
```
Since they're always added to the top, the order of `routes` is reversed. We switch it around since users of this function might expect routes to be inserted in the order that they are defined.
https://github.com/redwoodjs/redwood/blob/04f137d149eee5b9bae0a5876e1685c83ec0cb4a/packages/cli/src/lib/index.js#L144-L156
Fixes #211
=> Fix route insertion order

packages/api/package.json, packages/api/src/makeMergedSchema/makeMergedSchema.js
Basically the title says it all!
Motivation in #333 
Unfortunately what @peterp mentioned in https://github.com/redwoodjs/redwood/issues/333#issuecomment-604070287 didn't fly; just swapping out `apollo-server-lambda` for `graphql-tools-fork` didn't work. It seems like `graph-tools-fork` is improving on the seemingly abandoned `graphql-tools`, but not (yet) on custom directive support for `mergeSchemas`.
What _does_ however support custom directives is `makeExecutableSchema`. In order to use this I needed to merge the `typeDefs`, and the only/quickest/cleanest way I could find to do this is using `merge-graphql-schemas`, the second package mentioned by @peterp.  
Using this PR you can pass `schemaDirectives` in `makeMergedSchemas` like so:
```javascript
schema: makeMergedSchema({
schemas, …
```
=> Swap mergeSchemas with makeExecutableSchema

packages/api/package.json, packages/api/src/__tests__/graphQLServer.test.js, packages/api/src/graphQLServer.ts
This makes `handleContext` return a Promise, which `ApolloServer` handles automatically.
This enables users to write asynchronous context functions, e.g. to fetch user data for authentication.
=> Make context handler asynchronous

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Closes #344 
@peterp 
This PR is dependent on PR #349 and should be merged after it is merged.
I first tested the upgrades in #349. Then, using those upgrades, I tested these Prisma2 package upgrades.
🎉 _There are no new errors or issues with the app locally or deployed_   
Confirming this passes build, lint, and tests === ✅ 
https://github.com/thedavidprice/redwood-tutorial-test
https://jovial-bohr-4ac134.netlify.com/
=> Prisma2 packages upgrade to preview025

packages/cli/package.json, packages/cli/src/lib/index.js, yarn.lock
This PR helps us format the generated code using the configuration provided in `prettier.config.js` of a Redwood project.
Closes #339
=> Make generators adhere to `prettier.config.js`

packages/cli/src/lib/index.js
I wanted to change this a bit more but figured I'd start with a small change. Alternatives.
"Schema definition for Post not found in schema.prism file"
=> more explicit where the scheme should be

packages/router/src/page-loader.js
When a user navigates from one page to another the `PageLoader` renders the existing `Page` whilst it is downloading and parsing the next `Page`.
I stored the `Page` in state, but not the `params` 🤦‍♂ 
Fixes #201
=> Save params to stabalize renders.

packages/cli/src/commands/generate/templates/scaffold/assets/scaffold.css.template, packages/cli/src/commands/generate/templates/scaffold/components/NameForm.js.template
Scaffolded form input fields have their width set to 100%, but since their parent has a padding and its box-sizing is set to `inherit`, the field gets cut off.
This commit adds an extra class from Tailwind CSS and applies it to the form container to ensure that the entire inputs are visible.
I wasn’t sure where in the CSS template file to put the new selector since they seem to be grouped by function (rather than alphabetically) and I didn’t find any related selectors, so I stuck it at the end of the list. Let me know if I should move it.
**Before**
**After**
----
**Edit**: added other commits to add consistency to error messages’ margins, see screenshots below:
**Before**
**After**
=> Fix a layout issue with scaffolded forms

packages/router/src/__tests__/util.test.js, packages/router/src/util.js
@cannikin : turns out the `constraint` part of params types was simply not used in path matching 🙂 
Fixes #346
=> [Router] Fixes route matching by enforcing type constraints

packages/api/package.json, packages/cli/package.json, packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/down.js, packages/cli/src/commands/dbCommands/generate.js, packages/cli/src/commands/dbCommands/save.js, packages/cli/src/commands/dbCommands/up.js, packages/cli/src/commands/dev.js, packages/cli/src/commands/generate/commands/sdl.js, packages/core/package.json, yarn.lock
* Updates api, cli and core's `package.json`
* Updates commands that previously called "prisma2" to use just "prisma" now
* Ignores other objects when building Input types
Testing:
* `yarn test` passes 
* in example-blog I deleted the existing migrations, created them from scratch and seeded the database. Site worked as normal.
* new app, created scaffold for a relationship defined with the new syntax
The changes to the schema syntax didn't seem to affect us. Prisma now requires a `@relation` keyword on fields that have X-to-many relationships, but we didn't do anything special to support those anyway so it doesn't seem to make a difference.
I'd like to add support for relationships, but that can be a separate PR.
Does this need to be a 0.5.0 point release? It will make existing schemas …
=> Updates Prisma to 2.0.0-beta.1

CONTRIBUTING.md
CONTRIBUTING.md didn't explicitly say to run `yarn build` after cloning `redwoodjs/redwood` and running `yarn install`, causing files necessary for using the cli locally, such as `main.js` in `redwood/internal`, to not exist. This PR stems from a discussion on discourse: https://community.redwoodjs.com/t/guide-on-redwood-package-development/135/3?u=dom.
=> Add iniital yarn build to CONTRIBUTING.md

packages/cli/src/commands/build.js
yarn rw build api script was not working due to setting the NODE_ENV. Using cross-env fixes the problem.
=> Support for App yarn rw build on Windows

packages/cli/package.json, packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/introspect.js
This is my first PR, and I picked an issue based on the label. Hopefully no one else was looking at it!
=> Changes for #379, `yarn rw db introspect`

packages/web/src/form/form.js
As outlined in #250, when calling `setError` through use of Redwood Forms we bump into a warning like the following:
> Warning: Cannot update a component (`ContactPage`) while rendering a different component (`Label`).
A similar warning is included in the React `16.3.0` [notes](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render) and it appears to be linked to the use of `setState` in `form.js`.
Following the advice linked above -- specifically, “in the rare case that you intentionally want to change the state of another component as a result of rendering, you can wrap the `setState` call into `useEffect`” -- I have made the following amendments.
I have question marks over the specific dependencies that should be included in the `useEffect`, but …
=> Fix setState warning from setError call in Redwood Forms

docs/connectionPooling.md, docs/localPostgresSetup.md
Based on discussion in redwoodjs/redwoodjs.com#87, I've added two docs to the `docs` section.
The first gives more information around Connection Pools, and includes relevant links to recommended providers. ([Rendered](https://github.com/redwoodjs/redwood/blob/ed0eb079ff9f7a67ae7f2ff49d4aef0649a1510e/docs/connectionPooling.md))
The second documents how to setup Postgres locally, and how to have Redwood create/migrate the new database. ([Rendered](https://github.com/redwoodjs/redwood/blob/ed0eb079ff9f7a67ae7f2ff49d4aef0649a1510e/docs/localPostgresSetup.md))
=> Add docs for local Postgres and connection pooling.

docs/localPostgresSetup.md
This was tripping up the HTML parser and causing it to add `.env` to the TOC.
=> Remove code comment in localPostgresSetup.md

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/editCell.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/edit.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/new.js, packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template, packages/cli/src/commands/generate/sdl/__tests__/fixtures/multiWordSdl.js, packages/cli/src/commands/generate/sdl/__tests__/fixtures/multiWordSdlCrud.js, packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js, packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdlCrud.js, packages/cli/src/commands/generate/sdl/sdl.js, packages/cli/src/commands/generate/sdl/templates/sdl.js.template
Following discussions in #316 and #324 I made some updates to the SDL generators. Assuming the following `schema.prisma` definition:
```
model Post {
id       Int      @id @default(autoincrement())
title    String
slug     String @unique
author   String
body     String
image    String?
postedAt DateTime?
}
```
Currently Redwood generates a CRUD SDL that looks like:
```
export const schema = gql`
type Post {
id: Int!
title: String!
slug: String!
author: String!
body: String!
image: String
postedAt: DateTime
}
type Query {
posts: [Post]
post(id: Int!): Post
}
input PostInput {
title: String
slug: String
author: String
body: String
image: String
postedAt: DateTime
}
type Mutation {
createPost(input: PostInput!): Post
updatePost(id: Int!, input: PostInput!): Post
deletePost(id: Int!): Post
} …
```
=> Updates GraphQL SDL Required Types logic

.gitignore, CONTRIBUTING.md, package.json, packages/api/package.json, packages/cli/package.json, packages/cli/src/rwdev.js, packages/core/package.json, packages/create-redwood-app/package.json, packages/dev-server/package.json, packages/eslint-plugin-redwood/package.json, packages/internal/package.json, packages/router/package.json, packages/web/package.json, tasks/publish-local, tasks/run-local-npm, tasks/verdaccio.yml
When contributing to Redwood you'll often want to add, fix, or change something in the Redwood Framework's monorepo, and see the implementation "running "live" in your own side project or one of our example apps.
We offer two workflows for making that possible: "watch and copy" with some restrictions, and "emulate npm" without restrictions. The consideration for using the "emulate npm" workflow is if you've installed or upgraded a dependency, otherwise the "watch and copy" workflow should be fine.
The first step is to watch files for changes and build those changes in the Redwood framework:
```terminal
cd redwood
yarn build:watch
@redwoodjs/api: $ nodemon --watch src -e ts,js --ignore dist --exec 'yarn build'
@redwoodjs/core: $ nodemon --ignore dist --exec 'yarn build'
create-redwood-app: …
```
=> Add workflows for local development

docs/redwood.toml.md, packages/core/config/webpack.common.js
Closes https://github.com/redwoodjs/redwood/issues/427
This PR updates `core/config/webpack.common.js` to include `process.env.*` variables, via `webpack.DefinePlugin`, in 2 cases:
- Prefixed with `REDWOOD_ENV_`
- Matching the set defined in `redwoodConfig.web.includeEnvironmentVariables` via `redwood.toml`
@peterp
=> Support ENV vars in webpack projects

packages/router/src/__tests__/util.test.js, packages/router/src/util.js
Closes #382 
This PR makes `validatePath` throw an error when a route's provided path contains at least one space character.
It's only looking for `' '`; I figured other whitespace characters such as `'\t'`, `'\n'`, ... would make so little sense that it does not warrant "complicating" the code & tests with that.
Super easy to change if you'd rather reject everything though!
I also took the opportunity to fix the duplicate params detection, which was broken when only one of two duplicates used a type, and to refactor the router's utils tests a little 🙂 
**Question:** I intentionally added a test case that validates `'/users/{id}/photos/{photo_id}?format=jpg&w=400&h=400'` as a valid route.
I don't see why not, but I wanted to make sure we actually allow query strings in routes paths?
=> [Router] fixes `validatePath` duplicate params & reject spaces in routes

packages/core/config/webpack.common.js, packages/internal/package.json, packages/internal/src/paths.ts
This removes JavaScript specific things from the api and web servers configurations. The consequence of this is that if you rename your `.js` files to `.ts` or `.tsx` that they'll be picked up by the api development server, and webpack.
I do not think we have any blockers anymore for _developing_ with typescript. After this merges, it's more a case of is that experience good? And can you actually build and deploy to production.
On the api side:
On the web side:
=> TypeScript support: Let api-dev-server and webpack load .ts and .tsx files

packages/cli/package.json, packages/cli/src/redwood-tools.js
@peterp I think I'm getting the hang of this workflow! Thanks again for putting in the time.
- switched command $0 from 'rwdev' to 'redwood-tools', aliased to 'rwt'. 
I think the main need to keep 'redwood-tools' around (if there is one), is it's more readable as a filename. I played around with --help description and couldn't find a way to have alias displayed for $0 command. So might not be needed.
- added `.strict()` to improve error catching on options
Handing over to you for any further tweaks. Go ahead and merge if it's ready.
=> change rwdev to redwood-tools, aliased rwt

packages/cli/src/commands/upgrade.js
Step 1 of #271 
- `yarn rw upgrade` runs an interactive upgrade process
- `yarn rw upgrade --check` checks for outdated packages (without upgrading)
Experimented with [npm-check-updates](https://www.npmjs.com/package/npm-check-updates), [npm-check](https://www.npmjs.com/package/npm-check), and [yarn-check](https://www.npmjs.com/package/yarn-check). Ended up using yarn built-in checks and upgrade. However, [yarn doesn't play nice with its own workspaces](https://github.com/yarnpkg/yarn/issues/4442), go figure, so I was limited to use `yarn upgrade-interactive [packages] --latest`. Other commands/options would not work. 👎 
I also attempted to first build this without Listr, but Execa didn't play nice with the interactive terminal. So Listr it is (I seem to recall we've had this problem …
=> Add 'yarn rw upgrade' helper to upgrade @redwoodjs packages

packages/cli/src/rwdev.js
The CLI for local development, `rwdev` (soon to be renamed!) has a `watch` command, the structure of which seems like it could benefit by being more analogous to `yarn build` and `yarn build:watch`. So it's been reworked to be that way. Now you can run the following commands (complete with aliases).
To copy just once, similar to `yarn build`:
```
yarn rwdev copy RW_PATH
yarn rwdev cp RW_PATH
```
To copy and watch for changes, similar to `yarn build:watch`:
```
yarn rwdev copy:watch RW_PATH
yarn rwdev cpw RW_PATH
```
@peterp I tried to be DRY and factored out a function I called `copyFiles`. Lemme know what you think of this way of doing it.
=> Split rwdev watch into copy and copy:watch

packages/cli/src/commands/build.js
Closes #437 
During an App build process, Prisma errors that may occur do _not_ result in the build itself to fail. This is problematic during deploy: for example, a Netlify deploy may run 'successfully' when in fact the Prisma Client failed to generate or the DB migration failed, etc.
@peterp adding this to tasks.run() seemed obvious. Additionally, I added to `generatePrismaClient()` -- any reactions to this part being overly aggressive? It's hard to test actual failures locally. But the two example cases so far (my own and Chris' in #437) seem to be different sources, e.g. Chris' was Prisma Client and mine was DB migration.
When we are ready to move forward, I will publish a release-candidate for both Chris and me to test against our deployment examples.
=> add process.exit(1) to ensure App build fails on error

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
closes #404 #405 #409 via https://github.com/prisma/prisma/issues/1973
Prisma release notes: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.3
⚠️ I have **not** yet tested deploy. To do before a new release.
=> Upgrade to Prisma-2.0.0-beta.3

CONTRIBUTING.md
This is for reference for #434.
This PR includes changes that I think would be immediate improvements on the document as it stands. It adds a short welcome message, and edits/proofreads CONTRIBUTING.md generally, but shies away from making any major organizational changes.
=> Edit and proofread CONTRIBUTING.md

docs/connectionPooling.md
It's a little weird that line says "MySQL or RDS PostgreSQL". Why is RDS included before "PostgreSQL" but not "MySQL"?
Amazon says connection pooling is supported for "Aurora MySQL, RDS MySQL, Aurora PostgreSQL, and RDS PostgreSQL"
I wonder if we should change "MySQL or RDS PostgreSQL" to just be "MySQL or PostgreSQL"
=> Fix link markup

packages/web/src/form/README.md, packages/web/src/form/form.js
Closes #464
This PR is the implementation of the `radio` text field in the redwood framework. 
The default `required` attribute is `false` for the radio field. If the user wants to have required `true` for a group of radio fields, the user has to pass the prop `validation={{ required: true }}` for all the radio fields/buttons.
To check how `react-hook-form` handles the creation of the radio fields,  It can be checked [here](https://react-hook-form.com/form-builder). They also do `{ required: true }` for all the radio fields in a group. :)
=> feat: add Radio Field

packages/web/src/form/README.md, packages/web/src/form/form.js
Close #463
This PR is the implementation of the `checkbox` field in the redwood framework.
The default required attribute is false for the `checkbox` field. If the user wants to have `checkbox` checked before the form submission, for that the user has to pass the prop `validation={{ required: true }}` for the particular `checkbox`.
=> feature: add checkbox field

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js, packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
=> fixes possible null error in truncate (fixes #484)

packages/web/src/form/README.md
See `<CheckBox>`:
This PR fixes the Markdown syntax so the `<CheckBox>` line is its own list item.
=> Fix typo on CheckBox docs

packages/cli/package.json, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template, yarn.lock
This is my first code contribution to Redwood, so hoping I did this right!
Right now, when you generate scaffolding, the input labels are exactly the names of the database columns. If I were making a Pitchfork clone, it might have this:
I really like how Rails converts those names to more readable labels. Now, using [humanize-string](https://github.com/sindresorhus/humanize-string):
This adds a dependency to the CLI package, but we already have a number of string-converting libraries in use for scaffolding, & it doesn't add any weight to the app dependencies or the forms themselves.
=> Humanize labels on scaffold forms

packages/internal/README.md
Fixing an apostrophe mostly, but also added a link to Redwood & simplified the wording of the last sentence. Not super attached to these other changes, mostly wanted to fix the typo.
=> Fix typo in internal README

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma, packages/cli/src/commands/generate/sdl/__tests__/fixtures/schema.prisma, packages/cli/src/lib/__tests__/fixtures/schema.prisma
Just noticed these were still in some of the fixture schemas.
=> Switch out "Hammer" data source

packages/cli/src/commands/dev.js
=> Fix: 'yarn rw dev' now only starts the API and DB servers when the api folder is present

packages/dev-server/src/main.ts
while following along the redwood tutorial on youtube, I found that we are not logging something after the rebuild. I kept looking on the screen.xD. Then I just tried the request. and it worked.
A console log on rebuild complete might be helpful for people when they are looking in the terminal for the build processes.
Let me know if something is off or it needs further improvement. thanks!!
attaching screenshots for better understanding. 
**before the console log it looks like this. 
** after putting the console log it looks like this.
=> Add console log on rebuild complete

packages/cli/src/commands/generate/__tests__/helpers.test.js, packages/cli/src/commands/generate/function/__tests__/fixtures/multiWord.js, packages/cli/src/commands/generate/function/__tests__/fixtures/singleWord.js, packages/cli/src/commands/generate/function/__tests__/function.test.js, packages/cli/src/commands/generate/function/function.js, packages/cli/src/commands/generate/function/templates/function.js.template, packages/cli/src/commands/generate/helpers.js, packages/cli/src/lib/test.js
=> Adds function generator

packages/core/config/webpack.common.js, packages/core/config/webpack.development.js, packages/core/package.json, yarn.lock
Fixes #140 
Adds the Webpack Plugin 'ErrorOverlayPlugin':
https://github.com/smooth-code/error-overlay-webpack-plugin
**Error display before:**
```javascript
Something went wrong
```
**Error display after:**
=> Improve Error Handling at FatalErrorBoundary

packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template
Use pluralCamelName in place of hardcoded string when performing refetchQuery in delete handler
Fixes #518
=> Fix NamesCell reload after deleting item

packages/api/README.md, packages/core/README.md, packages/create-redwood-app/README.md, packages/eslint-config/README.md, packages/eslint-plugin-redwood/README.md, packages/web/README.md
Some of the Redwood packages lack a README. This PR adds stubs that serve as 1) placeholders and 2) outlines of what's to come. The stubs comprise the following table of contents:
* Purpose
* Package lead
* Roadmap
* Overview
* Contributing
* FAQ
I got the list from @thedavidprice and added a few (Overview, FAQ) myself. This early on, FAQ might be unnecessary (if not impossible).
Not all the sections have to be a section ("Package lead" could be a sentence), but all of them should probably be addressed. Definitely note that this structure is extremely general and will/probably should change between packages.
Definitely welcome feedback on this structure. And answers! (Who is the package lead?)
=> Add README stubs to packages lacking one

packages/core/config/__tests__/__fixtures__/commented/code.js, packages/core/config/__tests__/__fixtures__/commented/output.js, packages/core/config/__tests__/__fixtures__/complete-cell/code.js, packages/core/config/__tests__/__fixtures__/complete-cell/output.js, packages/core/config/__tests__/babel-plugin-redwood-cell.test.js, packages/core/config/babel-plugin-redwood-cell.js, packages/core/config/babel-preset.js, packages/core/config/webpack.common.js, packages/core/jest.config.js, packages/core/package.json
This implements #503 and opens up the possibility for using Cells in Jest!
I've never written a Babel Plugin or done anything with AST's before, so I just wanted to get this out here to gather some feedback before looking into writing tests for it, and also to discuss on where to locate the plugin file!
This also fixes some issues with Cells where they break if you comment out some const exports and supports using function declarations instead of variable function declarations!
=> [Core] Convert custom webpack cell-loader into Babel Plugin

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Prisma release notes: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.4
- **Support for JSON types** unknown if JSON will work with RW, but experiment in progress here https://community.redwoodjs.com/t/jsonb-support-from-prisma-2-0-0-beta4/508/5
- **Support for Yarn workspaces** I'm not sure this applies to RW's setup. In any event, a simple test running `yarn prisma generate` from root failed. This likely has more to do with installation than CLI.
- **Prisma Studio** tests running `yarn prisma studio --experimental` failed. It does not seem studio supports the use of `env(...)` in the schema. Nor supports workspaces (running from api/ couldn't find client in root 'node_modules/.prisma/'
=> Upgrade to Prisma-2.0.0-beta.4

packages/cli/src/commands/upgrade.js
Adds `--canary` option to `yarn rw upgrade`. 
Yarn itself offers poor support targeting any tag besides 'latest' for our use case of workspaces and `yarn upgrade-interactive`. As a result, we are limited to using `yarn upgrade [package@canary]`, which will effectively force upgrade to the most recent 'canary' release. Unfortunately, `yarn outdated`, which checks to see if more recent release is available, is not supported for tags -- this means the `--dry-run` option does not work here either.
Given all this, I'm approaching this as a "Warning, please understand what you are doing before you hit enter" use-case.
- added WARNING in the option description with appropriate language about unstable versions
- did not provide an alias, thus require full use of `--canary`
=> Adds --canary option to CLI upgrade command

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Prisma release notes: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.5
- Now supports Alpine Linux. Untested, but will come in handy for potential, future Docker support
- Now supports Node v14. Untested.
=> Upgrade to Prisma-2.0.0-beta.5

packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPath.test.js, packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathMultiword.test.js, packages/cli/src/commands/generate/scaffold/__tests__/scaffoldPathNested.test.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NameCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template, packages/cli/src/commands/generate/scaffold/templates/layouts/NamesLayout.js.template, packages/cli/src/commands/generate/scaffold/templates/pages/EditNamePage.js.template, packages/cli/src/commands/generate/scaffold/templates/pages/NamePage.js.template, packages/cli/src/commands/generate/scaffold/templates/pages/NamesPage.js.template, packages/cli/src/commands/generate/scaffold/templates/pages/NewNamePage.js.template, packages/internal/src/paths.ts
This PR proposes the following change to the `g scaffold` command:
```
yarn rw g scaffold <path/model>
```
E.g. given the model user, running `yarn rw g scaffold admin/user` will output:
```
$ /home/dominic/projects/redwood/redwood-test/node_modules/.bin/rw g scaffold admin/users
✔ Generating scaffold files...
✔ Writing `./api/src/graphql/users.sdl.js`...
✔ Writing `./api/src/services/users/users.test.js`...
✔ Writing `./api/src/services/users/users.js`...
✔ Writing `./web/src/scaffold.css`...
✔ Writing `./web/src/layouts/UsersLayout/UsersLayout.js`...
✔ Writing `./web/src/pages/Admin/EditUserPage/EditUserPage.js`...
✔ Writing `./web/src/pages/Admin/UserPage/UserPage.js`...
✔ Writing `./web/src/pages/Admin/UsersPage/UsersPage.js`...
✔ Writing …
```
=> Add path specification to scaffolds

packages/auth/README.md
@peterp added instructions to use generator along with a couple other small edits. Look ok?
note: I changed the title to 'Authentication' because it's automatically used as the menu item for docs on redwoodjs.com --> but RC might have an option to add a title. Let me know if Auth is preferred and I'll try to figure out the website menu title separately.
will also create PR to add to website docs.
=> edits, add RW CLI auth generator instructions

packages/cli/src/commands/upgrade.js
closes #546
@peterp Due to inconsistent ways Yarn itself handles 1) workspaces and 2) tags (e.g. @canary), this one got a bit messy. It _is_ working now:
- for each option, upgrade and @canary upgrade, it checks to see if Auth package is installed to determine if it should be included. `yarn upgrade-interactive ...` will do this by default. For `yarn upgrade ...@canary`, things were a bit messier. (Note: upgrade-interactive does not support tags)
- refuses to --dry-run with --canary options; canary effectively force updates to most recent canary, and the `yarn outdated ...` doesn’t know how to handle tags
The only annoying thing left to fixe is **Listr duplicating the titles** when I try to dynamically change them. This was working fine until I added the logic in the first step, 'Checking …
=> Add @redwoodjs/auth package to CLI upgrade command

packages/cli/src/commands/generate/scaffold/scaffold.js
This PR resolves a sub-discussion of #487, and is a continuation of #423. @thedavidprice @cannikin @antonmoiseev
The functionality introduced in #423 remains unchanged--you can still specify a path in the model, but we're no longer calling it `pathSlashModel`. Just `model` now, and the functionality will be revealed in a help message:
<details><summary>Output for <code>yarn rw g scaffold --help</code></summary>
```
~/redwood-app$ yarn rw g scaffold --help
$ /redwood-app/node_modules/.bin/rw g scaffold --help
rw g scaffold <model>
Generate Pages, SDL, and Services files based on a given DB schema Model.
Positionals:
model  Model to scaffold. Optionally may use "path/model" to nest files by
type at the given path directory (or directories)            [required]
Options: …
```
=> Rename pathSlashModel to model and remove path flag

packages/cli/src/commands/upgrade.js
This replaces --canary (boolean) with --tag (choices: canary, rc).
=> CLI upgrade command: add option --tag with choices 'canary' or 'rc'

packages/auth/README.md, packages/auth/src/AuthProvider.tsx, packages/router/src/router.js, packages/web/src/components/RedwoodProvider.js, packages/web/src/graphql/index.js
=> Auth: Rename state and functions

packages/dev-server/src/main.ts
This allows accessing the IP address of the client when using the dev-server.
=> Add IP address to the Lambda event's requestContext in dev server

.github/workflows/publish-npm-canary.yaml
When I update my master branch it keeps failing the actions because it tries to publish the canary version of redwood.
With this the publish version action is only run in the main repository.
=> Do not attempt to publish canary if not original repo

CONTRIBUTING.md
Follow up on [@redwoodjs/redwoodjs.com #129](https://github.com/redwoodjs/redwoodjs.com/pull/129), this PR adds a Reference section for the `redwood-tools` command, and links back to the [CLI Reference on redwoodjs.com](https://redwoodjs.com/reference/command-line-interface).
@thedavidprice One thing I'm concerned about is being too repetitive and self-referential in this doc? But since people might come _straight_ to the Reference section, it might not be a problem to redirect them to sections earlier in the doc because it's all about finding what you want fast?
=> Add reference section to CONTRIBUTING.md

packages/cli/src/commands/dev.js
Related #596
**This addresses two separate problems when paths contain spaces:**
1. errors when checking if dir or file exists: the previous implementation gave a false-negative if the path contained a space
2. running the commands with `concurrently`: running commands will fail if the path spaces are not sanitized
**Solutions:**
- for dir and file validation checks, uses `getPaths()`
- in case of DB, now checks if `schema.prisma` exists
- in case of effectively setting the working directory for `concurrently` (e.g. `cd api/`), we still need to use the "sanitize-path" method  `replace(' ', '\\ ')`, otherwise spaces still cause the run(s) to fail
=> Fix dev server run error when path contains spaces

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/assets/scaffold.css, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/editCell.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/edit.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/indexCell.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/new.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/layouts/layout.js, packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template, packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template, packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template, packages/cli/src/commands/generate/scaffold/templates/layouts/NamesLayout.js.template
Update scaffold css to use semantic classes - WIP!!
- replaces utility classes with semantic classes in all scaffold generator templates
- reduces classes used in components and migrates style declarations to scaffold.css template
- these changes have no effect on the visual design of generated pages or components
Closes #610
=> Update scaffold css to use semantic classes

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Prisma release notes: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.6
=> Upgrade to Prisma-2.0.0-beta.6

packages/cli/src/commands/build.js, packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/generate.js
If an App does not include `api/prisma/`, then `yarn rw build` throws an error.
This adds a simple check to determine whether to generate the Prisma Client based on whether `prisma/` exists.
=> Improve building api by first checking if `api/prisma/` exists

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Prisma release notes: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.7
=> Upgrade to Prisma-2.0.0-beta.7

packages/cli/src/commands/generate/auth/providers/auth0.js
@peterp Not sure how I missed this but the auth0 generator wouldn't have been importing correctly according to your docs (meaning your docs were correct but the generator didn't create the right import). How's it look now?
=> Auth0Client needs to be destructured from @auth0/auth0-spa-js

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Prisma release notes: https://github.com/prisma/prisma/releases/tag/2.0.0-beta.8
=> Upgrade to Prisma-2.0.0-beta.8

packages/core/config/webpack.common.js
This PR adds SCSS/CSS module support. Usage is as follows:
```scss
// Filename: HomePage.module.scss
.hero {
color: red;
}
```
```jsx
// Filename: HomePage.js
import styles from './HomePage.module.scss'
const HomePage = () => (
<div className={styles.hero}>Hello</div>
)
export default HomePage
```
The div that contains hello will have the `hero` class applied to it.
This also adds sourcemap support for SCSS/CSS with or without modules. So in your web inspector, you can view the source for the styles, instead of it saying `<style>` for the source.
Classnames are generated with hashes in production builds, like in the image above. In dev, the names are more descriptive like: `.src-pages-HomePage-HomePage-module__heroName--rNGDY`. This is based on the …
=> SCSS/CSS Module support

packages/core/config/babel-preset.js
It looks like regex matching doesn't normalize path slashes like strings do in babel's "test" fields.
I'll add tests for these scenarios.
Closes #657
=> Fix windows matching paths in babel.

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Includes the same codebase from #668 Merging and testing via canary packages.
Prisma release notes v2: https://github.com/prisma/prisma/releases/tag/2.0.0
=> upgrade prisma v2 🎉

packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js, packages/cli/src/commands/generate.js, packages/cli/src/commands/generate/helpers.js, packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/sdl/sdl.js, packages/cli/src/commands/generate/service/service.js, packages/cli/src/lib/index.js
As a follow-up to https://github.com/redwoodjs/redwood/pull/594 (which is itself a follow-up on #322 :^)) and @peterp's suggestion on https://github.com/kimadeline/redwood/pull/1#discussion_r434722128 I did a bit of cleanup:
🧹 Moved the defaults for the javascript, typescript and force args to `src/commands/generate.js`;
🧹 There are 2 methods in `src/lib/index.js` that were both iterating on `[ '.js', '.ts']`, so I merged both arrays together and added `.tsx` to it.
✨ I did this cleanup as part of a PR to convert the Layout generator to TS, but since I was cramming too many changes in one PR I figured I'd split them, stay tuned for a Layout generator PR ✌️
=> CLI: Centralize yargs defaults

packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.test.js, packages/cli/src/commands/generate/cell/templates/test.js.template, packages/cli/src/commands/generate/component/__tests__/fixtures/multiWordComponent.test.tsx, packages/cli/src/commands/generate/component/__tests__/fixtures/singleWordComponent.test.tsx, packages/cli/src/commands/generate/component/templates/test.tsx.template, packages/cli/src/commands/generate/layout/__tests__/fixtures/multiWordLayout.test.js, packages/cli/src/commands/generate/layout/__tests__/fixtures/singleWordLayout.test.js, packages/cli/src/commands/generate/layout/templates/test.js.template, packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.test.js, packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.test.js, packages/cli/src/commands/generate/page/templates/test.js.template
Removes cleanup from cell, component, layout, and page because it already runs automatically: https://testing-library.com/docs/react-testing-library/setup#skipping-auto-cleanup.
=> Remove cleanup from some generator test templates

packages/core/config/jest.setup.web.js, packages/core/package.json, packages/testing/package.json, packages/testing/src/index.js, packages/testing/src/mockServer.ts, packages/testing/src/render.js, yarn.lock
@peterp I just started playing around with and this tools is totally awesome!
There's probably a lot more magic we can do for users, like providing a default file where users can define default mocks, but I think this is something we can figure out while we implement config extension and that kind of business.
Check this example for how to use: https://github.com/RobertBroersma/redwood-testing/blob/master/web/src/pages/BlogPostPage/BlogPostPage.test.js
It's good that this decouples us from Apollo.
It does add some tiny constraints, like you can't test anonymous GraphQL queries (or at least _I didn't manage to) but I think that could even be a positive as it enforces the better practice of naming your queries.
This should also Just Work™ with mutations but I haven't tested that yet. I got …
=> Add MSW to testing package

packages/cli/src/commands/dev.js, yarn.lock
This command no longer makes sense since database migrations are not applied automatically. When we run `yarn rw db up` (which is required when the schema changes) the client is already generated.
=> Remove `prisma generate --watch` task from dev command.

packages/core/config/webpack.development.js, packages/internal/src/__tests__/config.test.ts, packages/internal/src/config.ts
This PR makes it so that if `browser.open` is not in a Redwood app's redwood.toml, it'll default to `false` instead of `true`. This is the desired behavior. For background, ~~see #173~~ referenced the wrong issue, it's actually https://github.com/redwoodjs/redwoodjs.com/pull/173#issuecomment-645647833
This PR also removes an extraneous conditional in webpack.development.js.
=> Set browser.open default to false

packages/internal/src/config.ts
This PR adds a comment that points people to webpack.common.js for web's includeEnvironmentVariables. Via https://github.com/redwoodjs/redwoodjs.com/pull/173#issuecomment-644537696
=> Add link to includeEnvironmentVariables in config.ts

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Patch: https://github.com/prisma/prisma/releases/tag/2.0.1
- The database detection in prisma introspect got improved so there are fewer false positives that tell users their database is Prisma 1.
=> upgrade prisma 2.0.1

packages/api/src/auth/authHeaders.ts
Suggestion: Return the type of unknown token so that it can be handled in `api/src/lib/auth.js` 
**Why?**
For example, you might want to support multiple types of auth within the same redwood api. In our case we use both JWT and an opaque token
Relevant discussion: [Community discussion](https://community.redwoodjs.com/t/custom-github-jwt-auth-with-redwood-auth-advice-needed/610/11?u=danny)
---
Please note I am unable to test it with 0.11 - copy:watch isn't work for me, however I have been using patch-package in 0.10 with this code successfully
=> Suggestion: Change custom authHeader to return type

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/assets/scaffold.css, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/editCell.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/indexCell.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/showCell.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/schema.prisma, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/scaffold/templates/assets/scaffold.css.template, packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template
I rebased all of @lachlanjc's commits in #495, and addressed @cannikin's comments.
I didn't do it exactly as Rob suggested, but I think the outcome is what we want.
=> Scaffolds use checkbox fields

packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/generate.js, packages/cli/src/commands/dev.js
Since we moved the Prisma generate --watch command we now need to generate the client before we start the dev server.
=> Generate Prisma client if it doesn't exist

packages/api/package.json, packages/cli/package.json, packages/core/package.json, yarn.lock
Prisma release notes:
- https://github.com/prisma/prisma/releases/tag/2.1.0
- https://github.com/prisma/prisma/releases/tag/2.1.1
Passing E2E and manual tests locally:
=> Upgrade to Prisma-2.1.1

CONTRIBUTING.md, packages/cli/README.md
related to #718 
Changes document permalinks to reference `main` branch
=> update permalinks to use `main` branch

packages/dev-server/README.md
(To my knowledge) there's no configuration option in ./redwood.toml that lets you change where the dev server looks for lambda functions. So this PR removes the line saying there is one from the dev server's README.md. (Please correct me if I'm wrong and I'll update the app configuration doc too.)
=> Correct lambda function dir info in dev server README

packages/auth/README.md
**Fixes**
In commit https://github.com/redwoodjs/redwood/commit/7e8ebbc60af8f05fe073255ec1ec229a1300934e auth Provider 'magic-link' was changed to 'magicLink', and thus `yarn rw generate auth magic-link` won't work. 
```
Invalid values:
Argument: provider, Given: "magic-link", Choices: "auth0", "firebase", "magicLink", "netlify"
```
**Additional Information**]
I noticed that `goTrue` was added as Auth Provider in the same commit. Two points here;
1. As `goTrue` is part of Netify, would it make it sense to prefix this Auth provider with e.g. `netifyGoTrue`?
2. In the [Auth documentation overview](https://github.com/redwoodjs/redwood/tree/main/packages/auth#authentication) I suggest that this can be re-ordered, e.g. having 1. Netify, 2. Netify GoTrue, 3. Auth0 4. ...
Thanks for the great …
=> Changing from magic-link to magicLink in docs

packages/auth/README.md
This PR adds some some auth instruction and example code for configuring GoTrue-JS to the auth readme.
Probably doesn't quite close [#220 @ redwoodjs.com](https://github.com/redwoodjs/redwoodjs.com/issues/220) but it's a start. :)
@jtoar
=> add GoTrue-JS doc and example code to auth readme

packages/auth/README.md, packages/cli/src/commands/generate/auth/providers/goTrue.js
This PR adds a GoTrue-JS provider to the CLI auth generator and updates the auth readme with relevant info.
`gotrue` can now be passed as a provider argument to the CLI command, e.g. `yarn rw g auth gotrue`.
Closes #767
=> Add a GoTrue-JS provider to the CLI auth generator

packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.js, packages/cli/src/commands/generate/sdl/__tests__/fixtures/singleWordSdl.ts, packages/cli/src/commands/generate/sdl/sdl.js
Closes #741 
Closes #740 
Ammends #747 
This PR fixes the format of the generated relational arrays
=> fix: generated relational arrays

packages/router/README.md, packages/router/package.json, packages/router/src/index.d.ts
This adds a bunch of type definitions to `@redwoodjs/router`
/cc @koolamusic
=> Add initial types to Router

packages/web/package.json
This adds a `test` script to the `web` project, to include it in the main test run executed by GitHub's actions.
So now this is part of the action output:
```
@redwoodjs/web: $ jest --colors
@redwoodjs/router:  PASS  src/__tests__/util.test.js
@redwoodjs/router:  PASS  src/__tests__/links.test.js
@redwoodjs/web:  PASS  src/flash/__tests__/FlashContext.test.js
@redwoodjs/router:  PASS  src/__tests__/location.test.js
@redwoodjs/router: Test Suites: 3 passed, 3 total
@redwoodjs/router: Tests:       43 passed, 43 total
@redwoodjs/router: Snapshots:   0 total
@redwoodjs/router: Time:        4.428s
@redwoodjs/router: Ran all test suites matching /src/i.
@redwoodjs/web:  PASS  src/flash/__tests__/flash.test.js
@redwoodjs/web: Test Suites: 2 passed, 2 total
@redwoodjs/web: Tests:       7 passed, …
```
=> Add test script to web

packages/cli/src/commands/dbCommands/ide.js, packages/cli/src/commands/dbCommands/studio.js
This PR adds a new db command: `ide`. It starts Prisma Studio.
```
yarn rw db ide
```
Note that you have to have a `dev.db` and a `migrations` directory in `api/prisma` for this to work. If either are missing, the command outputs:
```terminal
[warning] your app doesn't have a database (api/prisma/dev.db) and/or migrations (api/prisma/migrations). Save and up before starting the IDE.
```
Should this actually just be a flag on dev like @thedavidprice suggested in #467?
```
yarn rw dev --prismastudio
```
I'm open to anything, I just finally got it to work this way and wanted to reopen the discussion with a working spike.
> **NOTE:** I accidentally kind of overwrote #467, otherwise I would've just reopened that one.
Before attempting to write any kind of Prisma primer, I think we should get …
=> Add prisma studio via db studio command

packages/cli/src/commands/dbCommands/studio.js
The `yarn rw db studio` command would check for the presence of a `dev.db` and `migrations` file before starting. This PR removes those checks and replaces it with a check for only the `schema.prisma` file.
=> Remove dev.db/migrations check in db studio

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/indexCell.js, packages/cli/src/commands/generate/scaffold/templates/components/NamesCell.js.template, packages/web/src/graphql/withCell.js
This PR closes #717 by changing `beforeQuery`'s `fetchPolicy` to `'cache-and-network'` (previously, it didn't have one).
Was working on the Cells doc (https://github.com/redwoodjs/redwoodjs.com/pull/202) and found #717 in the process of documenting. Figured I'd close it out real quick because it seemed simple enough (is it this simple?).
There could also be complementary PRs to remove the export of `beforeQuery` in scaffolds (as it wouldn't differ from just the default after this gets merged). Or is it better to be explicit?
=> Add cache-and-network fetchPolicy to beforeQuery

packages/core/package.json
This PR adds the `@storybook/react` package to `@redwood/core`. Let me know if this isn't necessary, but I didn't see storybook as a dependency, even though we require it in [packages/core/config/storybook/preview.js](https://github.com/redwoodjs/redwood/blob/c52fd6620a137012c5db39d8b63170879efb0ea3/packages/core/config/storybook/preview.js#L2):
```js
const { addDecorator } = require('@storybook/react')
```
Also, even when I upgrade one of my local Redwood apps to canary, I have to install it myself (i.e. run `yarn workspace web add -D @storybook/react`). `yarn rw storybook` fails otherwise ("missing command start-storybook"). Maybe this is why?
Last question: ideally it should be a dev dependency in Redwood app's web side right?
=> Add @storybook/react to @redwoodjs/core

packages/router/src/index.d.ts, packages/testing/package.json, packages/testing/src/MockProviders.tsx, packages/testing/src/MockRouter.tsx, packages/testing/src/__tests__/MockRouter.test.tsx
Fix `MockRouter` not correctly mapping `Routes` nested in `Private`.
=> Make MockRouter also map private routes.

packages/cli/src/commands/storybook.js
This PR closes #816 by adding the alias `sb` to the storybook command. So now you can run it like:
```
yarn rw sb
```
=> Add alias sb for storybook command

packages/cli/src/commands/generate/auth/auth.js
This PR closes #830 by fixing the RegExp the auth generator uses to add the `import { getCurrentUser } from 'src/lib/auth.js` statement to the graphql function.
There's probably a better fix than just replacing "importAll" with "services", but this works.
=> Fix auth generator regex

packages/cli/src/commands/diagnostics.js, packages/structure/src/index.ts, packages/structure/src/x/__tests__/vscode-languageserver-types-x.test.ts, packages/structure/src/x/vscode-languageserver-types.ts
* This PR adds a new command to the CLI called "diagnostics"
* For now all it does is print some diagnostics (with no stats, no summaries, etc)
* It delegates all work to the @redwoodjs/structure package
=> Add "diagnostics" command to CLI

packages/cli/jest.config.js
=> jest: increase cli test timeout

__fixtures__/example-todo-main-with-errors/web/src/components/TodoListCell/TodoListCell.js, __fixtures__/example-todo-main/web/src/components/TodoListCell/TodoListCell.js, packages/structure/src/model/RWCell.ts, packages/structure/src/model/RWProject.ts, packages/structure/src/model/RWRouter.ts, packages/structure/src/model/RWSDLField.ts, packages/structure/src/model/__tests__/model.test.ts
We want to make mocking data in Storybook and Jest super simple. In order to achieve that we need to be able to get the operation name from a QUERY export in a Cell:
```js
export const QUERY = gql`query <i.want.this.operation.value> { invoices { id } }`
```
/cc @aldonline
=> Use structure to extract operation name from Cell's QUERY

packages/web/src/form/__tests__/form.test.js, packages/web/src/form/coercion.js, packages/web/src/form/form.js
This is an alternative solution to #826 to handle nested form fields. 
I feel this is a more idiomatic React solution, using Context instead of recursive looping over child elements.
Fixes #825
=> Form: use context to handle coercions

packages/cli/package.json, packages/structure/package.json, yarn.lock
> Upgrade lodash to version 4.17.19 or later
done.
=> dependabot security alert: upgrade lodash in main packages

babel.config.js, packages/cli/src/commands/destroy/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.js, packages/cli/src/commands/generate/cell/cell.js, packages/cli/src/commands/generate/cell/templates/cell.js.template, packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js, packages/cli/tsconfig.json, tsconfig.json
We now give generated cells an operation name:
```diff
export const QUERY = gql`
- query {
+ query TestQuery {
userProfile {
id
}
}
`
```
If the operation name is already taken we append `_2`, `_3`, `_4` to the operation name.
=> Give a Cell's query an operation name

packages/router/src/location.js
This PR converts the Router package LocationProvider component to a function component and adds cleanup duty to the useEffect hook. This should fix the setState memory leak and related warnings in cases where the router is unmounted (like auth state change).
=> Convert LocationProvider to function component and add cleanup effects

packages/web/src/index.js
I tried to use `useLazyQuery` hook and noticed that along with the useSubscription it's not being exported from @web package.
=> Export useLazyQuery/useSubscription from @apollo

.gitignore, __fixtures__/example-todo-main-with-errors/.gitignore, __fixtures__/example-todo-main/.gitignore, __fixtures__/new-project/.gitignore
I've noticed `.vscode` directories merged in repository so I assumed it would be okay to put Jetbrain's `.idea` to gitignore to avoid constant flow of:
=> Add .idea/ dir for Jetbrains IDE's config to .gitignore

packages/cli/src/lib/index.js
If you ran a generator in the `./web` or `./api` directory the babel transformation code would pick up the `.babelrc.js` file and transpile the code way beyond the typescript -> JS conversion we wanted.
We set the cwd to the base of the project to avoid that.
Fixes #798
=> Set cwd for generator babel transforms.

packages/cli/src/commands/generate/helpers.js, packages/cli/src/commands/test.js, packages/cli/src/redwood-tools.js, packages/internal/src/__tests__/paths.test.ts, packages/internal/src/paths.ts
My take on https://github.com/redwoodjs/redwood/pull/854
=> Fix test db path on Windows

packages/router/src/__tests__/router.test.js
We had a bunch of warnings about not wrapping things in 'act'. This wraps those in act removing those warnings.
=> Remove warnings about "act" in router tests.

packages/web/src/form/coercion.js
As an example, using a `<SelectField />`  in a form breaks the submit action with the following error:
> coercion.js:67 Uncaught (in promise) TypeError: coercionContext.coercions[name] is not a function
>     at coercion.js:67
>     at form.js:161
>     at Array.forEach (<anonymous>)
>     at coerceValues (form.js:160)
>     at form.js:183
>     at react-hook-form.es.js:1215
=> Ignore coercion for unsupported form fields

packages/auth/README.md, packages/auth/src/authClients/auth0.ts, packages/router/README.md, packages/router/src/router.js
See: https://community.redwoodjs.com/t/accessing-the-target-url-from-the-unauthenticated-redirect/913
bennet asked the RW Community
> Would it be possible to add the ability to access the url the user was trying to reach if they are blocked by a Private route? It would be nice if there was an easy way to redirect the user back to the url they were trying to access once they successfully authenticate. Even if we just had access to the name of the original target url after being redirected to the unauthenticated route I think that would be enough.
I found that
https://community.redwoodjs.com/t/accessing-the-target-url-from-the-unauthenticated-redirect/913/9
* the Auth0 client `restoreAuthState` already had a mechanism in place to redirect to a `targerUrl`, it simply needed to. be set as …
=> redirectTo a url on login after authenticated

packages/cli/src/commands/generate/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.mock.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.stories.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.mock.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.stories.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.mock.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.stories.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.test.js, packages/cli/src/commands/generate/cell/cell.js
Fixes https://github.com/redwoodjs/redwood/issues/883
As of v0.14.0, cell queries now get an operation name to work with Storybook:
See: #867
Example:
```js
export const QUERY = gql`
- query {
+ query TestQuery {
userProfile {
id
}
}
`
```
I created a cell via the generator:
`yarn rw g cell my_sites`
and
```
✔ Generating cell files...
✔ Writing 
`./web/src/components/MySitesCell/MySitesCell.mock.j
s`...
✔ Writing 
`./web/src/components/MySitesCell/MySitesCell.storie
s.js`...
✔ Writing 
`./web/src/components/MySitesCell/MySitesCell.test.j
s`...
✔ Writing `./web/src/components/MySitesCell/MySi
tesCell.js`...
✨  Done in 1.57s.
```
the files, used the MySite upper camelCasing (aka Pascal Case).
However, my query operation name is
```js
export const QUERY = gql`
query my_sitesQuery {
mySites { …
```
=> Fix  #883 - Cell Operation Names not PascalCased

packages/cli/src/commands/test.js, packages/core/src/configs/browser/jest.createConfig.ts, packages/core/src/configs/browser/jest.setup.js, packages/core/src/configs/node/jest.createConfig.ts, packages/structure/src/model/RWProject.ts, packages/testing/src/mockRequests.ts
This introduces the ability to mock network requests via the `*.mock.js` files on the testing side. It has the identical API to storybook, so the mocks that you declare during development of storybook are also automatically declared in Jest.
You can overwrite the global mocks.
Fixes #892
Fixes #872
=> Add graphQL mocks to jest

packages/structure/.vscode/launch.json, packages/structure/src/ide.ts, packages/structure/src/language_server/RWLanguageServer.ts, packages/structure/src/language_server/commands.ts, packages/structure/src/language_server/diagnostics.ts, packages/structure/src/language_server/outline.ts, packages/structure/src/language_server/xmethods.ts, packages/structure/src/model/RWRoute.ts, packages/structure/src/model/RWRouter.ts, packages/structure/src/model/util/__tests__/advanced_path_parser.test.ts, packages/structure/src/model/util/advanced_path_parser.ts, packages/structure/src/outline/outline.ts, packages/structure/src/x/vscode-languageserver-types.ts, packages/structure/src/x/vscode.ts
* This PR adds the last critical features to the Language Server
* Once this code is published as part of a redwood release, Decoupled Studio will be updated to rely completely on this Language Server, which will (finally) get us to the point where we can have a great VSCode experience which is coming 100% from the Redwood codebase and can evolve from version to version.
* Some of the features in this PR:
* Outline
* Improve the performance of the outline. This was achieved by removing abstractions
* Make the outline API closely match the [TreeView API (in vscode)](https://code.visualstudio.com/api/extension-guides/tree-view) to remove ambiguities
* Commands in the outline now follow the command API, which makes it possible to define them 100% in the Redwood codebase.
* Decorations
* …
=> Improve Language Server

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js, packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template, packages/cli/src/commands/upgrade.js, packages/web/src/form/index.js
I recently moved the forms from `@redwoodjs/web` into `@redwoodjs/forms`. You are still able to reference them via `@redwoodjs/web`, but I didn't export them properly. This fixes that and a bunch of things I didn't fully appreciate below:
Fixes #901
=> Make scaffold use @redwoodjs/forms

packages/cli/src/commands/dev.js
Fix #890
This is an alternate, mutual approach to #891 We could merge both and add to CLI docs for `yarn rw dev`
@peterp My approach here is to add a string option to the Yargs command, which could be used to pass any+all Webpack DevServer config options, which will override `webpack.development.js`.
Most importantly --> What do you this of this approach?
Secondarly --> does the code implementation pass your PPSniffTest™?
**edit:** Oh, one question. Should the name of the option be `webpack-config` or `webpackConfig` for CLI option?
=> Add `yarn rw dev` option to pass any Webpack config as a string

babel.config.js, packages/core/config/babel-preset.js, packages/core/src/configs/browser/jest.createConfig.ts, packages/core/src/configs/browser/jest.setup.js
This circumvents a bug where jest and babel module aliases could not directly determine their paths.
This code was not release, but if you're running canary, then please clear your jest cache before running tests again: `yarn test --clearCache`
Fixes #872
=> Fix jest module alias resolution

packages/create-redwood-app/README.md, packages/create-redwood-app/src/create-redwood-app.js
Resolves https://github.com/redwoodjs/redwood/issues/811
@peterp suggested that after someone creates a new redwood app, they are prompted to join in on the community:
```
It would be great if we could invite people to:
* Signup to the newsletter 
* Just our discord and discourse
```
Notes:
* added a little RW color
* I used the Discord url from the website, though I noticed that `https://discord.gg/redwoodjs` also went to an invite
* The newsletter doesn't have a link or anchor, so just directed to WWW (but could just go to the Mailchimp form, though the url is not terribly friendly: `https://redwoodjs.us19.list-manage.com/subscribe/post?u=0c27354a06a7fdf4d83ce07fc&id=09f634eea4` actually, could setup a Netlify redirect to go there instead: 
`https://www.redwoodjs.com/newsletter` or …
=> Issue #811 after create redwood-app prompt to join

packages/api/src/__tests__/authDecoder.test.ts, packages/api/src/__tests__/fixtures/apiGatewayProxyEvent.fixture.ts, packages/api/src/auth/decoders/index.ts
- Allow users to use any type of auth provider without a hard error.
- Add tests for decoder selection to prevent regression in the future!
If you have a custom auth setup, you might want multiple different types of custom auth. e.g. in our case they're "jwt" and "cli-token" - this is a string, not a jwt. Although I could use "custom" instead of "jwt" for web, it would mean all the cli clients would break and would need a forced upgrade.
---
=> fix(auth-decoder): Make auth decoder backwards compatible with 0.12

packages/router/README.md
In the Router docs we never say what happens to params you give to a named route function that don't have corresponding params defined on the route. They end up as search params appended to the URL, so let's document that!
=> Document behavior of named route function route params not defined on route

packages/api/package.json, packages/api/src/makeMergedSchema/rootSchema.ts, yarn.lock
graphql-iso-date is deprecated. See https://github.com/redwoodjs/redwood/issues/881
=> Switch Date and Time scalar types to graphql-scalars 

packages/core/config/webpack.common.js, packages/core/package.json, yarn.lock
Adds webpack retry chunks plugin, so that RW will retry loading chunks upto 5 times
This is important because currently RW Router will just show a blank white page, if you try to navigate somewhere and loading the chunk fails.
Helps mitigate issue seen in #893 
---
=> Add webpack retry chunks plugin

packages/structure/src/model/RWServiceFunction.ts
This PR disables SDL parameter type checking, which resulted in errors being shown when parameters were actually valid. 
The implementation was naive. We need to work on this and re-enable the diagnostic check. See #943.
=> Disable SDL parameter type checking

packages/cli/src/commands/test.js
references #868 and redwoodjs/redwoodjs.com#285
I lightly edited the option descriptions from those proposed for the redwoodjs.com docs to better fit the terminal.
=> Add descriptions to yarn rw test --help output

packages/cli/src/commands/generate/dataMigration/dataMigration.js
Adds process.exit(1) to error handling of <code>yarn rw dataMigrate up</code> as suggested in #942,
=> dataMigrate exits(1) when failing

packages/cli/src/commands/generate/__tests__/helpers.test.js, packages/cli/src/commands/generate/helpers.js, packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.stories.js, packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.test.js, packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.js, packages/cli/src/commands/generate/page/__tests__/page.test.js, packages/cli/src/commands/generate/page/page.js, packages/cli/src/commands/generate/page/templates/page.js.template, packages/cli/src/commands/generate/page/templates/stories.js.template, packages/cli/src/commands/generate/page/templates/test.js.template, packages/cli/src/lib/index.js, packages/cli/src/lib/test.js
This PR adds support to the page generator for generating pages with route parameters.
Let's say you want to generate a page for displaying posts. You probably already know from the start that you will have to take the post ID as a route parameter. Now you can directly generate a page for that.
Is this useful? How do you like the syntax? What about the naming of everything? 
The new generator cli syntax looks like this
```bash
$ yarn rw g page post {id}
```
That will give you an entry in your routes like this:
```jsx
<Route path="/post/{id}" page={PostPage} name="post" />
```
and the generated page will look like this:
```jsx
import { Link } from '@redwoodjs/router'
const PostPage = ({ id }) => {
return (
<>
<h1>PostPage</h1>
<p>Find me in "./web/src/pages/PostPage/PostPage.js"</p>
<p>
My …
```
=> Generate pages with route parameters

packages/core/config/webpack.development.js
See https://github.com/redwoodjs/redwood/issues/923 for more details.
Also adds `Connection: keep-alive` header for better fault tolerance. See https://github.com/webpack/webpack-dev-server/issues/793#issuecomment-444165866
=> Fix intermittent connection issues between web and api in devServer

packages/eslint-config/index.js
The "error" for Prettier is distracting while editing code . You're typing along and get a red underline for something you could can ignore _entirely_ because when you hit save it resolves automatically.
E.g. here I omitted a space,
And there's this dense error in the Problems pane too,
This PR drops it to a warning to be less demanding of attention. I wish it could simply be turned "off" and still be autofixed within ESlint but I don't think that's supported. Another option is to remove it as a "linting" concern entirely (which it isn't really) and move to hooks like `formatOnSave` and a "style" validation adjacent to whenever ESlint is run. I can file an issue if that's a direction the maintainers are open to.
=> Warn instead of error on "prettier" deviations

packages/router/src/history.js, packages/router/src/location.js
This reverts: https://github.com/redwoodjs/redwood/pull/836/files and adds a way to remove history listeners.
Fixes: https://github.com/redwoodjs/redwoodjs.com/issues/288
/cc @Terris Sorry, I didn't have enough time to figure out why the useEffect was causing issue here, so I reverted back to the class component.
=> Add a way to remove history listeners.

packages/cli/src/commands/generate/deploy/deploy.js
Generator currently matches the text in comments above the config. E.g:
I've removed that comment line from the CRWA file, but currently installed projects will still have the text and could run into issues if they want to test on Vercel.
=> Deploy Generator: fix regex match to skip text in comments

packages/cli/src/commands/generate.js, packages/cli/src/commands/generate/util.js, packages/cli/src/commands/generate/util/tailwind/tailwind.js, packages/cli/src/commands/generate/util/tailwind/templates/postcss.config.js.template
This PR adds a generator that adds Tailwind to a Redwood app:
```
yarn rw g tailwind
```
We do already have the process documented in the doc on [Webpack Configuration](https://redwoodjs.com/docs/webpack-configuration#adding-tailwindcss). But I feel like adding Tailwind to a Redwood app happens often enough to warrant a generator for it. Let me know if you guys think it's extraneous though. And/or if it should be part of a larger "css" generator:
```
yarn rw g css tailwind
```
Right now, adding-directives-to-your-index.css bit is a note at the end, much like the way auth works:
```
const notes = [
'Add the following directives to your ./web/src/index.css:',
'',
'@tailwind base;',
'@tailwind components;',
'@tailwind utilities;',
]
```
I thought this was better than just overwriting …
=> Add tailwind generator

packages/cli/package.json, packages/cli/src/commands/generate/scaffold/scaffold.js
I've added a new doc about Schema Relations, which explains how to manually modify the code generated by Scaffold when the model is relational:
https://redwoodjs.com/docs/schema-relations
This PR attempts the following:
- In the case of `rw g scaffold <model>`, checks if the model is relational
- If it is relational, a Warning is given after the generator CLI output.
The Warning states manual code modification is required and provides a link to the doc.
What say you @peterp? I'm open to any/all suggestions. This isn't meant to be a fix — just trying to smooth out the bumps in the near-term.
=> Add Scaffold generator CLI warning when model contains @relation

packages/core/config/webpack.development.js
We just bumped webpack-merge (https://github.com/redwoodjs/redwood/pull/991) and have to change the way we import the merge function now to avoid this TypeError:
```
web | /home/dominic/projects/redwood/redwood-app/node_modules/@redwoodjs/core/config/webpack.development.js:11
web | const baseConfig = merge(webpackConfig('development'), {
web |                    ^
web | 
web | TypeError: merge is not a function
```
=> Fix webpack merge TypeError

packages/api-server/.babelrc.js, packages/api-server/ambient.d.ts, packages/api-server/package.json, packages/api-server/src/error.ts, packages/api-server/src/http.ts, packages/api-server/src/index.ts, packages/api-server/src/requestHandlers/awsLambda.ts, packages/api-server/tsconfig.json, packages/cli/src/redwood-tools.js, packages/dev-server/package.json, tsconfig.json
We're getting ready to split apart the concept of the "dev-server" which watches the api side for changes and reloads the serverless functions when a change is detected. 
Splitting these two concepts will give us greater abilities to generate code, and give people the ability to self-host Redwood projects on their own infrastructure.
So, we'll create two separate processes : one for watching files and performing actions in response to a change, and another for serving serverless functions over http (`api-server`).
=> Add "api-server" package

packages/cli/src/commands/generate/util/tailwind/templates/postcss.config.js.template
This PR fixes the tailwind utility generator. I forgot to add `path.resolve` to postcss.config.js. @thedavidprice I'm going to do the appending-the-directives-to-index.css in another PR because this fix is a matter of the generator being broken or not.
=> Fix tailwind generator

packages/cli/src/commands/generate/util/tailwind/tailwind.js
This PR makes the tailwind generator append (preprend technically?) imports to index.css. Before, it instructed the user to copy-paste a code block. With this PR, here's what index.css looks like post tailwind generate:
```css
/**
* START --- TAILWIND GENERATOR EDIT
*
* `yarn rw g util tailwind` placed these imports here
* to inject Tailwind's styles into your CSS.
* For more information, see: https://tailwindcss.com/docs/installation#add-tailwind-to-your-css
*/
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
/**
* END --- TAILWIND GENERATOR EDIT
*/
```
=> Make tailwind generator append to index.css

packages/forms/src/__tests__/form.test.js, packages/forms/src/coercion.js, packages/forms/src/index.js
regarding Forms Roadmap: redwoodjs/redwoodjs.com#239
This might be a naive approach, but this PR lets you provide a custom coercion function for a form field. 
Do I need to integrate this with validation error handling somehow?
Thanks!
=> support passing coercion functions to form fields

packages/cli/src/commands/deploy.js, packages/cli/src/commands/deploy/api/__tests__/api.test.js, packages/cli/src/commands/deploy/api/api.js, packages/cli/src/commands/deploy/api/providers/aws_serverless.js
Addresses part 2 of https://github.com/redwoodjs/redwood/issues/431#issuecomment-676357234
For the last deploy command, we need to stream the output of the `serverless` command because it will contain the outputs of the serverless functions and also other important information. I tried streaming the output in `listr` and looked around as well, but it doesn't allow easy streaming of stdout. So I added the deploy command separately at the end. Let me know if someone has a better suggestion.
=> Add deploy command for api with aws_serverless provider

packages/auth/README.md, packages/auth/src/AuthProvider.tsx, packages/auth/src/__tests__/AuthProvider.test.tsx, packages/cli/src/commands/generate/auth/templates/auth.js.template, packages/router/src/index.d.ts, packages/router/src/router.js
This PR addresses https://github.com/redwoodjs/redwood/issues/977
In AuthProvider `hasRole()` now accepts a single string role or an array of strings/
```js
/**
* @example
* ```js
*  hasRole("editor")
*  hasRole(["editor"])
*  hasRole(["editor", "author"])
* ```
*
* Checks if the "currentUser" from the api side
* is assigned a role or one of a list of roles.
* If the user is assigned any of the provided list of roles,
* the hasRole is considered to be true.
*/
```
This can be used in routes:
```js
<Private unauthenticated="home" role="admin">
<Route path="/admin/users" page={UsersPage} name="users" />
</Private>
<Private unauthenticated="home" role={['admin', 'editor']}>
<Route path="/settings" page={SettingsPage} name="settings" />
</Private>
```
and in pages, cells, components:
```js …
```
=> Auth RBAC, hasRole accepts a single role or an array of roles

README.md
This adds @thedavidprice to the authors list (now same as core team), credits the more than 100 additional contributors, and adds some of my background to hopefully demonstrate the credibility of the project up front, as suggested by @monarchwadia.
@monarchwadia, is this what you had in mind?
=> Add more context about authors

packages/api/src/auth/decoders/index.ts, packages/api/src/functions/authDecoder.test.ts, packages/auth/package.json, packages/auth/src/authClients/index.ts, packages/auth/src/authClients/supabase.ts, packages/cli/src/commands/generate/auth/providers/supabase.js, yarn.lock
I got really excited [by the discussion around supabase](https://community.redwoodjs.com/t/supabase-redwood-experiments/1088/15) and really wanted to use it in my Redwood project. I figured I'd give it a spin. It was much easier than I expected. Looking for feedback to see if we can get this supported as I'd prefer to use supabase over anything else at the moment. 😅 
This PR:
~I've marked this PR as a **draft** because I'm not sure if it's worth having Supabase as an auth provider at this point. They are missing key features like password resets, etc.~
=> Add supabase auth provider

.github/workflows/build-eslint-jest.yaml
Attempting three adjustments:
- runner is still triggering on merge; moved conditional and updated syntax
- set cache to be conditional to skip Windows
- attempting a fix to Windows long running yarn install
Cache is still having false positives on Windows, which results in failed CI due to missing packages.
Cache or no cache, the Windows runner takes about 10 min largely due to the warning "There appears to be trouble with your network connection. Retrying..." during yarn install. I'm trying the yarn config registry workaround here: https://github.com/yarnpkg/yarn/issues/5259#issuecomment-670972053
**SUMMARY**
- I was not able to work around the Windows runner "...trouble with network connection..."
- The runner is now skipping caching for Widows
- The "is merged PR" conditional wasn't …
=> fix CI runner Windows cache false positive

packages/cli/src/commands/generate/__tests__/helpers.test.js, packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.js, packages/cli/src/commands/generate/page/templates/page.js.template
Last time I ran `yarn rw lint` I got [no-unescaped-entities](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md ) errors from the scaffolded pages. I'm not certain this was Redwood's lint config but I figure being robust to that lint rule wouldn't hurt.
=> quote paths and keywords with <tt> instead of quotation marks in JSX template generator

packages/router/src/index.d.ts
This adds the missing type definitions to the router.
=> Add typedefs to router

packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/save.js
Resolves #1120 
Here are my local testing results:
```bash
❯ yarn rw db save "test name"
$ /Users/amorriscode/dev/test-app/node_modules/.bin/rw db save 'test name'
Creating database migration... [started]
$ /Users/amorriscode/dev/test-app/node_modules/.bin/prisma migrate save --name 'test name' --create-db --experimental
📼  migrate save --name test name
....
Prisma Migrate just created your migration 20200909230629-test-name in
migrations/
└─ 20200909230629-test-name/
└─ steps.json
└─ schema.prisma
└─ README.md
Run yarn prisma migrate up --experimental to apply the migration
Creating database migration... [completed]
✨  Done in 3.05s.
```
=> Put migration name in quotes

babel.config.js, packages/core/config/webpack.common.js, packages/router/src/internal.js, packages/router/src/router.js, packages/web/src/graphql/index.js, packages/web/src/graphql/withCell.js, packages/web/src/index.js
My goal is to get the bundle size under 500 KB
=> Reduce bundle size

packages/web/src/flash/Flash.js, packages/web/src/flash/FlashReducer.js, packages/web/src/flash/__tests__/flash.test.js
per @cannikin's [suggestion](https://github.com/redwoodjs/redwoodjs.com/pull/344/files/7470e65de34f74bb4b361f2d953f9cfab8bd0543#r486455023), this PR would add the option to style a Flash message with a style object for convenience.
=> feat: support styling Flash with style object

README.md, tasks/all-contributors/.all-contributorsrc, tasks/all-contributors/.crwa.all-contributorsrc, tasks/all-contributors/.rwjs.com.all-contributorsrc
This adds two sections to Readme#Contributors: Core Team and Community Leads.
Updates contributors across projects. Current count is 115 🚀
=> update contributors and Readme sections

packages/cli/src/commands/build.js, packages/cli/src/commands/check.js, packages/cli/src/commands/deploy/api/api.js, packages/cli/src/commands/generate/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/cell.js, packages/cli/src/commands/test.js
I've noticed that it takes 1.5 seconds to run and exit `yarn rw`
Digging deeper I found that we're executing code outside function blocks - so when they're directly imported.
Fixes #1135 
I've lazily imported @rwjs/structure and moved a bunch of the logic into the builder functions so that they're not run when files are imported.
=> Improve CLI speed

packages/api/src/functions/graphql.ts
This allows the user to pass in `cors` and `onHealthCheck` parameters that'll be forwarded to the `createHandler` method.
Fixes #1172
=> Allow CORS to be passed to AWS Lambda Handler

packages/cli/src/commands/destroy/page/page.js
This PR resolves the `propParam is not defined` error currently thrown when running `yarn rw destroy page PageName`.
When instantiating the list of page files to destroy, not all template variables were being passed in. This caused lodash to throw an exception when attempting to interpolate the page template.
The proposed fix is to include the default page template variables when instantiating the destroy file list to ensure that lodash can successfully interpolate the template.
Closes #1037 
Thanks!
=> Resolve destroy page "propParam is not defined" error

CHANGELOG.md
@peterp Changelog.md hasn't been used since January. I added a link to GH Releases, but what do you think about simply deleting this file?
=> Add link to Releases in Changelog.md

packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.test.js, packages/cli/src/commands/generate/cell/templates/test.js.template
@peterp looping you in on this one. Dom and I are coordinating the generated tests that need to be fixed/completed. This seemed to do the trick for cells but would welcome your eyes/improvement.
=> fix cell generated test template

packages/web/src/index.js
This reimplement missing apollo client hooks that are referenced in the types [here](https://github.com/redwoodjs/redwood/blob/main/packages/web/src/index.d.ts)
closes https://github.com/redwoodjs/redwood/issues/1184
=> Implement missing Apollo methods

packages/core/config/webpack.common.js
**Issue**
`TypeError: merge is not a function`
**Related commit**
https://github.com/redwoodjs/redwood/commit/fb1e20eff33b2724220445cdcf04e932a50b7da2 - Bump webpack-merge from 4.2.2 to 5.1.2 
> Breaking - `merge` has been moved as a regular import (i.e. `import { merge } from 'webpack-merge'`).
https://github.com/survivejs/webpack-merge/blob/master/CHANGELOG.md#503--2020-07-06
**Related Issue**
https://github.com/redwoodjs/redwood/issues/1174 Fix webpack merge not a function error 
**Error message**
```bash
❯ yarn rw dev
$ /home/user/redwood-webpack-merge/node_modules/.bin/rw dev
$ /home/user/redwood-webpack-merge/node_modules/.bin/dev-server
$ /home/user/redwood-webpack-merge/node_modules/.bin/webpack-dev-server --config …
```
=> Fix of TypeError: merge is not a function

packages/cli/src/commands/generate/util/tailwind/tailwind.js
Fixes Issue https://github.com/redwoodjs/redwood/issues/1170
This PR pins postcss-loader and autoprefixers such that when setting up tailwindcss, it is compatible with PostCSS v7 (the version currently used by RedwoodJS).
```
'postcss-loader@4.0.2',
'autoprefixer@9.8.6',
```
The current, latest version of autoprefixer is v10.0.0 and this requires PostCSS v8. Installing that version in the setup causes errors seen in the [issue](https://github.com/redwoodjs/redwood/issues/1170) above.
=> Pins postcss-loader & autoprefixer for tailwindcss

packages/create-redwood-app/README.md, packages/create-redwood-app/src/create-redwood-app.js
**Description**
Updates the success message when a Redwood application is created using `yarn create redwood-app`.
**Related**
#1171 Improve final "success" output during CRWA installation
**Questions**
**Latest output**
=> CRWA installation success message

packages/api/package.json, packages/cli/package.json, packages/structure/package.json, yarn.lock
> note: dependabot had previously bumped @prisma/sdk to 2.7.1 Reminder to self to add @prisma to dependabot ignore list.
- 2.7.0 https://github.com/prisma/prisma/releases/tag/2.7.0
- Prisma Studio is Stable
- Configure Prisma schema location via package.json for more flexibility: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema#prisma-schema-file-location
- lots of fixes
- 2.7.1 https://github.com/prisma/prisma/releases/tag/2.7.1
- fixes
=> Upgrade prisma v2.7.1

packages/internal/src/paths.ts
This fixes a config locating error for users of `yarn link`
=> Fix cwd in getConfigPath to actual cwd

CONTRIBUTING.md
I think it would be helpful to call out that `yarn` should be used to install the dependencies.
=> Updating contributing.md with install instructions

packages/cli/src/commands/generate/util.js, packages/cli/src/commands/generate/util/tailwind/tailwind.js, packages/cli/src/commands/generate/util/tailwind/templates/postcss.config.js.template, packages/cli/src/commands/setup.js, packages/cli/src/commands/setup/tailwind/tailwind.js
=> Improve new Setup command

packages/web/src/graphql/withCell.tsx
This PR resolves #1104. I used the [example blog](https://github.com/redwoodjs/example-blog) to test it. It's actually really easy to reproduce the double render issue with `Success` which made it was easy to confirm the fix!
=> Revert to default Apollo fetch policy

packages/structure/src/language_server/RWLanguageServer.ts, packages/structure/src/model/RWProject.ts, packages/structure/src/outline/outline.ts, packages/structure/src/x/vscode-languageserver.ts
* This PR contains a set of minimal changes to the Language Server code
* They are critical for some users who are running into issues when trying to use the VSCode extension (see #1261)
* I am keeping them as small and self-contained as possible so we can release a patch ASAP
* By patching the `lsp.Connection` object (the top-most entry point), we're catching all errors that would otherwise result in VSCode showing a warning (or worse, an information message that doesn't go away)
* This is brute force, but it is still correct (DX-wise). We want the IDE to support all kinds of malformed projects without failing (just suppressing functionality). We're still logging the errors to the Redwood Language Server output channel.
* Eventually, some of the errors that will get logged should be …
=> Small Language Server fixes (to get VSCode extension working)

packages/cli/src/commands/generate/__tests__/helpers.test.js, packages/cli/src/commands/generate/page/__tests__/fixtures/multiWordPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/paramPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/pluralWordPage.js, packages/cli/src/commands/generate/page/__tests__/fixtures/singleWordPage.js, packages/cli/src/commands/generate/page/templates/page.js.template
The Teletype Text element `<tt>` is obsolete in HTML 5.2 W3C recommandation. Where the `<tt>` element would have been used for marking up keyboard input, [it is now advised to use the `<code>` element for computer code](https://www.w3.org/TR/html52/obsolete.html#elementdef-tt).
=> Replace <tt> HTML elements with semantic <code> HTML elements

packages/cli/src/commands/dbCommands/studio.js
Hi all, 
`--experimental` is no longer needed in currently shipping prisma
studio. this drops the warning shown bellow when calling
`yarn rw db studio`
```
$ /Users/am/hacks/osmium/node_modules/.bin/prisma studio --experimental
warn --experimental is no longer required for this command
Starting Prisma Studio ...
```
first contrib here, excuse me in advance if i missed something obvious :-) 
All the best && keep the great work!
=> remote deprecated argument from prisma studio call

packages/cli/src/commands/setup/webpack/templates/webpack.config.js.template, packages/cli/src/commands/setup/webpack/webpack.js
Simple command to setup the webpack config for the web side at the right place.
Beyond "hello world" projects, you probably want to setup custom webpack plugins, resolvers or rules.
=> (rw setup): Add command to setup webpack.config.js for web

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
Tested locally.
Needs deploy testing.
Release Notes:
- v2.8.0: https://github.com/prisma/prisma/releases/tag/2.8.0
- `findFirst`
- Case insensitive filters for PostgreSQL are now stable
- v2.8.1: https://github.com/prisma/prisma/releases/tag/2.8.1
- misc fixes
=> Upgrade Prisma v2.8.1

packages/structure/src/language_server/RWLanguageServer.ts, packages/structure/src/model/RWPage.ts, packages/structure/src/x/URL.ts, packages/structure/src/x/__tests__/URL.test.ts, packages/structure/src/x/path.ts
This is a hotfix/patch:
* Original PR: https://github.com/redwoodjs/redwood/pull/1316
* Related Issue:  #1261
=> [hotfix] Fix windows related path and file-uri errors in redwoodjs/structure

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
Fixes https://github.com/redwoodjs/redwood/issues/1313
Tested deploy via manual project upgrade. Will test using canary once merged and published.
Prisma [v2.9.0 Release Notes](https://github.com/prisma/prisma/releases/tag/2.9.0)
=> Upgrade Prisma v2.9.0

packages/structure/src/model/RWRouter.ts
Fixes #1256 by modifying the location in which the codelens is rendered. It used to be rendered above the first route and now is rendered on top of the `<Router>` tag instead.
This also allows for further changes within the structure of router without disrupting the codelens.
=> fix #1256 router "Create Page..." codelens positon

.github/dependabot.yml
Also make it update the `package.json` files rather than the lockfiles. I don't know if that's reasonable, but it seems reasonable to me.
=> Limit dependabot to Fridays. So much noise.

packages/core/src/babelPlugins/__tests__/babel-plugin-redwood-directory-named-imports.ts, packages/core/src/babelPlugins/babel-plugin-redwood-directory-named-import.ts, packages/internal/src/paths.ts
This PR uses a relative path to test if a module exists, but then returns an import-type path for for importing the module.
=> Fix directory named imports

README.md
This is related to https://github.com/redwoodjs/redwoodjs.com/issues/339. Now that we have a quick start guide in the docs, we can link to it.
=> Added Quick Start callout to Quick Start page

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/foreignKeys/new.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/index.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/new.js, packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/show.js, packages/cli/src/commands/generate/scaffold/templates/components/Name.js.template, packages/cli/src/commands/generate/scaffold/templates/components/Names.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NewName.js.template
We've changed to the default caching policy in Apollo's client. So now we're require to update our cache manually. This adds a stop-gap solution which reloads the queries.
We're going to evaluate different GraphQL clients, and based on the evaluation, we'll add a more robust cache updating technique or switch libraries.
=> Add refetch queries to create and delete mutations.

packages/cli/src/commands/generate/cell/__tests__/fixtures/camelCaseWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/kebabCaseWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/multiWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/singleWordCell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/snakeCaseWordCell.test.js, packages/cli/src/commands/generate/cell/templates/test.js.template
Right now the cell tests are testing very specific (sometimes the exact) text output from each state (Loading, Empty, Failure, Success). As soon as you change anything in any of these functions, the test fails. I feel like this is not ideal for new developers, or new-to-Redwood developers—a failing test inherently signals to you that you did something "bad" but in this case you just started building out your real functionality. Why should they be "punished" for that?
I propose that the default Cell tests follow the lead of the default Component, Page and Layout tests: just check that no errors are raised. Once you get your component/cell dialed in you can update your test to target specific output, but when you're just building them out the safest thing to check is that no errors are …
=> Proposal: Update cell tests to just test that nothing is thrown

packages/cli/src/commands/dataMigrate/up.js
The `prisma.disconnect` function has been deprecated in favor of `prisma.$disconnect`.  
Fix #1402
=> fix: :bug: fix `prisma.disconnect` deprecated warning

packages/cli/src/commands/test.js
@thedavidprice and I got on a call and were trying to figure out why running the test suite with `yarn rw test` would wipe out the dev database. 
Turns out that when you don't specify a side with the command (like `yarn rw test api`) that *no* sides are set, and it skips the DB setup code that sets the `DATABASE_URL` to `TEST_DATABASE_URL`.
/cc @RobertBroersma @peterp
=> Default sides to all in test command

packages/cli/src/commands/generate/deploy/providers/netlify.js, packages/cli/src/commands/generate/deploy/providers/vercel.js
🚚  Updated the CLI command rw generate deploy anchor links to match the documentation for Netlify and Vercel.
Fixes https://github.com/redwoodjs/redwood/issues/1421.
=> 🚚  Updated the CLI command rw generate deploy anchor links to match the documentation for Netlify and Vercel

packages/web/src/graphql/withCell.tsx
=> Add fetchPolicy and nextFetchPolicy to beforeQuery

packages/auth/src/AuthProvider.tsx, packages/auth/src/authClients/firebase.ts
So far this works for me with:
tried microsoft, but couldn't get their oauth config to work.
The login function wasn't returning the data from the client login, this may be useful in some cases.
---
**Breaking changes:** none 🤞🏽
@peterp, @dthyresson would love your thoughts, and tips on how to add more tests.
﻿
=> improve(auth): Add multiproviders for firebase auth

packages/api/src/makeMergedSchema/rootSchema.ts
For easier debugging we want to add PrismaVersion to the `redwood`
graphql call. This can help people easier identify which version of
Prisma is actually running.
Fixes: #1395
=> Add prismaVersion to redwood graphQL call

packages/api/src/makeMergedSchema/rootSchema.ts
fixes typo introduced [here](https://github.com/redwoodjs/redwood/commit/0f1a378829fb280e7a2e89f914ce69baf5130f44) which seems to be breaking latest canary revs. 
All the best, 
António
=> fix prisma version field resolver not working

packages/cli/src/commands/test.js
My previous PR fixed it for migrating the database, but the new `DATABASE_URL` wasn't being given to the actual jest run, so that was still overriding the dev database.
=> Overwritten DATABASE_URL wasn't being used in actual Jest run

packages/core/config/webpack.common.js, packages/core/config/webpack.development.js, packages/core/package.json, packages/internal/src/config.ts, yarn.lock
Adds fast refresh support, but it must be enabled in redwood.toml like this:
```toml
[web]
#... others
experimentalFastRefresh = true
```
Obligatory tape to show how it works:
=> Add fast-refresh plugin. Experimental support only

packages/cli/src/commands/storybook.js
This adds two flags, one is to open in browser on start, and the other
is to set a different port if you want to.
Fixes: #916
=> Add flag to storybook command

packages/api-server/src/http.ts, packages/dev-server/src/http.ts
I came across a few bugs in the http-servers, both for dev and production. This PR fixes:
=> Small http server tweaks

packages/cli/src/commands/test.js
Jest will run all test files simultaneously by default. This means it's impossible to test services—any database records created in them can potentially be overwritten or wiped out by another file running at the same time.
This PR adds the `--runInBand` flag that makes Jest run each file one after the other. It's too bad we can't do this just for the api side but I don't see any way to specify that only certain files should run in band and not others.
Strangely enough this actually makes the services tests *feel* faster since you see them running and completing in sequence, instead of nothing happening for a couple of seconds and then them all completing at the same time.
=> Run Jest tests in sequence

packages/api/src/makeMergedSchema/rootSchema.ts
actually fetch and consume prismaVersion the right way
#1495 solved the crash but didn't solve the root issue which was to actually have #1395
working as intended. (my bad for not testing enough :( ).
this one fixes it (famous last words).
All the best, and sorry for the noise
=> Fixes setting Prisma Version in root redwood schema

packages/core/package.json
Moves fast refresh dependencies to main dependencies instead of dev. It's dev for the user, not for RW
=> Move fast refresh to dependencies, instead of dev

packages/core/config/webpack.common.js, packages/core/config/webpack.development.js
Moves fast-refresh plugin to `webpack.common.js` as it _can_ be used by storybook.
Storybook doesn't currently use `webpack.development.js` - we should think about renaming these files to be a little bit more explicit perhaps?
=> Move fast-refresh config to work with storybook

.github/workflows/create_pr_package.yaml
This is a Github action that builds PR branches and runs `npm pack` to create packages. These packages are then uploaded to s3 and links are posted as a comment on the PR
Before merging this PR AWS secrets should be added to the repo (I don't have access to do that)
Resolves #1458
=> GH Action to create packages from PRs

packages/cli/src/commands/dev.js, packages/internal/src/__tests__/config.test.ts, packages/internal/src/config.ts
We've introduced a new `redwood.toml` configuration option that allows you to change the default prisma schema path. It's now `./api/db` instead of `./api/prisma` when you create a new project.
This sets the default value for existing projects back to the default so that upgrading the the latest version
=> Use original prisma schema path.

packages/cli/src/commands/__tests__/build.test.js, packages/cli/src/commands/dbCommands/__tests__/dbCommands.test.js, packages/cli/src/commands/dbCommands/down.js, packages/cli/src/commands/dbCommands/generate.js, packages/cli/src/commands/dbCommands/introspect.js, packages/cli/src/commands/dbCommands/save.js, packages/cli/src/commands/dbCommands/studio.js, packages/cli/src/commands/dbCommands/up.js
Issue:
If your RedwoodJS project path includes characters like spaces or other problematic characters like ( or ), then the schema cannot be found and all the `db`-related generators like save, up, etc fail like:
```
yarn rw db save                                           
yarn run v1.22.10
$ '/Users/username/Dropbox (Personal)/projects/redwoodjs/pectin/node_modules/.bin/rw' db save
Creating database migration... [started]
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `yarn prisma migrate save --name "migration" --create-db --experimental --schema=/Users/username/Dropbox (Personal)/projects/redwoodjs/pectin/api/db/schema.prisma'
Creating database migration... [failed]
→ Command failed with exit code 2: yarn prisma migrate save --name "migration" …
```
=> Fixes DB Generators failing when a schema path includes spaces or other problematic characters

packages/cli/src/commands/storybook.js
This PR addresses issue #1278
https://github.com/redwoodjs/redwood/issues/1278
Now, the `yarn rw storybook` command succeeds to:
```
yarn rw storybook     
yarn run v1.22.10
$ '/Users/dthyresson/Dropbox (Personal)/projects/redwoodjs/pectin/node_modules/.bin/rw' storybook
$ '/Users/dthyresson/Dropbox (Personal)/projects/redwoodjs/pectin/node_modules/.bin/start-storybook' --config-dir ../node_modules/@redwoodjs/core/config/storybook --port 7910 --no-version-updates --static-dir '/Users/dthyresson/Dropbox (Personal)/projects/redwoodjs/pectin/web/public' --ci
$ '/Users/dthyresson/Dropbox (Personal)/projects/redwoodjs/pectin/node_modules/.bin/msw' init '/Users/dthyresson/Dropbox (Personal)/projects/redwoodjs/pectin/web/public'
Initializing the Mock Service Worker at "/Users/dthyresson/Dropbox …
```
=> Fix #1278 launch Storybook with path w/ spaces

.github/workflows/create_pr_package.yaml
I've included the sha-1 of the commit in the filename to make it more deterministic what package (code) you install and deploy. There is still only one comment from the bot with the filenames. Each time a new commit comes on on the PR the comment is updated. You can always see past comments (with the old filenames) by using the dropdown on the comment, see screenshot. The screenshot also shows that the first 7 characters of the commit sha-1 are included in the package filenames
/cc @jeliasson
=> create_pr_package: Unique names per build

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
[2.11.0](https://github.com/prisma/prisma/releases/tag/2.11.0)
- Native database types in the Prisma schema (Preview)
- New types in the Prisma schema: BigInt, Bytes and Decimal (Preview)
- Set foreign keys directly (Preview)
[2.10.2](https://github.com/prisma/prisma/releases/tag/2.10.2)
[2.10.1](https://github.com/prisma/prisma/releases/tag/2.10.1)
[2.10.0](https://github.com/prisma/prisma/releases/tag/2.10.0)
- Support for Microsoft SQL Server (Preview)
- Single-command schema changes for prototyping `prisma db push` (Preview)
=> upgrade to Prisma v2.11.0

packages/web/src/components/FetchConfigProvider.tsx
**Edit**: originally I tried to reprise the control flow of RedwoodProvider; now we just default `loading` and `isAuthenticated` to false.
---
Right now the `FetchConfigProvider` tries to invoke the `useAuth` hook immediately (line 28; the check to see if `useAuth` is defined is 15 lines later at 43):
https://github.com/redwoodjs/redwood/blob/a78cfe80d852ff53ce108face446db869ddba9b6/packages/web/src/components/FetchConfigProvider.tsx#L20-L45
This a problem for no-auth Redwood apps; they get this error on `yarn rw dev`:
This PR reprises the control flow similar to the `RedwoodProvider` in v0.21.0, which checks to see if `useAuth` is defined and returns a provider appropriately:
https://github.com/redwoodjs/redwood/blob/53349fd121f9198a8fdb5c0217cec8c4f8b6badd/packages/web/src/components/Red …
=> Fix FetchConfigProvider to reprise handling no auth

packages/cli/src/commands/storybook.js, packages/core/config/storybook/main.js
This adds `--build` to the `yarn rw storybook` command, it produces a set of files that can be statically served. Handy during pull-requests.
=> Add --build option to `yarn rw storybook`

packages/auth/src/AuthProvider.tsx, packages/auth/src/__tests__/AuthProvider.test.tsx, packages/router/package.json, packages/router/src/__tests__/router.test.js, packages/router/src/router.js, packages/testing/src/MockProviders.tsx, packages/web/src/components/FetchConfigProvider.test.tsx, packages/web/src/components/FetchConfigProvider.tsx
This PR does a whole bunch, and changes some fundemental behaviour, but for the better.
Previously we would block all rendering until we were able to determine if a user was logged in, once we were able to determine that a user was logged, and they were, we would further block until we had a currentUser.
This blocking behaviour is now based on the type of route:`<Private />` blocks, `<Route />` does not. You can also supply a loading component whilst you're waiting for auth-state-hydration:
```<Private whileLoading={() => 'Loading...'} />```
Thanks to @dac09 for the idea!
/cc @Tobbe you might find this interesting too :)
=> Only stop rendering on Private routes

packages/auth/src/authClients/supabase.ts
With the upgrade to Supabase v1.0, graphql calls are not getting authenticated because the token is not being set.
Supabase v1.0 changes the way the user and access token information is set in localStorage.
Previously, this code in the supabase auth provider client would fetch the accessToken by parsing the `supabase.auth.token' contents and then would retrieve the accessToken:
```
getToken: async () => {
const supabaseJson = localStorage.getItem('supabase.auth.token')
const supabaseData = supabaseJson ? JSON.parse(supabaseJson) : null
return supabaseData?.accessToken || null
},
```
In the new supabase-js SDK, this info is kept in a "currentSession" in localStorage and the there is a method to fetch the session which can then retrieve the access token:
```
getToken: async () => {
const …
```
=> Supabase getToken uses session to get access_token so that graphql calls are authenticated

packages/cli/src/commands/setup/tailwind/tailwind.js
This PR changes the version of Tailwind CSS installed by the setup command to be compatible with v7 of PostCSS. (I got the version from here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build.)
=> Update Setup TailwindCSS to v2 using PostCSS v7 compatible install

packages/cli/src/commands/generate/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/cell.js, packages/cli/src/commands/generate/component/__tests__/component.test.ts, packages/cli/src/commands/generate/component/component.js, packages/cli/src/commands/generate/helpers.js, packages/cli/src/commands/generate/layout/__tests__/layout.test.ts, packages/cli/src/commands/generate/layout/layout.js, packages/cli/src/commands/generate/page/__tests__/page.test.js, packages/cli/src/commands/generate/page/page.js, packages/cli/src/commands/generate/service/__tests__/service.test.js, packages/cli/src/commands/generate/service/service.js
This adds flags to the generator to allow people to skip test generation and story file generation.
List of generators that need to be changed:
Fixes #1444
=> Add flags to generators to skip tests and story files

.github/workflows/publish_pr_packages.yaml, packages/cli/src/commands/upgrade.js
Adds the ability to install the PR packages we build using the `upgrade` cli command.
Example:
`$ yarn rw upgrade --pr 1454:0.21.0-d3b0abd`
You specify the PR id (1454 in the example above), the base RW version the PR is based on (0.21.0 above) and the SHA of the commit that was built (d3b0abd).
Yes, it would be nice if you could just do `yarn rw upgrade --pr 1454` and get the latest packages built for that PR. But I think we can add that in a future PR. Also, the exact command you need to run is provided as a comment on the PR. So just copy/paste and you're good to go. I think that's easy enough.
=> Add --pr to upgrade command

packages/auth/src/authClients/netlify.ts, packages/core/src/configs/browser/jest.setup.js, packages/core/src/storybook/StorybookProvider.tsx, packages/testing/src/mockRequests.ts
We tried to automatically determine which env MSW is using, that was flakey. Now it's explicit by passing in the required target.
=> Explicit target environment for MSW

packages/router/src/__tests__/router.test.js, packages/router/src/named-routes.js
Fixed #1453 
e.g. Say you're going to `https://mysite.com/dashboard?param1=something&token=hunter2`
It used to redirect to `https://mysite.com/login?redirectTo=/dashboard`. Now it'll redirect to `https://mysite.com/login?redirectTo=/dashboard%3Fparam1%3Dsomething%26token%3Dhunter2`
Adds tests for:
---
=> fix(router): Include queryParams in redirectTo

packages/cli/src/commands/generate/deploy/providers/aws_serverless.js
Fixes #1550
Note: The ternary in the template string isn't necessarily the cleanest looking solution, but it seems to be the simplest.
=> Fix aws_serverless config when api folder missing

packages/api/src/auth/decoders/azureActiveDirectory.ts, packages/api/src/makeMergedSchema/makeMergedSchema.ts, packages/auth/src/authClients/azureActiveDirectory.ts, packages/auth/src/authClients/index.ts, packages/cli/src/commands/generate/auth/providers/azureActiveDirectory.js, packages/cli/src/commands/generate/component/__tests__/component.test.ts, packages/cli/src/commands/generate/layout/__tests__/layout.test.ts, packages/core/src/storybook/StorybookProvider.tsx, packages/forms/src/index.tsx, packages/structure/src/model/RWCell.ts, packages/structure/src/model/RWRouter.ts, packages/structure/src/x/child_process.ts, packages/testing/src/__tests__/MockRouter.test.tsx
I've fixed 20 eslint warnings. (106 down to 86.)
I didn't look at all the `any` warnings. 
There are a couple of other warnings that I plain didn't know how to fix. Plz help? It's "Don't use `Function` as a type." in `mockRequests.ts` and "Don't use `{}` as a type" in `vscode.ts`. Both can totally be left to be solved in another PR.
As long as no one spots any error in what I've done I think this is good to merge, and then we can keep squashing those warnings in future PRs.
=> Fixed a few eslint warnings

packages/forms/src/FormError.tsx, packages/forms/src/index.tsx
The `<FormError>` `error` prop was previously typed as `any`. This PR tries to give it some proper typings.
In adapting the code for the types I also made some small implementation changes. I've tried to test things manually, but it's difficult to know what exactly to do to trigger all possible error states. I have, for example, not been able to trigger an error that hits [line 78](https://github.com/redwoodjs/redwood/pull/1510/files#diff-d62339bed2ff80375e94b9f3e929214dfcac60aa1ebad0f49c2cb3870027bcabR78) (That's [line 163](https://github.com/redwoodjs/redwood/pull/1510/files#diff-f22ed6538894aa3d779aa9616f36c5c8343be52cbfae026288a749c3a839e7aaL163) the old code)
=> forms: Improve typings for errors

packages/auth/src/authClients/firebase.ts
Adds `password` as a login/signup method for [Firebase Auth](https://firebase.google.com/docs/auth/web/password-auth).
Example:
```javascript
const { logIn, signUp } = useAuth()
await signUp({ email: 'test@test.com', password: 'testPassword' })
await login({ email: 'test@test.com', password: 'testPassword' })
```
=> Firebase Auth: Signup, login with email, password

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
> note: as of Prisma 2.13 the dynamic provider is deprecated. We need to resolve the SQLite deploy issue with the Tutorial before upgrading further
This version of Prisma includes a **BREAKING** change for 1-1 relations:
https://github.com/prisma/prisma/releases/tag/2.12.0
https://github.com/prisma/prisma/releases/tag/2.12.1
- Standalone Prisma Studio app for macOS
- Prisma codemods help upgrading your codebase
- Microsoft SQL Server now supports native database types (Preview)
- BREAKING: Remove non-$ methods
- BREAKING: 1-1-relations must now have an optional side
- BREAKING: Fix how data for Json[] fields is stored
- DEPRECATION: Rename findOne to findUnique
- DEPRECATION: Move most types under the Prisma namespace
=> Upgrade Prisma v2.12.1

packages/auth/src/AuthProvider.tsx, packages/auth/src/__tests__/AuthProvider.test.tsx, packages/testing/src/MockProviders.tsx, packages/web/src/components/RedwoodApolloProvider.tsx
+ AuthContext.authToken to be deparacated
Starts fix for #1576. Implements proposal and discussion in #1608
Verified only with firebase, but individual provider changes will be added later.
=> Configure ApolloProvider to always use fresh tokens 

packages/auth/src/AuthProvider.tsx, packages/auth/src/__tests__/AuthProvider.test.tsx, packages/web/src/components/RedwoodApolloProvider.tsx
Reverts redwoodjs/redwood#1609
Breaking on integration tests with a very unhelpful GraphQL error `Error: getToken is not a function` and no other error output.
=> Revert "Configure ApolloProvider to always use fresh tokens "

packages/core/package.json
=> Move whatwg-fetch from devDep to dep

packages/cli/src/commands/generate/auth/templates/auth.js.template, packages/cli/src/commands/generate/auth/templates/azureActiveDirectory.auth.js.template, packages/cli/src/commands/generate/auth/templates/firebase.auth.js.template, packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord_crud.js, packages/cli/src/commands/generate/service/__tests__/fixtures/multiWord_crud.ts, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_belongsTo.js, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_belongsTo.ts, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_crud.js, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_crud.ts, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_hasMany.js, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_hasMany.ts, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_multiple.js, packages/cli/src/commands/generate/service/__tests__/fixtures/singleWord_multiple.ts, packages/cli/src/commands/generate/service/templates/service.ts.template
=> Replace prisma deprecated fineOne() -> findUnique()

packages/cli/src/commands/console.js
Another way of abstracting away the need for top-level await in the redwood console, by automatically resolving promises (cc @mojombo from today's contributor's meetup).
A really nice copy-paste fix I took from the resources referenced in https://github.com/redwoodjs/redwood/issues/1613#issue-781559618 ("hack the eval").
Also tagging @peterp just in case you want to take a look at this one too. Guled brought up the good point that even if we enable top-level await, it might be annoying to have to type "await ..." all the time.
=> Resolve promises in the console

README.md, tasks/all-contributors/.all-contributorsrc, tasks/all-contributors/.crwa.all-contributorsrc, tasks/all-contributors/.rwjs.com.all-contributorsrc
I noticed that the all-contributors data hasn't been updated in a while so I followed the steps [here](https://github.com/redwoodjs/redwood/tree/main/tasks/all-contributors/README.md) to generate the updated version.
=> Updated All-Contributors Data

README.md, tasks/all-contributors/.all-contributorsrc, tasks/all-contributors/.crwa.all-contributorsrc, tasks/all-contributors/.learn.all-contributorsrc, tasks/all-contributors/.rwjs.com.all-contributorsrc, tasks/all-contributors/README.md, tasks/all-contributors/mergeContributors.js
This adds the new `learn.redwoodjs.com` repo to the #contributors data files and docs. Contributors are also up to date. 
Total count is 151 + 12 (core team) = 163
@clairefro I've added @mbush92 and @Thieffen to the contributor's data for `learn.redwoodjs.com`. You're already included in the #core-team section. And @Thieffen is already a contributor but there's additional information about the contribution to this repo.
When the project is announced, we'll do a proper write up giving massive props to you all (and the others that help between now and then) 🚀
=> add learn.rwjs.com repo to contributors

packages/api/src/auth/decoders/netlify.ts
Explicitly check for `NODE_ENV === 'development'` and `NODE_ENV === 'test'` to make the code easier to understand
=> Auth: Netlify decoder: specifically check for dev and test

packages/api/src/functions/graphql.ts
Fixes https://github.com/redwoodjs/redwood/issues/1591
=> GQL Playground: Only run in dev mode

packages/structure/src/model/RWCell.ts
Someone asked on Discord where we define what's a Cell and not, besides babel. 
I thought about the structure package and noticed the comment in there had a negation wrong, which is confusing. This fixes that (cells *do* have a QUERY export)
=> Structure: Fix cell comment

packages/api/src/auth/decoders/ethereum.ts, packages/api/src/auth/decoders/index.ts, packages/auth/README.md, packages/auth/package.json, packages/auth/src/authClients/ethereum.ts, packages/auth/src/authClients/index.ts, packages/cli/src/commands/generate/auth/auth.js, packages/cli/src/commands/generate/auth/providers/ethereum.js, packages/cli/src/commands/generate/auth/templates/ethereum.auth.js.template
This PR allows users to log in with an ethereum wallet. See discussion on discourse: https://community.redwoodjs.com/t/custom-auth-web3-ethereum/1618/2
In parallel with this PR I have created + published the client library `@oneclickdapp/ethereum-auth` https://github.com/oneclickdapp/ethereum-auth
Looking forward to feedback!
=> Add Auth Provider - Ethereum

packages/cli/src/commands/setup/tailwind/tailwind.js
=> Tailwind Setup: Use fully specified paths

packages/auth/src/useAuth.ts, packages/cli/src/commands/generate/auth/auth.js, packages/core/config/webpack.common.js, packages/create-redwood-app/template/web/src/index.js, packages/testing/src/MockProviders.tsx, packages/testing/tsconfig.json, packages/web/package.json, packages/web/src/components/apollo.ts, packages/web/src/flash/README.md, packages/web/src/index.ts
Redwood bundles Apollo GraphQL, but offers the ability to specify your own GraphQL client. Unfortunately even when you use your own GraphQL client you'll still get Apollo bundled. This PR attempts to place Apollo's client outside of `main`, so if you do not use it it will not be bundled.
=> Don't bundle Apollo Client if the user specify their own client

.eslintignore, packages/api/src/auth/decoders/supabase.ts, packages/auth/src/__tests__/AuthProvider.test.tsx, packages/cli/src/commands/dev.js, packages/structure/src/model/RWPage.ts, packages/web/src/components/RedwoodApolloProvider.tsx
Ignores the template folder in CRWA, to avoid loading lots of eslint rules that are only meant to apply to the redwood project (on the users side), not on the redwood repo
=> Ignore linting template folder in create-redwood-app

packages/auth/src/authClients/netlify.ts, packages/auth/src/authClients/supabase.ts, packages/cli/src/commands/generate/auth/providers/supabase.js
With Supabase 1.0, it supports OAuth via 'bitbucket' | 'github' | 'gitlab' | 'google' | 'azure' as well as Magic Link passwordless email auth.
resolves https://github.com/redwoodjs/redwood/issues/1538
resolves https://github.com/redwoodjs/redwood/issues/1537
resolves https://github.com/redwoodjs/redwood/issues/1246
addresses https://github.com/redwoodjs/redwood/issues/1479
See: https://supabase.io/docs/client/auth-signin
Note that Supabase will support Azure as well, they just have not undated their docs or admin interface to configure the provider.
Authentication doc updates are here: https://github.com/redwoodjs/redwoodjs.com/pull/531
And can be previewed: https://deploy-preview-531--redwoodjs.netlify.app/docs/authentication#supabase
Updates to the playground auth is: …
=> Support Supabase OAuth and Magic Link auth

packages/router/README.md
The component said 'Routes' instead of 'Route'
=> Fix typo in Private Routes

packages/auth/src/authClients/azureActiveDirectory.ts
PR updates Azure Active Directory default AuthRequest's `scopes` when trying to silently acquire a token
See resolved discussions
https://github.com/redwoodjs/redwoodjs.com/pull/534
=> Azure Active Directory: Updating default auth request for acquireTokenSilent

packages/cli/src/commands/dataMigrate/install.js
Fix: https://github.com/redwoodjs/redwood/issues/1717
Data Migrate Command: dataMigrate install refers to `yarn rw db up` when it should refer to `yarn rw dataMigrate up`
When running the command `yarn rw dataMigrate install`:
```
... dataMigrate install
✔ Creating dataMigrations directory...
✔ Adding RW_DataMigration model to schema.prisma...
✔ Create db migration...
✔ Next steps:
Don't forget to apply your migration when ready:
yarn rw db up
✨  Done in 6.17s.
```
However, the message should be:
`yarn rw dataMigrate up`
as that is the instruction after creating a dataMigration file:
```
✔ Generating data migration file...
✔ Successfully wrote file `./api/prisma/dataMigrations/20210203150029-some-migration.js`
✔ Next steps...
After writing your migration, you can run it with:
yarn rw …
```
=> Corrects dataMigrate install instructions

packages/core/src/babelPlugins/babel-plugin-redwood-import-dir.ts, packages/core/src/babelPlugins/babel-plugin-redwood-routes-auto-loader.ts
This PR addresses the concern raised in https://github.com/redwoodjs/redwoodjs.com/issues/539
This is what it looks like now, with this fix (and a fix for the Windows paths, but that's another PR another time)
**EDIT:** Also added formatting of the other two .d.ts files we're generating
=> Format generated *.d.ts files

packages/router/package.json
Makes type generation run when you manually build just the router package. See this comment for more context https://github.com/redwoodjs/redwood/pull/1641#discussion_r569810369
=> Router: Explicitly build types

.github/workflows/create_pr_artifact.yaml, .github/workflows/publish_pr_packages.yaml
When you fork a repo you get all the repo's actions as well. That means the PR build and publish actions will run. But they'll fail because they don't have access to the S3 bucket secret (which is as it should be). So there really is no point in running these on any other repo than redwoodjs/redwood
Thanks to @jeliasson for the idea!
=> Don't run PR build actions on forks

packages/auth/package.json, packages/auth/src/authClients/supabase.ts, yarn.lock
As of Supabase JS 1.3.3, Facebook is a supported OAuth provider.
This PR includes Facebook in the params to help inform developers of the supported providers and also bumps dependencies to 1.3.3 which then bumps the needed go-true lib that contains the types change to include `facebook`
=> Adds Facebook to list of supported Supabase OAuth providers

packages/cli/src/commands/prisma.js
Minor change to first check if flags exist (via user input). Will output error and console message if `--schema` is given at CLI.
=> improve rw prisma command options handling

packages/cli/jsconfig.json, packages/cli/src/commands/build.js, packages/cli/src/commands/dev.js, packages/cli/src/commands/prisma.js, packages/cli/src/lib/generatePrismaClient.js
```bash
◭  Prisma is a modern DB toolkit to query, migrate and model your database (https://prisma.io)
Usage
$ prisma [command]
Commands
init   Setup Prisma for your app
introspect   Get the datamodel of your database
generate   Generate artifacts (e.g. Prisma Client)
format   Formats your schema
Flags
--experimental   Show and run experimental Prisma commands
Examples
Setup a new Prisma project
$ prisma init
Introspect an existing database
$ prisma introspect
Generate artifacts (e.g. Prisma Client)
$ prisma generate
```
Closes #1749
=> Improvements to `rw prisma` alias

packages/cli/src/commands/prisma.js
Addresses https://github.com/redwoodjs/redwood/issues/1749
Ran
`yarn rw prisma migrate dev --create-only`
Because my path has spaces and parentheses in it on OSX, I get and error seen before with storybook and other commands where the path isn't surrounded by quotes, etc.
```
$ '/Users/dthyresson/some path (with parens)/projects/redwoodjs/some_app/node_modules/.bin/rw' prisma migrate dev --create-only
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `yarn prisma migrate dev --create-only --preview-feature --name migration --create-only --schema /Users/dthyresson/some path (with parens)/projects/redwoodjs/some_app/api/db/schema.prisma'
...
Unknown arguments: create-only, createOnly, dev
error Command failed with exit code 1.
```
Modified
``` …
```
=> [v0.25] - Prisma migrate dev now handles schema path with spaces

packages/cli/src/commands/prisma.js
Two fixes. 
I wrote the format of the yargs command incorrectly and I was filtering out the wrong things in the args.
=> Fix rw prisma alias bugs

packages/cli/src/commands/prisma.js
While a prior PR fixed the case when the Prisma schema path has spaces or parentheses, this PR fixes the case where prisma itself exists in a path with spaces.
=> Fixes `prisma` command when path has spaces

packages/cli/src/commands/test.js
Required for back-to-back runs of `rw test`. Otherwise would prompt for migrations and/or being out of sync.
=> use prisma db push for test DB

packages/core/package.json, yarn.lock
Current canary packages result in a Vercel deployment failure --> built API is > 50mb. Prisma has suggested _not_ using the new `prisma` package as a possible workaround.
This PR is an attempt to give it a go.
=> [v0.25] revert to @prisma/cli; recreate yarn.lock

packages/structure/src/model/RWEnvHelper.ts
"pisma" is probably "prisma"? :)
I don't know much about the structure package and am not aware whether the code is being used anywhere else.
At least grep'ing the RW source says no.
=> "pisma" is probably "prisma"

packages/cli/src/commands/prisma.ts
Fixes #1786
**1. Allows interactivity when using commands like `yarn rw prisma migrate reset`**
**2. Only show tip in help, or if prisma has yarn prisma in its output**
The downside:  if you run the wrong command, redwood tip won't show.
The upside: fail fast, and removes confusion where the tip isn't relevant, if you're running `yarn rw prisma migrate dev` and it fails, it won't show the tip (where its not relevant anyway)
=> Hotfix: Use inherit to allow interactivity in yarn rw prisma

packages/cli/src/commands/dataMigrate/install.js, packages/cli/src/commands/dataMigrate/up.js
The legacy dataMigrate install invoked `yarn rw db save` which is deprecated and not longer works.
This PR changes the command to use:
`yarn rw prisma migrate dev --create-only` and passes the migration name as `--name=create_data_migrations`.
Note that I have tested that `yarn prisma migrate dev --create-only --name=create_data_migrations --preview-feature --schema "...api/db/schema.prisma"` works as expected, so I know can pass the migration name this way.
Unfortunately due to other prisma output issues (? https://github.com/redwoodjs/redwood/issues/1786 ?) when running the command in the current `0.25.1-canary.2` release with this PR applied:
`yarn rw dataMigrate install`
I get the error:
```
✔ Creating dataMigrations directory...
✔ Adding RW_DataMigration model to schema.prisma...
✖ …
```
=> dataMigrate install uses prisma migrate command

packages/cli/src/commands/dataMigrate/install.js
_continues https://github.com/redwoodjs/redwood/pull/1787_
In the v0.25 point release, we saw during `dataMigrate install` duplicated output like:
```
✔ Creating dataMigrations directory...
✔ Adding RW_DataMigration model to schema.prisma...
⠦ Create db migration...
One more thing...
✔ Creating dataMigrations directory...
✔ Adding RW_DataMigration model to schema.prisma...
⠏ Create db migration...
✔ Creating dataMigrations directory...
✔ Adding RW_DataMigration model to schema.prisma...
⠸ Create db migration...
One more thing...
Prisma schema loaded from db/schema.prisma
Datasource "DS": SQLite database "dev.db" at "file:./dev.db"
✔ Creating dataMigrations directory...
✔ Adding RW_DataMigration model to schema.prisma...
✔ Create db migration...
✔ Next steps:
Don't forget to apply your …
```
=> Attempt to fix dm install duplicate console output

README.md
This PR adds a bullet to the end of the Features list directing readers to the Roadmap. @thedavidprice is this what you had in mind?
=> Docs: link to roadmap in readme

packages/create-redwood-app/template/web/src/entry.js, packages/create-redwood-app/template/web/src/index.js
- Fix entry js, not sure when rootElement went missing!
- Make index a little more readable, as it confuses people with the export default function
=> Fixes to crwa template for prerender

packages/router/src/router.tsx
Adds support for the `prerender` prop on routes, and fixes the type for `notfound`
=> Router: Fix TS types

.eslintignore, packages/create-redwood-app/template/web/src/entry.js, packages/create-redwood-app/template/web/src/index.js
Thi would've prevented the bug in #1819, which was that a variable was undefined.
=> Lint the create-redwood-app template

packages/create-redwood-app/src/create-redwood-app.js
I propose this change for uniformity reason so that anyone searching for "single-quoted" strings would not miss this one. There is a chance that the author had a good reason for avoiding "double-quoted" strings - in that case, please ignore this PR.
=> Remove backticks

CONTRIBUTING.md
Removes step for upgrading to canary (which can cause probablems with rwt link)
=> Docs: Update CONTRIBUTING.md `rwt link` docs

packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/setup/auth/auth.js, packages/cli/src/commands/setup/auth/providers/auth0.js, packages/cli/src/commands/setup/auth/providers/azureActiveDirectory.js, packages/cli/src/commands/setup/auth/providers/ethereum.js, packages/cli/src/commands/setup/auth/providers/firebase.js, packages/cli/src/commands/setup/auth/providers/goTrue.js, packages/cli/src/commands/setup/auth/providers/magicLink.js, packages/cli/src/commands/setup/auth/providers/netlify.js, packages/cli/src/commands/setup/auth/providers/nhost.js, packages/cli/src/commands/setup/auth/providers/supabase.js, packages/cli/src/commands/setup/i18n/i18n.js
Prerender added the file `web/src/App.js` and placed `web/src/index.js` in the Redwood Web package.
This PR updates all other commands and references to index.js that should now be App.js, e.g. the Scaffold generator css is now added as an import to App.js.
=> replace instances of web/src/index.js with web/src/App.js

packages/cli/src/commands/generate/scaffold/__tests__/fixtures/components/form.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/scaffold/templates/components/NameForm.js.template, packages/forms/src/__tests__/form.test.tsx, packages/forms/src/coercion.tsx
Two parts:
1. if you're using a `<DateField>` or `<DatetimeLocalField>` form element, the data will be coersed into the proper format (`yyyy-mm-ddThh:mm:ss.sssZ`) before sending through GraphQL 
2. when using the scaffold generator, datetimes are formatted properly before being set as the `defaultValue` prop in  `<DatetimeLocalField>` (`yyyy-mm-ddThh:mm`)
Closes #1457
=> Fixes marshalling datetimes in and out of forms

packages/create-redwood-app/template/package.json
to prevent module duplication in web/node_modules
The recent upgrade to React 17.x, and storybook's dependency on 16.x causes this duplication.
Fixes https://github.com/redwoodjs/redwood/issues/1907
Fixes https://github.com/redwoodjs/redwood/issues/1931
=> Adds resolution for react to template

packages/cli/src/commands/prerender.js
As suggested by @thedavidprice, runs a diagnostic check for duplicated node_modules when prerendering fails
When all goes well: https://s.tape.sh/N7s2V5ED
When diagnostics pass, but prerender fails: https://s.tape.sh/W6L6LqKK
When diagnostics also fail: https://s.tape.sh/W6L6LqKK
Much clearer logs when running `yarn rw prerender --dryrun`
https://s.tape.sh/Qpm2jVKs
FYI: 
the diagnostic might be useful for storybook too, because storybook can break because of the duplicated modules as well
=> Run a diagnostic check when prerender fails

packages/api/src/auth/decoders/azureActiveDirectory.ts
As per ongoing partial Azure Active Directory outage I noticed that the error message thrown by the `azureActiveDirectory` auth client might be enough for initial troubleshooting. 
**Error**
```
api | TypeError: Cannot read property 'getPublicKey' of undefined
api |     at Immediate._onImmediate (/home/johan/work/git/sjoraddningssallskapet/ssrs-se-portal/node_modules/@redwoodjs/api/dist/auth/decoders/azureActiveDirectory.js:39:33)
api |     at processImmediate (internal/timers.js:463:21)
api |     at process.callbackTrampoline (internal/async_hooks.js:131:14)
```
This PR will give the developer an early indication on what may be wrong. 
```
api | An error occured while trying to obtain signing key from Azure Active Directory. This might be a result of a Azure Active Directory outage. See …
```
=> Azure Active Directory Auth: Adding try-catch block on callback to capture empty key

packages/auth/package.json, yarn.lock
Both @dthyresson and I experienced local development issues with `yarn install` failing due to the `gotrue-js` package not being found. The version of Gotrue installed is the GitHub package registry:
https://github.com/redwoodjs/redwood/blob/15dff8915505c1b0b643b51cd21aa3481e017da5/packages/auth/package.json#L17
This was added 9 months ago. Since then there have been several patch releases with no breaking changes. I upgrade to the latest version in this branch, which resolved my installation issues. See https://github.com/netlify/gotrue-js/releases I believe the GitHub registry version corresponds with [v0.9.22](https://github.com/netlify/gotrue-js/releases/tag/v0.9.22), which is 2 years old now.
@peterp I'm assuming you used the GitHub registry version to solve a specific problem. …
=> Fix yarn install errors: upgrade `gotrue-js` to v0.9.29

packages/cli/src/commands/lint.js
=> Fix lint breaking when deleting a side

packages/api/package.json, packages/cli/package.json, packages/cli/src/commands/prisma.js, packages/core/package.json, packages/structure/package.json, yarn.lock
- Prisma Migrate now GA
updated docs here: https://github.com/redwoodjs/redwoodjs.com/pull/636
closed #2013
=> Upgrade to Prisma 2.19.0 (Prisma Migrate GA)

packages/internal/src/__tests__/paths.test.ts, packages/internal/src/paths.ts
Fixes Issue #2015 
On Windows, the path did not resolve correctly when using pages in subdirectories.  Added some new tests and made a simple change to the code.  Note that glob appears to return posix style paths on Windows, so to the reference to path.sep did not work.
This is my first or (ever) so let me know if you have any suggestions for the future.
=> Fixed path on windows to allow for pages under subdirectories

packages/router/src/private-context.tsx, packages/router/src/router-context.tsx, packages/router/src/router.tsx
Hooks need to run in a predictable order.
If `useAuth` isn't passed to the router, it should use the default one from @redwoodjs/auth
=> Router: Fix auth

packages/core/config/storybook/main.js, packages/core/config/storybook/preview.example.js, packages/core/config/storybook/preview.js, packages/core/package.json, packages/internal/src/paths.ts, yarn.lock
This PR is a superset of https://github.com/redwoodjs/redwood/pull/2048. It lets users define a custom Storybook preview file in `web/config/storybook.preview.js`, and then merges that into the framework's storybook preview config.
Additionally, it bumps the `@storybook/react` dependency from 5.3 to 6.1 (the latest stable version). This turned out to be a pretty simple change, since none of the features that Redwood depends on broke. It *is* possible that this breaks some user Storybook configurations, but based on the small (if verbose) list of breaking changes from 5.3 -> 6.0 and 6.0 -> 6.1 [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) I think very few users will be affected.
I decided to combine these into one PR because they ended up being pretty intertwined. …
=> Bump Storybook to 6.1

packages/api/src/logger/README.md
The params in the Datadog and Logflare example code for the Logger README had incorrect params.
This PR fixes that so there are both `options` and `destination` params (not the destination is a part of options).
=> Fix Logger Readme destination param in transport examples

packages/cli/src/commands/upgrade.js
https://github.com/redwoodjs/redwood/issues/1659
used getPaths to get the base path, then added it to each execa with the cwd option
did some extremely rudimentary manual testing, so could definitely use some help on that front
=> Set `cwd` to project's base path when running `yarn rw upgrade`

packages/core/config/storybook/main.js
The a11y add on hasn't been fixed yet (see https://github.com/storybookjs/storybook/issues/14321); this PR just comments out the block of code enabling it by default. We can comment it back in when it's fixed.
Here's the console in the terminal again for reference:
=> Remove a11y addon (for now)

packages/router/src/__tests__/route-announcer.test.tsx
This PR fixes the following console error when running the route-announcer test
```
@redwoodjs/router:  PASS  src/__tests__/route-announcer.test.tsx
@redwoodjs/router:   ● Console
@redwoodjs/router:     console.error
@redwoodjs/router:       Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>.
@redwoodjs/router:           at html
@redwoodjs/router:           at RouteAnnouncementPage
...
```
The reason this was happening was that the markup `<html><head><title>...`, was being rendered inside `<body>` by dom testing lib's render function.
=> Fix invalid html in route announcer test

packages/api/src/makeMergedSchema/makeMergedSchema.ts
We supply typedefs a bit higher, so I'm making it optional a bit lower down.
The validation flags also need to be added to `addResolveFunctionsToSchema`, otherwise this isn't very helpful.
=> Fix typeDefs for schema options

packages/router/src/__tests__/router.test.tsx, packages/router/src/page-loader.tsx, packages/router/src/params.tsx, packages/router/src/router-context.tsx, packages/router/src/router.tsx
`useParams` should always contain the current parameters.
Closes #2137
=> useParams should always be populated.

packages/testing/src/MockRouter.tsx
We have a separate `<MockRouter>` that we use instead of the real `<Router>` when running tests in RW apps (not RW framework). This MockRouter is now updated to reflect the rewrite of the real Router.
Fixes #2131
=> Router: Populate `routes` for tests

packages/api/package.json, packages/create-redwood-app/template/package.json, packages/create-redwood-app/template/yarn.lock, yarn.lock
_continues https://github.com/redwoodjs/redwood/issues/2127 and https://github.com/redwoodjs/redwood/pull/2129_
If this is gtg, I'd like to include in v0.28.3 patch
- API console is clean — see screenshot below
I've added notes to v0.29 draft to remove resolution (if exists).
@peterp Let's discuss further the addition of crwa/template/yarn.lock I still don't see the benefit as it wouldn't have caught this issue had it existed previously. Feels like overhead that's not a full solution and my preference would be to remove it. TBD and doesn't need to be resolved prior to merging this PR.
=> [v0.28.3] Upgrade apollo-server-lambda and remove resolution

packages/cli/src/commands/setup/tsconfig/tsconfig.js, packages/cli/src/lib/index.js
Fixes `yarn rw setup tsconfig` for running on canary projects. 
In pseudocode
```
if canary, use main
else use v{REDWOOD_VERSION}
```
=> Fix setup tsconfig: github version tag for canary builds

packages/cli/src/commands/storybook.js
dependency of https://github.com/redwoodjs/redwood/pull/2073
This adds the `--output-directory` option to `yarn build-storybook`, providing an override to the default directory to store the built static files.
```
--build-directory  Directory in web/ to store static files
[string] [default: "storybook-static"]
```
TBD whether or not the default directory should be `web/public/storybook`. Files in public will be statically served during both local dev or deployment.
=> CLI Storybook command: add output directory option

packages/api/src/auth/decoders/auth0.test.ts, packages/api/src/auth/decoders/auth0.ts
This is small speed improvement for people using auth0 during development. Instead of verifying the token, which performs a network request to grab the key, we just decode it.
Closes #2155
=> Just decode, not verify, auth0 token during development and test.

packages/router/src/Set.tsx, packages/router/src/__tests__/set.test.tsx
Any prop you give to `<Set>` (except for `wrap`) will be passed on to the wrapper components.
This...
```
<Set wrap={[LayoutA, LayoutB]} data="atad" id="5">
<Route path="/" page={HomePage} name="home" />
</Set>
```
becomes...
```
<LayoutA data="atad" id="5">
<LayoutB data="atad" id="5">
<Route path="/" page={HomePage} name="home" />
</LayoutB>
</LayoutA>
=> Set: Forward props to wrapper components

packages/router/src/router-context.tsx, packages/router/src/router.tsx
In the rush to fix the `<Set>` bugs a regression to the Router props sneaked in. `routes` is not a required, or even valid, prop for `<Router>`. It's just an internal value used in the router context. Simply omitting it from the prop interface fixes the issue.
This was causing errors in our tests, and would also cause errors for all users who have a TS router (i.e. Routes.tsx). We didn't catch it because we already had other errors on that line in our tests that covered this one up (PR incoming for that as well, later)
This is what it would look like in a Redwood app
And fixing that regression I noticed the typing for `useAuth` was wrong as well. It should be optional. So I fixed that also.
=> Router: routes is not a prop

packages/router/src/__tests__/router.test.tsx
TypeScript was complaining about the global variable, which was causing errors throughout the test file. So I removed that and also simplified the auth setup a bit in the process.
Before:
Those errors are all gone now
=> Router tests: Don't use window.__REDWOOD__USE_AUTH

packages/cli/src/commands/storybook.js
part two of https://github.com/redwoodjs/redwood/pull/2168
This changes the default output directory for `rw storybook --build` from `web/storybook-static` to `web/public/storybook`
The output directory for `yarn redwood storybook --build` can now be configured with the `--build-directory` flag. Prior to this, the output directory default was `web/storybook-static`. The default has been changed to `web/public/storybook`, taking advantage of Redwood's public web directory to serve static files. Users can still output to `storybook-static` via `yarn redwood storybook --build --build-directory storybook-static`.
=> CLI Storybook command: change default output directory

package.json, packages/api-server/package.json, packages/api/package.json, packages/auth/package.json, packages/cli/package.json, packages/cli/src/redwood-tools.js, packages/core/package.json, packages/dev-server/package.json, packages/eslint-config/package.json, packages/eslint-plugin-redwood/package.json, packages/forms/package.json, packages/internal/package.json, packages/prerender/package.json, packages/router/package.json, packages/structure/package.json, packages/testing/package.json, packages/web/package.json, tasks/build-link
Try number 1500.
Tries to make `yarn rwt link` faster by only spinning up one watcher (rather than like 16).
Bonus:
- Now supports --only flag to selectively link a certain package e.g.
```
yarn rwt link ~/Code/redwood --only router
```
Note that only is the folder name, not the package name. i.e. the part here -> `@redwoodjs/<PACKAGE_FOLDER_NAME>`
- Much easier to link to any project directly from the framework (but only use this if you know what you're doing)
```
yarn build:link --dest ~/MyRedwoodProject/packages
```
This just does the build, you still need to install on the repo to actually link. This can be really useful in certain situations. Note that the path has packages because this is included by default in your workspaces
=> Fix rwt link performance issues

packages/create-redwood-app/src/create-redwood-app.js
Currently we have
```
$ yarn create redwood-app --help
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
...
[4/4] 🔨  Building fresh packages...
success Installed "create-redwood-app@0.28.4" with binaries:
- create-redwood-app
Usage: create-redwood-app <project directory> [option]
Options:
--help          Show help                                            [boolean]
--yarn-install  Skip yarn install with --no-yarn-install       [default: true]
----javascript  Generate a JavaScript project                  [default: true]
--version       Show version number                                  [boolean]
Examples:
create-redwood-app newapp
✨  Done in 2.54s.
```
Surely option with four leading dashes does work (I've tried), it …
=> fix typo for `--javascript` option

packages/web/src/components/GraphQLHooksProvider.tsx
Currently, completing [tutorial 2](https://learn.redwoodjs.com/docs/tutorial2/creating-a-comment-form#graphql-query-caching) in TS throws a type error because the `onCompleted` and `refetchQueries` keys aren't permitted in `GraphQLHookOptions`.
I've also added a catch-all `[key: string]: any`. Since `GraphQLHooksOptions` just passes its options into the underlying implementation, it's possible that the user's implementation will accept/expect more keys, and those shouldn't throw an error if provided.
cc @peterp
=> Correctly type `GraphQLHookOptions`

tasks/build-link
Fixes changes sometimes not being picked up when using rwt link
=> fix(build-link): Wait for build to complete before copying

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
Release notes:
- [2.20.0](https://github.com/prisma/prisma/releases/tag/2.20.0)
- [2.20.1](https://github.com/prisma/prisma/releases/tag/2.20.1)
- New `push` operation available for arrays on PostgreSQL
- `groupBy` and `createMany` are now Generally Available
=> upgrade Prisma v2.20.1

tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
This fixes an assertion in our E2E Cypress tests. In the first step we generate the About page, and then we update the content of that page. Previously we asserted on the original content of the file even after updating it. Now it asserts on the updated content instead. 
I think the reason it still passed before was Cypress managed to do the assertion before HMR had a chance to update the page with the new content.
=> e2e cy: Fix for step 1

packages/cli/src/commands/upgrade.js
The package `@redwoodjs/api-server` was added to the CRWA template in v0.28.1 via https://github.com/redwoodjs/redwood/pull/2129
This adds the api-server package to the `rw upgrade` tags, PR, and dry-run options.
For release notes:
- add step to install api-server in api/package.json
- add step to confirm api/package.json is at v0.29.0 _after_ upgrade is complete
Also 🤦‍♂️
=> add api-server to upgrade command

packages/api/package.json, packages/cli/jsconfig.json
Adds `@redwoodjs/api-server` as explicit dependency to cli.
This may not be a major issue, since we ask people to install `@redwoodjs/api-server`anyway, but incase you don't have it, it errors out the whole cli.
=> fix(cli): Cli package should depend on api server explicitly

packages/create-redwood-app/template/api/src/lib/logger.ts
This PR fixes some typos in the JSDoc comment in logger.ts
=> logger.ts: Fix comment spelling

packages/router/README.md
Document prop forwarding from Set to the wrapper components. This feature was introduced in RW 0.29.0
Closes https://github.com/redwoodjs/redwoodjs.com/issues/657
=> Router README: Pass props to set wrappers

packages/core/config/webpack.common.js, packages/core/package.json, yarn.lock
JS wasn't being minified on `yarn rw build web`.
Adds `TerserPlugin` to optimizations stage in webpack config to perform minification.
Note: I intentionally didn't enabled the `parallel: true` flag, because as noted in their docs on CircleCI for example, it causes issues.
=> Fix: webpack optimizations for JS

packages/cli/src/redwood-tools.js, tasks/build-link
- Adds better messages for rwt link 
e.g. tells you if it can't compile a specific package after you make a change (common with types)
- Watcher does not exist on build failure
- Only remove node_modules after a succesful framework build
Just moves where rimraf is called
=> Small improvements to rwt link

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
Release Notes: 
https://github.com/prisma/prisma/releases/tag/2.21.0
- Previously, aggregations on nullable fields always returned 0. All aggregated fields are now nullable. Aggregated fields can return null when there's either no record in the database or if all the aggregated records are null.
- `disconnect` no longer throws an error on unconnected records
- `@default(dbgenerated(""))` is no longer permitted
=> upgrade prisma v2.21.0

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
@dac09 @peterp 
Using our [Patch Release Process](https://github.com/redwoodjs/redwood/issues/2067#issuecomment-808721151), I have created branch `v0.30.0-branch` and cherry-picked the following:
- upgrade Prisma v2.21.0 (#2273) 3315f14b @thedavidprice 
- see this PR for Prisma Release Notes (includes breaking)
- Fix: webpack optimizations for JS (#2235) 73c78878 @dac09 
- Adds better messages for rwt link | Watcher does not exist on build failure | Only remove node_modules after a succesful framework build (#2269) 472d5378 @dac09
- fix(cli): Cli package should depend on api server explicitly (#2251) d3ce5d45 @dac09 
This PR will merge a branch with Prisma v2.21.2 (including fix for Netlify deploy) against `v0.30.0-branch`.
@peterp The next step will be to release v0.30.0 using the …
=> [v0.30.0 release] Upgrade Prisma v2.21.2

packages/api/package.json, packages/cli/package.json
Fixes #2299 
- Moves api-server dependency out of api and into cli
Why CLI? Because of the `yarn rw serve api` command. I think I added it to api by mistake
cc @jeliasson
=> fix(cli): Move api-server dep from api to cli

packages/api/ambient.d.ts, packages/api/package.json, packages/api/tsconfig.json, yarn.lock
Instead of just letting dependabot update pino-types as in PR https://github.com/redwoodjs/redwood/pull/2283 this PR upgrades:
* pino
* pino-pretty
* pino-types
to the latest versions that use these new types.
No logger updates as types were compatible and build/tests passed. 
Can revisit to see if new pino pretty types can give more info or not.
=> chore(logger): Upgraded pino and new related types for PinoPretty

packages/api-server/src/middleware/withWebServer.ts, packages/cli/src/commands/generate/page/page.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/create-redwood-app/src/create-redwood-app.js, tasks/run-e2e
Some fixes for the release. Mostly stuff I broke 
@thedavidprice this is a breaking change for CRWA (which is why e2e tests failing). Need to discuss this!
=> Fix page generator taking in ts | Fix rw serve crashing out cli

packages/api/src/webhooks/index.ts, packages/api/src/webhooks/webhooks.test.ts
There can be situations where the event is base64 encoded (which apparently can happen often on Vercel).
See with discussion between @Burnsy and @alecortega:
> I had this exact same issue with all my functions hosted on Vercel. I found that when working with Redwood locally the body of a function is decoded, however, once deployed to Vercel, the body may be base64 encoded. 
https://github.com/redwoodjs/redwood/issues/1410#issuecomment-825156426
Therefore, this PR checks the event to see if it isBase64Encoded and decodes before sending to the verifier.
=> feat(webhooks): Handle base64 encoded webhook payloads

packages/eslint-config/index.js
This PR addresses the discussions in the RedwoodJS Community post https://community.redwoodjs.com/t/eslint-process-and-require-undefined-error-in-web-side/2046 raised by @clairefro 
> We are noticing eslint errors in /src/web js files when using process.env.FOO and require are undefined (‘process’/‘require’ is not defined. eslint no-undef rule) in the auth playground app.
Seen here:
@peterp Suggested that `process` and `require` could be added as globals to the web-side eslint config.
This PR does just that:
```js
// `web` side
{
files: 'web/src/**',
env: {
browser: true,
es6: true,
},
globals: {
React: 'readonly',
gql: 'readonly',
process: 'readonly',
require: 'readonly',
},
},
```
And after the globals:
Can see that several `process` have been recognized, but a few have not -- but that …
=> fix(eslint): Adds process and require to eslint config web

packages/api/src/__tests__/beforeResolverSpec.test.js, packages/api/src/beforeResolverSpec.ts, packages/api/src/makeServices.ts, packages/api/src/types.ts
This provides an update to Secure Services (which was merged like 2 hours ago). Now, any arguments that would have been given to the service function call (like the variables coming in from GraphQL) will also be given to the resolver function, so it can use them in determining whether a call is valid or not.
A great use case is verifying the format of data before allowing a record to be created or updated, like an email address. Rather than doing it in the service function itself, it can happen in `beforeResolvers` and the service can just focus on creating/updating the record:
```javascript
const EMAIL_REGEX = new Regexp(/[^@]+@[^\.]+\..+/)
export const beforeResolvers = (rules) => {
const verifyEmail = (name, { input }) => {
if (!emailRegex.test(input.email)) {
throw Error, `Invalid …
```
=> Pass service args through to beforeResolver verification functions

.github/workflows/publish-npm-rc.yaml, tasks/publish-rc
Github workflow to publish release candidate created based on the instructions in the [CONTRIBUTING.md](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#releases).
I added the need to check the pattern 0.0.0-rc0  in the branches' name. Not sure if we need it.
Closes #2342
=> Create github workflow to publish release candidate

packages/structure/package.json, yarn.lock
This makes sure that we don't have an older version of typescript in the project, which interferes with Prisma sometimes (and prevents tsc from running properly on projects)
=> Bump ts-morph in rw/structure

packages/create-redwood-app/template/package.json
There's a bug with Prisma that causes it to crash on node 16. And that makes RW's api side crash. 
This PR sets the node version to be <16, which keeps us safe.
See more here: https://community.redwoodjs.com/t/node-v16-issues/2057
=> node < 16, otherwise prisma crashes

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
- [v2.22.0 Release Notes](https://github.com/prisma/prisma/releases/tag/2.22.0)
- [v2.22.1 Release Notes](https://github.com/prisma/prisma/releases/tag/2.22.1)
- `prisma db push` is now Generally Available. Prisma official [docs](https://www.prisma.io/docs/concepts/components/prisma-migrate/db-push).
=> Upgrade Prisma v2.22.1

packages/cli/package.json, packages/core/package.json, packages/structure/package.json, tasks/e2e/yarn.lock, yarn.lock
- [SECURITY] bump hosted-git-info from 2.8.8 to 2.8.9 #2484
- bump esbuild from 0.11.16 to 0.11.20 #2477
- bump @types/node from 15.0.1 to 15.0.2 #2458
- bump @types/listr from 0.14.2 to 0.14.3 #2448
=> misc Dependabot patch release PRs grouped

packages/create-redwood-app/template/.gitignore
Noticing that the migrate command also creates a dev.db-journal file
=> Ignore dev.db-journal

packages/cli/package.json, packages/cli/src/commands/upgrade.js, yarn.lock
As per @peterp's suggestion, this implements the upgrade command to:
1. query npm to find the lastest/ canary package versions
2. iterate over a user's package.json (root, web, api) files, replace the versions of packages that start with @redwoodjs/*
3. run yarn install
What it looks like: https://s.tape.sh/UFLppMbI
- I've removed the upgrade pr command/flag as its unstable
=> improve `rw upgrade` command and remove "publish PR packages" option

packages/api/package.json, packages/api/src/__tests__/makeServices.test.js, packages/api/src/makeServices.ts, packages/api/tsconfig.json, packages/cli/src/commands/__tests__/serve.test.js, packages/cli/src/commands/dev.js, packages/cli/src/commands/serve.js
`@redwoodjs/internal` can't be used at runtime because `redwood.toml` isn't present in lambda environments.
=> Use env-var to toggle secure-services

packages/api/src/makeServices.ts, packages/cli/src/commands/dev.js, packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap, packages/cli/src/commands/generate/service/templates/service.ts.template, packages/cli/src/commands/serve.js, packages/create-redwood-app/template/.env.defaults, packages/create-redwood-app/template/.env.example, packages/create-redwood-app/template/redwood.toml, packages/internal/src/__tests__/config.test.ts, packages/internal/src/config.ts
This does 2 things:
1. Does **not** opt-in new projects automatically (because its easy to miss the environment variable when deploying to Netlify/Vercel/whatever)
We might achieve the opposite of what we were aiming for, by accidentally making services public by default ;)
2. Removes the flag from the TOML
Secure services now only controlled using the environment variable. We originally did this because we can't read the config at runtime (causes graphql crashes)
=> Move experimental secure services out of toml

__fixtures__/example-todo-main/web/src/Routes.js, __fixtures__/example-todo-main/web/src/layouts/SetLayout/SetLayout.js, __fixtures__/example-todo-main/web/src/pages/BarPage/BarPage.tsx, __fixtures__/example-todo-main/web/src/pages/FooPage/FooPage.tsx, packages/internal/src/__tests__/paths.test.ts, packages/router/src/Set.tsx, packages/structure/src/model/RWRouter.ts, packages/structure/src/model/__tests__/model.test.ts
This PR adds support for specifying `prerender` on `<Set>`s. All routes in a Set like that will be prerendered.
```
<Set prerender>
<Route path="/foo" page={FooPage} name="fooPage" />
<Route path="/bar" page={BarPage} name="barPage" />
</Set>
```
is equivalent to
```
<Route path="/foo" page={FooPage} name="fooPage" prerender />
<Route path="/bar" page={BarPage} name="barPage" prerender />
```
=> Prerender all routes nested in Set with prerender prop

babel.config.js
As title
When running `yarn build`, we got warnings from babel. To reproduce, in main, run build in the cli package. 
```shell
cd packages/cli
yarn build
```
you should see warnings like this:
```
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The …
```
=> [Internal] Configure babel-plugin-private-methods loose explicitly

README.md, tasks/all-contributors/.all-contributorsrc, tasks/all-contributors/.learn.all-contributorsrc
_continued from #2545_
Crowdin does not include the translator in the PRs to the repo; added manually to `.learn.all-contributorsrc`
Adds these users as translator contributors to learn repo:
- https://github.com/pdjota
- https://github.com/renansoares
- https://github.com/bugsfunny
- https://github.com/luispinto23
- https://github.com/simoncrypta
---
@clairefro I re-ran the process 1) added directly to `.learn.all-contributorsrc` 2) ran the merge script and 3) ran the update README command
Could you confirm these are the correct folks?
=> Add learn.rwjs.com translator contributors from crowdin

packages/api/package.json, packages/cli/package.json, packages/cli/src/commands/exec.js, packages/core/package.json, yarn.lock
Prisma {v2.23.0 Release Notes](https://github.com/prisma/prisma/releases/tag/2.23.0)
- JSON Filtering is now in Preview
- BREAKING: Options in groupBy queries are now prefixed with an underscore
- DEPRECATING: Options in aggregate queries
=> upgrade Prisma v2.23.0

packages/router/src/router.tsx
By utilizing function overloads I was able to make the types for `<Route>` much more helpful.
VS Code now complains if you miss a prop, or if you combine props that shouldn't be combined, when declaring your routes.
A few examples:
Missing `page`
`name` shouldn't be specified for redirect routes
No `path` should be specified for the "not found" route
This is (parts of) the error message VS Code gives you for the last one
If someone has a TypeScript `Routes.tsx` file with misconfigured routes it will now not compile for them anymore.
=> Router: More helpful typings for Route

packages/cli/src/commands/destroy/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/__tests__/__snapshots__/cell.test.js.snap, packages/cli/src/commands/generate/cell/__tests__/cell.test.js, packages/cli/src/commands/generate/cell/__tests__/fixtures/schema.prisma, packages/cli/src/commands/generate/cell/cell.js, packages/cli/src/commands/generate/cell/templates/cellList.js.template, packages/cli/src/commands/generate/cell/templates/mockList.js.template, packages/cli/src/commands/generate/helpers.js
This PR fixes issue https://github.com/redwoodjs/redwood/issues/2565
This PR updates:
* cell generator
* adds "list" variants of the cell component and mock templates
* the new list component success renders a `ul` with items
* the new list mock returns an array of items (just ids)
* the singular template renders a by id query
* the test template is unchanged
* ***Important*** Scaffold generation is unchanged.
* ***Important*** Service generation is unchanged (required for the non-pluralisable names e.g. `manyEquipment`)
---
> yarn rw g cell User 
```terminal
cells-test % yarn rw g cell User --force 
yarn run v1.22.10
$ /Users/dthyresson/redwood-tests/cells-test/node_modules/.bin/rw g cell User --force
✔ Generating cell files...
✔ Successfully wrote file …
```
=> Adds option to cell generation for lists of a given model

CONTRIBUTING.md
First ever contribution!
Replaces ``` ./tasks/test-tutorial``` with ``` ./tasks/run-e2e```   in [CONTRIBUTING.md](https://github.com/redwoodjs/redwood/blob/main/CONTRIBUTING.md#integration-tests) as per issue #2136!
@thedavidprice this should be good to go if all is well.
=> Fix CONTRIBUTING.md#integration-tests ./tasks/test-tutorial to ./tasks/run-e2e

package.json, packages/auth/package.json, packages/core/package.json, packages/eslint-config/package.json, packages/internal/package.json, packages/structure/package.json, packages/testing/package.json, packages/web/package.json, yarn.lock
Includes the following Dependabot PRs:
- bump @types/node from 15.0.3 to 15.3.1 #2570
- bump typescript-transform-paths from 2.2.3 to 2.2.4 #2571
- bump @typescript-eslint/eslint-plugin from 4.23.0 to 4.24.0 #2573
- bump ts-morph from 10.0.2 to 10.1.0 #2577
- bump esbuild-loader from 2.13.0 to 2.13.1 #2582
- bump @supabase/supabase-js from 1.11.13 to 1.11.14
- bump firebase from 8.6.1 to 8.6.2 #2584
- bump @babel/core from 7.14.2 to 7.14.3 #2585
- bump @typescript-eslint/parser from 4.23.0 to 4.24.0 #2586
- bump @babel/plugin-transform-typescript from 7.13.0 to 7.14.3
- bump @types/react from 17.0.5 to 17.0.6 #2589
=> Aggregate Dependabot misc patch minor upgrades

CONTRIBUTING.md
Hi again ...
_en passant_ also fixed a plain issue in the TOC which was missing the pointer to `#link`. 
The remaining changes are a matter of taste perhaps.  One thing that may or not make sense to address - here and elsewhere - is having a proper style guide on how to reference/address "**Redwood**". It may make sense to when referencing it always using **bold** [and adopt the same behaviour to whatever 3dr party projects / tooling we reference]. 
All the Best, 
António
=> CONTRIBUTING.md: styling tweaks for improved readability and consistency

packages/router/src/__tests__/history.test.tsx, packages/router/src/history.tsx
=> Manage history state length exploding if clicking on a link with with the current route location

packages/cli/src/commands/__tests__/serve.test.js
Running the RW test suite locally I had some trouble with the `serve` tests. This fixes them.
This was the error I saw
```
Summary of all failing tests
FAIL  src/commands/__tests__/serve.test.js
● yarn rw serve › Should proxy serve api with params to api-server handler
expect(jest.fn()).toHaveBeenCalledWith(...expected)
Expected: ObjectContaining {"apiRootPath": "/funkyFunctions/", "port": 5555}
Received: {"$0": "..\\..\\node_modules\\jest-worker\\build\\workers\\processChild.js", "_": ["serve", "api"], "port": 5555, "rootPath": "funkyFunctions"}
Number of calls: 1
59 |     parser.parse('serve api --port 5555 --rootPath funkyFunctions')
60 |
> 61 |     expect(apiServerHandler).toHaveBeenCalledWith(
|                              ^
62 |       expect.objectContaining({
63 |         port: …
```
=> Fix serve tests

packages/create-redwood-app/template/redwood.toml
no longer needed per changes to the default value in https://github.com/redwoodjs/redwood/pull/2677
=> remove CRWA/template/redwood.toml schemaPort

packages/api/package.json, packages/cli/package.json, packages/core/package.json, packages/structure/package.json, yarn.lock
Prisma release notes:
- [v2.24.0](https://github.com/prisma/prisma/releases/tag/2.24.0)
- [v2.24.1](https://github.com/prisma/prisma/releases/tag/2.24.1)
Highlights:
- MongoDB gets Json and Enum Support
=> Upgrade Prisma v2.24.1

packages/cli/src/commands/prisma.js
The prisma command `db push` is now GA and no longer requires the --preview option to run. This PR updates the rw command to no longer pass the --preview option.
=> remove preview option from db push

.github/workflows/proj.yml
I just merged #2635 which adds a GitHub action for updating a pull request's milestone on merge/close. It looks like that action might fail because it doesn't have the permissions it needs, which is to be able to read (what's the current milestone) and write (change the milestone) pull requests. This PR adds those two permissions to just that GitHub action.
Here's GitHub's docs about permissions:
- https://docs.github.com/en/actions/reference/authentication-in-a-workflow
=> Give change milestone PR read-and-write permissions

.github/workflows/proj.yml
`read|write` isn't a valid value for a permission; reducing it to just write, assuming it can also read (it needs to read the PR's current milestone).
=> Use correct syntax for permisisons

tasks/test-project/codemods/blogPostsCell.js, tasks/test-project/test-project
Fixes #2758
cc @renansoares 
Also, there was a strange import error in Routes.js resulting from jscodeshift adding semicolons by default. For some reason, this breaks the formatting on our generators.
The result was this line of imports mashed up:
```js
import { Router, Route, Set } from '@redwoodjs/router';import PostsLayout from 'src/layouts/PostsLayout'
```
I moved lint to run at the end of both the Web setup and the API setup, which resolved the issue.
=> Test Project Build: fix lint errors during build

packages/internal/src/ts2js.ts
I was giving Redwood a test run and ran `yarn rw ts-to-js` on my new project (with no TS or TSConfigs) - what was really weird is that it raised an unexpected exception:
```sh
❯ yarn rw ts-to-js
$ /Users/ortatherox/dev/orta/my-redwood-app/node_modules/.bin/rw ts-to-js
Error: ENOENT: no such file or directory, rename '/Users/ortatherox/dev/orta/my-redwood-app/api/tsconfig.json' -> '/Users/ortatherox/dev/orta/my-redwood-app/api/jsconfig.json'
at Object.renameSync (fs.js:794:3)
at convertTsProjectToJs (/Users/ortatherox/dev/orta/my-redwood-app/node_modules/@redwoodjs/internal/dist/ts2js.js:44:17)
at Object.handler (/Users/ortatherox/dev/orta/my-redwood-app/node_modules/@redwoodjs/cli/dist/commands/ts-to-js.js:19:38)
at Object.runCommand …
```
=> Adds some minor polish to the TS to JS command

packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap, packages/cli/src/commands/generate/scaffold/templates/components/EditNameCell.js.template, packages/cli/src/commands/generate/scaffold/templates/components/NameCell.js.template
Fixes https://github.com/redwoodjs/redwood/issues/2764
Andrew Lam from the Discord Community asked:
> Hi, I'm curious what is the reason for using different casing for the name of query and mutation?
There is inconsistency in the operation name casing and redwood could standardize: 
* Pascal Case (OperationName)
* Capitalized Snake Name (OPERATION_NAME)
This PR fixes the edit and view cells such that their templates will have a pascal cased operation name consistency with other queries and mutations.
Change is to use `singularPascalName` instead of `singularConstantName` and change the template surrounding operation name casing:
```
-   query FIND_USER_PROFILE_BY_ID($id: Int!) {
+   query FindUserProfileById(($id: Int!) {
-   query FIND_POST_BY_ID($id: Int!) {
+   query FindPostById($id: …
```
=> Use consistent GQL operation name case in cell scaffolds generators

packages/web/src/components/createCell.tsx
As of Apollo Client `v3`, [the default `fetchPolicy` is `cache-first`](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy). `cache-first` is great, but `cache-and-network` is better. Accordingly, it's what we [default to](https://github.com/redwoodjs/redwood/blob/fbccb88b31c51258d04d98f5145dcf7c88436168/packages/web/src/components/createCell.tsx#L98). It comes with a hiccup though: `cache-and-network` gives you data if it's there (the "cache" part), then makes a GraphQL request to see if there's anything new ("and-network"). This means that the "result" Cells get (and use to figure out what to render) has data (usually an object/array) and `loading = true`. And if `loading = true`, that means Loading gets rendered. Because things go in order: …
=> Add Updating to Cells

tasks/test-project/test-project
_related to work in https://github.com/redwoodjs/redwood/issues/2714_
@renansoares this is a quick-fix to run the upgrade canary command immediately after the project installation. I also set the canary option to be true by default.
I did a minor console display change to make it more apparent that the installation process was running as a part of the project creation.
All just incremental for now. Ideally I think the first `yarn install` wouldn't even run in the create-redwood-project.js and we'd be able to upgrade to canary versions and then install. I just don't know of a simple way to do this (yet).
=> build test project: run canary upgrade earlier in tasks

packages/cli/src/commands/prisma.js, packages/cli/src/index.js
This adds a `--cwd` option to the CLI.
`yarn rw --cwd ../path/to/redwoodjs/project` 
Most people will not use this, but as a contributor it's a very effective way to test the CLI, since you can now make changes in the RedwoodJS repo, and test those in a RedwoodJS project without having to copy or link the CLI files.
```terminal
cd ~gh/redwoodjs/redwood
cd packages/cli
<make some  changes>
yarn dev --cwd ~gh/snaplet/snaplet
```
Closes #2792
=> Add `--cwd` option to CLI.

packages/cli/src/commands/info.js
The `rw info` command was looking for a specific `@redwoodjs/` package to report the version number, which became out of sync due to a change in #2769 that was reverted in #2825
Turns out we can use glob (which I should have done originally) to get any/all `@redwoodjs` packages in root package.json. Doing that now!
=> revert change to `rw info` command; use glob

packages/create-redwood-app/template/gitignore.template
Generated gql types should now be ignored.
1. Add the following lines to your `.gitignore`
```
web/types/graphql.d.ts
api/types/graphql.d.ts
```
2. Now lets remove tracking these generated types from your git history. In your terminal run
```
git rm --cached api/types/graphql.d.ts web/types/graphql.d.ts
```
**Note** supercedes PR from peter here: #2807
=> Adds generate gql types to gitignore

packages/internal/src/__tests__/files.test.ts, packages/internal/src/__tests__/typeDefinitions.test.ts, packages/internal/src/files.ts
I was excluding "Cell" files from directory named modules, and apparently
negative matches in fast glob don't seem to be working nicely, or I don't understand them very well, either way it was not a 100% correct way to determine if a file is a Cell.
This PR improves the logic and generates all the proper mirror files.
=> Fix directory named module imports mirror generation

CONTRIBUTING.md
This adds the following to the contributors documentation:
----
If you've made build or design time changes to RedwoodJS, that is if you have modified one of the following packages:
```terminal
./packages/
├ api-server
├ cli
├ core
├ dev-server
├ eslint-config
├ internal
├ prerender
├ structure
├ testing
```
You can run a development version of the CLI directly from the framework's repo where you don't have to sync any files or node modules.
(For all of the packages above the entry point is the CLI, these are what we consider "build time" and "design time" packages, rather than "run-time" packages which are web, auth, api, forms.)
In order to do that you use the `--cwd` option to set the current working directory to your "test project":
```terminal
yarn build
cd packages/cli
yarn dev …
```
=> Add information about --cwd to contributors documentation.

packages/cli/src/commands/exec.js
In v0.34.0, `rw exec` doesn't pick up typescript scripts (how DARE it!?)
You need the babel config loaded for `require.resolve` to know how to handle TS files
I think I broke this when I "fixed" the prerender stuff.
=> fix(rw-exec): Pick up ts scripts too

packages/graphql-server/package.json, packages/graphql-server/src/functions/graphql.ts, yarn.lock
This PR upgrades envelop/core to 0.3.1 used by the graphql-server.
=> Upgrades Envelop to 0.3.1

packages/graphql-server/src/index.ts, packages/graphql-server/tsconfig.json
- Exports context correctly from @redwoodjs/api
=> fix(graphql-server): context exports from graphql-server

packages/cli/src/commands/exec.js
Fixes the issue where scripts would keep the shell active, even after they'd complete. 
I believe prisma opens a socket, which is why it stays active, until `db.$disconnect` is called. 
Related to #2881 #2843
=> fix(exec): Always disconnect prisma after exec

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/structure/package.json, yarn.lock
Prisma release notes:
[v2.25.0](https://github.com/prisma/prisma/releases/tag/2.25.0)
Highlights:
Human-readable drift diagnostics for prisma migrate dev
Notable Fixes:
[Resolves](https://github.com/prisma/prisma/issues/7091) the _count field not found when referenced in relation context
Breaking changes:
Dropping support for Node.js v10
=> upgrade Prisma v2.25.0

packages/cli/src/commands/__tests__/type-check.test.js, packages/cli/src/commands/typeCheck.js
This simply change the CLI for typecheck to keep it in lowercase like the [doc](https://redwoodjs.com/docs/typescript#running-type-checks) 
fix #2904
=> Rename the CLI "rw typeCheck" for "rw typecheck"

packages/router/src/Set.tsx, packages/router/src/__tests__/router.test.tsx, packages/router/src/params.tsx, packages/router/src/router-context.tsx, packages/router/src/router.tsx
Doing some reorganization and simplification of the code. This is a continuation of #2795 
* Remove RouteScanner and just move the functionality into a function instead
* Now that we only have the one active route as children, there is much less need of looping through all routes
* No need to store all routes in context anymore
* Added a couple of tests for things I ran into when refactoring
I've added some review comments to try and explain the changes I've made. Hope it helps.
=> Router: Remove RouteScanner, don't store all routes in context

packages/auth/package.json, packages/auth/src/authClients/supabase.ts, yarn.lock
Fixes https://github.com/redwoodjs/redwood/issues/2939
Supabase now supports authentication via Discord.
https://github.com/supabase/gotrue-js/blob/4575b2a116048b8226b5d4bd12a33777571b9b2a/src/lib/types.ts#L1
https://twitter.com/supabase_io/status/1410912532705943556?s=21
This PR upgrades to the latest Supabase JS client and supports Discord auth.
=> Upgrades supabase-js to support Discord third party authentication

packages/internal/src/generate/templates/web-routerRoutes.d.ts.template
Fixes #2868
- Updates Route parser type to support more cases
- This time round, uses Compute to have a nicer hover experience
Tested with the following
```ts
type mixed = RouteParams<'/path/{b:Int}/{c}/{d}'>
type oneEach = RouteParams<'/path/{b:Int}/{c}/{d:Boolean}'>
type oneEachDiffOrder = RouteParams<'/path/{b}/{c:Int}/{d:Boolean}'>
type noTypesatall3 = RouteParams<'/path/{b}/{c}/{d}'>
type aftersOnly2 = RouteParams<'/path/{b}/{c}'>
type aftersOnly4 = RouteParams<'/path/{b}/{c}/{d}/{e}'>
type aftWithTypes = RouteParams<'/path/{b:Int}/{c}'>
type aftWithTypes2 = RouteParams<'/path/{b:Int}/{c:Boolean}'>
// greedy matching {b}/{c:Int}
type aftWithTypes3 = RouteParams<'/path/{b}/{c:Int}/{d:Boolean}'>
// greedy matching reversed {b:Int}/{c}
type aftWithTypes4 = …
```
=> Update Route param parser TS

packages/forms/src/__tests__/form.test.tsx, packages/forms/src/index.tsx
A simple fix for #2979 to retrieve form `errors` using lodash like `get` utility from RHF
=> Used RHF get to retrieve errors

packages/cli/src/commands/data-migrate.js
In https://github.com/redwoodjs/redwood/pull/2988 we incorrectly understood that Yargs would create the alias `dataMigrate`, making the PR backward compatible. Currently `dataMigrate` is referenced in the codebase. And, more importantly, Render Yaml requires calling this command explicitly — deprecating would mean projects would need to update Render.yaml manually. 
If we do choose to deprecate this alias, we will need to manage and message accordingly.
=> add alias `dataMigrate` to data-migrate command

packages/cli/src/commands/generate/scaffold/scaffold.js
`yarn rw g scaffold Something` would crash if your Prettier config was set up to use `"` instead of `'` because of a regex that assumed `'` throughout the codebase.
This both corrects that regex so it is flexible between the quotation styles and also adds a guard so that the scaffold process will complete even if that regex fails to match in the future.
Resolves #3027
=> Fix issue where generate scaffold would crash if using double quotes

packages/api/src/functions/dbAuth/DbAuthHandler.ts
I was getting this error when trying to build the framework
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined>'.
No index signature with a parameter of type 'string' was found on type 'PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined>'.ts(7053)
```
This PR fixes the error by using the `keyof` types from `PrismaClient`
=> DbAuth: Fix TS error with authModelAccessor

packages/router/src/__tests__/route-announcer.test.tsx, packages/router/src/__tests__/router.test.tsx
```jsx
<Router>
<Route path="/" page={HomePage} name="home" />
<Route path="/about" page={AboutPage} name="about" />
<Set private unauthenticated="home">
<Route path="/{param}" page={ParamPage} name="param" />
</Set>
</Router>
```
If you tried to navigate to `/about` the private Set would see that `/about` matches `/{param}` (`param` would be set to "about"), and if you weren't authenticated, you'd be redirected to the home page
This PR fixes this by looking at the route name. It knows you're trying to go to the "about" page, so in the Set, it looks at name="param" and sees that "param" !== "about", and so it skips it.
=> Router.tsx: Test Route matching in Sets

packages/cli/src/commands/generate/layout/__tests__/__snapshots__/layout.test.ts.snap, packages/cli/src/commands/generate/layout/templates/layout.tsx.a11yTemplate, packages/cli/src/commands/generate/layout/templates/layout.tsx.template
close #3035 
@dac09 
1. change the test
2. change the type
The reason we go with solution 2 here is for the case where the content is gone after a conditional rendering. Usually, it will lead to ugly UI, but for MVP stage, highly likely it will happen
=> Made the children prop optional for layout template

packages/testing/config/storybook/main.js
Storybook takes the path in the `stories` config setting and uses that to import the stories to run. On Windows our config ended up being a path with a mix of `\\` and `/` path separators. This PR makes sure we use only `/` which works for importing files on both Windows and Posix. See the three linked issues/PRs for more info.
Fixes #3046 
BTW, I've already fixed this once before in #1324 (Which fixed my issue #954)
=> Fix Storybook stories path on Windows

tasks/test-project/package.json
This fixes 
`Command failed with exit code 127:`
which happens when running `yarn build:test-project`. This is to do with line endings, when jscodeshift runs.
=> fix: Fixes yarn build:test-project failing due to jscodeshift

packages/cli/src/lib/index.js, yarn.lock
fixes #3056
This fixes the case where the scaffold generator would fail to generate routes if `<Routes>` contained props, e.g. `<Router useAuth={useAuth}>`
=> fix: generate scaffold routes when <Router> contains props

packages/cli/src/rwfw.js
This PR will:
As mentioned in #3074, we should be able to run `yarn rwfw --help|help` and get the same output as `yarn rwfw`. This PR enables that. 😄
=> Add help command to rwfw

packages/auth/src/AuthProvider.tsx, packages/cli/src/commands/generate/dbAuth/templates/login.tsx.template, packages/cli/src/commands/generate/dbAuth/templates/signup.tsx.template
=> Fix: type issue on the dbAuth generated pages

packages/cli/package.json, packages/cli/src/commands/setup/tailwind/tailwind.js, packages/cli/src/commands/setup/tailwind/templates/postcss.config.js.template, yarn.lock
This PR upgrades the setup tailwind command to 1) take advantage of postcss v8 compatibility and 2) enable jit mode by purging (effectively "watching") the correct files.
Todos:
- `import 'tailwind/tailwind.css'` is now added to App.{js|tsx} instead of adding the directive block to index.css; this is cleaner and keeps index.css just for index.css things
- jit and purge are enough
Other changes:
- we use the tailwind cli to initialize a postcss.config.js (instead of maintaining a template that we copy over)
- tailwind.config.js is moved to web/config because the extension recognizes it there now
=> Upgrade setup tailwind

packages/graphql-server/src/functions/graphql.ts, tsconfig.json
This adds the `graphql-server` to `tsconfig.json` which builds the type definitions. I ignored the errors because I'm a bit pressed for time, but we should try and remove the errors that are ignored @dthyresson.
Related: #3125
=> Ignore graphql-server TS errors

.gitignore, packages/graphql-server/package.json, packages/graphql-server/src/functions/graphql.ts, yarn.lock
Reworks https://github.com/redwoodjs/redwood/pull/3126
Fixes https://github.com/redwoodjs/redwood/issues/3125
Fixes https://github.com/redwoodjs/redwood/issues/3098
This PR reworks the `useRedwoodLogger` envelop plugin to better type the result.
The result can either be a single executionResult or an async integration of them (in streams and subscriptions).
Now that the result is properly type, a function handler will log the result(s) as needed - single or each one.
Small change: Since I have some project files in iCloud, from time to time .icloud files get sync'd and clutter up so now the .gitignore excludes there.
=> Resolves Typescript errors in useRedwoodLogger plugin in GraphQL-server

packages/api/src/makeMergedSchema/makeMergedSchema.ts, packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
Fix https://github.com/redwoodjs/redwood/issues/3114
Fix https://github.com/redwoodjs/redwood/issues/3123
In the app's `graphql.ts` function where we `createGraphQLHandler` there is a type issue in `services`:
```js
src/functions/graphql.ts:16:5 - error TS2322: Type 'ServicesCollection' is not assignable to type 'Services'.
Index signatures are incompatible.
Type 'Services' is not assignable to type 'Resolver'.
Type 'Services' provides no match for the signature '(...args: unknown[]): unknown'.
16     services: makeServices({ services }),
~~~~~~~~
../node_modules/@redwoodjs/api/dist/makeMergedSchema/makeMergedSchema.d.ts:11:5
11     services: Services;
~~~~~~~~
The expected type comes from property 'services' which is declared here on type '{ schemas: { [key: string]: { schema: …
```
=> Typing services on makeMergedSchema

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/structure/package.json, yarn.lock
**Release Notes:**
https://github.com/prisma/prisma/releases/tag/2.28.0
Best. News. Ever:
> Prisma Adopts Semantic Versioning (SemVer)
> 
> We are adjusting our release policy to adhere more strictly to Semantic Versioning.
> 
> In the future, breaking changes in the stable development surface i.e. [General Availability](https://www.prisma.io/docs/about/releases#generally-available-ga) will only be rolled out with major version increments.
> 
> You can learn more about the change in the announcement [blog post](https://www.prisma.io/blog/prisma-adopts-semver-strictly).
=> upgrade Prisma v2.28

packages/cli/src/commands/setup/tailwind/tailwind.js
Using a setup command that installs packages doesn't gel with `yarn rwfw project:sync`. We discussed two ways around this: 
- have `yarn rwfw project:sync` copy over a dummy package with a postinstall script that runs `yarn rwfw project:copy`
- make a setup command's install step configurable, so that packages can be manually installed and manually followed up by a project:copy. This would look like...
- `yarn add postcss postcss-loader tailwindcss autoprefixer`
- `yarn rwfw projext:copy`
- `yarn rw setup tailwind --no-install` 
This PR implements the second bullet point, only because I've tried to do the first and come up empty so far. Will keep trying, but as long as the install step isn't peculiar (i.e. installing ultra-specific versions) this seems like a viable option in the meantime …
=> [setup tailwind] Add ability to skip install

tasks/test-project/util.js
This adds RW_PATH to the environment so the rwfw `project:copy` and `:sync` work even if you don't have the value set on your profile
=> fix(project-generator): Add RW_PATH to execa options

packages/cli/src/commands/setup/tailwind/tailwind.js
Closes #3149. This PR reverts part of the behavior of the setup tailwind command. To restore storybook compatibility, we include tailwind's css via directives in index.css instead of an import in App.js.
<a href="https://gitpod.io/#https://github.com/redwoodjs/redwood/pull/3181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [setup tailwind] Include tailwind by adding directives to index.css

.gitpod.yml
As title
<a href="https://gitpod.io/#https://github.com/redwoodjs/redwood/pull/3185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add more info in the terminal | Tweak  gitpod settings

packages/auth/src/__tests__/AuthProvider.test.tsx
There were two main type issues that this PR fixes.
1. `__REDWOOD__API_PROXY_PATH` was being set on `window`, but our type definitions have it on `global`, so I just moved it.
2. Our custom auth adds `hasRole` to the client, but that doesn't exist on our client interface. So I created a new interface, that extends the standard interface with a `hasRole` method.
<a href="https://gitpod.io/#https://github.com/redwoodjs/redwood/pull/3155"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Auth test: Fix typings

packages/api-server/src/requestHandlers/awsLambda.ts
AWS lambda functions can serve binary data (instead of a string or JSON) by returning a base64-encoded body and setting the `isBase64Encoded` optional response parameter to `true` (see https://aws.amazon.com/blogs/compute/handling-binary-data-using-amazon-api-gateway-http-apis/).
This change augments the API server to implement the same functionality.
Motivated by https://community.redwoodjs.com/t/serving-binary-files-in-a-custom-function/2340.
=> Allow custom functions to serve binary data

tasks/test-project/test-project
Reverts behavior to build project and upgrade to canary, which avoids the potential for breaking changes in CRWA template to conflict with installed packages.
Can still use latest packages via `--no-canary` option.
=> [build:test-project] set canary as default

packages/internal/src/__tests__/build_api.test.ts, packages/internal/src/build/api.ts
This PR fixes sourcemaps (API side) so the VSCode debugger can resolve them correctly.
After making these changes I was able to run the VSCode extension + Debugging against the functional test project (`build:test-project ... --typescript`).
I can't be certain this doesn't break other parts of Redwood (ex: Jest errors, storybook). I believe not, because the final result is "correct". But this PR has to be reviewed by someone who has more visibility into other parts of the framework.
Details:
* The current transpilation process has two steps:
* 1: Babel. Used to create "intermediate" files in `.redwood/prebuild/...`
* 2: ESBuild. Used to transpile these intermediate files into `./dist`
* The strategy to make sourcemaps work is roughly the following:
* 1: Babel
* Ask babel to generate …
=> Fix API sourcemaps (babel+esbuild) for debugging

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/structure/package.json, yarn.lock
Prisma [2.29.0 Release Notes](https://github.com/prisma/prisma/releases/tag/2.29.0):
- Interactive Transactions are now in Preview
- Named Constraints are now in Preview
=> upgrade Prisma v2.29.0

tasks/framework-tools/src/frameworkSyncToProject.mjs
Rufus would always say "done" even when it errored out, and was hard to spot unless you scrolled up in the console.
When it errors out, doesn't print a success message, and uses red to make it easier to spot errors. 
This is what it looks like:
=> Makes it clearer in the logs when Rufus errors out

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/structure/package.json, yarn.lock
Prisma 2.29.1 Release Notes:
Prisma Client
Cannot find namespace 'debug' in 2.29.0
Interactive transactions not working with $queryRaw and $executeRaw in 2.29.0
Calling .catch() or .finally() on a prisma client model query does not fire the request in 2.29.0
=> upgrade Prisma v2.29.1

packages/cli/package.json, yarn.lock
Closes #3239. As of v6, Configstore is an ESM. While we should look more into ESMs, downgrading Configstore to v3.1.5 (the previous version) should be ok for now since it's only used sparingly in one place, `rwfw.js`.
=> downgrade configstore

babel.config.js, packages/api/package.json
Fixes #3216
In v0.36, we've removed preset-env from the babel config, and instead are using esbuild to transform the code to the target. Which means, the module generated by `@babel/plugin-transform-runtime` does not exist (it used to be generated by babel, when you have preset-env and this plugin)
This change makes sure the code we ship within the framework does not rely on the generated modules anymore (trade off being a larger node_modules size, in the project I guess).
=> v0.36 fix(babel): Dont transform runtime for framework

.github/workflows/e2e.yaml
Add the following command checks to GitHub E2E CI:
- `rwfw`
- `rw exec`
- `dm up`
Can't run any commands that install packages as they'll break the Redwood package links.
=> add e2e cli commands

.gitpod.yml
There must have been some changes in gitpod's prebuild, small changes to make sure its all working again
a) Use absolute paths to mkdir/cd into
b) Before running yarn install/etc. making sure I'm in the redwood framework (It used to default there before I guess)
c) Improves terminal messaging to explain whats going on. Most contributors wont' have to wait though, its only when we push/merge to main that prebuild would rerun.
=> fix(contributor-workflow): Adjust prebuild commands on gitpod

packages/web/src/components/createCell.tsx
**Problem:** 
Currently `CellFailureProps` allows usage of `error` field only, even though other nice fields from `QueryResult` are available like `refetch` function.
Expected behavior is to allow access of such other properties (without breaking test and stories).
@dac09 @thedavidprice
=> TS: Fix missing properties in CellFailureProps type

packages/auth/src/authClients/clerk.ts
Import the possible option types directly from the clerk/types options for the `login` and `signup` methods.
Docs update at: https://github.com/redwoodjs/redwoodjs.com/pull/779
=> Auth: Add login and signup types for Clerk auth

packages/router/README.md
Add `navigate("", { replace: true })` and `back()` to the router README. The README is also used for the docs on rwjs.com
=> Router README: Document new navigation functionality

packages/testing/src/web/MockProviders.tsx
This fix #3268 
Not sure how to handle `titleTemplate`.  Right now I use the one in CRA, but if we want to test the title in a project we need the real `titleTemplate` configuration. 🤔
=> add RedwoodProvider to mockProviders for unit testing 

CONTRIBUTING.md
@KrisCoulson pointed out that the positional argument in `yarn rwfw project:sync <framework directory>` is incorrect (passing in the framework directory causes the framework's dependencies to be added back to the framework instead of to the project). This PR fixes this.
- related: https://github.com/webpack/webpack/issues/11612
=> Fix rwfw instructions in CONTRIBUTING.md

packages/api/src/functions/dbAuth/DbAuthHandler.ts, packages/api/src/functions/dbAuth/__tests__/DbAuthHandler.test.js, packages/auth/src/authClients/dbAuth.ts, packages/cli/src/commands/setup/auth/templates/dbAuth.function.js.template
Fixes two issues that Vercel was blowing up on:
1. Vercel does not like having a return body that's JSON and turning it into a string for us—it MUST be a string
2. If the body is empty, Vercel will still set `isBase64Encoded` to true, and you can't decode an empty string
Fixing these introduced another issue, where `getToken` returned an empty string which a client call for `getUserMetadata` interpreted as there being a user logged in and so would call the GraphQL endpoint for `getCurrentUser`, which then returned a 500. This is patched as well.
Serverless functions may already wait for async code to complete before returning (this hasn't been an issue in dev or a serverfull deployment). But in case they don't, anyone already using dbAuth should update their `api/src/functions/auth.js` to …
=> dbAuth Vercel Fix

packages/internal/src/__tests__/build_api.test.ts
Canaries can't be published because the tests update the snapshot during run. This should've been committed :)
=> fix: Snapshots updates weren't commited in test

packages/core/config/babel-preset.js
Closes #3332. `removeViewBox` is actually the only default plugin we override; the rest are built-in but not part of the preset-default.
=> Use newer plugin syntax for babel-plugin-inline-react-svg

packages/core/src/babelPlugins/babel-plugin-redwood-import-dir.ts, yarn.lock
The generated imports for services and schemas had "C:\Users\Tobbe\dev\Redwood\" style paths, but that doesn't work for imports. Need to be "C:/Users/Tobbe/dev/Redwood/". We already have a function for doing the conversion, so I just used that.
Also the regex for turning file paths into variable names had a slight bug that I fixed.
=> babel-plugin-redwood-import-dir: Fix regex and Windows paths

packages/api-server/src/watch.ts
Fixes #3338
This 🤞 fixes the windows api dev server.
=> fix(api-dev): Ensure dist, types and db paths are ignored on windows

packages/api-server/src/handler.ts
Some API side errors were not printed to the console, making it very difficult to debug.
Before:
```
$ yarn rw dev
yarn run v1.22.11
$ C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\.bin\rw dev
$ C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\.bin\rw-gen-watch
$ C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\.bin\cross-env NODE_ENV=development webpack serve --config C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\@redwoodjs\core\
config\webpack.development.js
$ C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\.bin\cross-env NODE_ENV=development NODE_OPTIONS=--enable-source-maps yarn nodemon --watch C:\Users\tobbe\dev\redwood\acm-store-
rw\redwood.toml --exec "yarn rw-api-server-watch"
$ C:\Users\tobbe\dev\redwood\acm-store-rw\node_modules\.bin\nodemon --watch …
```
=> Surface errors on the api side

packages/cli/src/commands/generate/cell/cell.js, packages/cli/src/commands/generate/page/page.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/sdl/sdl.js
Closes #3345.
Like @dac09 suggested, implemented exactly same of scaffold and other generators.
=> Fix: Generate types when generating sdl

packages/graphql-server/src/functions/graphql.ts
Orignally reported by jan_mei on Discord: https://discord.com/channels/679514959968993311/716252919875240007/886349812147032124
Currently, if there's an error during GraphQL execution, there's no log of the actual error which makes debugging difficult. This PR attempts to fix this by logging that error.
**Cause:**
In [`graphql-server/src/functions/graphql.ts`](https://github.com/redwoodjs/redwood/blob/main/packages/graphql-server/src/functions/graphql.ts#L345), it currently checks if `result.data` exists before checking for the error but when the error happens the `data` key is null, that's why that error log becomes unreachable.
**Fix**:
Moved error check outside of `result.data` check.
=> Fix: Log error during GraphQL execution

packages/testing/config/jest/api/jest.setup.js
This was something that was bothering me when using scenarios.
This PR allows `scenario` to also be used with `scenario.only`
```
scenario('testName', () => {})
scenario.only('testName', () => {})
```
=> extend scenario with support for scenario.only

packages/testing/config/jest/api/jest.setup.js
This is a quick fix to allow scenarios to use other scenario data as input. #2422
It can be used like so.
```
export const standard = defineScenario({
user: {
one: { data: { email: 'String8522832' } },
two: { data: { email: 'String9268083' } },
},
event: {
one: (scenario) => {
return {
data: {
name: 'testing',
userId: scenario.user.one.id,
},
}
},
},
})
```
This should work in the order that the keys are defined in the scenario.
Since as of es2015 object keys are chronological https://tc39.es/ecma262/#sec-ordinaryownpropertykeys
Any part of the scenario whose key is created above should be accessible when you use a function to access the data.
Data returned from the function should be an object of the data that you want to be created.
=> Use data previously created in the scenario as input to other scenario data

packages/graphql-server/src/plugins/__tests__/useRedwoodDirective.test.ts, packages/graphql-server/src/plugins/useRedwoodDirective.ts
...because we now have build time and devtime checks
The run time check seems superflous!
=> fix(gql-server): Allow query/mutate without directives

packages/api/src/functions/dbAuth/DbAuthHandler.ts
Fixes typescript error `'${field} cannot be blank' is not type of string` 
The type should be type `string` instead of plain text.
Fixes #3391
=> Fix invalid type in DbAuthHandler

packages/graphql-server/src/makeMergedSchema/__tests__/makeMergedSchema.test.ts, packages/internal/src/validateSchema.ts
Currently, when no directives are declared on any mutation or query (for example in the test project app for Posts and Contacts), when building:
> `yarn rw build`
```terminal
✔ Generating Prisma Client...
✖ Verifying graphql schema...
→ - deletePost Mutation
Building API...
Cleaning Web...
Building Web...
Prerendering Web...
You must specify one of @requireAuth, @skipAuth or a custom directive for
- createContact Mutation
- createPost Mutation
- updatePost Mutation
- deletePost Mutation 
```
and when launching the dev server
> `yarn rw dev`
```terminal
api | [nodemon] 2.0.12
api | [nodemon] to restart at any time, enter `rs`
api | [nodemon] watching path(s): redwood.toml
api | [nodemon] watching extensions: js,mjs,json
api | [nodemon] starting `yarn rw-api-server-watch`
gen | Generating …
```
=> Fixes GraphQL Verification to check for directives on queries

packages/cli/src/commands/generate/service/__tests__/__snapshots__/service.test.js.snap, packages/cli/src/commands/generate/service/templates/service.ts.template, packages/create-redwood-app/template/api/src/lib/auth.ts
The Services template still includes BeforeResolverSpecType and requireAuth, which are no longer needed per changes coming in v0.37 (and are currently throwing import eslint errors).
This removes the imports and updates the template logic to include Prisma type when needed (model relation and/or crud).
=> fix generated service template (remove beforeResolvers)

packages/cli/src/commands/setup/auth/templates/auth.js.template
Fixes https://github.com/redwoodjs/redwood/issues/3142
Before Resolvers are no longer used in the auth template.
However, these was a Typescript issue with roles:
This has been fixed by adding an "AllowedRoles" type that lets the value be a string (one role), a list (several roles), or undefined (none) when checking the role membership.
=> Fixes Type error with requireAuth roles in lib/auth template

packages/cli/src/commands/generate/directive/__tests__/__snapshots__/directive.test.ts.snap, packages/cli/src/commands/generate/directive/templates/transformer.directive.ts.template, packages/cli/src/commands/generate/directive/templates/validator.directive.ts.template, packages/create-redwood-app/template/api/src/directives/requireAuth/requireAuth.ts, packages/create-redwood-app/template/api/src/directives/skipAuth/skipAuth.ts
Descriptions help document the GraphQL schema.
This PR adds comments to the built-in @requireAtuh and @skipAuth directives and also adds some boilerplate that can be edited for custom validator and transformer templates.
These use `string literals` ie (`"""`).
You can see the descriptions when introspecting the schema docs, seen here:
Note: Similar descriptions could be added to
* Redwood types
* SDL generators for Types and Query/Mutations
FYI: Descriptions like these appear in the schema. A comment (`#`) is a comment, but not shared when introspecting the schema.
=> Adds descriptions to @requireAuth @skipAuth directives and its generator templates

packages/internal/package.json
`@redwoodjs/codemods` relies on `@redwoodjs/internal` which was relying on some hoisted modules. They aren't there when it's just published alone so this PR adds them explicitly so it can work with npx.
=> Add some missing @redwoodjs/internal dependencies

packages/codemods/jest.config.js, packages/codemods/package.json, packages/codemods/src/codemods/v0.37.x/addDirectives/addDirectives.ts, packages/codemods/src/codemods/v0.37.x/addPrismaCreateToScenarios/addPrismaCreateToScenarios.yargs.ts, packages/codemods/src/codemods/v0.37.x/updateApiImports/updateApiImports.yargs.ts, packages/codemods/src/codemods/v0.37.x/updateGraphQLFunction/updateGraphQLFunction.yargs.ts, packages/codemods/src/codemods/v0.37.x/useRHFCoercion/useRHFCoercion.yargs.ts, packages/codemods/src/lib/getRWPaths.ts
This PR removes `redwoodjs/codemods` dependency on `redwoodjs/internal`. 
I had trouble running the codemods from `npx`. The error message suggested that it had something to do with `redwoodjs/internal` using dependencies that weren't listed in its package.json. I think we normally get away with this because, in a redwood project, `redwoodjs/internal` is used with all the other packages, one of which has the modules it's using.
We'll focus on tidying up our `package.json`s after we merge yarn 3 which will help tremendously in identifying where we're hoisting a bit too much.
=> Remove codemods dependency on @redwoodjs/internal

packages/codemods/package.json
Fix dependency errors, running codemods package through npx
Because we use `Set` in one of the codemods, the corejs polyfill needs to be included. 
If you look at the output of the compiled JS these require statements are in there:
```
───────┬────────────────────────────────────────────────────────────────────────
│ File: dist/codemods/v0.37.x/updateApiImports/updateApiImports.js
───────┼────────────────────────────────────────────────────────────────────────
1   │ "use strict";
2   │
3   │ Object.defineProperty(exports, "__esModule", {
4   │   value: true
5   │ });
6   │ exports.default = transformer;
7   │
8   │ require("core-js/modules/esnext.set.add-all.js");
9   │
10   │ require("core-js/modules/esnext.set.delete-all.js");
11   │
12   │ …
```
=> Add core-js to codemods dep for polyfills

packages/codemods/jest.setup.js, packages/codemods/package.json, packages/codemods/testUtils.d.ts, packages/codemods/testUtils/index.ts, packages/codemods/tsconfig.json
Attempts to fix babel issues that happen when running codemods with np
The way I had tsconfig setup meant when the types were generated, it was creating stuff in dist/src.
I also removed the `--copy-files` flag from the build command, which may have also been the cause of our woes.
=> Dont generate types for codemods, as its not a lib to import

babel.config.js, packages/codemods/.babelrc.js
We get the following babel error when running codemods:
```
Error: 'loose' mode configuration must be the same for @babel/plugin-proposal-class-properties, 
@babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object 
(when they are enabled).
```
We enable loose mode for `@babel/plugin-proposal-class-properties` and `@babel/plugin-proposal-private-methods`, but not for `@babel/plugin-proposal-private-property-in-object`:
https://github.com/redwoodjs/redwood/blob/a8d0cf899a4a82c85230bd6a21ae638ba0f7deec/babel.config.js#L47-L56
According to the babel docs for `@babel/plugin-proposal-private-property-in-object`:
> Note: The loose mode configuration setting must be the same as @babel/proposal-class-properties.
>
> …
=> Align loose mode in babel plugins

packages/codemods/src/codemods/v0.37.x/updateGraphQLFunction/updateGraphQLFunction.yargs.ts, packages/codemods/src/codemods/v0.37.x/updateScenarios/updateScenarios.yargs.ts, packages/codemods/src/lib/runTransform.ts
Invoking jscodeshift with yarn seems to work for testing on Windows, but not when actually invoking the binary to do codemods via npx. This PR fixes that and fg.sync's paths by adding a pretty unfortunate/gnarly conditional to runTransform.
=> (Codemods) Use correct bin, paths for Windows

packages/codemods/src/codemods/v0.37.x/addDirectives/addDirectives.ts
The URLs were swapped for `skipAuth.ts` and `skipAuth.test.ts` and the codemod didn't respect the type of project.
=> Fix add-directives codemod

packages/graphql-server/package.json
First we fixed the bloated function on Netlify. Now it turns out Netlify isn't including core-js.
Adding it directly to graphql-server package.
=> adding missing dep for Netlify

packages/api/package.json
more brute force diagnosing to get functions to run on Netlify
=> add uuid dep to api 'cause Netlify wants it

packages/cli/src/commands/setup/i18n/templates/i18n.js.template
Very simple PR to remove `lng: 'en'` from the `i18n.js` template, letting the language detection plugin do its job.
- [Issue justifying this change](https://github.com/i18next/i18next-browser-languageDetector/issues/183).
- [PR from this year reinforcing it as still valid](https://github.com/i18next/react-i18next-gitbook/pull/110).
With `lng: 'en'`:
Without:
I believe this would be a good place for a codemod for existing applications (I haven't the faintest clue how that works - happy to learn).
=> removed lng: 'en' from i18n template

packages/create-redwood-app/template/redwood.toml, packages/graphql-server/package.json, tasks/framework-tools/yarn.lock
There could be more to it than this, but this seems necessary. Closes #3494.
=> Add missing dependency graphql-tag to graphql-server

.github/workflows/netlify-build.yaml
Ref: https://github.com/redwoodjs/redwoodjs.com/pull/808#issuecomment-933857921
@thedavidprice Instead of adding trigger for new tags I've added for `edited` event of release. Current workflow was running on every release but for last patch release we `edited` instead of a new release.
=> Run netlify-build on release edit event

tasks/e2e/cypress/integration/03-storybook/storybook.spec.js
Avoid false positive. It seems `stderr` contains info as well as error, so just checking if it is `''` will not work.
See Also:
* #3508 
* https://github.com/redwoodjs/redwood/runs/3799459178?check_suite_focus=true
cc: @thedavidprice 
---
_note:_ while #3154 looks to fix the *"connection time out" error we were seeing in CI checks*; speaking from experience, there still can be inadvertent regressions added to the CI when upgrading Storybook, or other "unrelated" dependencies. This PR ( and #3508 even though the check was wrong ) makes sure that if there are build errors output, the `stderr` is surfaced to the CI so that maintainers can more easily see the potential issue.
=> fix: check no "ERR!" string is in stderr when running Storybook build

packages/router/src/splash-page.tsx
**Problem:**
Splash pages lists `undefined` as route if Routes are wrapped in `Set`. This PR changes to process only `Route` elements.
Problem Screenshot:
Routes:
After Fix:
@thedavidprice Okay for you to review?
=> Skip `undefined` routes in splash page

packages/internal/src/build/babel/web.ts, packages/prerender/src/runPrerender.tsx
Closes #3042.
While registering babel, this PR:
- sets root as Redwood app project root, so it searches for babel at correct place when prerender is executed someplace other than root dir.
- updates `ignore` to use regex `node_modules` instead as string, which should match node_module anywhere.
=> Fix prerender if run inside `web` directory

packages/router/src/splash-page.tsx
This fixes the styling of the logo on the splash page after running the 'yarn rw setup tailwind' command. Tailwind's preflight (their version of reset.css )makes the default svg 'display' attribute 'block'. By giving the logo the web-default 'display: inline', it overrides the preflight to correct the styling.
Closes #3695
=> Fix styling of logo on splash page after tailwind setup

packages/cli/src/commands/generate/dbAuth/templates/forgotPassword.tsx.template, packages/cli/src/commands/generate/dbAuth/templates/resetPassword.tsx.template
Resolves a few typos and a spot where ForgotPasswordPage had a dissimilar flow to other auth-templates.
* Adds a [generic](https://www.typescriptlang.org/docs/handbook/2/generics.html) to `passwordRef` on ResetPassword.
* Adds a generic to `usernameRef` on ForgotPassword.
* Updates toast-type on ForgotPassword error.
* Relocates `navigate()` to the success conditional of ForgotPassword.
=> dbAuth: Resolved typos and inconsistencies in templates

packages/router/src/__tests__/util.test.ts, packages/router/src/util.ts
The current implementation of the Glob type in the router includes the `...` in the name of the prop that is passed down to the Page component. The expectation is that a route path like `/path/{path...}` would result in a prop called `path` not `path...`.
This PR also refactors the `paramsForRoute` function to have a more consistent and useful result that cleans up the `matchPath` code.
I've also added some more tests to make sure we're handling all the expected cases properly.
cc @macovedj since this affects the code you wrote recently.
=> Glob param type should not include ellipsis in extracted variable name

packages/cli/src/commands/setup/auth/templates/firebase.auth.ts.template
Fixes https://github.com/redwoodjs/redwood/issues/3701
The `initializeApp` setup was missing a closing parentheses thus causing a syntax error when starting up the Redwood.
This PR fixes the error.
=> Fixes syntax error Firebase Auth template initializeApp

packages/internal/package.json, packages/internal/src/__tests__/config.test.ts, packages/internal/src/__tests__/fixtures/redwood.withEnv.toml, packages/internal/src/config.ts, yarn.lock
Fixes #3692
Already discussed with @mojombo. Any thoughts on the implementation?
Adding you as a reviewer because I'm messing with TOML
When deploying to multiple environments (staging,test, prod, etc.) it is sometimes necessary to override certain properties of the toml per environment. 
This is especially useful for using tools like GraphCDN
Adds support for env var interpolation. Example syntax:
```toml
[web]
title = "App running on ${APP_ENV}"
port = "${PORT:8910}"
apiUrl = "${API_URL:/.redwood/functions}"
includeEnvironmentVariables = []
```
This will do the following:
- set value of **title** from the env var `$APP_TITLE`, and interpolate it
- read the value of **port** from `$PORT`, but fallback to 8910 if not present. Note that the fallback has to be a string
- read **apiUrl** …
=> feat(rw-toml): Support env var interpolation in redwood.toml

packages/prerender/package.json, packages/prerender/src/babelPlugins/__tests__/babel-plugin-redwood-prerender-media-imports.test.ts, packages/prerender/src/babelPlugins/babel-plugin-redwood-prerender-media-imports.ts, packages/prerender/src/babelPlugins/utils.ts, yarn.lock
Fixes #2509 
Imported assets i.e. png, bmp, etc. is handled during the webpack bundling process using Webpack's asset loader (https://webpack.js.org/guides/asset-modules/).
It is configured to:
1. Copy over assets with a specific file name to the assets folder for larger assets
2. To create dataUris for smaller images (https://github.com/redwoodjs/redwood/blob/main/packages/core/config/webpack.common.js)
Prerendering does _not_ use webpack - so we have to:
a) For larger images, lookup the path it generates from the build manifest (generated by the webpack manifest plugin) and use that path for the source e.g. `<img src="/path/from/webpack/manifest">`
b) But for smaller images (i.e. assets not found in the manifest), we were just rendering a blank gif and relying on React to update with …
=> Base64 encode smaller required images during prerender

README.md, packages/internal/src/generate/templates/web-routerRoutes.d.ts.template, packages/router/src/util.ts
When specifying custom router param types there are two things you can (optionally) specify
1. The regexp to use when "finding" the part of the route to use your custom type for. This is now called `match`
2. A function that interprets the string in the route and then makes it into the type you want. This is now called `parse`
These names better reflects what's going on, and also better prepares for the addition of more functionality in the future.
Docs are here https://github.com/redwoodjs/redwoodjs.com/pull/882
=> Rename paramType properties

packages/web/src/apollo/index.tsx, packages/web/src/components/createCell.tsx
Helps with #2473.
- Add an option to set the log level of Apollo. Default `debug`. From [Apollo Client's changelog](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#improvements-16):
> all logs, warnings, and errors are hidden in production.
- Adds a warning detailing possible next step if Cell throws an error due to query result's inconsistent state.
=> Set Apollo's verbosity to debug and update Cell's error message

packages/web/src/apollo/index.tsx
Just adds a comment explaining why that line is there since it's for a very specific reason.
=> Document setLogVerbosity in RedwoodApolloProvider

packages/web/src/apollo/index.tsx, packages/web/src/components/createCell.tsx
Right now, if you export your own `beforeQuery` in one of your Cells, you better include all of Redwood's defaults too if you want Cells to still work the way they do. This is pretty annoying because you basically have to look up the defaults from the source every time you want to make a simple change to `beforeQuery`.
It turns out we can include all of that Cell config in `RedwoodApolloProvider` itself. So this PR moves that config up and out of the way so that you don't accidentally break Cells while trying to write your own `beforeQuery`.
=> Move default watchQuery config out of Cells

packages/web/src/apollo/index.tsx
In this example:
- I'm using dbAuth
- I'm logged in
- Posts are public (i.e. `skipAuth`ed)
So why do I see `Loading...` twice? Aren't Cells configured to show stale data from the cache?
https://user-images.githubusercontent.com/32992335/142494018-bca4374c-756c-4a0f-bc0e-6ef9665b1f74.mp4
The answer is that the Apollo Client cache is getting completely wiped during changes to Auth. Here's the sequence of events:
- `App` mounts
- `AuthProvider` mounts; `AuthProvider` tries to see if it's authenticated or not
- `RedwoodApolloProvider` mounts and instantiates a client and cache
- Not a private route? Keep rendering
- `PostsCell` mounts, issues it's query
- The query comes back. Success!
- The `AuthProvider` has discovered it's authenticated. `setState` incoming—rerender everything!
- …
=> Make Apollo Client cache resilient to changes in Auth

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/structure/package.json, yarn.lock
Release Notes:
- [v3.4.0](https://github.com/prisma/prisma/releases/tag/3.4.0)
- [v3.4.1](https://github.com/prisma/prisma/releases/tag/3.4.1)
- [v3.4.2](https://github.com/prisma/prisma/releases/tag/3.4.2)
- [v3.5.0](https://github.com/prisma/prisma/releases/tag/3.5.0)
- Support for PostgreSQL 14
- MongoDB misc improvements
- Order by relevance in full text search (PostgreSQL)
- More configuration options for indexes and constraints in the Prisma schema (Preview)
=> Upgrade to Prisma v3.5.0

packages/codemods/src/codemods/v0.38.x/updateNodeEngine/README.md, packages/codemods/src/codemods/v0.38.x/updateNodeEngine/updateNodeEngine.ts, packages/create-redwood-app/template/package.json
closed #3728
A dependency of Jest, `jest-watch-typeahead` requires Node.js `^12.22.0 || ^14.17.0 || >=16.0.0`. Prior to this change, create-redwood-app would run up until yarn install, which would fail during the middle of the run.
This PR bumps the Node.js engine in the CRWA Template to:
```
"node": ">=14.17 <=16.x"
```
=> bump CRWA node engine to 14.17

packages/api/package.json, packages/graphql-server/package.json
Remove jest testPathIgnorePatterns from api and graphql-server jest configs
When running `yarn test` the `api` and `graphql-server` runs were reporting the following warnings about jest confg:
```
redwoodjs/api: ● Multiple configurations found:
@redwoodjs/api:     * /Users/dthyresson/Dropbox/Code/redwoodjs/redwood/packages/api/jest.config.js
@redwoodjs/api:     * `jest` key in /Users/dthyresson/Dropbox/Code/redwoodjs/redwood/packages/api/package.json
@redwoodjs/api: 
@redwoodjs/api:   Implicit config resolution does not allow multiple configuration files.
@redwoodjs/api:   Either remove unused config files or select one explicitly with `--config`.
@redwoodjs/api: 
@redwoodjs/api:   Configuration Documentation:
@redwoodjs/api:   https://jestjs.io/docs/configuration.html …
```
=> Running tests no longer warn about api and graphql-server multiple jest configurations

packages/router/src/links.tsx
Spinning up the test project I noticed that `<Link>` had gotten red squiggles. I fixed it by making `onClick` optional in the TS typings. The code already handled it. It was just the types that were wrong.
Before
After
=> onClick should be optional on Link

packages/create-redwood-app/src/create-redwood-app.js, packages/create-redwood-app/template/package.json
In the Redwood Tutorial, we've always stated the Yarn prerequisite is >=v1.15:
- https://learn.redwoodjs.com/docs/tutorial/prerequisites
And Redwood projects will not work with Yarn >=v2. 
This PR updates the yarn engine requirements to enforce these conditions.
=> fix yarn engine requirements in CRWA package.json

packages/web/package.json, packages/web/src/components/createCell.tsx, yarn.lock
Apollo Client v3.5.4 Release Notes:
- https://github.com/apollographql/apollo-client/releases/tag/v3.5.4
~~May depend on https://github.com/redwoodjs/redwood/pull/3760.~~ We can merge this without upgrading `graphql`; see `@apollo/client`'s [peerDeps](https://github.com/apollographql/apollo-client/blob/8fc56eda7cc34c7a6c952703c797c04edffa462d/package.json#L65-L66).
=> Upgrade Apollo Client

packages/internal/src/build/babelPlugins/__tests__/__fixtures__/cell/cell-with-commented-exports/output.js, packages/internal/src/build/babelPlugins/__tests__/__fixtures__/cell/cell-with-required-exports/output.js, packages/internal/src/build/babelPlugins/babel-plugin-redwood-cell.ts, packages/web/src/components/createCell.tsx
Right now Cells are just called `Anonymous` in the React Component profiler:
If you have multiple Cells on a page, this can make it really hard to find what you're looking for.
Why's this happening anyway? Because Cells are actually anonymous function components:
https://github.com/redwoodjs/redwood/blob/b56821466d9fc2ff788a0d19642bf3eb15651b3c/packages/web/src/components/createCell.tsx#L137-L147
It'd be great if they were named after the filename! That's what this PR does.
=> Give Cells a displayName

packages/web/src/apollo/index.tsx, packages/web/src/components/createCell.tsx
While the diff of this PR may be intimidating, this PR introduces no new features and instead just cleans up the `createCell` file, commenting as much as I could (let me know if that gets annoying but I feel like every decision should be explained) and getting rid of a few things that I think were there only for historical reasons (i.e. before react hooks).
The only new thing this PR intentionally introduces is more a concise component-listing in the dev tools. Notice that there's no intermediate `Query` component:
**Before**
**After**
=> Refactor `createCell`

packages/cli/src/commands/setup/auth/templates/auth.ts.template, packages/graphql-server/src/functions/__tests__/useRequireAuth.test.ts, packages/graphql-server/src/functions/useRequireAuth.ts, packages/graphql-server/src/index.ts
Fix: https://github.com/redwoodjs/redwood/issues/3727
This PR allows developers to have their serverless function support `requireAuth` and it's currentUser and role checking by wrapping the their function handler in a handler that will authenticate the request event and set the global context with the currentUser in the same manner that the GraphQLHandler does.
While we don't necessarily encourage tis behavior, we can support it. Rather, if your function needs auth, then it can simply be a GraphQL request -- or treat your serverless function like a webhook and use a known verifier method.
Note: the wrapper lives in `@redwoodjs/graphql-server` because 1) it mimics the graphQLHandler auth flow and 2) that's when globalContext lives
To support requireAuth in your serverless function:
```ts …
```
=> Implements a wrapper for serverless functions to support requireAuth

packages/cli/src/commands/generate/model/model.js
The command `rw generate` was failing if `@redwoodjs/record` package isn't installed. This uses a lazy import for the task in model.js that requires `record`, which fixes the generate command for projects without record installed.
=> lazy import record package in cli

packages/internal/src/build/babel/web.ts
So turns out there's certain cases where you need to override some of the default babel config for the webside - such as using emotion ui with the `css` prop.
While most plugins/presets play nicely - it seems `@babel/preset-react` is sensitive to the order in which it is configured.
This PR allows users to pass preset-react config, by adding it to their `web/babel.config.js`. 
e.g. To configure emotion
```js
// ./web/babel.config.js 
{
"presets": [
[
"@babel/preset-react",
{ "runtime": "automatic", "importSource": "@emotion/react" } // <--- this is the special config required for emotion
]
],
"plugins": ["@emotion/babel-plugin"]
}
```
---
More reading: https://emotion.sh/docs/css-prop#babel-preset
=> Allow configuration of preset-react on the web side

.github/renovate.json
To run CI on PRs, renovate needs to be able to update the lock file.
=> [Renovate] Enable lock file updates, order config

packages/internal/src/build/babel/web.ts, packages/prerender/src/runPrerender.tsx
This PR includes 2 fixes:
**1. Routes autoloader plugin**
Fixes #3814
On v0.39.1, the routes autoloader plugin doesn't run because of the test regex, which doesn't work due to the different path syntax on Windows.
I'm switching back to the string form (which I've confirmed works), because I don't want to mess around with regexes.
**2. Module resolver**
Module resolution seems to be broken on windows. See repro here: https://github.com/jtoar/babel-windows-repro
To fix this, I've re-added the `babel-module-resolver` plugin. We totally want to move away from this longer term, but clearly our custom plugins aren't ready to operate without this plugin.
=> Windows babel fixes for v0.39.x

__fixtures__/example-todo-main/api/src/services/todos/todos.test.js, packages/internal/src/__tests__/build_api.test.ts, packages/internal/src/build/api.ts, packages/internal/src/build/babel/api.ts, packages/testing/config/jest/api/index.js
Fixes the situation where you've used an alias in a jest mock
e.g.
```js
jest.mock('src/lib/s3', () => {
return {
getSignedUrl: jest.fn(() => 'https://mockedBucket.tape.sh?sign=xxx'),
}
})
```
This is now transformed to the relative path correctly.
```js
jest.mock('../../src/lib/s3', () => {
return {
getSignedUrl: jest.fn(() => 'https://mockedBucket.tape.sh?sign=xxx'),
}
})
```
=> fix(babel): Fix jest.mock module resolution

tasks/framework-tools/src/lib/framework.mjs
Pretty sure this is the fix for `project:sync` building in an infinite loop. I was overthinking the change at the time / misunderstanding which script `lerna run` targets. To be sure, I'll work on a feature with this branch, with `project:sync` on for a while.
=> Fix rwfw project:sync loop

packages/cli/src/commands/setup.js, packages/cli/src/commands/setup/auth/auth.js, packages/cli/src/commands/setup/deploy/deploy.js, packages/cli/src/middleware/detectProjectRwVersion.js
Fixes #3876
This adds a yargs middleware to pass the current redwood version to all setup commands.
I only found these two sub commainds affected:
- `rw setup auth xxxx`
- `rw setup deploy yyy`
Note that we would still not see this have any affect when using `rwfw`, becuase the current version of redwood is detected from the cli package.json.
=> Uses current RW version for setup commands auth and deploy

packages/cli/src/commands/setup/ui/tailwindcss.js
Tailwind v3 has been published. This updates the setup ui tailwindcss command to use `latest` (instead of `next`)
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0
=> install latest tailwindcss during setup ui

packages/router/src/links.tsx
The onClick prop was recently added to the NavLinkProps.  I believe the prop should be optional.
@Tobbe , can I tag you on this?  Feel free to reassign.
=> Make onClick prop of NavLink optional.

packages/cli/src/commands/generate/__tests__/helpers.test.js, packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap, packages/cli/src/commands/generate/page/page.js, packages/cli/src/commands/generate/page/templates/page.tsx.template
As I'm updating the tutorial for v1.0 I didn't love the "feel" of the default `<MetaTags>` component in the page template: the comment in there describing how to use it is really long and messes with the nice clean flow of the blank page:
```jsx
<MetaTags
title="About"
// description="About description"
/* you should un-comment description and add a unique description, 155 characters or less
You can look at this documentation for best practices : https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets */
/>
```
(The weird indenting of the second line is actually present in the generated code.)
This PR removes the comment and actually enables the description which just reads "PageName page":
```jsx
<MetaTags title="About" description="About page" />
```
I've …
=> Simplify template MetaTags description

package.json
Inadvertently removed in https://github.com/redwoodjs/redwood/pull/3831.
=> Add clean:prisma back to build:clean

.github/renovate.json
Right now renovate's failing on dedupe checks so this PR instructs it to run dedupe after install: https://docs.renovatebot.com/configuration-options/#postupdateoptions.
The "highest" strategy is appropriate for the version of yarn we're using:
```
dom@evaM1 ~/p/r/redwood (renovate/envelop-core-1.x)> yarn dedupe --check
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ @envelop/core@npm:^1.6.1 can be deduped from @envelop/core@npm:1.6.2 to @envelop/core@npm:1.6.5
➤ YN0000: │ One package can be deduped using the highest strategy
➤ YN0000: └ Completed
```
=> [Renovate] Run dedupe after install

packages/forms/src/FormError.tsx
The form error property accepts `any`:
```
interface FormProps extends Omit<React.ComponentPropsWithRef<'form'>, 'onSubmit'> {
error?: any;
```
But raises an exception if it doesn't conform to `RWGqlError` which is an internal type. The form does a validation check for the other possible property `networkError` (via the null check) but doesn't for `graphQLErrors`. This was the minimal case change, but I think a tighter change might be making:
```ts
interface RWGqlError {
message: string
graphQLErrors: ReadonlyArray<GraphQLError>
networkError: Error | ServerParseError | ServerError | null
}
```
to
```ts
interface RWGqlError extends Error {
graphQLErrors?: ReadonlyArray<GraphQLError>
networkError?: Error | ServerParseError | ServerError | null
}
```
=> Still allow generic Errors in redwood forms

packages/core/config/webpack.common.js, packages/internal/src/__tests__/config.test.ts, packages/internal/src/config.ts
Disable sourcemaps in prod for the web side unless explicitly enabled in toml
```toml
#redwood.toml
[web]
#...
sourceMap = true 
```
If you set sourceMap to true, it'll will build with source maps even in production. This might be useful in certain scenarios, where you're getting an error in production but not in dev.
Fixes #2416
=> fix(webpack): Disable sourcemaps in prod

packages/router/src/ActivePageContext.tsx, packages/router/src/PageLoadingContext.tsx, packages/router/src/__tests__/router.test.tsx, packages/router/src/__tests__/set.test.tsx, packages/router/src/active-route-loader.tsx, packages/router/src/links.tsx, packages/router/src/location.tsx, packages/router/src/page-loader.tsx, packages/router/src/params.tsx, packages/router/src/router-context.tsx, packages/router/src/router.tsx, packages/router/src/useIsMounted.ts, packages/router/src/util.ts, packages/testing/src/web/__tests__/MockRouter.test.tsx
This is an alternative attempt at a solution for #2124 
When I was reviewing @callingmedic911's PR for the same issue (#3767) I did some refactoring while getting myself up-to-speed on the code again. And while doing so (and after reading @jtoar's excellent link to the React beta docs) I came up with a (in my eyes) simpler solution to the problem.
This PR has two commits (as of writing this). The first one is just the refactoring I did. The second one is the actual solution to the linked issue.
The TL;DR of it is: Set a hard-coded `key` on the `<Route>`s so that `<PageLoader>` can keep its state while navigating.
Need to update the docs: https://redwoodjs.com/docs/prerender#flash-after-page-load
=> Fix: Router white flash on first navigation to page

packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
When I tried to add scalars from [`graphql-scalars`](https://www.graphql-scalars.dev/) I found that `typeDefs` passed to `schemaOptions` were overwriting the default ones.
For example:
```javascript
import { createGraphQLHandler } from "@redwoodjs/graphql-server";
import { CurrencyDefinition, CurrencyResolver } from "graphql-scalars";
export const handler = createGraphQLHandler({
getCurrentUser,
loggerConfig: { logger, options: {} },
directives,
sdls,
services,
onException: () => {
db.$disconnect();
},
schemaOptions: {
typeDefs: [CurrencyDefinition],  // <-- ISSUE
resolvers: { Currency: CurrencyResolver },
},
});
```
This PR should hopefully fix that behaviour.
=> Properly merge typeDefs in makeMergedSchema

.github/renovate.json, .github/workflows/require-PR-label.yaml
This is a step towards better automation of our release process. These labels will be used to categorize Release Notes. We can also set up additional triggers for `release:feature-breaking`, which in the future will mean a PR likely requires additional steps (e.g. copy for Release, deferred until next major release, etc.)
I'm using this GitHub Marketplace Action. In the future, we can customize if/as needed:
- https://github.com/marketplace/actions/require-labels
I’ve created the new labels:
=> Add GitHub Action requiring PRs to include one of the "release:*" labels

packages/cli/src/commands/deploy/aws-providers/serverless.js, packages/cli/src/commands/deploy/aws.js, packages/cli/src/commands/deploy/packing/nft.js, packages/cli/src/commands/setup/deploy/providers/aws-serverless.js
Work related to #3284 / #3686
---
- target latest node runtime
- improve CORS defaults
- remove deprecation warnings
- clean up packaging (unrelated prisma binaries not included) 
see also: https://github.com/redwoodjs/redwood/issues/3284#issuecomment-922375958
=> Update Serverless Framework's AWS integration

packages/prerender/src/internal.ts, packages/prerender/src/runPrerender.tsx
I added some code to my i18n initialization that looks at the url to figure out what language to load. Unfortunately that broke prerendering.
This PR adds the prerendered path to `global.location.pathname`.
We already set the prerendered path in the location provider used by the router, but that's not enough for code that runs outside of the router, or even code inside the router that looks at the global location directly instead of using the `useLocation` hook. Now code like that should work.
I thought about the other properties on `location`, like href, hostname etc. Should we fake those? What hostname should we use in that case? localhost?
I left them out for now, mainly because it felt weird to make up a hostname.
=> Populate global.location when prerendering

packages/cli/src/middleware/checkForBabelConfig.js
1 ) Say you have a project setup like this 
```
├── packages
├── someother
│   └── myModule.ts
│   └── .babelrc
├── web
│   ├── config
├── api
│   ├── config
```
The CLI will not run the dev server at all. 
2) It will also error out if you have node_modules with babelrc in them (and they're not hoisted).
3) It just prints out the warning now, isntead of erroring out
=> fix(babel-check): Scope glob for babelrc check

packages/graphql-server/src/functions/graphql.ts
After https://github.com/redwoodjs/redwood/pull/3884 you can now merge in and use custom [graphql-scalars ](https://www.graphql-scalars.dev/docs) (eg, Currency, EmailAddress, PositiveInt, etc).
The how to will be documented as part of a fix for https://github.com/redwoodjs/redwoodjs.com/issues/925.
But the error masking was suppressing the validation message.
This PR updates the masked error format method to better check if the original error was a type error (which is what the scalar raises in its validate method) and then uses the original message.
In the example below, we use the [`Currency`](https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/Currency.ts) scalar that validates if it is a string of one of the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) cods like …
=> Support and format custom GraphQL Scalar validation error messages

packages/cli/src/commands/setup.js, packages/cli/src/commands/setup/ui/libraries/chakra-ui.js, packages/cli/src/commands/setup/ui/libraries/tailwindcss.js, packages/cli/src/commands/setup/ui/ui.js
Fixes #3956
Duplicates, in a different implementation #4036
Changes the setup command to ignore double nested commands. Examples
- `setup/ui/libraries/chakra-ui` ignored when you just do `yarn rw`, but configured to be picked up in `yarn rw setup ui`
- `setup/bazinga/bazinga.js` - ignored by root `yarn rw`, but available in `yarn rw setup` 
- `setup/foobar.js` - ignored by root `yarn rw` but available in `yarn rw setup`
=> fix(setup): Fix handling of nested setup commands

packages/core/package.json, yarn.lock
> Update: CI seems to be passing now, so TBD.
e2e tests have been flaky lately. One tends to pass while the other fails (usually the one running on node.js v14). This seemed to have started four days ago, after upgrading webpack-dev-server https://github.com/redwoodjs/redwood/pull/4032. This PR reverts the upgrade (it was only a semver patch).
https://github.com/redwoodjs/redwood/actions/workflows/e2e.yaml?page=10
https://github.com/redwoodjs/redwood/actions/runs/1651259167
=> Revert webpack-dev-server upgrade

.github/workflows/e2e.yaml
This is an attempt to fix network flakiness using the strategy in https://github.com/vercel/next.js/pull/28264. I tried this out on my fork of redwood and it seemed to actually work (PR here: https://github.com/jtoar/redwood/pull/155), but I have no idea what this really does. (The [original comment](https://github.com/actions/virtual-environments/issues/1187#issuecomment-686735760) says that it "disables TCP/UCP offloading", but I don't really know what that entails.)
=> Try fixing e2e network flakiness

packages/forms/src/index.tsx
This PR adds `export` statements to the prop-interfaces provided by `packages/forms`, making it easier to compose components which extend their functionality - or provide defaults on top of them.
=> added exports to form-component props

packages/core/package.json, yarn.lock
Seeing as https://github.com/redwoodjs/redwood/pull/4073 didn't matter, reverting my reversion.
=> Upgrade webpack dev server

packages/testing/src/api/scenario.ts
Though it's possible to do `scenario.only` to run a single scenario, it shows a TS error. This small PR adds that missing type.
Original error:
=> Add missing type for `only` in scenario

packages/codemods/package.json, packages/codemods/src/lib/getFilesWithPattern.ts, yarn.lock
cc @jtoar 
vscode-ripgrep was deprecated and replaced with @vscode/ripgrep, which was causing an error during Yarn install:
- https://www.npmjs.com/package/vscode-ripgrep
=> replace vscode-ripgrep with @vscode/ripgrep

tasks/test-project/tasks.js
As of v0.41, the CI test-project fails (in context of GitPod) due to issue with tailwind and PostCSS. It's possibly related to Webpack changes (and/or Storybook). Here's some background that's helpful but from a non-tailwind PR topic:
- https://github.com/redwoodjs/redwood/pull/3515#issuecomment-1000974638
This PR adds the workaround to get CI running for near-term. Overall issue needs to be resolved before next release.
=> chore: test-project workaround for tailwind PostCSS error

.github/issue_template.md, .github/pull_request_template.md
Copy for new Issues and PRs. Purpose:
- general status update
- set expectations
- communicate needs
- encourage next steps; this is not meant to be a blocker
Feedback?
---
The Redwood v1 release candidate has been published, and we're actively working toward a 1.0.0 GA. 🎯
Read @mojombo's post about what to expect, what this means for current priorities, and how to help:
- v1-rc Announcement: https://community.redwoodjs.com/t/what-the-1-0-release-candidate-phase-means-and-when-1-0-will-drop/2604
- v1-rc Priorities that need community help: https://redwoodjs.com/good-first-issue
New Issues and PRs are still welcome and helpful! 😀 If you're not sure whether this new one will be a v1 priority, then please go ahead and ask by submitting it. Or reach out via the community chat or forums:
- …
=> Update Issue and PR templates with v1-rc status

packages/graphql-server/src/functions/graphql.ts
The GraphQL error masking is useful in prod/staging environments, but not very valuable in dev environments. This also means that dev tooling can work with the original server error messages.
=> Don't mask GraphQL errors when you're in the dev environment

packages/cli/src/commands/generate/page/__tests__/__snapshots__/page.test.js.snap, packages/cli/src/commands/generate/page/__tests__/page.test.js, packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/scaffold/templates/pages/NamePage.tsx.template
1. The snapshot tests for TS files had "undefined" snapshots.
This PR fixes that, to ensure the tests actually test something! Dangers of snapshot testing!
2. The scaffold templates weren't using the correct variable for the typescript type
i.e.
It would generate a type of `Int`. It now does
```diff
type PostPageProps = {
-   id: Int
+  id: number
}
```
=> fix(generator): Fix incorrect TS page param type on scaffold 

tasks/release-notes/release-notes.mjs
- now accounts for the fact that we could merge more than 100 PRs in a release (thanks to renovate)
- uses the `release:feature`, `release:fix`, `release:chore` labels to sort PRs
- removes renovate from the "Unique contributors" and "PRs merged" stats
- simplifies the code a bit hopefully
=> Update release notes script

packages/cli/src/commands/lint.js
The command `rw lint` is hardcoded to run eslint on the web and api directories. However, eslint accepts paths to files or directories. 
This PR updates `yarn rw lint [path]` to accept an array of file(s) or directory(ies), overriding the default behavior. This will make it possible to test `yarn rw lint` during CI (current test projects always have some lint errors, which are challenging to resolve during test project generation).
=> Add path param array to `rw lint [path]`

tasks/release-notes/release-notes.mjs
Fixing a typo from the previous PR that updated this: https://github.com/redwoodjs/redwood/pull/4212.
=> [Release notes] Only use list items for renovate

.github/renovate.json
After we release, renovate tries to rollback the versions of the redwoodjs packages (see https://github.com/redwoodjs/redwood/pull/4214). This change just tells it not to bother with doing that.
=> [Renovate] Rearrange config, ignore redwoodjs packages

packages/api-server/package.json, packages/api/package.json, packages/auth/package.json, packages/cli/package.json, packages/create-redwood-app/package.json, packages/forms/package.json, packages/graphql-server/package.json, packages/internal/package.json, packages/prerender/package.json, packages/record/package.json, packages/router/package.json, packages/structure/package.json, packages/telemetry/package.json, packages/testing/package.json, packages/web/package.json, yarn.lock
This resolves errors from running `yarn dlx @yarnpkg/doctor`:
- create-redwood-app package
- telemetry package
- @babel/core devDep across packages
=> resolve yarn doctor issues

packages/cli/src/commands/setup/deploy/providers/netlify.js
=> Fixed netlify api config

packages/telemetry/src/sendTelemetry.ts
Fixes the non-critical errors we're receiving from the CLI running on Windows. I'm not 100% certain if it always happens, because @cannikin had some code to detect the shell for windows, but on my Windows dev box, I never see the shell property.
Walkthrough: https://s.tape.sh/xGJk8Iu0
=> fix(telemetry): Safely lookup shell for windows

packages/codemods/package.json, packages/graphql-server/package.json, packages/prerender/package.json, packages/telemetry/package.json, yarn.lock
Recommended security upgrade:
- https://nvd.nist.gov/vuln/detail/CVE-2022-0235
=> (chore) upgrade node-fetch 2.6.7 (security)

packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap, packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
Remove accidentally committed `describe.only` in a test file.
Needed to also update the snapshots. Now that we're running all tests again some of the snapshots had become stale.
=> Scaffold: Enable all tests again and update snapshots

tasks/release/__tests__/release.test.mjs, tasks/release/__tests__/updateNextReleasePullRequestsMilestone.test.mjs, tasks/release/prompts.mjs, tasks/release/release.mjs, tasks/release/updateNextReleasePullRequestsMilestone.mjs
This PR gets the patch release process ready for action. While it doesn't change the minor release process, it does 1) improve some of the tests and 2) improve the code organization significantly:
- add basic test for release script (check that the queries are right)
- add a legit MSW unit test for updating next release pull requests 
- add better primitives
- `ask`, `check`, `fix`, `ok` tagged template literals
- add an option to exit the process to `confirm` prompts
- add a new `confirmRuns` function to consolidate running tasks after asking
=> Update release script

packages/forms/jest.config.js, packages/forms/package.json, yarn.lock
While I was reviewing #4302, I ran `yarn dlx @yarnpkg/doctor` to see if anything was missing. There were a few things missing and a few things there that we don't need.
I also sorted the `package.json` file and removed some jest config because it wasn't necessary anymore; moreover, `yarn dlx @yarnpkg/doctor` doesn't like seeing `node_modules` in strings.
The output from `yarn dlx @yarnpkg/doctor`:
```
dom@evaM1 ~/p/r/r/p/forms (ds-update-forms-package.json)> yarn dlx @yarnpkg/doctor
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 827ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ util-deprecate@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ which@npm:2.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ …
```
=> Add missing deps to @redwoodjs/forms package.json

CONTRIBUTING.md
@jtoar this is the complementary PR to https://github.com/redwoodjs/redwoodjs.com/pull/958
- link to other contributing docs
- update section structure
- misc improvements
=> update contributing content

packages/web/src/components/createCell.tsx
This PR resolves https://github.com/redwoodjs/redwood/issues/2962
It's not the solution we decided on, but it's the solution I want 😁
So, this is the setup
```jsx
<JoinCell inviteCode={inviteCode} />
```
and a cell query like this
```jsx
export const QUERY = gql`
query JoinTeamQuery($inviteCode: String!) {
inviteCode(code: $inviteCode) {
code
expiry
}
}
`
```
And finally a Success component like this
```jsx
export const Success = ({ inviteCode }) => {
return <pre>{JSON.stringify(inviteCode, null, 2)}</pre>
}
```
With my new implementation you'd see this:
```
{
"__typename": "InviteCode",
"code": "1NBVWN",
"expiry": "2022-01-31T16:04:00.000Z"
}
```
With the old implementation all you'd get was this:
```
"1NBVWN"
```
And, finally, if you want to get at the actual props that have been …
=> createCell: Give cell results priority over cell props

packages/core/config/webpack.common.js
As a workaround to publish v0.44, this temporarily reverts a Webpack DotEnv config that was added to support running Storybook in CI. The config change caused an error for some cases where env vars were defined but empty until deployed to production — those env vars were no longer included in the production build.
Long term solution is #4344
=> revert dotenv ignorestub

packages/testing/config/jest/api/jest.setup.js
When running `yarn rw test api`, it generate scenarioTeardown.json at the root of the project now. This was done by accident! 
This PR restores the behaviour to put it into the `.redwood` folder
=> fix(scenario): Accidentally comitted debugging change

packages/cli/src/commands/generate/cell/cell.js, packages/cli/src/commands/generate/page/page.js, packages/cli/src/commands/generate/scaffold/scaffold.js, packages/cli/src/commands/generate/sdl/sdl.js
Related to #4303
This PR fixes a bug where types weren't being generated after runnign `yarn rw g` on Cells, Pages, Scaffold or SDLs
=> fix(generators): Generate types after gen-ing files

packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default.input.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default.output.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/input/api/jest.config.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/input/web/jest.config.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/api/jest.config.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/jest.config.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__testfixtures__/default/output/web/jest.config.js, packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
Alternative to https://github.com/redwoodjs/redwood/pull/4388, which didn't work. Two of the tests I added were redundant (i.e. covered by the other two tests). Hoping removing the redundant test fixes the timeout. But it's still worth investigating why things are taking so long assuming the test itself is ok.
=> Try fixing codemod test timeout

packages/codemods/jest.config.js, packages/testing/src/web/__tests__/MockHandlers.test.tsx
This PR tries to close #4316 by doing the easiest thing possible first which is wait a little longer for the result in `MockHandlers.test.tsx` to update. Also see https://github.com/redwoodjs/redwood/pull/4370#issuecomment-1030757284.
Although https://github.com/redwoodjs/redwood/pull/4389 passed CI, `updateJestConfig.test.ts` is still flaky too, so we try the same strategy.
=> Increase test timeout

packages/create-redwood-app/template/web/tsconfig.json
Looks like we were missing configuration for getting types in web-side tests.
Explanation here: https://s.tape.sh/za2n6n8j
=> Add types for react-testing library to tsconfig

package.json, tasks/release/__tests__/release.test.mjs, tasks/release/__tests__/updatePullRequestsMilestone.test.mjs, tasks/release/cli.mjs, tasks/release/prompts.mjs, tasks/release/release.mjs, tasks/release/updatePRsMilestone.mjs
Partially closes https://github.com/redwoodjs/redwood/issues/2067. This PR prepares the release script for releasing patches.
Also, you can now pass options to answer some of the questions from the CLI and speed things up:
```
yarn release --semver minor --no-prs --checkout
```
But "check" steps will never be skipped.
@thedavidprice, a couple things:
-> I've seen two syntaxes for checking out the release branch:
```shell
git checkout -b release/patch/v0.28.1 v0.28.0
git checkout tags/v0.28.0 -b release/patch/v0.28.1
```
I'm going with the first one because that's what's in the git-tagging docs: https://git-scm.com/book/en/v2/Git-Basics-Tagging (at the end—"Checking out Tags").
-> This script now handles updating `next-release-patch` pull requests.
-> This one's probably obvious but we …
=> Prepare release script for patches

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/record/package.json, packages/structure/package.json, yarn.lock
There was a regression in Prisma 3.9.0 (and 3.9.1). See https://github.com/prisma/prisma/issues/11641
So until they have a fix out we're downgrading to 3.8.1 which is the last version before 3.9.0
Fixes https://github.com/redwoodjs/redwood/issues/4396
=> Downgrade Prisma to 3.8.1

packages/cli/src/commands/deploy/render.js
This PR disables the detached telemetry process from the api service deployment, which was causing `yarn rw deploy render api` to exceed the mem limit for the Render.com free tier.
=> (render.com deployment) resolve deploy render exceeding memory on free tier

packages/api/package.json, packages/cli/package.json, packages/graphql-server/package.json, packages/record/package.json, packages/structure/package.json, yarn.lock
We reverted Prisma because a regression in v 3.9.1. That regression has now been fix, so let's upgrade again
More info about the regression
https://github.com/redwoodjs/redwood/issues/4396
https://github.com/prisma/prisma/issues/11641
Prisma's fix
https://github.com/prisma/prisma/pull/11679
Prisma's release notes for this release
https://github.com/prisma/prisma/releases/tag/3.9.2
=> Upgrade Prisma to 3.9.2

packages/api-server/src/index.ts
Ensure we use posix paths for the code to work on both *nix and Windows
fixes #4424
=> api server: Windows fix, ensure posix paths

package.json
Gitpod is currently failing, because rimraf (or yarn) has started exiting the `build:clean` command with the exit code `127`. 
This results in the test project not being generated annoyingly, which means Gitpod also doesn't spin up correctly.
This PR ignores the exit code from rimraf, in the `build:clean` script
=> fix(test-project): Ignore exit code from rimraf if dist not present

package.json
Windows doesn't do any path expansion when passing arguments to CLI executables.
So if you're in a directory with two files: `a.txt` and `b.txt` and run `rimraf *.txt` this is what happens:
Windows: `rimraf "*.txt"`
Linux: `rimraf a.txt b.txt`
What this also means is if the glob-path doesn't exist, on Windows the CLI executable has to deal with it itself, on Linux the shell with throw an error before even trying to run the cli.
So, to make this work the same on both platform what you need to do is to quote the path: `rimraf "*.txt"`. On Windows this is already what happens, so no change, and rimraf will deal with it. On *nix this bypasses the shell path expansion and rimraf will deal with it instead.
Related: https://github.com/redwoodjs/redwood/pull/4462
=> package.json: Quote path to rimraf to let rimraf do globbing

packages/cli/src/commands/prisma.js
Closes https://github.com/redwoodjs/redwood/issues/4170.
=> [CLI] Enable short-form prisma options

.github/renovate.json
Pretty bytes is now ESM only: https://github.com/redwoodjs/redwood/pull/4458.
=> [Renovate] Ignore pretty bytes

packages/auth/src/AuthProvider.tsx, packages/web/src/apollo/index.tsx, packages/web/src/components/FetchConfigProvider.tsx
When a user signs in with an auth provider a call to `setState` is made to set `isAuthenticated: true`. `setState` is async, so will happen some time in the future. When in does happen it'll update the auth React Context.
RW's gql client (apollo) is a consumer of the auth context. Previously the client would look at `isAuthenticated` to decide whether to send auth tokens or not.
The problem is if the RW app has (psuedo-)code like this
```
const { logIn } = useAuth();
logIn({ username, password })
.then((user) => {
getUserProfile({ variables: { id: user.sub } })
})
```
In the above case the `getUserProfile` gql query might fire off before the `isAuthenticated: true` state update has propagated down to the gql client.
Use `getToken` to ask the auth provider client for a token. The provider …
=> Apollo: isAuthenticated might not be up-to-date

tasks/release/release.mjs, tasks/release/updatePRsMilestone.mjs
- opens the link to the updated PRs before asking for confirmation
- fixes `git push` (I wasn't handling arrays properly https://github.com/google/zx/blob/main/docs/quotes.md#array-of-arguments)
- reverts to `git push --tags`
=> Fix release script

packages/codemods/src/codemods/v0.44.x/updateJestConfig/__tests__/updateJestConfig.test.ts
The update jest config codemod test seems to keep failing on Windows because of a timeout. See https://github.com/redwoodjs/redwood/runs/5258703596?check_suite_focus=true#step:11:154 for an example. This PR increases the timeout by five seconds.
=> Try increasing timeout for flaky codemods test

packages/graphql-server/src/functions/graphql.ts
Envelop recently added a new plugin:
> Add new plugin `useImmediateIntrospection` for speeding up introspection only operations by skipping context building.
We added that in https://github.com/redwoodjs/redwood/commit/faede7f5dbcf7291fe4a5813c10175b056b9abbb, but it seems it caused some auth bugs. See https://github.com/redwoodjs/redwood/issues/4520
So this PR reverts that change.
It was only enabled in dev as a performance optimization. So should be safe to go without.
Fixes: https://github.com/redwoodjs/redwood/issues/4520
=> Envelop: Don't use useImmediateIntrospection as it causes auth bug

packages/auth/src/authClients/goTrue.ts, packages/auth/src/authClients/netlify.ts
This PR fixes an issue in the Netlify authentication client where refreshing and getting a token can cause an error such as:
```
Error: null is not an object (evaluating 'u.default.gotrue.currentUser().jwt')
```
Because of a null default value set as part of the isAuthentication fix to set default values: https://github.com/redwoodjs/redwood/pull/4320/files
This PR catches any error from the Netlify client sdk and handles it.
Note that it isn't client that's null and raising the error as checking from it still causes the error.
```
if (client) {
// The client refresh function only actually refreshes token
// when it's been expired. Don't panic
await client.refresh()
const user = await client.currentUser()
return user?.token?.access_token || null
} else {
return null
}
```
Edit: Also added …
=> Netlify client getToken fix when GoTrue client refreshes JWT

packages/create-redwood-app/src/create-redwood-app.js
I think the logic in the description was reversed
=> create-redwood-app: Correct --overwrite description

packages/cli/src/commands/generate/secret/__tests__/secret.test.js, packages/cli/src/commands/generate/secret/secret.js
This PR makes the `yarn redwood generate secret` command output just the secret, no extra information messaging, when used in a pipeline. 
It allows you to do things like `yarn --silent rw g secret > myfile` to print just the secret to a file.
Or more relevant for dbAuth:
```
echo "SESSION_SECRET=$(yarn --silent rw g secret --raw)" >> .env
```
To append the needed environment variable to the user's .env file
(Updated to add `--silent`)
=> g secret: raw output

packages/cli/src/commands/exec.js
This PR makes the script name optional, and provides a bit more guidance, because its easy to forget script names.
Explanation: https://s.tape.sh/G92eIWlR
To list scripts you can run
Just: `yarn rw exec`
or `yarn rw exec --list`
=> feat(exec): Allow listing of scripts with rw exec to improve dx

packages/cli/src/lib/index.js
The `runCommandTask` which currently is only used in https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/lib/generatePrismaClient.js had the cwd set to the api side.
This PR does the following:
1. Run command tasks now take a cwd
2. Sets default cwd to the root of the project 
---
This won't 100% solve the problem we're seeing with prisma, as it seems to be a problem on their side too. Tracking issue here: https://github.com/redwoodjs/redwood/issues/4605
=> fixi(prisma): Set default cwd for runCommand task to base

packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.ts
I added a codemod in https://github.com/redwoodjs/redwood/pull/4444 for upgrading projects to yarn 3. But the codemod didn't work for projects on Node.js versions less than `v14.19`. The codemod handled that by saying upgrade Node first, but there's an alternative to that we prefer: install corepack via `npm i -g corepack`.
This PR updates the codemod so that it throws a more helpful error message.
=> [Codemod] Handle node versions that don't bundle corepack

packages/codemods/src/codemods/v0.48.x/upgradeYarn/upgradeYarn.ts
@callingmedic911 discovered that `corepack enable` can cause the yarn version to regress (say, from `1.22.15` to `1.22.11`). We need the yarn version to be at least `1.22.15` or so for `yarn set version stable` to work. Luckily, `corepack` has a `prepare` command that lets us do just this.
=> Make upgrade-yarn codemod more robust by preparing yarn version

packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/README.md, packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__testfixtures__/simple.input.js, packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__testfixtures__/simple.output.js, packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/__tests__/renameVerifierTimestamp.test.ts, packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/renameVerifierTimestamp.ts, packages/codemods/src/codemods/v0.48.x/renameVerifierTimestamp/renameVerifierTimestamp.yargs.ts
This PR adds a codemod for renaming `timestamp` to `currentTimestampOverride` for webhook verifiers
The PR that introduced that change, that this is a codemod for, is https://github.com/redwoodjs/redwood/pull/4608
Command to run the codemod (once it's published): `npx @redwoodjs/codemods@latest rename-verifier-timestamp`
=> Codemod for webhook verifier option renaming

packages/testing/config/storybook/main.js
Part one of two resolving #4676 by removing TS config added here 
- https://github.com/redwoodjs/redwood/pull/3515/files#diff-f2b8508ea44e00ef06fe0b2cd1197025d60d22cbcb4c32767b238f5c2bb57c63
This is a change to fix a DX problem with new Redwood TS projects and/or cases where Cells design in Storybook is broken because query types do not exist.
As a next step, we'll update the RW Storybook doc to explain how to enable type check. We'll also need to cover the caveat about Cells, which needs discussion.
=> fix storybook DX by removing default type check config

packages/codemods/src/codemods/v47.x/updateDevFatalErrorPage/__testfixtures__/default/output/web/src/pages/FatalErrorPage/FatalErrorPage.js
The codemod test to update the development fatal error page was failing (not sure why didn't see in PR but ... this fixes the issue):
And with this PR change:
```bash
PASS  src/codemods/v0.37.x/updateForms/__tests__/updateForms.test.ts
PASS  src/codemods/v47.x/updateDevFatalErrorPage/__tests__/updateDevFatalErrorPage.test.ts
PASS  src/codemods/v0.39.x/updateRouterParamTypes/__tests__/updateRouterParamTypes.ts
...
Test Suites: 10 passed, 10 total
Tests:       20 passed, 20 total
Snapshots:   0 total
Time:        4.405 s, estimated 8 s
Ran all test suites matching /src/i.
```
=> Fix failing codemod test for RedwoodDevFatalErrorPage

packages/api/src/auth/index.ts, packages/graphql-server/src/functions/useRequireAuth.ts
I was reading this code to try to figure out how `useRequireAuth` works. While reading it I made some changes that, imho, made it easier to read the code.
=> useRequireAuth: Refactor to make it easier to read

packages/cli/src/commands/setup/deploy/templates/serverless/api.js
Fixing two spelling misstakes in the serverless api yml template
=> Serverles api template: Fix spelling

packages/api/src/auth/verifiers/jwtVerifier.ts
Found some code that was unreachable. Because of the `return` the `throw` statement will never be executed.
And because we're not using the `error` in the `catch` I removed that too.
=> jwtVerifier: Remove unreachable code

packages/graphql-server/src/functions/types.ts
Fix and format JSDocs in types.ts for graphql-server
=> graphql-server types: Fix/format jsdocs

packages/api-server/src/cliHandlers.ts
This enables zero-downtime restarts for the API server with pm2. See https://pm2.keymetrics.io/docs/usage/signals-clean-restart/#graceful-start
`process.send` will only exist if the process was spawned from a parent, so we need to check if it is defined (which it is when pm2 is in control). There is no "api server" in serverless environments so this code should have no effect there.
We'll also want to document the fact somewhere that you need to add two things to your `ecosystem.config.js` for pm2:
```diff
{
name: 'algostake-api',
script: 'node_modules/.bin/rw',
args: 'serve api',
instances: 'max',
exec_mode: 'cluster',
+ wait_ready: true,
+ listen_timeout: 10000,
},
```
`wait_ready` tells it to actually listen for that message. The default timeout is 3 seconds which is not enough for the …
=> Send a 'ready' message to parent process if api server was spawned

.github/renovate.json
We ignored `lru-cache` in https://github.com/redwoodjs/redwood/pull/4442; just ignoring the the types too.
=> [Renovate] Ignore @types/lru-cache

.github/workflows/build-eslint-jest.yaml, .github/workflows/e2e.yaml, .github/workflows/publish-npm-canary.yaml, .github/workflows/smoke-test.yaml
Updates the cache key, so invalid cache isn't used in workflows
=> Chore: Change yarn cache key, to bust invalid cache

packages/api/package.json, packages/api/src/validations/errors.ts, packages/forms/src/FormError.tsx, yarn.lock
The new Service Validation update #4756 almost works, just a couple of tweaks:
* the error message needs to be in the form of an array instead of a string
* the field name is now included in the error message so no need to prefix on output
* Update the title of the `<FormError>` box
Before this PR:
After this PR:
=> Service Validations: Returns error message as an array in faked extensions

.github/workflows/build-eslint-jest.yaml, tasks/test-project/test-project
The smoke test is failing at the setup project step because the "setting yarn to v1" task is being skipped. As of https://github.com/redwoodjs/redwood/commit/097aa4e4cdb04259e7db5b24bcc9e9cd478c4624, yarn 1 is no longer included in the fixture, so we shouldn't skip that task by default.
I'm not exactly sure what the correct logic is here for skipping it.
=> Reverse logic in smoke test for setting yarn 1

.github/workflows/build-eslint-jest.yaml, .github/workflows/e2e.yaml, .github/workflows/smoke-test.yaml
Requiring CI to pass for changes to docs seems a little excessive. We definitely want some CI to run, but probably just some kind of check that confirms that the docs site still deploys. Opening this up for discussion! Here's the docs on the workflow syntax I'm using: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
=> Consider not running CI on changes to docs

README.md, docs/docs/app-configuration-redwood-toml.md, docs/docs/authentication.md, docs/docs/cells.md, docs/docs/cli-commands.md, docs/docs/contributing-walkthrough.md, docs/docs/cookbook/file-uploads.md, docs/docs/cookbook/gotrue-auth.md, docs/docs/cookbook/pagination.md, docs/docs/cookbook/role-based-access-control.md, docs/docs/cookbook/supabase-auth.md, docs/docs/deploy.md, docs/docs/quick-start.md, docs/docs/router.md, packages/create-redwood-app/README.md, packages/create-redwood-app/src/create-redwood-app.js, packages/create-redwood-app/template/README.md, packages/structure/src/outline/outline.ts, tasks/e2e/cypress/integration/01-tutorial/sharedTests.js, tasks/e2e/cypress/integration/01-tutorial/tutorial.spec.js
This replace 
https://redwoodjs.com/tutorial
to 
https://redwoodjs.com/docs/tutorial
for the new path URL of the tutorial
=> Fix URL of all tutorial path

packages/graphql-server/package.json, packages/graphql-server/src/functions/graphql.ts, yarn.lock
- Build base cors options for Yoga once before initial startup
- Use `https` as protocol, and `domainName` as hostname
- And add query parameters back to the URL
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
Once we use 2.0, we can use `rawPath` and `rawQueryString`.
=> Fix Request object passed to Yoga

packages/graphql-server/src/functions/graphql.ts
Since the event.requestContext can be undefined in certain provider deploys, needs to have an optional check
=> event.requestContext can be optional for domain name
